"""The description of the Asteroids game, used to build its four pages."""

SPEC = dict(
    slug="asteroids",
    name="Asteroids",
    icon="🚀",
    title="ASTEROIDS",
    subtitle="Turn, thrust, shoot — and remember that space has no brakes",
    python_subtitle="The same drifting ship — but the trigonometry is Python",
    canvas_id="asteroids-board", canvas_width=340, canvas_height=340,
    hud=[("Score", "score", "0"), ("Lives", "lives", "3"),
         ("Wave", "wave", "1"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-left", "◀ TURN"), ("btn-thrust", "THRUST"), ("btn-right", "TURN ▶")],
              [("btn-fire", "FIRE")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> turn the ship &nbsp;•&nbsp; <span class="key">↑</span> fire the engine',
            '<span class="key">SPACE</span> shoot — up to four shots at once',
            'Tapping the field shoots too',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Turning points the ship. Thrust pushes it — and it <strong>keeps going</strong>.",
            "To stop, turn all the way round and thrust against your own drift.",
            "Fly off any edge and you come back on the other side.",
            "The dashed ring means you cannot be hit for a moment. Use it to get clear.",
        ]),
        ("🏆 Scoring", [
            "Big rock <strong>20</strong> &nbsp;•&nbsp; medium <strong>50</strong> &nbsp;•&nbsp; small <strong>100</strong>.",
            "Every rock you break makes two smaller, faster ones.",
            "Clearing a whole wave is another <strong>100</strong>.",
            "Tip: break the big ones one at a time. Break them all at once and there will be sixteen little rocks after you.",
        ]),
    ],
    js_files=["asteroids-rules.js", "asteroids-draw.js", "asteroids-main.js"],
    py_files=["asteroids_rules.py", "asteroids_draw.py", "asteroids_web.py"],
    py_workshop_files=["asteroids_rules.py", "asteroids_draw.py", "asteroids_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/asteroids-rules.js", "The rules: angles, drifting, wrapping, breaking",
         "<code>pointFrom</code>, <code>wrapPosition</code>, <code>thrustShip</code>, <code>hitRocks</code>"),
        ("lib/asteroids-draw.js", "Painting the ship and the lumpy rocks",
         "<code>drawShip</code>, <code>drawRock</code>, <code>renderGame</code>"),
        ("lib/asteroids-main.js", "The glue: the held keys, the taps, the loop",
         "<code>doAction</code>, <code>holdButton</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/asteroids_rules.py", "The rules: angles, drifting, wrapping, breaking",
         "<code>point_from</code>, <code>wrap_position</code>, <code>thrust_ship</code>, <code>hit_rocks</code>"),
        ("pylib/asteroids_draw.py", "Painting space — Python calling the canvas",
         "<code>draw_ship</code>, <code>draw_rock</code>, <code>render_game</code>"),
        ("pylib/asteroids_web.py", "The glue: the held keys, the taps, the loop",
         "<code>do_action</code>, <code>on_key_down</code>, <code>frame</code>"),
    ],
    big_idea="<code>cos</code> and <code>sin</code> turn <strong>a direction into a place</strong>. Give them an angle and a distance and they tell you exactly where you end up. Learn that one function and you can point, aim, orbit and steer in any game you ever write.",
    step_count=20,
    py_steps_const="ASTEROIDS_PYTHON_STEPS",
    next_challenge="add a flying saucer that shoots back, give the ship a hyperspace jump to somewhere random, or make the rocks bounce off each other.",
    footer="Space has no brakes. 🚀",
)
