"""The description of the Breakout game, used to build its four pages."""

SPEC = dict(
    slug="breakout",
    name="Breakout",
    icon="🧱",
    title="BREAKOUT",
    subtitle="Bounce the ball, clear the wall — and never let it past you",
    python_subtitle="The same bouncing ball — but every line of the physics is Python",
    canvas_id="breakout-board", canvas_width=320, canvas_height=420,
    hud=[("Score", "score", "0"), ("Lives", "lives", "3"),
         ("Bricks", "bricks", "35"), ("Best", "best", "0")],
    play_label="▶ Launch",
    touchpad=[[("btn-left", "◀"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> or <span class="key">A</span> <span class="key">D</span> slide the paddle',
            'The paddle also follows your mouse or finger across the field',
            '<span class="key">SPACE</span> launch the ball &nbsp;•&nbsp; <span class="key">P</span> pause',
            '<span class="key">R</span> start a new game',
        ]),
        ("🎯 How to play", [
            "Keep the ball off the floor. You get three lives.",
            "Every brick the ball touches disappears.",
            "Clear all 35 bricks to win.",
            "Where the ball lands on the paddle decides where it goes next — that is your steering.",
        ]),
        ("🏆 Scoring", [
            "The top row is worth <strong>50</strong> points, the bottom row <strong>10</strong>.",
            "A perfect wall is 1050 points.",
            "Hit the ball with the <em>edge</em> of the paddle to send it sideways at the corners.",
            "The middle of the paddle sends it straight up — safe, but slow going.",
        ]),
    ],
    js_files=["breakout-rules.js", "breakout-draw.js", "breakout-main.js"],
    py_files=["breakout_rules.py", "breakout_draw.py", "breakout_web.py"],
    py_workshop_files=["breakout_rules.py", "breakout_draw.py", "breakout_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/breakout-rules.js", "The rules: the ball, the bounces, the bricks",
         "<code>hitsRect</code>, <code>bounceOffWalls</code>, <code>bounceOffPaddle</code>, <code>breakBricks</code>"),
        ("lib/breakout-draw.js", "Painting the wall, the bat and the ball",
         "<code>drawBrick</code>, <code>drawPaddle</code>, <code>renderGame</code>"),
        ("lib/breakout-main.js", "The glue: the keyboard, the mouse, the loop",
         "<code>doAction</code>, <code>connectMouse</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/breakout_rules.py", "The rules: the ball, the bounces, the bricks",
         "<code>hits_rect</code>, <code>bounce_off_walls</code>, <code>bounce_off_paddle</code>, <code>break_bricks</code>"),
        ("pylib/breakout_draw.py", "Painting the wall — Python calling the canvas",
         "<code>draw_brick</code>, <code>draw_paddle</code>, <code>render_game</code>"),
        ("pylib/breakout_web.py", "The glue: the keyboard, the mouse, the loop",
         "<code>do_action</code>, <code>on_mouse_move</code>, <code>frame</code>"),
    ],
    big_idea="a <strong>bounce is just a flipped direction</strong>. <code>dy = -dy</code> and the ball goes back the way it came. Almost all game physics is made of tiny rules like that, run sixty times a second.",
    step_count=7,
    py_steps_const="BREAKOUT_PYTHON_STEPS",
    next_challenge="add a second ball, make the paddle shrink as the score goes up, or give the top row two hits before it breaks.",
    footer="Aim with the edges of the paddle. 🧱",
)
