"""The description of the Bubble Shooter game, used to build its four pages."""

SPEC = dict(
    slug="bubbles",
    name="Bubble Shooter",
    icon="🫧",
    title="BUBBLE SHOOTER",
    subtitle="Three of a kind pop — and everything hanging from them falls",
    python_subtitle="The same bubbles — but both searches are written in Python",
    canvas_id="bubbles-board", canvas_width=280, canvas_height=400,
    hud=[("Score", "score", "0"), ("Popped", "popped", "0"),
         ("Shots", "shots", "0"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-left", "◀"), ("btn-shoot", "SHOOT"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> or <span class="key">A</span> <span class="key">D</span> swing the aim',
            '<span class="key">SPACE</span> or <span class="key">↑</span> shoot',
            'On a phone: tap where you want the bubble to go',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Stick your bubble next to <strong>two more of the same kind</strong> and all three pop.",
            "Bubbles are told apart by their pattern: solid, ring, dotted, striped, crossed.",
            "Anything left hanging with nothing above it <strong>falls</strong> — and falling is worth more.",
            "If the bubbles reach the dashed line, the game is over.",
        ]),
        ("🏆 Scoring", [
            "Popped bubble <strong>10</strong> &nbsp;•&nbsp; dropped bubble <strong>25</strong>.",
            "Clearing the whole ceiling is another <strong>500</strong>.",
            "Shots bounce off the side walls — that is how you reach the corners.",
            "Look for the one bubble holding up a whole cluster. Pop that and the lot comes down.",
        ]),
    ],
    js_files=["bubbles-rules.js", "bubbles-draw.js", "bubbles-main.js"],
    py_files=["bubbles_rules.py", "bubbles_draw.py", "bubbles_web.py"],
    py_workshop_files=["bubbles_rules.py", "bubbles_draw.py", "bubbles_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/bubbles-rules.js", "The rules: aiming, sticking, popping, falling",
         "<code>turnShooter</code>, <code>sameGroup</code>, <code>popGroup</code>, <code>dropFloaters</code>"),
        ("lib/bubbles-draw.js", "Painting five kinds of bubble without any colour",
         "<code>drawBubble</code>, <code>drawShooter</code>, <code>renderGame</code>"),
        ("lib/bubbles-main.js", "The glue: the held keys, tap-to-aim, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/bubbles_rules.py", "The rules: aiming, sticking, popping, falling",
         "<code>turn_shooter</code>, <code>same_group</code>, <code>pop_group</code>, <code>drop_floaters</code>"),
        ("pylib/bubbles_draw.py", "Painting the bubbles — Python calling the canvas",
         "<code>draw_bubble</code>, <code>draw_shooter</code>, <code>render_game</code>"),
        ("pylib/bubbles_web.py", "The glue: the held keys, tap-to-aim, the loop",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="<strong>one search, two questions</strong>. The same flood fill that asks \"which bubbles of this kind are joined together?\" also answers \"which bubbles are joined to the ceiling?\" — you only change where it starts and what it is willing to walk through. Learning one algorithm well beats learning two badly.",
    step_count=5,
    py_steps_const="BUBBLES_PYTHON_STEPS",
    next_challenge="drop a new row from the ceiling every ten shots, add a bubble that pops everything of one kind, or show the bounce line so you can aim off the walls.",
    footer="Look for the bubble holding up the rest. 🫧",
)
