"""The description of the Connect Four game, used to build its four pages."""

SPEC = dict(
    slug="connect4",
    name="Connect Four",
    icon="🔴",
    title="CONNECT FOUR",
    subtitle="Drop your counters and get four in a row — the computer is trying to stop you",
    python_subtitle="The same game — but every line of it is Python, running in your browser",
    canvas_id="connect4-board", canvas_width=384, canvas_height=366,
    hud=[("You", "wins", "0"), ("Computer", "losses", "0"), ("Draws", "draws", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-left", "←"), ("btn-drop", "Drop"), ("btn-right", "→")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> aim above a column',
            '<span class="key">Space</span>, <span class="key">Enter</span> or <span class="key">↓</span> drop a counter',
            'Clicking or tapping a column works too',
            '<span class="key">R</span> next round &nbsp;•&nbsp; <span class="key">P</span> pause',
        ]),
        ("🎯 How to play", [
            "You are the <strong>solid</strong> counters; the computer is the <strong>rings</strong>.",
            "Counters fall to the lowest free hole in the column you pick.",
            "Get four in a row — across, down or diagonally.",
            "The computer replies straight away, so every drop is a whole turn.",
        ]),
        ("🤖 How the computer thinks", [
            "1. If it can make four, it does.",
            "2. If you are about to make four, it blocks you.",
            "3. Otherwise it plays as near the middle as it can — the middle column is part of more possible lines than any other.",
            "4. And it never drops a counter that lets you win by landing on top of it.",
            "To beat it, build <strong>two</strong> threats at once. It can only block one!",
        ]),
    ],
    js_files=["connect4-rules.js", "connect4-draw.js", "connect4-main.js"],
    py_files=["connect4_rules.py", "connect4_draw.py", "connect4_web.py"],
    py_workshop_files=["connect4_rules.py", "connect4_draw.py", "connect4_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/connect4-rules.js", "The rules, the win check and the computer",
         "<code>dropRow</code>, <code>countInDirection</code>, <code>isWinAt</code>, <code>computerColumn</code>"),
        ("lib/connect4-draw.js", "Painting the holes and counters",
         "<code>drawCounter</code>, <code>drawDropMarker</code>, <code>columnAtPixel</code>"),
        ("lib/connect4-main.js", "The glue: clicks, keyboard, the scoreboard",
         "<code>doAction</code>, <code>connectBoard</code>, <code>updateScoreboard</code>"),
    ],
    py_coder_rows=[
        ("pylib/connect4_rules.py", "The rules, the win check and the computer",
         "<code>drop_row</code>, <code>count_in_direction</code>, <code>is_win_at</code>, <code>computer_column</code>"),
        ("pylib/connect4_draw.py", "Painting the board — Python calling the canvas",
         "<code>draw_counter</code>, <code>draw_drop_marker</code>, <code>column_at_pixel</code>"),
        ("pylib/connect4_web.py", "The glue: clicks, keyboard, the scoreboard",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="you never have to search the whole board for four in a row. Only the counter that was <em>just dropped</em> can have made a new line, so you look outwards from that one square — in four directions, both ways. That trick keeps the check fast no matter how big the board gets.",
    step_count=7,
    py_steps_const="CONNECT4_PYTHON_STEPS",
    next_challenge="make the board bigger, let two people play, or teach the computer to look two moves ahead.",
    footer="Build two threats at once and even a computer cannot stop you. 🔴",
)
