"""The description of the Flappy game, used to build its four pages."""

SPEC = dict(
    slug="flappy",
    name="Flappy",
    icon="🐤",
    title="FLAPPY",
    subtitle="One button. Gravity. And a great many pipes",
    python_subtitle="The same bird — but the gravity is written in Python",
    canvas_id="flappy-board", canvas_width=300, canvas_height=420,
    hud=[("Score", "score", "0"), ("Level", "level", "1"),
         ("Pipes", "pipes", "1"), ("Best", "best", "0")],
    play_label="▶ Start",
    touchpad=[[("btn-flap", "FLAP")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">SPACE</span>, <span class="key">↑</span> or <span class="key">W</span> flap',
            'Clicking or tapping the sky flaps too',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
            'Your first flap starts the game — no need to press start.',
        ]),
        ("🎯 How to play", [
            "The bird falls all by itself. Flapping is the only thing you control.",
            "Fly through the gap in each pipe.",
            "Touching a pipe, the ground or the ceiling ends the run.",
            "Short taps beat long ones — flap little and often.",
        ]),
        ("🏆 Scoring", [
            "One point per pipe you get through.",
            "Every 5 pipes the game speeds up a little, all the way to level 15.",
            "Ten pipes is a good run. Twenty is showing off.",
            "Tip: aim for the <em>middle</em> of the gap, not the bottom of it.",
        ]),
    ],
    js_files=["flappy-rules.js", "flappy-draw.js", "flappy-main.js"],
    py_files=["flappy_rules.py", "flappy_draw.py", "flappy_web.py"],
    py_workshop_files=["flappy_rules.py", "flappy_draw.py", "flappy_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/flappy-rules.js", "The rules: gravity, pipes, crashes",
         "<code>applyGravity</code>, <code>flap</code>, <code>movePipes</code>, <code>isCrashed</code>"),
        ("lib/flappy-draw.js", "Painting the sky, the pipes and the bird",
         "<code>drawPipe</code>, <code>drawBird</code>, <code>renderGame</code>"),
        ("lib/flappy-main.js", "The glue: the keyboard, the taps, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/flappy_rules.py", "The rules: gravity, pipes, crashes",
         "<code>apply_gravity</code>, <code>flap</code>, <code>move_pipes</code>, <code>is_crashed</code>"),
        ("pylib/flappy_draw.py", "Painting the sky — Python calling the canvas",
         "<code>draw_pipe</code>, <code>draw_bird</code>, <code>render_game</code>"),
        ("pylib/flappy_web.py", "The glue: the keyboard, the taps, the loop",
         "<code>do_action</code>, <code>on_board_press</code>, <code>frame</code>"),
    ],
    big_idea="<strong>gravity changes speed, not position</strong>. Add a little to <code>dy</code> every frame, then move by <code>dy</code>. That one pattern is behind every jump, every falling rock and every bouncing ball you have ever played with.",
    step_count=8,
    py_steps_const="FLAPPY_PYTHON_STEPS",
    next_challenge="give the bird two lives, put a coin in some of the gaps, or make the gap slowly shrink as the score climbs.",
    footer="Little flaps. Lots of them. 🐤",
)
