"""The description of the Hundred Floors game, used to build its four pages."""

SPEC = dict(
    slug="floors",
    name="Hundred Floors",
    icon="🪜",
    title="HUNDRED FLOORS",
    subtitle="Drop from floor to floor — miss and you fall, land on the 锯齿 and you bleed",
    python_subtitle="The same shaft — but the camera and the landings are all Python",
    canvas_id="floors-board", canvas_width=300, canvas_height=420,
    hud=[("Floor", "floor", "1"), ("Blood", "health", "10 / 10"),
         ("Score", "score", "0"), ("Deepest", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-left", "◀"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> or <span class="key">A</span> <span class="key">D</span> walk — hold them down',
            'On a phone: hold your finger on the left or right half of the shaft',
            'There is no jump. You go DOWN by walking off an edge.',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Keep landing on the platforms. Miss them all and you fall off the bottom — that is the end.",
            "The view keeps sinking, so standing still pushes you up into the <strong>spiked ceiling</strong>.",
            "Land on a platform with <strong>锯齿 sawteeth</strong> and it costs you two blood.",
            "Ten blood. Five spiked landings and you are finished.",
        ]),
        ("🪜 The six platforms", [
            "<strong>Plain</strong> — a solid bar. Perfectly safe.",
            "<strong>锯齿 spiked</strong> — sawteeth on top. Avoid these.",
            "<strong>Arrows</strong> — a moving floor that carries you that way.",
            "<strong>Coil</strong> — a spring, and it throws you straight back up.",
            "<strong>Dashed</strong> — it crumbles away a moment after you land.",
        ]),
    ],
    js_files=["floors-rules.js", "floors-draw.js", "floors-main.js"],
    py_files=["floors_rules.py", "floors_draw.py", "floors_web.py"],
    py_workshop_files=["floors_rules.py", "floors_draw.py", "floors_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/floors-rules.js", "The rules: the camera, the landings, the six kinds",
         "<code>screenY</code>, <code>cameraSpeed</code>, <code>landsOn</code>, <code>landOnPlatform</code>"),
        ("lib/floors-draw.js", "Painting the shaft, the 锯齿 and the blood bar",
         "<code>drawSawteeth</code>, <code>drawPlatform</code>, <code>renderGame</code>"),
        ("lib/floors-main.js", "The glue: the held keys, the touch halves, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/floors_rules.py", "The rules: the camera, the landings, the six kinds",
         "<code>screen_y</code>, <code>camera_speed</code>, <code>lands_on</code>, <code>land_on_platform</code>"),
        ("pylib/floors_draw.py", "Painting the shaft — Python calling the canvas",
         "<code>draw_sawteeth</code>, <code>draw_platform</code>, <code>render_game</code>"),
        ("pylib/floors_web.py", "The glue: the held keys, the touch halves, the loop",
         "<code>do_action</code>, <code>on_press</code>, <code>frame</code>"),
    ],
    big_idea="<strong>the world stays still and the camera moves.</strong> It is tempting to slide all the platforms upwards instead — until you notice that anybody standing on one has to be dragged along too, so hurrying the view would physically fling the player into the ceiling. Move the camera and nothing in the world is disturbed at all.",
    step_count=6,
    py_steps_const="FLOORS_PYTHON_STEPS",
    next_challenge="add a platform that heals you, make the shaft narrower as you go deeper, or show how far you fell and give a bonus for a really long drop.",
    footer="There is no jump. Walk off the edge. 🪜",
)
