"""The description of the Frogger game, used to build its four pages."""

SPEC = dict(
    slug="frogger",
    name="Frogger",
    icon="🐸",
    title="FROGGER",
    subtitle="Nine lanes of traffic. One frog. Good luck",
    python_subtitle="The same road — but every car is moved by Python",
    canvas_id="frogger-board", canvas_width=288, canvas_height=352,
    hud=[("Score", "score", "0"), ("Lives", "lives", "3"),
         ("Crossings", "crossings", "0"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> or <span class="key">W</span> <span class="key">A</span> <span class="key">S</span> <span class="key">D</span> hop one square',
            'Tapping the board hops towards where you tapped',
            '<span class="key">P</span> or <span class="key">SPACE</span> pause',
            '<span class="key">R</span> start a new game',
        ]),
        ("🎯 How to play", [
            "Hop from the bottom bank to the top without being run over.",
            "The striped rows are safe — the one in the middle is a place to stop and think.",
            "You get three frogs. Every crossing makes the traffic faster.",
            "Odd rows drive right, even rows drive left. Watch both ways!",
        ]),
        ("🏆 Scoring", [
            "<strong>10</strong> points for every row you reach for the first time.",
            "<strong>100</strong> points for a whole crossing.",
            "Hopping back and forth pays nothing — a row only counts once.",
            "Tip: wait on the safe island until a gap opens all the way up.",
        ]),
    ],
    js_files=["frogger-rules.js", "frogger-draw.js", "frogger-main.js"],
    py_files=["frogger_rules.py", "frogger_draw.py", "frogger_web.py"],
    py_workshop_files=["frogger_rules.py", "frogger_draw.py", "frogger_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/frogger-rules.js", "The rules: the lanes, the traffic, the hops",
         "<code>laneSpeed</code>, <code>wrapCar</code>, <code>moveFrog</code>, <code>isSquashed</code>"),
        ("lib/frogger-draw.js", "Painting the road, the cars and the frog",
         "<code>drawCar</code>, <code>drawFrog</code>, <code>renderGame</code>"),
        ("lib/frogger-main.js", "The glue: the keyboard, the taps, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/frogger_rules.py", "The rules: the lanes, the traffic, the hops",
         "<code>lane_speed</code>, <code>wrap_car</code>, <code>move_frog</code>, <code>is_squashed</code>"),
        ("pylib/frogger_draw.py", "Painting the road — Python calling the canvas",
         "<code>draw_car</code>, <code>draw_frog</code>, <code>render_game</code>"),
        ("pylib/frogger_web.py", "The glue: the keyboard, the taps, the loop",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="two different worlds can live in one game. The frog moves on a <strong>grid</strong>, one square at a time; the cars move in <strong>pixels</strong>, smoothly. Turning both into rectangles is what lets them meet.",
    step_count=7,
    py_steps_const="FROGGER_PYTHON_STEPS",
    next_challenge="add a river of logs above the road, put a time limit on each crossing, or give one lane a car that speeds up when you step in front of it.",
    footer="Look both ways. 🐸",
)
