"""The description of the Hangman game, used to build its four pages."""

SPEC = dict(
    slug="hangman",
    name="Hangman",
    icon="🔤",
    title="HANGMAN",
    subtitle="Sixty hidden words, six lives, and one letter at a time",
    python_subtitle="The same word game — but every string is handled by Python",
    canvas_id="hangman-board", canvas_width=320, canvas_height=330,
    hud=[("Lives", "lives", "6"), ("Letters tried", "letters", "0"),
         ("Wins", "wins", "0"), ("Losses", "losses", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-vowels", "A E I O U")]],
    help=[
        ("⌨️ Controls", [
            'Just <strong>type a letter</strong> — any letter is a guess',
            'Or click the alphabet along the bottom of the picture',
            '<span class="key">ENTER</span> a new word &nbsp;•&nbsp; <span class="key">ESC</span> pause',
            'The A E I O U button tries all five vowels at once.',
        ]),
        ("🎯 How to play", [
            "A word is hidden. Every letter you find is filled in.",
            "A letter that is not in the word costs a life and draws another line.",
            "Six wrong guesses and the picture is finished.",
            "Guessing the same letter twice is free — it costs nothing.",
        ]),
        ("🧠 Getting good", [
            "Start with the vowels: <strong>E, A, I, O, U</strong>. Almost every word has one.",
            "Then the common consonants: <strong>R, S, T, N, L</strong>.",
            "Count the blanks. Short words are much harder than long ones.",
            "Look at what you have: <code>_ I O N</code> is not many words.",
        ]),
    ],
    js_files=["hangman-rules.js", "hangman-draw.js", "hangman-main.js"],
    py_files=["hangman_rules.py", "hangman_draw.py", "hangman_web.py"],
    py_workshop_files=["hangman_rules.py", "hangman_draw.py", "hangman_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/hangman-rules.js", "The rules: hiding the word, counting mistakes",
         "<code>maskedWord</code>, <code>isWordComplete</code>, <code>wrongLetters</code>, <code>guessLetter</code>"),
        ("lib/hangman-draw.js", "The drawing that grows one line at a time",
         "<code>drawGallows</code>, <code>drawParts</code>, <code>renderGame</code>"),
        ("lib/hangman-main.js", "The glue: the keyboard and the alphabet row",
         "<code>doAction</code>, <code>connectBoard</code>, <code>setUpGame</code>"),
    ],
    py_coder_rows=[
        ("pylib/hangman_rules.py", "The rules: hiding the word, counting mistakes",
         "<code>masked_word</code>, <code>is_word_complete</code>, <code>wrong_letters</code>, <code>guess_letter</code>"),
        ("pylib/hangman_draw.py", "The drawing — Python calling the canvas",
         "<code>draw_gallows</code>, <code>draw_parts</code>, <code>render_game</code>"),
        ("pylib/hangman_web.py", "The glue: the keyboard and the alphabet row",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="<strong>work things out, do not store them twice</strong>. The number of lives left is not kept anywhere — it is counted from the guesses whenever it is needed. Two copies of the same fact can disagree with each other; one cannot.",
    step_count=5,
    py_steps_const="HANGMAN_PYTHON_STEPS",
    next_challenge="add your own words to the list, give a clue after three wrong guesses, or let two players take turns picking words for each other.",
    footer="Try the vowels first. 🔤",
)
