"""The description of the Space Invaders game, used to build its four pages."""

SPEC = dict(
    slug="invaders",
    name="Space Invaders",
    icon="👾",
    title="SPACE INVADERS",
    subtitle="Twenty-four aliens, three lives, and one bullet at a time",
    python_subtitle="The same fleet — but every alien is marched by Python",
    canvas_id="invaders-board", canvas_width=320, canvas_height=400,
    hud=[("Score", "score", "0"), ("Lives", "lives", "3"),
         ("Wave", "wave", "1"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-left", "◀"), ("btn-fire", "FIRE"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> or <span class="key">A</span> <span class="key">D</span> slide the ship',
            '<span class="key">SPACE</span>, <span class="key">↑</span> or <span class="key">W</span> fire',
            'Tapping the field fires too',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Shoot all 24 aliens before they land on you.",
            "Only <strong>one</strong> of your bullets can be in the air at a time — make it count.",
            "The hollow shots are alien bombs. Do not stand under them.",
            "Every time the fleet touches a wall it drops a row closer.",
        ]),
        ("🏆 Scoring", [
            "The back row is worth <strong>40</strong>, the front row <strong>10</strong>.",
            "Clearing a whole wave is another <strong>100</strong>.",
            "The fewer aliens are left, the faster they march.",
            "Tip: shoot a column out at one end and the fleet gets extra room to march — that buys you time.",
        ]),
    ],
    js_files=["invaders-rules.js", "invaders-draw.js", "invaders-main.js"],
    py_files=["invaders_rules.py", "invaders_draw.py", "invaders_web.py"],
    py_workshop_files=["invaders_rules.py", "invaders_draw.py", "invaders_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/invaders-rules.js", "The rules: the fleet, the shots, the hits",
         "<code>alienRect</code>, <code>moveFleet</code>, <code>fireBullet</code>, <code>hitAliens</code>"),
        ("lib/invaders-draw.js", "Painting the fleet, the ship and the shots",
         "<code>drawAlien</code>, <code>drawShip</code>, <code>renderGame</code>"),
        ("lib/invaders-main.js", "The glue: the keyboard, the taps, the loop",
         "<code>doAction</code>, <code>holdButton</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/invaders_rules.py", "The rules: the fleet, the shots, the hits",
         "<code>alien_rect</code>, <code>move_fleet</code>, <code>fire_bullet</code>, <code>hit_aliens</code>"),
        ("pylib/invaders_draw.py", "Painting the fleet — Python calling the canvas",
         "<code>draw_alien</code>, <code>draw_ship</code>, <code>render_game</code>"),
        ("pylib/invaders_web.py", "The glue: the keyboard, the taps, the loop",
         "<code>do_action</code>, <code>on_key_down</code>, <code>frame</code>"),
    ],
    big_idea="twenty-four things can share <strong>one</strong> position. The fleet knows where it is; each alien only knows its column and row. Change one number and the whole fleet moves — that is how this game ran on a computer with less memory than a single photo takes today.",
    step_count=7,
    py_steps_const="INVADERS_PYTHON_STEPS",
    next_challenge="add the four shields to hide behind, put a mystery ship across the top, or let the player have two bullets once they reach wave 5.",
    footer="One bullet at a time. Make it count. 👾",
)
