"""The description of the lights game, used to build its four pages."""

SPEC = dict(
    slug="lights",
    name="Lights Out",
    icon="💡",
    title="LIGHTS OUT",
    subtitle="Press a square and its neighbours flip — can you turn them all off?",
    python_subtitle="The same puzzle — but every line of it is Python, running in your browser",
    canvas_id="lights-board", canvas_width=358, canvas_height=358,
    hud=[("Presses", "moves", "0"), ("Still lit", "lit", "0"), ("Best", "best", "—")],
    play_label="⏸ Pause",
    touchpad=[[None, ("btn-up", "↑"), None],
              [("btn-left", "←"), ("btn-press", "Press"), ("btn-right", "→")],
              [None, ("btn-down", "↓"), None]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> <span class="key">↑</span> <span class="key">↓</span> move the dashed cursor',
            '<span class="key">Space</span> or <span class="key">Enter</span> press the square',
            'Clicking or tapping a square works too',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new puzzle',
        ]),
        ("🎯 How to play", [
            "Pressing a square flips it <strong>and its four neighbours</strong> — a plus shape.",
            "At the edges the cross is smaller, because some neighbours do not exist.",
            "Turn every light off to win.",
            "Every puzzle can be solved — the game builds them by pressing, so they can always be un-pressed.",
        ]),
        ("💡 Two tricks", [
            "Pressing the same square twice puts everything back. Every move is its own undo.",
            "So the order you press in does not matter at all — only <em>which</em> squares you press.",
            "That means every puzzle has a shortest answer, and no square ever needs pressing twice.",
            "Try solving the top row first, then work down. It really helps.",
        ]),
    ],
    js_files=["lights-rules.js", "lights-draw.js", "lights-main.js"],
    py_files=["lights_rules.py", "lights_draw.py", "lights_web.py"],
    py_workshop_files=["lights_rules.py", "lights_draw.py", "lights_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/lights-rules.js", "The rules: the cross, the flips, the win",
         "<code>lightIndex</code>, <code>neighbours</code>, <code>pressLight</code>, <code>createPuzzle</code>"),
        ("lib/lights-draw.js", "Painting the lights and the cursor",
         "<code>drawLight</code>, <code>squareAtPixel</code>, <code>renderGame</code>"),
        ("lib/lights-main.js", "The glue: clicks, keyboard, the scoreboard",
         "<code>doAction</code>, <code>connectBoard</code>, <code>updateScoreboard</code>"),
    ],
    py_coder_rows=[
        ("pylib/lights_rules.py", "The rules: the cross, the flips, the win",
         "<code>light_index</code>, <code>neighbours</code>, <code>press_light</code>, <code>create_puzzle</code>"),
        ("pylib/lights_draw.py", "Painting the lights — Python calling the canvas",
         "<code>draw_light</code>, <code>square_at_pixel</code>, <code>render_game</code>"),
        ("pylib/lights_web.py", "The glue: clicks, keyboard, the scoreboard",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="the puzzle is built by <em>pressing random squares on a solved board</em>. Because every press undoes itself, a puzzle made that way can always be solved — a lovely example of making a problem impossible to get wrong.",
    step_count=7,
    py_steps_const="LIGHTS_PYTHON_STEPS",
    next_challenge="make the board 6 x 6, count down a timer, or add a Hint button that shows one square worth pressing.",
    footer="Every press undoes itself. Think before you tap. 💡",
)
