"""The description of the Match Three game, used to build its four pages."""

SPEC = dict(
    slug="match3",
    name="Match Three",
    icon="💠",
    title="MATCH THREE",
    subtitle="Swap two shapes to make a line — then watch the chain reaction",
    python_subtitle="The same puzzle — but every match is found by Python",
    canvas_id="match3-board", canvas_width=288, canvas_height=288,
    hud=[("Score", "score", "0"), ("Moves", "moves", "0"),
         ("Best chain", "chain", "0"), ("Best score", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲"), ("btn-pick", "PICK")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")],
              [("btn-shuffle", "↻ SHUFFLE")]],
    help=[
        ("⌨️ Controls", [
            'Click a shape, then click the one next to it — they swap',
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> move &nbsp;•&nbsp; <span class="key">SPACE</span> pick and swap',
            '<span class="key">N</span> shuffle the board &nbsp;•&nbsp; <span class="key">R</span> new game',
            '<span class="key">P</span> pause',
        ]),
        ("🎯 How to play", [
            "Swap two shapes that are touching to make a line of three or more.",
            "The line vanishes, everything above falls down, and new shapes drop in.",
            "If the falling shapes make <em>another</em> line, that is a <strong>chain</strong> — and it is worth more.",
            "A swap that makes no line is not allowed: the shapes simply swap back.",
        ]),
        ("🏆 Scoring", [
            "Each shape cleared is worth <strong>10</strong> points.",
            "The second link of a chain is worth double, the third triple, and so on.",
            "So one big chain beats a lot of small matches.",
            "Look for swaps that drop shapes onto other shapes of the same kind.",
        ]),
    ],
    js_files=["match3-rules.js", "match3-draw.js", "match3-main.js"],
    py_files=["match3_rules.py", "match3_draw.py", "match3_web.py"],
    py_workshop_files=["match3_rules.py", "match3_draw.py", "match3_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/match3-rules.js", "The rules: swapping, matching, falling, cascading",
         "<code>swapGems</code>, <code>findMatches</code>, <code>applyGravity</code>, <code>trySwap</code>"),
        ("lib/match3-draw.js", "Painting six shapes that need no colour",
         "<code>drawShape</code>, <code>drawGrid</code>, <code>renderGame</code>"),
        ("lib/match3-main.js", "The glue: clicks, the keyboard, the cursor",
         "<code>doAction</code>, <code>connectBoard</code>, <code>setUpGame</code>"),
    ],
    py_coder_rows=[
        ("pylib/match3_rules.py", "The rules: swapping, matching, falling, cascading",
         "<code>swap_gems</code>, <code>find_matches</code>, <code>apply_gravity</code>, <code>try_swap</code>"),
        ("pylib/match3_draw.py", "Painting the shapes — Python calling the canvas",
         "<code>draw_shape</code>, <code>draw_grid</code>, <code>render_game</code>"),
        ("pylib/match3_web.py", "The glue: clicks, the keyboard, the cursor",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="<strong>make a copy, then decide</strong>. Every swap happens on a copy of the board first. If it turns out to be a bad move, the copy is thrown away and the real board never knew. Undoing is free when you never changed anything in the first place.",
    step_count=5,
    py_steps_const="MATCH3_PYTHON_STEPS",
    next_challenge="add a move limit, make a line of four leave behind a special shape, or show the shapes sliding down instead of jumping.",
    footer="Chains are where the points are. 💠",
)
