"""The description of the Maze Runner game, used to build its four pages."""

SPEC = dict(
    slug="maze",
    name="Maze Runner",
    icon="🌀",
    title="MAZE RUNNER",
    subtitle="A brand-new maze every game — find the ring in the far corner",
    python_subtitle="The same maze — but Python digs it and Python finds the way out",
    canvas_id="maze-board", canvas_width=348, canvas_height=252,
    hud=[("Steps", "steps", "0"), ("Best possible", "shortest", "0"),
         ("Time", "time", "0"), ("Escaped", "solved", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲"), ("btn-hint", "? HINT")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> or <span class="key">W</span> <span class="key">A</span> <span class="key">S</span> <span class="key">D</span> walk',
            'Tapping the maze walks one step towards where you tapped',
            '<span class="key">H</span> or <span class="key">SPACE</span> show the shortest way out',
            '<span class="key">N</span> dig a brand-new maze &nbsp;•&nbsp; <span class="key">P</span> pause',
        ]),
        ("🎯 How to play", [
            "Start in the top-left corner. The ring in the bottom-right is the way out.",
            "Every maze is dug fresh, so you have never seen this one before.",
            "There is always exactly <strong>one</strong> route between any two places — no loops.",
            "The scoreboard shows the fewest steps possible. Can you match it?",
        ]),
        ("🧠 Two great algorithms", [
            "The maze is dug by a <strong>recursive backtracker</strong>: walk, dig, and back up when stuck.",
            "The hint uses <strong>breadth-first search</strong>, the shortest-path algorithm.",
            "The same search finds routes on road maps and in chess programs.",
            "Both are only about twenty lines. You write them in the workshop.",
        ]),
    ],
    js_files=["maze-rules.js", "maze-draw.js", "maze-main.js"],
    py_files=["maze_rules.py", "maze_draw.py", "maze_web.py"],
    py_workshop_files=["maze_rules.py", "maze_draw.py", "maze_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/maze-rules.js", "The rules: digging the maze and finding the way out",
         "<code>roomNeighbours</code>, <code>carveMaze</code>, <code>findPath</code>, <code>movePlayer</code>"),
        ("lib/maze-draw.js", "Painting the rock, the corridors and the hint",
         "<code>drawMaze</code>, <code>drawHint</code>, <code>renderGame</code>"),
        ("lib/maze-main.js", "The glue: the keyboard, the taps, the clock",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/maze_rules.py", "The rules: digging the maze and finding the way out",
         "<code>room_neighbours</code>, <code>carve_maze</code>, <code>find_path</code>, <code>move_player</code>"),
        ("pylib/maze_draw.py", "Painting the maze — Python calling the canvas",
         "<code>draw_maze</code>, <code>draw_hint</code>, <code>render_game</code>"),
        ("pylib/maze_web.py", "The glue: the keyboard, the taps, the clock",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="a <strong>stack</strong> and a <strong>queue</strong> are the same shape with one difference — which end you take from — and that one difference changes everything. Take from the back and you wander deep into a maze, which is perfect for digging one. Take from the front and you spread out evenly, which finds the shortest way through.",
    step_count=5,
    py_steps_const="MAZE_PYTHON_STEPS",
    next_challenge="make the maze bigger, show only the part you have explored so far, or add a second player racing you to the exit.",
    footer="Every maze is brand new. 🌀",
)
