"""The description of the memory game, used to build its four pages."""

SPEC = dict(
    slug="memory",
    name="Memory Match",
    icon="🧠",
    title="MEMORY MATCH",
    subtitle="Sixteen cards, eight pairs — can you remember where they are?",
    python_subtitle="The same card game — but every line of it is Python, running in your browser",
    canvas_id="memory-board", canvas_width=348, canvas_height=428,
    hud=[("Moves", "moves", "0"), ("Pairs", "pairs", "0 / 8"),
         ("Stars", "stars", "★★★"), ("Best", "best", "—")],
    play_label="⏸ Pause",
    touchpad=[[None, ("btn-up", "↑"), None],
              [("btn-left", "←"), ("btn-flip", "Flip"), ("btn-right", "→")],
              [None, ("btn-down", "↓"), None]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> <span class="key">↑</span> <span class="key">↓</span> move the dashed cursor',
            '<span class="key">Space</span> or <span class="key">Enter</span> turn a card over',
            'Clicking or tapping a card works too',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Sixteen cards lie face down, hiding eight pairs.",
            "Turn two over. If they match they stay up; if not, they turn back — so remember them!",
            "A <strong>move</strong> is a pair of cards, not a single one.",
            "Find all eight pairs to win.",
        ]),
        ("🏆 Scoring", [
            "Eight pairs cannot be found in fewer than <strong>8 moves</strong>.",
            "12 moves or fewer = ★★★",
            "18 moves or fewer = ★★",
            "More than that = ★ — everybody who finishes gets a star.",
        ]),
    ],
    js_files=["memory-rules.js", "memory-draw.js", "memory-main.js"],
    py_files=["memory_rules.py", "memory_draw.py", "memory_web.py"],
    py_workshop_files=["memory_rules.py", "memory_draw.py", "memory_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/memory-rules.js", "The rules: dealing, flipping, matching",
         "<code>cardIndex</code>, <code>createDeck</code>, <code>isMatch</code>, <code>flipCard</code>"),
        ("lib/memory-draw.js", "Painting the cards and the eight symbols",
         "<code>drawSymbol</code>, <code>drawCard</code>, <code>cardAtPixel</code>"),
        ("lib/memory-main.js", "The glue: clicks, keyboard, the loop",
         "<code>doAction</code>, <code>canvasPosition</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/memory_rules.py", "The rules: dealing, flipping, matching",
         "<code>card_index</code>, <code>create_deck</code>, <code>is_match</code>, <code>flip_card</code>"),
        ("pylib/memory_draw.py", "Painting the cards — Python calling the canvas",
         "<code>draw_symbol</code>, <code>draw_card</code>, <code>card_at_pixel</code>"),
        ("pylib/memory_web.py", "The glue: clicks, keyboard, the loop",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="the sixteen cards are one flat <strong>list</strong>, and <code>cardIndex(column, row)</code> is the little sum that turns a grid into a list. Almost every board game you write needs it.",
    step_count=9,
    py_steps_const="MEMORY_PYTHON_STEPS",
    next_challenge="make the board 6 x 6, add a timer, or give each pair a different number of points.",
    footer="Memory is a muscle. 🧠",
)
