"""The description of the Minesweeper game, used to build its four pages."""

SPEC = dict(
    slug="mines",
    name="Minesweeper",
    icon="💣",
    title="MINESWEEPER",
    subtitle="Ten mines, eighty-one squares, and nothing but logic",
    python_subtitle="The same puzzle — but the flood fill is written in Python",
    canvas_id="mines-board", canvas_width=286, canvas_height=286,
    hud=[("Mines left", "mines", "10"), ("Time", "time", "0"),
         ("Opened", "opened", "0"), ("Best time", "best", "—")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲"), ("btn-dig", "DIG")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")],
              [("btn-flag", "⚑ FLAG")]],
    help=[
        ("⌨️ Controls", [
            'Left click a square to dig &nbsp;•&nbsp; right click to flag it',
            'On a phone: tap to dig, press and hold to flag',
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> move &nbsp;•&nbsp; <span class="key">SPACE</span> dig &nbsp;•&nbsp; <span class="key">F</span> flag',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "The number on a square says how many of the eight squares around it are mines.",
            "A square with no number has no mines near it at all — so its neighbours open too.",
            "Your <strong>first click is always safe</strong>. Dig anywhere to start.",
            "You win by opening every square that is not a mine. Flags are just notes to yourself.",
        ]),
        ("🏆 Getting good", [
            "If a <strong>1</strong> already has one flag beside it, every other neighbour is safe.",
            "If a <strong>3</strong> has exactly three covered neighbours, all three are mines.",
            "Work along the edges of the opened area — that is where the clues are.",
            "Stuck? There is usually a square somewhere else you can still work out.",
        ]),
    ],
    js_files=["mines-rules.js", "mines-draw.js", "mines-main.js"],
    py_files=["mines_rules.py", "mines_draw.py", "mines_web.py"],
    py_workshop_files=["mines_rules.py", "mines_draw.py", "mines_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/mines-rules.js", "The rules: the neighbours, the mines, the flood fill",
         "<code>neighbours</code>, <code>countMines</code>, <code>placeMines</code>, <code>revealCell</code>"),
        ("lib/mines-draw.js", "Painting the squares, the flags and the mines",
         "<code>drawCovered</code>, <code>drawFlag</code>, <code>renderGame</code>"),
        ("lib/mines-main.js", "The glue: left click, right click, long press",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/mines_rules.py", "The rules: the neighbours, the mines, the flood fill",
         "<code>neighbours</code>, <code>count_mines</code>, <code>place_mines</code>, <code>reveal_cell</code>"),
        ("pylib/mines_draw.py", "Painting the board — Python calling the canvas",
         "<code>draw_covered</code>, <code>draw_flag</code>, <code>render_game</code>"),
        ("pylib/mines_web.py", "The glue: left click, right click, the clock",
         "<code>do_action</code>, <code>on_right_click</code>, <code>frame</code>"),
    ],
    big_idea="<strong>flood fill</strong>. Keep a to-do list of squares; take one off, deal with it, and if it is blank put its neighbours on the list. When the list is empty you are finished. That is how one click opens a whole field — and how the paint bucket works in every drawing program.",
    step_count=7,
    py_steps_const="MINES_PYTHON_STEPS",
    next_challenge="add a bigger board with more mines, count how many flags are in the right place, or write a solver that finds the safe squares for you.",
    footer="Your first click is always safe. 💣",
)
