"""The description of the Reaction Test, used to build its four pages."""

SPEC = dict(
    slug="reaction",
    name="Reaction Test",
    icon="⚡",
    title="REACTION TEST",
    subtitle="Wait for the black, then press. How fast are you really?",
    python_subtitle="The same test — but the stopwatch is Python",
    canvas_id="reaction-board", canvas_width=320, canvas_height=300,
    hud=[("Last go", "last", "—"), ("Average", "average", "—"),
         ("Goes", "goes", "0"), ("Best", "best", "—")],
    play_label="⏸ Pause",
    touchpad=[[("btn-press", "PRESS")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">SPACE</span> or <span class="key">ENTER</span> — that is the whole game',
            'Clicking or tapping the panel works too',
            '<span class="key">R</span> clear the scores &nbsp;•&nbsp; <span class="key">P</span> pause',
            'The panel reacts the moment your finger goes DOWN, not when it comes up.',
        ]),
        ("🎯 How to play", [
            "Press once to arm it. The panel says <strong>WAIT…</strong>",
            "After a random pause the panel turns <strong>solid black</strong>. Press!",
            "Press before it turns black and it does not count — that is a false start.",
            "The bar chart shows your last eight goes, with your best one filled in.",
        ]),
        ("🏆 What is a good time?", [
            "The average grown-up is about <strong>250 ms</strong>.",
            "Under <strong>200 ms</strong> is genuinely fast.",
            "Under <strong>150 ms</strong> usually means you guessed — and got lucky.",
            "Watch the panel, not your hand. And do not blink.",
        ]),
    ],
    js_files=["reaction-rules.js", "reaction-draw.js", "reaction-main.js"],
    py_files=["reaction_rules.py", "reaction_draw.py", "reaction_web.py"],
    py_workshop_files=["reaction_rules.py", "reaction_draw.py", "reaction_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/reaction-rules.js", "The rules: the phases, the delay, the stopwatch",
         "<code>randomDelay</code>, <code>updateGame</code>, <code>press</code>, <code>averageTime</code>"),
        ("lib/reaction-draw.js", "Painting the signal panel and the bar chart",
         "<code>panelWords</code>, <code>drawPanel</code>, <code>drawHistory</code>"),
        ("lib/reaction-main.js", "The glue: the keyboard and the panel",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/reaction_rules.py", "The rules: the phases, the delay, the stopwatch",
         "<code>random_delay</code>, <code>update_game</code>, <code>press</code>, <code>average_time</code>"),
        ("pylib/reaction_draw.py", "Painting the panel — Python calling the canvas",
         "<code>panel_words</code>, <code>draw_panel</code>, <code>draw_history</code>"),
        ("pylib/reaction_web.py", "The glue: the keyboard and the panel",
         "<code>do_action</code>, <code>on_press</code>, <code>frame</code>"),
    ],
    big_idea="a <strong>phase</strong>. This game is always in exactly one of five states, and every single rule starts by asking which one. One button means five different things — and the code stays simple because each branch only has to worry about its own case.",
    step_count=5,
    py_steps_const="REACTION_PYTHON_STEPS",
    next_challenge="add a two-player mode with a key each, make the panel show a shape you have to match, or record how much you improve over twenty goes.",
    footer="Watch the panel. Do not blink. ⚡",
)
