"""The description of the Simon Says game, used to build its four pages."""

SPEC = dict(
    slug="simon",
    name="Simon Says",
    icon="🎵",
    title="SIMON SAYS",
    subtitle="Watch the pattern, then play it back — one pad longer every round",
    python_subtitle="The same memory game — but every line of it is Python, running in your browser",
    canvas_id="simon-board", canvas_width=294, canvas_height=294,
    hud=[("Round", "round", "1"), ("Score", "score", "0"),
         ("Length", "length", "1"), ("Best round", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-pad0", "1"), ("btn-pad1", "2")],
              [("btn-pad2", "3"), ("btn-pad3", "4")]],
    help=[
        ("⌨️ Controls", [
            'Click or tap a pad — or use <span class="key">1</span> <span class="key">2</span> <span class="key">3</span> <span class="key">4</span>',
            '<span class="key">Q</span> <span class="key">W</span> <span class="key">A</span> <span class="key">S</span> work too, as do the arrow keys',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
            'Presses during the flashing are ignored — wait for YOUR TURN.',
        ]),
        ("🎯 How to play", [
            "The game flashes a pattern of pads. Watch carefully.",
            "When it says <strong>YOUR TURN</strong>, press the same pads in the same order.",
            "Get it right and the pattern grows by one and flashes again.",
            "One wrong pad ends the game — so take your time on the early rounds.",
        ]),
        ("🏆 Scoring", [
            "Finishing a round is worth <strong>10 × the round number</strong>.",
            "Round 1 flashes each pad for 620 ms; by round 15 it is down to 260.",
            "Most people manage 5 or 6. Ten is genuinely impressive.",
            "Tip: say the numbers out loud as they flash. It really works.",
        ]),
    ],
    js_files=["simon-rules.js", "simon-draw.js", "simon-main.js"],
    py_files=["simon_rules.py", "simon_draw.py", "simon_web.py"],
    py_workshop_files=["simon_rules.py", "simon_draw.py", "simon_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/simon-rules.js", "The rules: the sequence, the checking, the phases",
         "<code>addStep</code>, <code>isCorrectSoFar</code>, <code>pressPad</code>, <code>updateGame</code>"),
        ("lib/simon-draw.js", "Painting the four pads",
         "<code>drawPad</code>, <code>padAtPixel</code>, <code>renderGame</code>"),
        ("lib/simon-main.js", "The glue: clicks, keyboard, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/simon_rules.py", "The rules: the sequence, the checking, the phases",
         "<code>add_step</code>, <code>is_correct_so_far</code>, <code>press_pad</code>, <code>update_game</code>"),
        ("pylib/simon_draw.py", "Painting the pads — Python calling the canvas",
         "<code>draw_pad</code>, <code>pad_at_pixel</code>, <code>render_game</code>"),
        ("pylib/simon_web.py", "The glue: clicks, keyboard, the loop",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="the game is always in one of three <strong>phases</strong> — watching, playing, or over — and almost every rule starts by asking which one it is in. A little word like <code>phase</code> can organise a whole program.",
    step_count=6,
    py_steps_const="SIMON_PYTHON_STEPS",
    next_challenge="add a sound for each pad, let two players take turns, or add a strict mode where one mistake sends you back to round 1.",
    footer="Say the numbers out loud. It really helps. 🎵",
)
