"""The description of the Sokoban game, used to build its four pages."""

SPEC = dict(
    slug="sokoban",
    name="Sokoban",
    icon="📦",
    title="SOKOBAN",
    subtitle="Push every crate onto a ring — you can push, but never pull",
    python_subtitle="The same warehouse — but every push is worked out in Python",
    canvas_id="sokoban-board", canvas_width=356, canvas_height=254,
    hud=[("Level", "level", "1 / 6"), ("Moves", "moves", "0"),
         ("Boxes home", "boxes", "0 / 1"), ("Solved", "solved", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲"), ("btn-undo", "↶ UNDO")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")],
              [("btn-next", "➜ NEXT")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> or <span class="key">W</span> <span class="key">A</span> <span class="key">S</span> <span class="key">D</span> walk',
            'Tapping the board walks one step towards where you tapped',
            '<span class="key">U</span>, <span class="key">Z</span> or <span class="key">BACKSPACE</span> undo &nbsp;•&nbsp; <span class="key">R</span> start the level again',
            '<span class="key">N</span> or <span class="key">ENTER</span> next level &nbsp;•&nbsp; <span class="key">P</span> pause',
        ]),
        ("🎯 How to play", [
            "Push every crate onto a ring. A crate standing on a ring is filled in solid.",
            "You can only <strong>push</strong>. There is no way to pull a crate back.",
            "Push a crate into a corner and it is stuck there for good — undo is your friend.",
            "Six levels, getting harder. The last one needs sixteen moves.",
        ]),
        ("🧠 Thinking ahead", [
            "Look at where each crate has to end up <em>before</em> you touch it.",
            "A crate against a wall can only slide along that wall — never away from it.",
            "Work out which side of a crate you need to stand on, and go there first.",
            "Stuck? <span class=\"key\">U</span> as many times as you like. It costs nothing.",
        ]),
    ],
    js_files=["sokoban-rules.js", "sokoban-draw.js", "sokoban-main.js"],
    py_files=["sokoban_rules.py", "sokoban_draw.py", "sokoban_web.py"],
    py_workshop_files=["sokoban_rules.py", "sokoban_draw.py", "sokoban_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/sokoban-rules.js", "The rules: the levels, the pushing, the undo",
         "<code>isWall</code>, <code>boxAt</code>, <code>movePlayer</code>, <code>undoMove</code>"),
        ("lib/sokoban-draw.js", "Painting the walls, the crates and the player",
         "<code>drawWall</code>, <code>drawBox</code>, <code>renderGame</code>"),
        ("lib/sokoban-main.js", "The glue: the keyboard, the taps, the buttons",
         "<code>doAction</code>, <code>connectBoard</code>, <code>setUpGame</code>"),
    ],
    py_coder_rows=[
        ("pylib/sokoban_rules.py", "The rules: the levels, the pushing, the undo",
         "<code>is_wall</code>, <code>box_at</code>, <code>move_player</code>, <code>undo_move</code>"),
        ("pylib/sokoban_draw.py", "Painting the warehouse — Python calling the canvas",
         "<code>draw_wall</code>, <code>draw_box</code>, <code>render_game</code>"),
        ("pylib/sokoban_web.py", "The glue: the keyboard, the taps, the buttons",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="a <strong>stack</strong> gives you undo for free. Before every move, save a copy of everything and pile it up. Undo takes the top copy off and puts it back. That is how the undo button works in every program you have ever used.",
    step_count=6,
    py_steps_const="SOKOBAN_PYTHON_STEPS",
    next_challenge="draw your own level as a picture and add it to the list, count the fewest moves you can solve each one in, or write a checker that spots when a crate is stuck in a corner.",
    footer="Push, never pull. And undo is free. 📦",
)
