"""The description of the tictactoe game, used to build its four pages."""

SPEC = dict(
    slug="tictactoe",
    name="Tic-Tac-Toe",
    icon="⭕",
    title="TIC-TAC-TOE",
    subtitle="Three in a row — against a computer that never loses",
    python_subtitle="The same game — but every line of it is Python, running in your browser",
    canvas_id="tictactoe-board", canvas_width=324, canvas_height=324,
    hud=[("You", "wins", "0"), ("Computer", "losses", "0"), ("Draws", "draws", "0")],
    play_label="⏸ Pause",
    touchpad=[[None, ("btn-up", "↑"), None],
              [("btn-left", "←"), ("btn-play", "Play"), ("btn-right", "→")],
              [None, ("btn-down", "↓"), None]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> <span class="key">↑</span> <span class="key">↓</span> move the dashed cursor',
            '<span class="key">Space</span> or <span class="key">Enter</span> play there',
            'Clicking or tapping a square works too',
            '<span class="key">R</span> next round &nbsp;•&nbsp; <span class="key">P</span> pause',
        ]),
        ("🎯 How to play", [
            "You are <strong>X</strong> and you always go first.",
            "Get three in a row — across, down or diagonally.",
            "The computer replies straight away, so every tap is a whole turn.",
            "The scoreboard keeps count across rounds.",
        ]),
        ("🤖 How the computer thinks", [
            "1. If it can win this turn, it wins.",
            "2. If you are about to win, it blocks you.",
            "3. Otherwise it takes the middle — that square is on four lines.",
            "4. Otherwise a corner, which is on three.",
            "Those four rules are enough that it <strong>never loses</strong>. A draw is a win for you!",
        ]),
    ],
    js_files=["tictactoe-rules.js", "tictactoe-draw.js", "tictactoe-main.js"],
    py_files=["tictactoe_rules.py", "tictactoe_draw.py", "tictactoe_web.py"],
    py_workshop_files=["tictactoe_rules.py", "tictactoe_draw.py", "tictactoe_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/tictactoe-rules.js", "The rules, and the computer's brain",
         "<code>winningLine</code>, <code>isDraw</code>, <code>computerMove</code>"),
        ("lib/tictactoe-draw.js", "Painting the grid, the Xs and the Os",
         "<code>drawMark</code>, <code>drawWinningLine</code>, <code>squareAtPixel</code>"),
        ("lib/tictactoe-main.js", "The glue: clicks, keyboard, the scoreboard",
         "<code>doAction</code>, <code>connectBoard</code>, <code>updateScoreboard</code>"),
    ],
    py_coder_rows=[
        ("pylib/tictactoe_rules.py", "The rules, and the computer's brain",
         "<code>winning_line</code>, <code>is_draw</code>, <code>computer_move</code>"),
        ("pylib/tictactoe_draw.py", "Painting the board — Python calling the canvas",
         "<code>draw_mark</code>, <code>draw_winning_line</code>, <code>square_at_pixel</code>"),
        ("pylib/tictactoe_web.py", "The glue: clicks, keyboard, the scoreboard",
         "<code>do_action</code>, <code>on_board_click</code>, <code>start_game</code>"),
    ],
    big_idea="the computer plays by <em>trying</em> a move on a copy of the board and seeing what happens. That is why <code>placeMark</code> returns a new board instead of changing the old one — it lets you imagine a move without making it.",
    step_count=7,
    py_steps_const="TICTACTOE_PYTHON_STEPS",
    next_challenge="let two people play, add a 4 x 4 board, or make the computer easier by having it play randomly some of the time.",
    footer="A perfect game of noughts and crosses is always a draw. ⭕",
)
