"""The description of the 2048 game, used to build its four pages."""

SPEC = dict(
    slug="twenty48",
    name="2048",
    icon="🔢",
    title="2048",
    subtitle="Slide, join, and keep doubling until you reach 2048",
    python_subtitle="The same puzzle — but every slide and merge is Python",
    canvas_id="twenty48-board", canvas_width=284, canvas_height=284,
    hud=[("Score", "score", "0"), ("Biggest", "biggest", "2"),
         ("Moves", "moves", "0"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-up", "▲")],
              [("btn-left", "◀"), ("btn-down", "▼"), ("btn-right", "▶")]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">↑</span> <span class="key">↓</span> <span class="key">←</span> <span class="key">→</span> or <span class="key">W</span> <span class="key">A</span> <span class="key">S</span> <span class="key">D</span> slide everything',
            'On a phone: swipe the board',
            '<span class="key">SPACE</span> keep playing after you reach 2048',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "Every slide moves <strong>all</strong> the tiles as far as they can go.",
            "Two tiles with the same number join into one worth double.",
            "A new tile appears after every move that changed something.",
            "A tile can only join once per move — four 2s become two 4s, not one 8.",
        ]),
        ("🏆 Getting good", [
            "Pick a corner and keep your biggest tile there. Never move it out.",
            "Use three directions and avoid the fourth — that keeps the big tile put.",
            "Build a row in order along one edge: 2, 4, 8, 16…",
            "The game is over only when there are no gaps <em>and</em> no equal neighbours.",
        ]),
    ],
    js_files=["twenty48-rules.js", "twenty48-draw.js", "twenty48-main.js"],
    py_files=["twenty48_rules.py", "twenty48_draw.py", "twenty48_web.py"],
    py_workshop_files=["twenty48_rules.py", "twenty48_draw.py", "twenty48_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/twenty48-rules.js", "The rules: sliding, joining, turning",
         "<code>slideRow</code>, <code>mergeRow</code>, <code>rotateBoard</code>, <code>moveBoard</code>"),
        ("lib/twenty48-draw.js", "Painting the tiles and their numbers",
         "<code>tileLook</code>, <code>drawTile</code>, <code>renderGame</code>"),
        ("lib/twenty48-main.js", "The glue: the arrow keys and finger swipes",
         "<code>doAction</code>, <code>connectSwipe</code>, <code>setUpGame</code>"),
    ],
    py_coder_rows=[
        ("pylib/twenty48_rules.py", "The rules: sliding, joining, turning",
         "<code>slide_row</code>, <code>merge_row</code>, <code>rotate_board</code>, <code>move_board</code>"),
        ("pylib/twenty48_draw.py", "Painting the tiles — Python calling the canvas",
         "<code>tile_look</code>, <code>draw_tile</code>, <code>render_game</code>"),
        ("pylib/twenty48_web.py", "The glue: the arrow keys and finger swipes",
         "<code>do_action</code>, <code>on_touch_end</code>, <code>start_game</code>"),
    ],
    big_idea="write <strong>one</strong> move, not four. Sliding left is the only direction this game really knows; the other three are done by turning the board round, sliding left, and turning it back. One function to get right, one place for a bug to hide.",
    step_count=7,
    py_steps_const="TWENTY48_PYTHON_STEPS",
    next_challenge="add an undo button, make a 5×5 board, or show the tiles sliding smoothly instead of jumping.",
    footer="Keep your biggest tile in a corner. 🔢",
)
