"""The description of the Typing Race game, used to build its four pages."""

SPEC = dict(
    slug="typing",
    name="Typing Race",
    icon="⌨️",
    title="TYPING RACE",
    subtitle="Twenty-four words, sixty seconds — how fast can you go?",
    python_subtitle="The same race — but the speed and accuracy are worked out in Python",
    canvas_id="typing-board", canvas_width=340, canvas_height=278,
    hud=[("Speed", "wpm", "0"), ("Accuracy", "accuracy", "100%"),
         ("Words done", "words", "0"), ("Best WPM", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[("btn-keyboard", "⌨ TAP TO TYPE")]],
    hidden_input=True,
    help=[
        ("⌨️ Controls", [
            'Just start typing — the clock starts with your first letter',
            '<span class="key">SPACE</span> after each word',
            '<span class="key">BACKSPACE</span> to fix a letter',
            '<span class="key">ENTER</span> a new race &nbsp;•&nbsp; <span class="key">ESC</span> pause',
        ]),
        ("🎯 How to play", [
            "Type the boxed word, then press space. Right or wrong, the race moves on.",
            "Your typing turns black as it matches — and gets struck through when it does not.",
            "The bar shows the minute running out.",
            "The race ends after 24 words or 60 seconds, whichever comes first.",
        ]),
        ("🏆 What is a good speed?", [
            "A \"word\" means <strong>five characters</strong> — that is how typists have always counted.",
            "<strong>20 WPM</strong> is a good start. <strong>40</strong> is proper touch typing.",
            "Accuracy beats speed: a wrong word is worth nothing at all.",
            "Do not look at your hands. It feels slower and it is much faster.",
        ]),
    ],
    js_files=["typing-rules.js", "typing-draw.js", "typing-main.js"],
    py_files=["typing_rules.py", "typing_draw.py", "typing_web.py"],
    py_workshop_files=["typing_rules.py", "typing_draw.py", "typing_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/typing-rules.js", "The rules: matching letters and working out the speed",
         "<code>matchingLetters</code>, <code>submitWord</code>, <code>accuracy</code>, <code>wordsPerMinute</code>"),
        ("lib/typing-draw.js", "Painting the words, the typing and the clock",
         "<code>layoutWords</code>, <code>drawTyped</code>, <code>renderGame</code>"),
        ("lib/typing-main.js", "The glue: the keyboard and the on-screen one",
         "<code>doAction</code>, <code>connectKeyboard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/typing_rules.py", "The rules: matching letters and working out the speed",
         "<code>matching_letters</code>, <code>submit_word</code>, <code>accuracy</code>, <code>words_per_minute</code>"),
        ("pylib/typing_draw.py", "Painting the page — Python calling the canvas",
         "<code>layout_words</code>, <code>draw_typed</code>, <code>render_game</code>"),
        ("pylib/typing_web.py", "The glue: the keyboard and the on-screen one",
         "<code>do_action</code>, <code>on_hidden_input</code>, <code>frame</code>"),
    ],
    big_idea="<strong>check before you divide</strong>. Accuracy divides by the words attempted, and speed divides by the seconds gone by — and at the very start of a race both of those are zero. Two lines of guard turn a crash into a sensible answer.",
    step_count=5,
    py_steps_const="TYPING_PYTHON_STEPS",
    next_challenge="type real sentences instead of single words, show which letters you get wrong most often, or race against your own best run.",
    footer="Accuracy first. Speed follows. ⌨️",
)
