"""The description of the Whack-a-Mole game, used to build its four pages."""

SPEC = dict(
    slug="whack",
    name="Whack-a-Mole",
    icon="🔨",
    title="WHACK-A-MOLE",
    subtitle="Nine holes, one mole, forty-five seconds — how fast are you really?",
    python_subtitle="The same game — but every line of it is Python, running in your browser",
    canvas_id="whack-board", canvas_width=336, canvas_height=336,
    hud=[("Score", "score", "0"), ("Hits", "hits", "0"), ("Time", "time", "45"),
         ("Level", "level", "1"), ("Best", "best", "0")],
    play_label="⏸ Pause",
    touchpad=[[None, ("btn-up", "↑"), None],
              [("btn-left", "←"), ("btn-whack", "Whack!"), ("btn-right", "→")],
              [None, ("btn-down", "↓"), None]],
    help=[
        ("⌨️ Controls", [
            '<span class="key">←</span> <span class="key">→</span> <span class="key">↑</span> <span class="key">↓</span> aim the hammer',
            '<span class="key">Space</span> or <span class="key">Enter</span> swing',
            'Clicking or tapping a hole works too — much faster!',
            '<span class="key">P</span> pause &nbsp;•&nbsp; <span class="key">R</span> new game',
        ]),
        ("🎯 How to play", [
            "A mole pops out of one hole at a time. Hit it before it ducks back down.",
            "You have <strong>45 seconds</strong>.",
            "Every 5 hits you go up a level — and the moles get quicker.",
            "A miss does not move the mole, so hitting every hole in turn will not help you.",
        ]),
        ("🏆 Scoring", [
            "Each mole is worth <strong>10 × your level</strong>.",
            "Level 1 moles wait 1100 ms; level 10 moles wait only 350.",
            "So the points really pile up once you get going — the last ten seconds are worth more than the first thirty.",
        ]),
    ],
    js_files=["whack-rules.js", "whack-draw.js", "whack-main.js"],
    py_files=["whack_rules.py", "whack_draw.py", "whack_web.py"],
    py_workshop_files=["whack_rules.py", "whack_draw.py", "whack_demo.py", "workshop_support.py"],
    js_coder_rows=[
        ("lib/whack-rules.js", "The rules: the mole, the clock, the scoring",
         "<code>randomHole</code>, <code>moleInterval</code>, <code>whack</code>, <code>updateGame</code>"),
        ("lib/whack-draw.js", "Painting the holes and the mole",
         "<code>drawHole</code>, <code>drawMole</code>, <code>holeAtPixel</code>"),
        ("lib/whack-main.js", "The glue: clicks, keyboard, the loop",
         "<code>doAction</code>, <code>connectBoard</code>, <code>gameLoop</code>"),
    ],
    py_coder_rows=[
        ("pylib/whack_rules.py", "The rules: the mole, the clock, the scoring",
         "<code>random_hole</code>, <code>mole_interval</code>, <code>whack</code>, <code>update_game</code>"),
        ("pylib/whack_draw.py", "Painting the mole — Python calling the canvas",
         "<code>draw_hole</code>, <code>draw_mole</code>, <code>hole_at_pixel</code>"),
        ("pylib/whack_web.py", "The glue: clicks, keyboard, the loop",
         "<code>do_action</code>, <code>on_board_click</code>, <code>frame</code>"),
    ],
    big_idea="a <strong>timer</strong> is all that separates a board game from an arcade game. <code>updateGame</code> counts milliseconds and moves the mole when enough have passed — the same idea makes Tetris fall and the racing road scroll.",
    step_count=6,
    py_steps_const="WHACK_PYTHON_STEPS",
    next_challenge="add a second mole, a bomb you must NOT hit, or a combo bonus for three hits in a row.",
    footer="Nine holes, one hammer, forty-five seconds. 🔨",
)
