#!/usr/bin/env python3
import csv
from collections import Counter

path = "/Users/yyw/github/kidslearn/spelling/classical-roots/vocabulary_from_classical_roots_words_c.csv"

rows = [
    # ── Lesson 1 ──────────────────────────────────────────────
    (1,"anthropology","an-thruh-POL-uh-jee","noun","the study of human societies, cultures, and origins","Anthropology helped her understand the customs of ancient civilizations."),
    (1,"autocrat","AW-toh-krat","noun","a ruler who has absolute power","The autocrat ruled the country without any regard for its citizens' rights."),
    (1,"automaton","aw-TOM-uh-ton","noun","a moving mechanical device that resembles a human; a person who acts mechanically","The workers on the assembly line moved like automatons, repeating the same motions endlessly."),
    (1,"autonomy","aw-TON-uh-mee","noun","the right or condition of self-government; personal independence","The teenager yearned for more autonomy and less supervision from her parents."),
    (1,"autopsy","AW-top-see","noun","an examination of a body after death to determine the cause of death","The medical examiner performed an autopsy to establish the exact cause of death."),
    (1,"egoism","EE-goh-iz-um","noun","the habit of valuing everything only in relation to one's personal interest; self-centeredness","His egoism prevented him from ever truly listening to those around him."),
    (1,"feminism","FEM-ih-niz-um","noun","the advocacy of women's rights and equality with men","The history class covered the key figures in the early feminism movement."),
    (1,"feminist","FEM-ih-nist","noun/adjective","a person who advocates for women's rights and equality","She became a passionate feminist after studying the history of women's suffrage."),
    (1,"gynecology","gy-nuh-KOL-uh-jee","noun","the branch of medicine dealing with the health of the female reproductive system","She chose to specialize in gynecology after completing her medical degree."),
    (1,"homicide","HOM-ih-syd","noun","the killing of one person by another","The detective was assigned to investigate the homicide that occurred near the waterfront."),
    (1,"humane","hyoo-MAYN","adjective","having compassion and benevolence toward people or animals","The organization's mission was to promote humane treatment of all living creatures."),
    (1,"humanism","HYOO-muh-niz-um","noun","a philosophy that emphasizes human reason, dignity, and potential","Renaissance humanism shifted intellectual focus from divine authority to human capability."),
    (1,"humanities","hyoo-MAN-ih-teez","noun","academic subjects such as literature, philosophy, art, and history","She majored in the humanities because she loved studying literature, art, and history."),
    (1,"misanthrope","MIS-un-throhp","noun","a person who dislikes and distrusts other people in general","The misanthrope rarely left his house and avoided all social interaction."),
    (1,"virile","VIR-ul","adjective","having strength and vigor; strongly masculine","The novel's hero was portrayed as virile, courageous, and resourceful."),
    # ── Lesson 2 ──────────────────────────────────────────────
    (2,"congenital","kun-JEN-ih-tul","adjective","present from birth; innate","The child was born with a congenital heart defect that required surgery."),
    (2,"engender","en-JEN-der","verb","to cause or give rise to a feeling or situation","The mayor's speech was meant to engender trust between citizens and police."),
    (2,"genealogy","jee-nee-AL-uh-jee","noun","the study of family origins and history; a line of descent","He spent years tracing his genealogy and discovered relatives on three continents."),
    (2,"genesis","JEN-ih-sis","noun","the origin or beginning of something","The documentary traced the genesis of jazz back to New Orleans in the early 1900s."),
    (2,"genocide","JEN-uh-syd","noun","the deliberate killing of a large group based on ethnicity or nationality","The international tribunal was established to prosecute those responsible for genocide."),
    (2,"genre","ZHON-ruh","noun","a category of artistic composition characterized by a particular style or subject matter","Mystery is her favorite literary genre because she loves solving puzzles."),
    (2,"genteel","jen-TEEL","adjective","polite and refined in manner; characteristic of the upper class","The genteel hostess greeted every guest with practiced elegance."),
    (2,"gentile","JEN-tyl","noun/adjective","a person who is not Jewish; relating to non-Jewish people","The ancient text described customs observed by both Jewish people and gentiles."),
    (2,"gentry","JEN-tree","noun","people of good social position just below the nobility; the upper class","The local gentry attended the annual ball held at the manor house."),
    (2,"heterogeneous","het-er-oh-JEE-nee-us","adjective","diverse in character or content; made up of different kinds","The class was a heterogeneous group of students from many different backgrounds."),
    (2,"homogeneous","hoh-moh-JEE-nee-us","adjective","of the same kind; uniform in structure or composition","The neighborhood had once been a homogeneous community but had grown more diverse over time."),
    (2,"indigenous","in-DIJ-uh-nus","adjective","originating or occurring naturally in a particular place; native","The museum featured artifacts from indigenous peoples who had lived in the region for thousands of years."),
    (2,"ingenious","in-JEEN-yus","adjective","clever, original, and inventive","The engineer devised an ingenious solution to the drainage problem."),
    (2,"progenitor","proh-JEN-ih-ter","noun","a person or thing from which others descend or originate; an ancestor","Historians consider Darwin the progenitor of modern evolutionary theory."),
    (2,"progeny","PROJ-uh-nee","noun","a person's offspring or descendants","The wealthy patriarch divided his estate equally among his progeny."),
    # ── Lesson 3 ──────────────────────────────────────────────
    (3,"avuncular","uh-VUNK-yuh-ler","adjective","relating to an uncle; kind and friendly toward younger people","The avuncular professor always had time to offer advice to struggling students."),
    (3,"bigamy","BIG-uh-mee","noun","the offense of marrying someone while already married to another person","He was charged with bigamy after it was discovered he had two wives in different cities."),
    (3,"familial","fuh-MIL-ee-ul","adjective","relating to or characteristic of a family","The reunion centered on familial bonds that years of distance had not weakened."),
    (3,"fraternal","fruh-TUR-nul","adjective","relating to brothers; brotherly in nature","The two soldiers shared a fraternal bond forged through years of service together."),
    (3,"fraternize","FRAT-er-nyz","verb","to associate or form a friendship with others especially when this is discouraged","The opposing players were seen fraternizing on the field after the game."),
    (3,"matriarchy","MAY-tree-ar-kee","noun","a system of society or government ruled by women","Some anthropologists have described ancient Minoan society as a matriarchy."),
    (3,"matriculate","muh-TRIK-yuh-layt","verb","to be enrolled at a college or university","She was the first in her family to matriculate at a four-year university."),
    (3,"matrix","MAY-triks","noun","an environment in which something develops; a rectangular array of numbers","The city's transportation grid formed the matrix on which the whole economy depended."),
    (3,"monogamy","muh-NOG-uh-mee","noun","the practice of being married to only one person at a time","Most Western legal systems are built around the expectation of monogamy."),
    (3,"patriarch","PAY-tree-ark","noun","a man who rules a family or group; a founder or father figure","The elderly patriarch presided over every family gathering with quiet authority."),
    (3,"patrimony","PA-trih-moh-nee","noun","property or cultural legacy inherited from one's father or ancestors","The old estate had been part of the family's patrimony for two centuries."),
    (3,"patronage","PAY-truh-nij","noun","the support given by a patron to an artist or institution; regular business given to a shop","The museum depended heavily on the patronage of wealthy local donors."),
    (3,"patronize","PAY-truh-nyz","verb","to treat in a condescending way; to be a regular customer of","She refused to patronize any store that treated its workers poorly."),
    (3,"patronymic","pa-truh-NIM-ik","noun/adjective","a name derived from one's father's name; relating to such a name","In many cultures a patronymic surname links children directly to their fathers."),
    (3,"uxorious","uk-SOR-ee-us","adjective","excessively fond of or submissive to one's wife","His uxorious behavior earned teasing from friends who joked he never made a decision without consulting her."),
    # ── Lesson 4 ──────────────────────────────────────────────
    (4,"entity","EN-tih-tee","noun","a thing with distinct and independent existence","The corporation was recognized as a legal entity separate from its owners."),
    (4,"essence","ES-ens","noun","the intrinsic nature of something; the most important quality","Simplicity is the essence of good design."),
    (4,"euthanasia","yoo-thuh-NAY-zhuh","noun","the painless killing of a patient suffering from an incurable illness","The ethics of euthanasia continues to be debated by medical professionals and lawmakers."),
    (4,"innate","ih-NAYT","adjective","inborn; existing from birth; natural","She had an innate talent for music that no formal training could fully explain."),
    (4,"moribund","MOR-ih-bund","adjective","at the point of death; in terminal decline","The once-thriving newspaper industry appeared moribund in the digital age."),
    (4,"mortify","MOR-tih-fy","verb","to cause someone to feel deeply embarrassed or ashamed","He was mortified when he tripped and fell in front of the entire school."),
    (4,"naive","nah-EEV","adjective","showing a lack of experience or wisdom; innocent and unsuspecting","It was naive of her to trust a stranger with her personal information."),
    (4,"nascent","NAY-sent","adjective","just coming into existence; beginning to develop","The nascent technology company had only five employees and one product."),
    (4,"nonentity","non-EN-tih-tee","noun","a person or thing of no importance","Before his breakthrough role the actor had been a complete nonentity in Hollywood."),
    (4,"orthopedics","or-thoh-PEE-diks","noun","the branch of medicine dealing with the correction of bone and muscle deformities","After the accident she was referred to an orthopedics specialist for her broken wrist."),
    (4,"pedagogue","PED-uh-gog","noun","a teacher especially one who is overly formal or strict","The old pedagogue demanded perfect grammar in every written assignment."),
    (4,"pedant","PED-unt","noun","a person excessively concerned with rules and minor details","The pedant corrected every grammatical slip in casual conversation much to everyone's annoyance."),
    (4,"postmortem","pohst-MOR-tum","noun/adjective","an examination performed after death; an analysis done after an event is over","The team held a postmortem review to understand why the project had failed."),
    (4,"puerile","PYOO-er-ul","adjective","childishly silly and immature","His puerile jokes were met with eye rolls from the adults in the room."),
    (4,"renaissance","REN-uh-sahns","noun","a revival or renewed interest especially in culture, art, and learning","The city experienced a cultural renaissance after the new arts district opened."),
    # ── Lesson 5 ──────────────────────────────────────────────
    (5,"acrophobia","ak-roh-FOH-bee-uh","noun","an extreme or irrational fear of heights","His acrophobia made it impossible for him to climb even a short ladder."),
    (5,"amicable","AM-ih-kuh-bul","adjective","having a friendly and pleasant manner; showing goodwill","After months of dispute the neighbors reached an amicable agreement."),
    (5,"amity","AM-ih-tee","noun","a friendly relationship between people or countries","The treaty was signed in a spirit of international amity."),
    (5,"appease","uh-PEEZ","verb","to relieve or satisfy a demand by making concessions; to soothe","She brought cookies to the meeting hoping to appease her irritated colleagues."),
    (5,"bibliophile","BIB-lee-oh-fyl","noun","a person who collects or has a great love of books","The bibliophile's home was packed from floor to ceiling with carefully organized volumes."),
    (5,"enamored","ih-NAM-erd","adjective","filled with love and admiration for someone or something","He was completely enamored of the coastal town and vowed to return every summer."),
    (5,"hydrophobia","hy-droh-FOH-bee-uh","noun","extreme fear of water; a symptom of rabies","The infected animal displayed hydrophobia and refused to drink despite its thirst."),
    (5,"inimical","ih-NIM-ih-kul","adjective","tending to obstruct or harm; hostile","Sitting for twelve hours a day is inimical to good health."),
    (5,"odious","OH-dee-us","adjective","extremely unpleasant; offensive or repulsive","The odious smell from the landfill drifted across the entire neighborhood."),
    (5,"pacific","puh-SIF-ik","adjective","peaceful in character or intent; tending to avoid conflict","She had a pacific personality and always sought compromise over confrontation."),
    (5,"pacify","PAS-ih-fy","verb","to bring peace or calm to a situation or person","The parents tried to pacify the crying child with a favorite toy."),
    (5,"philanthropy","fih-LAN-thruh-pee","noun","the desire to promote the well-being of others especially through charitable donations","His philanthropy funded hospitals and schools across three continents."),
    (5,"phobia","FOH-bee-uh","noun","an extreme or irrational fear of or aversion to something","She developed a phobia of flying after a turbulent flight as a child."),
    (5,"xenophobia","zen-oh-FOH-bee-uh","noun","a deep dislike or fear of foreigners or strangers","The speech was criticized for encouraging xenophobia rather than tolerance."),
    # ── Lesson 6 ──────────────────────────────────────────────
    (6,"antipathy","an-TIP-uh-thee","noun","a deep-seated feeling of aversion or dislike","She felt a strong antipathy toward dishonesty in any form."),
    (6,"apathy","AP-uh-thee","noun","lack of interest, enthusiasm, or concern","Voter apathy reached an all-time high as turnout dropped below thirty percent."),
    (6,"complacent","kum-PLAY-sent","adjective","showing smug or uncritical satisfaction with oneself; not sufficiently alert to danger","The team became complacent after an early lead and nearly lost the game."),
    (6,"covet","KUV-et","verb","to yearn to possess something belonging to another","He tried not to covet his neighbor's brand-new sports car."),
    (6,"cupidity","kyoo-PID-ih-tee","noun","greed for money or possessions","The manager's cupidity led him to embezzle funds from the company over several years."),
    (6,"dysentery","DIS-en-ter-ee","noun","an intestinal infection causing severe diarrhea","Contaminated water supplies led to an outbreak of dysentery in the refugee camp."),
    (6,"dyslexia","dis-LEK-see-uh","noun","a learning difficulty that primarily affects reading and spelling","With proper support children with dyslexia can develop strong reading skills."),
    (6,"empathy","EM-puh-thee","noun","the ability to understand and share the feelings of another","Good counselors must be capable of empathy as well as sound advice."),
    (6,"implacable","im-PLAK-uh-bul","adjective","unable to be appeased; relentlessly harsh","The implacable critic found fault with every performance regardless of its quality."),
    (6,"misogamy","mih-SOG-uh-mee","noun","a dislike or hatred of marriage","His lifelong misogamy meant he preferred the freedom of living alone."),
    (6,"misogyny","mih-SOJ-ih-nee","noun","dislike or prejudice against women","The organization worked to expose and combat misogyny in the workplace."),
    (6,"pathological","path-uh-LOJ-ih-kul","adjective","relating to or caused by disease; compulsive","His pathological need to control every situation made teamwork nearly impossible."),
    (6,"pathos","PAY-thos","noun","a quality that evokes pity, sadness, or sympathy","The final scene of the film was full of pathos that left the audience in tears."),
    (6,"placate","PLAY-kayt","verb","to make someone less angry; to appease","The manager tried to placate the upset client with a full refund."),
    (6,"placid","PLAS-id","adjective","not easily upset or excited; calm and peaceful","The placid surface of the lake reflected the mountains perfectly."),
    # ── Lesson 7 ──────────────────────────────────────────────
    (7,"ablution","uh-BLOO-shun","noun","the act of washing oneself; a ceremonial washing","Morning ablutions were part of his strict daily routine."),
    (7,"deluge","DEL-yooj","noun/verb","a severe flood or heavy rainfall; to overwhelm with a great quantity","The city was deluged with calls after the emergency announcement."),
    (7,"divest","dih-VEST","verb","to deprive someone of power or possessions; to sell off a business interest","The court ordered the company to divest its holdings in the foreign subsidiary."),
    (7,"domain","doh-MAYN","noun","an area of knowledge or activity; a territory controlled by a ruler","Quantum physics is not within the domain of everyday experience."),
    (7,"domestic","duh-MES-tik","adjective","relating to the home; not foreign","She preferred domestic travel to the stress of international airports."),
    (7,"domicile","DOM-ih-syl","noun","a place of permanent residence; a person's home","The legal documents listed the countryside estate as his official domicile."),
    (7,"domineer","dom-ih-NEER","verb","to assert authority over others in an arrogant way","She refused to let her older brother domineer over her decisions."),
    (7,"dominion","duh-MIN-yun","noun","sovereignty or control; a territory under a ruler's power","The ancient empire extended its dominion across most of the known world."),
    (7,"dormant","DOR-ment","adjective","temporarily inactive; in a state of rest or sleep","The volcano had been dormant for centuries before suddenly showing signs of activity."),
    (7,"investiture","in-VES-tih-cher","noun","the formal ceremony of investing a person with an office, rank, or honor","The investiture ceremony celebrated the prince's elevation to his new title."),
    (7,"somnambulate","som-NAM-byuh-layt","verb","to walk and carry out actions while asleep; to sleepwalk","His roommate was alarmed to discover him somnambulating through the halls at midnight."),
    (7,"somnolent","SOM-nuh-lent","adjective","sleepy; inducing drowsiness","The somnolent hum of the air conditioner made it hard to stay awake during the lecture."),
    (7,"travesty","TRAV-uh-stee","noun","a false or distorted representation of something; a mockery","The rushed trial was described as a travesty of justice by human rights observers."),
    (7,"vested","VES-ted","adjective","having a personal stake in or fixed rights to something","She had a vested interest in the outcome because her savings were tied to the company."),
    (7,"vestment","VEST-ment","noun","a robe or garment worn by clergy during a church service","The priest adjusted his vestment before leading the congregation in prayer."),
    # ── Lesson 8 ──────────────────────────────────────────────
    (8,"allude","uh-LOOD","verb","to make an indirect reference to something","Without naming names the speaker alluded to recent scandals in the department."),
    (8,"carnivorous","kar-NIV-er-us","adjective","feeding on other animals; flesh-eating","Lions and tigers are carnivorous animals that hunt prey in the wild."),
    (8,"collusion","kuh-LOO-zhun","noun","secret cooperation for an illegal or deceitful purpose","The investigation uncovered evidence of collusion between the contractors and city officials."),
    (8,"concoct","kun-KOKT","verb","to create or devise by combining ingredients or ideas","She concocted a plausible excuse for arriving late to the meeting."),
    (8,"cuisine","kwih-ZEEN","noun","a style of cooking associated with a particular country or culture","The restaurant offered authentic French cuisine prepared by a classically trained chef."),
    (8,"delusion","dih-LOO-zhun","noun","a belief held despite evidence to the contrary","His delusion that he was being followed made everyday life extremely difficult."),
    (8,"herbivorous","her-BIV-er-us","adjective","feeding on plants","Cows, deer, and rabbits are herbivorous animals that graze on grass and vegetation."),
    (8,"imbibe","im-BYB","verb","to drink especially alcoholic drinks; to absorb ideas","She loved to imbibe the atmosphere of old libraries filled with leather-bound books."),
    (8,"mellifluous","muh-LIF-loo-us","adjective","sweet or musical in sound; pleasingly smooth","The singer's mellifluous voice filled the concert hall with ease."),
    (8,"potable","POH-tuh-bul","adjective","safe to drink","The hikers carried purification tablets to make stream water potable."),
    (8,"potion","POH-shun","noun","a liquid with healing or magical powers; a medicinal drink","The folk tale described a love potion that could make any two people fall in love."),
    (8,"precocious","prih-KOH-shus","adjective","having developed certain abilities at an earlier age than usual","The precocious child was reading chapter books before her fourth birthday."),
    (8,"saline","SAY-lyn","adjective/noun","containing salt; a salt solution used in medical treatment","The nurse administered a saline solution through the patient's IV drip."),
    (8,"voracious","vor-AY-shus","adjective","wanting or devouring great quantities; very eager","He was a voracious reader who finished three novels every week."),
    # ── Lesson 9 ──────────────────────────────────────────────
    (9,"affront","uh-FRUNT","noun/verb","an action or remark that causes offense; to offend publicly","He took her dismissive comment as a personal affront to his professionalism."),
    (9,"capitalist","KAP-ih-tuh-list","noun/adjective","a person who uses wealth to invest in trade; relating to capitalism","As a capitalist he believed that free markets drove innovation and prosperity."),
    (9,"capitulation","kuh-pich-uh-LAY-shun","noun","the act of surrendering or giving in to demands","The capitulation of the fortress ended three months of siege."),
    (9,"cerebral","SER-uh-brul","adjective","relating to the brain; intellectual rather than emotional","Chess is considered a cerebral game that requires careful strategic thinking."),
    (9,"cerebration","ser-uh-BRAY-shun","noun","the working of the brain; thinking","After hours of intense cerebration he finally solved the mathematical puzzle."),
    (9,"confront","kun-FRUNT","verb","to face up to and deal with a problem; to challenge someone directly","She knew she had to confront her fear of public speaking if she wanted to advance."),
    (9,"decapitate","dih-KAP-ih-tayt","verb","to cut off the head of; to behead","History's most notorious tyrants used decapitation as a public punishment."),
    (9,"deface","dih-FAYS","verb","to mar the surface or appearance of something; to vandalize","Vandals defaced the public mural with graffiti overnight."),
    (9,"efface","ih-FAYS","verb","to erase or obliterate; to make oneself inconspicuous","Time had effaced the carved inscription on the ancient stone tablet."),
    (9,"effrontery","ih-FRUN-ter-ee","noun","rude and shameless boldness","The student had the effrontery to demand extra credit after skipping most of the classes."),
    (9,"facade","fuh-SAHD","noun","the front of a building; an outward appearance that hides the true nature","The cheerful facade he presented at work masked his deep personal struggles."),
    (9,"facet","FAS-it","noun","one side of a cut gem; a particular aspect of something","Every facet of the negotiation had to be carefully considered before signing."),
    (9,"precipice","PRES-ih-pis","noun","a very steep rock face or cliff; a dangerous situation","The hikers stood at the edge of the precipice and looked down into the valley."),
    (9,"precipitate","prih-SIP-ih-tayt","verb/adjective","to cause to happen suddenly; done without due deliberation; rash","His precipitate decision to resign without another job lined up shocked his colleagues."),
    (9,"recapitulation","ree-kuh-pich-uh-LAY-shun","noun","a summary or repetition of the main points of something","The final chapter served as a recapitulation of all the book's major themes."),
    # ── Lesson 10 ─────────────────────────────────────────────
    (10,"disgorge","dis-GORJ","verb","to discharge or pour out violently; to eject from the throat","The factory pipe disgorged waste into the river for decades before the violation was discovered."),
    (10,"gargantuan","gar-GAN-choo-un","adjective","enormous; gigantic","The gargantuan cruise ship dwarfed every other vessel in the harbor."),
    (10,"gargoyle","GAR-goyl","noun","a grotesque carved stone figure used as a rainwater spout on buildings","Students sketched the gargoyle perched high on the cathedral's stone facade."),
    (10,"gorge","gorj","noun/verb","a narrow valley with steep rocky walls; to eat greedily","After the long hike he sat down and gorged himself on sandwiches and fruit."),
    (10,"indentation","in-den-TAY-shun","noun","a notch or recess in a surface; a deep inward curve","The first paragraph begins with an indentation of five spaces."),
    (10,"indenture","in-DEN-cher","noun/verb","a formal legal agreement binding one party to work for another; to bind by such contract","Indentured servants were bound by indenture to work for a master for a set number of years."),
    (10,"inexorable","in-EK-ser-uh-bul","adjective","impossible to stop or prevent; relentless","The inexorable rise of sea levels threatens low-lying coastal cities around the world."),
    (10,"oracle","OR-uh-kul","noun","a priest or shrine through which a deity gives advice; a wise and authoritative person","The oracle at Delphi was consulted by rulers from across the ancient world."),
    (10,"oration","or-AY-shun","noun","a formal speech given on a ceremonial occasion","The graduation oration moved many in the audience to tears."),
    (10,"orifice","OR-ih-fis","noun","an opening especially a natural one in the body","The doctor examined each orifice carefully during the routine physical examination."),
    (10,"orthodontist","or-thoh-DON-tist","noun","a dentist who specializes in correcting irregularities of the teeth","The orthodontist recommended braces to correct the misalignment of her teeth."),
    (10,"osculate","OS-kyuh-layt","verb","to kiss; in mathematics to touch at a single point without crossing","The two curves osculate at exactly one point on the graph."),
    (10,"regurgitate","rih-GUR-jih-tayt","verb","to bring swallowed food back up; to repeat information without understanding it","Students who merely regurgitate facts without analysis rarely earn top marks."),
    (10,"supercilious","soo-per-SIL-ee-us","adjective","behaving as though one is superior to others; condescending","His supercilious smirk irritated everyone who worked with him."),
    (10,"trident","TRY-dent","noun","a three-pronged spear","In Roman mythology Neptune carried a trident as a symbol of his power over the sea."),
    # ── Lesson 11 ─────────────────────────────────────────────
    (11,"accolade","AK-uh-layd","noun","an award or expression of praise; a ceremony of knighthood","The film received every major accolade including Best Picture at the awards ceremony."),
    (11,"accord","uh-KORD","noun/verb","agreement; to give or grant","The two nations signed an accord to end the conflict and establish trade relations."),
    (11,"carnage","KAR-nij","noun","the killing of a large number of people; great slaughter","The battlefield was a scene of carnage that shocked even the most experienced soldiers."),
    (11,"carrion","KAR-ee-un","noun","the decaying flesh of dead animals","Vultures circle overhead drawn by the smell of carrion on the desert floor."),
    (11,"concordance","kon-KOR-dens","noun","agreement; an alphabetical index of the main words in a text","The scholars used a biblical concordance to locate every passage containing the word 'mercy'."),
    (11,"cordial","KOR-jee-ul","adjective/noun","warm and friendly; a sweet fruit-flavored drink","The cordial welcome extended to every new employee made the office feel like a community."),
    (11,"corporal","KOR-per-ul","adjective","relating to the human body; of or for a non-commissioned military officer","Corporal punishment in schools has been banned in many countries."),
    (11,"corporeal","kor-POR-ee-ul","adjective","having a physical material form; relating to the body","The ghost story raised questions about whether a corporeal form was needed to experience pain."),
    (11,"corps","kor","noun","a body of people engaged in a particular activity; a military unit","She joined the Peace Corps after graduating and served in West Africa for two years."),
    (11,"corpulent","KOR-pyuh-lent","adjective","excessively overweight; fat","The corpulent figure in the old portrait suggested a life of great wealth and indulgence."),
    (11,"corpus","KOR-pus","noun","a collection of written texts; the main body of something","The linguist analyzed a large corpus of historical documents to study language change."),
    (11,"decolletage","day-kol-uh-TAHZH","noun","a low neckline on a woman's dress; a woman's neck and chest revealed by this","The formal gown featured an elegant decolletage that was sophisticated and understated."),
    (11,"incarnate","in-KAR-nit","adjective/verb","embodied in human form; to embody in flesh","Many fans considered him the spirit of rock and roll incarnate."),
    (11,"ossify","OS-ih-fy","verb","to turn to bone; to become rigid and unable to change","Bureaucracies tend to ossify over time and resist any new ideas or methods."),
    # ── Lesson 12 ─────────────────────────────────────────────
    (12,"assiduous","uh-SIJ-oo-us","adjective","showing great care and perseverance","The assiduous student reviewed her notes every night without fail."),
    (12,"consanguinity","kon-sang-GWIN-ih-tee","noun","the quality of being descended from the same ancestor; close kinship","Marriage between close relatives is prohibited by laws against consanguinity in most societies."),
    (12,"dermatology","dur-muh-TOL-uh-jee","noun","the branch of medicine dealing with skin disorders","After developing a rare rash she was referred to a specialist in dermatology."),
    (12,"dissident","DIS-ih-dent","noun/adjective","a person who opposes official policy; opposed to official policy","The dissident was imprisoned for publishing essays critical of the government."),
    (12,"dorsal","DOR-sul","adjective","relating to the upper side or back of an animal","A shark's dorsal fin cutting through the water is an unmistakable sight."),
    (12,"dossier","DOS-ee-ay","noun","a collection of documents about a particular person, event, or subject","The spy agency maintained a detailed dossier on every person of interest."),
    (12,"endorse","en-DORS","verb","to declare public support for; to sign the back of a check","The popular athlete was paid handsomely to endorse the new sports drink."),
    (12,"enervate","EN-er-vayt","verb","to make someone feel drained of energy or vitality","The relentless summer heat enervated the entire team before practice even began."),
    (12,"epidermis","ep-ih-DUR-mis","noun","the outer layer of the skin; the outer layer of a plant","A sunburn damages the epidermis causing redness, peeling, and pain."),
    (12,"gastric","GAS-trik","adjective","relating to the stomach","The patient complained of severe gastric pain after eating the spoiled food."),
    (12,"gastronome","GAS-truh-nohm","noun","a connoisseur of good food","As a dedicated gastronome he traveled to three cities just to sample the local specialties."),
    (12,"sanguine","SANG-gwin","adjective","optimistic especially in a difficult situation; blood-red in color","Despite the setbacks she remained sanguine about the project's ultimate success."),
    (12,"seance","SAY-ons","noun","a meeting at which people attempt to communicate with the dead","The characters in the novel held a seance to contact the spirit of the old general."),
    (12,"sedentary","SED-en-ter-ee","adjective","tending to spend much time seated; requiring little physical activity","A sedentary lifestyle combined with a poor diet increases the risk of heart disease."),
    (12,"supersede","soo-per-SEED","verb","to take the place of something previously in authority or use","Digital streaming has largely superseded physical media like DVDs."),
    # ── Lesson 13 ─────────────────────────────────────────────
    (13,"ambidextrous","am-bih-DEK-strus","adjective","able to use both hands equally well","The ambidextrous tennis player could switch her racket between hands during long rallies."),
    (13,"deflect","dih-FLEKT","verb","to cause something to change direction; to turn aside","The goalkeeper deflected the ball just over the crossbar with a brilliant save."),
    (13,"dexterity","dek-STER-ih-tee","noun","skill and grace in physical movement especially with the hands","Surgeons must have extraordinary dexterity to perform delicate operations."),
    (13,"digital","DIJ-ih-tul","adjective","relating to fingers; relating to data expressed as numerical digits","The digital revolution transformed how people communicate, work, and learn."),
    (13,"emancipate","ih-MAN-sih-payt","verb","to set free from legal, social, or political restriction","Lincoln's Emancipation Proclamation sought to emancipate enslaved people in Confederate states."),
    (13,"genuflect","JEN-yuh-flekt","verb","to lower one knee briefly as a sign of reverence; to be servilely obedient","Parishioners genuflect before entering the pew as a sign of reverence."),
    (13,"inflection","in-FLEK-shun","noun","a change in the form of a word; a change in pitch or tone of voice","His voice carried an upward inflection at the end of every sentence."),
    (13,"manacle","MAN-uh-kul","noun/verb","a metal band fastened around a prisoner's wrist; to restrain with manacles","The prisoner's wrists were bound in manacles during the courtroom hearing."),
    (13,"mandate","MAN-dayt","noun/verb","an official order or authority; to give official authorization","The new law mandated that all public buildings install wheelchair ramps."),
    (13,"manifest","MAN-ih-fest","adjective/verb","clear and obvious; to make clear or evident","Her frustration began to manifest itself in short, clipped answers to every question."),
    (13,"manipulate","muh-NIP-yuh-layt","verb","to handle skillfully; to influence or manage in a clever way","He knew how to manipulate statistics to make his argument seem stronger than it was."),
    (13,"rapacious","ruh-PAY-shus","adjective","aggressively greedy; disposed to seize by force","The rapacious developer bought up every piece of land in the neighborhood."),
    (13,"rapt","rapt","adjective","completely absorbed; entranced","The children sat in rapt attention as the storyteller described the dragon's lair."),
    (13,"reflection","rih-FLEK-shun","noun","the throwing back of light; serious thought; an image in a mirror","After the argument she spent the evening in quiet reflection on her own behavior."),
    (13,"surreptitious","sur-ep-TISH-us","adjective","done secretly and without permission","He cast a surreptitious glance at his neighbor's exam paper."),
    # ── Lesson 14 ─────────────────────────────────────────────
    (14,"apprehend","ap-rih-HEND","verb","to arrest or seize; to grasp mentally; to anticipate with fear","Police apprehended the suspect within hours of the robbery."),
    (14,"complicity","kum-PLIS-ih-tee","noun","involvement in an illegal act or wrongdoing","Evidence of his complicity in the fraud scheme was found on his computer."),
    (14,"comprise","kum-PRYZ","verb","to consist of; to make up","The committee comprises twelve members from five different departments."),
    (14,"duplicity","doo-PLIS-ih-tee","noun","deceitfulness; saying one thing while meaning or doing another","The duplicity of the double agent was revealed only after years of investigation."),
    (14,"entrepreneur","on-truh-pruh-NUR","noun","a person who starts and runs a business taking on financial risk","The young entrepreneur launched her app with nothing more than a laptop and a good idea."),
    (14,"explicate","EK-splih-kayt","verb","to explain and analyze in detail","The professor took thirty minutes to explicate the dense passage from the medieval text."),
    (14,"explicit","ik-SPLIS-it","adjective","stated clearly and in detail; not implied or ambiguous","The contract included an explicit clause about prohibited uses of the intellectual property."),
    (14,"exploit","EK-sployt","noun/verb","a bold achievement; to make full use of; to take unfair advantage of","The company was accused of exploiting cheap foreign labor to maximize profits."),
    (14,"imply","im-PLY","verb","to suggest or indicate something indirectly","Her tone implied that she was disappointed even though she said nothing critical."),
    (14,"impregnable","im-PREG-nuh-bul","adjective","unable to be captured; too strong to overcome","The castle's thick stone walls and deep moat made it virtually impregnable."),
    (14,"ploy","ploy","noun","a cunning plan or strategy intended to gain an advantage","Asking for a glass of water was just a ploy to delay bedtime."),
    (14,"ply","ply","verb/noun","to work steadily at a trade; to travel regularly over a route; a layer of material","The ferryboat plied the river between the two cities all day long."),
    (14,"reprehend","rep-rih-HEND","verb","to express sharp disapproval or criticism of","The editorial board strongly reprehended the senator's inflammatory remarks."),
    (14,"reprisal","rih-PRY-zul","noun","an act of retaliation","The bombing was feared to trigger a reprisal that could escalate into full-scale war."),
    (14,"supplicate","SUP-lih-kayt","verb","to ask or beg for something earnestly and humbly","The villagers supplicated the king to reduce their tax burden after the failed harvest."),
    # ── Lesson 15 ─────────────────────────────────────────────
    (15,"aggression","uh-GRESH-un","noun","hostile or violent behavior; forceful pursuit of aims","Random acts of aggression on the streets prompted increased police patrols."),
    (15,"antipodes","an-TIP-oh-deez","noun","the opposite side of the Earth; a direct opposite","Australia and New Zealand are sometimes called the antipodes because of their position relative to Europe."),
    (15,"degradation","deg-ruh-DAY-shun","noun","the process of becoming worse; humiliation; decomposition","Soil degradation caused by overfarming threatens food production worldwide."),
    (15,"digress","dy-GRES","verb","to depart from the main subject in speech or writing","The professor tended to digress into personal anecdotes much to his students' amusement."),
    (15,"expedient","ik-SPEE-dee-ent","adjective/noun","convenient and practical though possibly improper; a means of achieving an end","Raising tuition was seen as politically expedient but educationally damaging."),
    (15,"expedite","EK-spih-dyt","verb","to make an action happen sooner; to assist the progress of","Please expedite this order — the client needs it by Friday without fail."),
    (15,"gradation","gruh-DAY-shun","noun","a scale of successive changes; a change by degrees or stages","The artist achieved a beautiful gradation of color from deep blue to pale white."),
    (15,"gradient","GRAY-dee-ent","noun","a sloping surface; the rate of change of a variable quantity","The steep gradient of the road made cycling up the hill extremely difficult."),
    (15,"impede","im-PEED","verb","to delay or prevent by obstructing","Fallen trees blocked the road and impeded the rescue vehicles for hours."),
    (15,"pedigree","PED-ih-gree","noun","the ancestry of a person or animal; a background of distinguished lineage","The show dog's impressive pedigree traced back to three national champions."),
    (15,"pedometer","pih-DOM-ih-ter","noun","an instrument that counts the number of steps taken","She wore a pedometer to track her goal of ten thousand steps each day."),
    (15,"podiatry","poh-DY-uh-tree","noun","the branch of medicine dealing with disorders of the foot and lower leg","After months of foot pain she finally made an appointment with a podiatry specialist."),
    (15,"podium","POH-dee-um","noun","a small platform on which a speaker or conductor stands; an Olympic medal position","The gold medalist stepped up to the highest tier of the podium to receive her medal."),
    (15,"regress","rih-GRES","verb/noun","to return to an earlier or less developed state","Under extreme stress some adults regress to childlike behavior."),
    # ── Lesson 16 ─────────────────────────────────────────────
    (16,"ambulatory","AM-byuh-luh-tor-ee","adjective","relating to walking; able to walk","The patient was ambulatory within two days of the surgery."),
    (16,"constituent","kun-STICH-oo-ent","noun/adjective","a member of a constituency; a component or ingredient","Every elected official is accountable to his or her constituents."),
    (16,"desist","dih-SIST","verb","to stop or abstain from doing something","The lawyer sent a cease-and-desist letter ordering them to stop using the trademarked name."),
    (16,"destitute","DES-tih-toot","adjective","extremely poor and lacking basic necessities","The earthquake left thousands of families destitute, without shelter or food."),
    (16,"interstice","in-TUR-stis","noun","a small gap or crack in a structure","Moss grew in every interstice between the old cobblestones of the courtyard."),
    (16,"obstinate","OB-stih-nit","adjective","stubbornly refusing to change one's opinion or course of action","The obstinate mule refused to move no matter how much the farmer coaxed it."),
    (16,"oust","owst","verb","to drive out or remove from a position","The board voted to oust the CEO following the financial scandal."),
    (16,"preamble","PREE-am-bul","noun","a preliminary statement especially the introduction to a formal document","The preamble to the Constitution explains the purpose and principles of the document."),
    (16,"recalcitrant","rih-KAL-sih-trent","adjective","having an obstinately uncooperative attitude toward authority","The recalcitrant student refused to follow classroom rules despite repeated warnings."),
    (16,"restitution","res-tih-TOO-shun","noun","the restoration of something lost or stolen; making amends","As part of his sentence he was ordered to pay restitution to all of his victims."),
    (16,"restive","RES-tiv","adjective","unable to keep still; restless or impatient","The long delay made the crowd increasingly restive and difficult to manage."),
    (16,"stance","stans","noun","the way in which someone stands; a person's position or attitude on an issue","The candidate's stance on healthcare reform was the central issue of the debate."),
    (16,"static","STAT-ik","adjective/noun","lacking movement or change; electrical interference causing noise","House prices remained static throughout the year despite rising demand."),
    (16,"subsist","sub-SIST","verb","to maintain or support oneself especially at a minimal level","The survivors had to subsist on berries and insects for three weeks before being rescued."),
]

with open(path, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["lesson","word","pronunciation","partOfSpeech","definition","example"])
    w.writerows(rows)

print(f"Written {len(rows)} rows to {path}")
counts = Counter(r[0] for r in rows)
for lesson in sorted(counts):
    print(f"  Lesson {lesson}: {counts[lesson]} words")
