"""The five steps of "Build Asteroids", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("point_from", "pointFrom", "point_from",
  "Which way is forward?", "The ship knows where its nose is.",
  "<p>The ship points somewhere — an <strong>angle</strong> — and the game constantly needs to turn that into an actual place: where is the nose? which way does a shot fly? where does a rock drift?</p>"
  "<p>That is what <code>cos</code> and <code>sin</code> are for, and you only need to learn them once. <code>cos(angle)</code> is how much of the direction is sideways, and <code>sin(angle)</code> is how much is up and down. Multiply each by the distance and add them on.</p>"
  "<p>One thing to hold on to: angle 0 points <strong>right</strong>, and a quarter turn points <strong>down</strong> — because y grows downwards on a canvas.</p>",
  "x, y — where you start. angle — which way, in radians. distance — how far.",
  "a point: { x, y }",
  ["The new x is x + cos(angle) × distance.",
   "The new y is y + sin(angle) × distance.",
   "Give both back together."],
  js=dict(starter="function pointFrom(x, y, angle, distance) {\n    return { x: x, y: y };\n}\n",
    answer="function pointFrom(x, y, angle, distance) {\n    return {\n        x: x + Math.cos(angle) * distance,\n        y: y + Math.sin(angle) * distance\n    };\n}\n",
    hints=["Math.cos and Math.sin both want the angle in radians, which is what we have.",
           "cos goes with x, sin goes with y. Always that way round.",
           "x: x + Math.cos(angle) * distance"],
    tests=[("Angle 0 goes to the right",
            "const p = pointFrom(0, 0, 0, 10);\nassert(Math.abs(p.x - 10) < 0.001, 'x is ' + p.x);\nassert(Math.abs(p.y) < 0.001, 'y is ' + p.y + ' — angle 0 should not move up or down at all');"),
           ("A quarter turn goes DOWN",
            "const p = pointFrom(0, 0, Math.PI / 2, 10);\nassert(Math.abs(p.x) < 0.001);\nassert(Math.abs(p.y - 10) < 0.001, 'y is ' + p.y + ' — on a canvas, y grows downwards');"),
           ("Half a turn goes left",
            "const p = pointFrom(0, 0, Math.PI, 10);\nassert(Math.abs(p.x + 10) < 0.001, 'x is ' + p.x);"),
           ("Three quarters goes UP",
            "const p = pointFrom(0, 0, -Math.PI / 2, 10);\nassert(Math.abs(p.y + 10) < 0.001, 'y is ' + p.y);"),
           ("It starts from where you tell it",
            "const p = pointFrom(100, 50, 0, 10);\nassert(Math.abs(p.x - 110) < 0.001);\nassert(Math.abs(p.y - 50) < 0.001);"),
           ("Twice the distance is twice as far",
            "const near = pointFrom(0, 0, 1, 10);\nconst far = pointFrom(0, 0, 1, 20);\nassert(Math.abs(far.x - near.x * 2) < 0.001);\nassert(Math.abs(far.y - near.y * 2) < 0.001);"),
           ("Every angle lands the right distance away",
            "for (let step = 0; step < 16; step++) {\n    const angle = step / 16 * Math.PI * 2;\n    const p = pointFrom(0, 0, angle, 25);\n    const away = Math.sqrt(p.x * p.x + p.y * p.y);\n    assert(Math.abs(away - 25) < 0.001, 'angle ' + angle.toFixed(2) + ' landed ' + away.toFixed(1) + ' away, not 25');\n}"),
           ("Zero distance does not move at all",
            "const p = pointFrom(30, 40, 2.1, 0);\nassert(Math.abs(p.x - 30) < 0.001 && Math.abs(p.y - 40) < 0.001);")]),
  py=dict(starter="def point_from(x, y, angle, distance):\n    return {\"x\": x, \"y\": y}\n",
    answer="def point_from(x, y, angle, distance):\n    return {\n        \"x\": x + math.cos(angle) * distance,\n        \"y\": y + math.sin(angle) * distance,\n    }\n",
    hints=["math.cos and math.sin both want the angle in radians, which is what we have.",
           "cos goes with x, sin goes with y. Always that way round.",
           "\"x\": x + math.cos(angle) * distance"],
    tests=[("Angle 0 goes to the right",
            "p = point_from(0, 0, 0, 10)\nassert abs(p['x'] - 10) < 0.001\nassert abs(p['y']) < 0.001"),
           ("A quarter turn goes DOWN",
            "p = point_from(0, 0, math.pi / 2, 10)\nassert abs(p['x']) < 0.001\nassert abs(p['y'] - 10) < 0.001, 'on a canvas, y grows downwards'"),
           ("Half a turn goes left",
            "p = point_from(0, 0, math.pi, 10)\nassert abs(p['x'] + 10) < 0.001"),
           ("Three quarters goes UP",
            "p = point_from(0, 0, -math.pi / 2, 10)\nassert abs(p['y'] + 10) < 0.001"),
           ("It starts from where you tell it",
            "p = point_from(100, 50, 0, 10)\nassert abs(p['x'] - 110) < 0.001 and abs(p['y'] - 50) < 0.001"),
           ("Twice the distance is twice as far",
            "near = point_from(0, 0, 1, 10)\nfar = point_from(0, 0, 1, 20)\nassert abs(far['x'] - near['x'] * 2) < 0.001"),
           ("Every angle lands the right distance away",
            "for step in range(16):\n    angle = step / 16 * math.pi * 2\n    p = point_from(0, 0, angle, 25)\n    away = math.sqrt(p['x'] ** 2 + p['y'] ** 2)\n    assert abs(away - 25) < 0.001, f'angle {angle:.2f} landed {away:.1f} away'"),
           ("Zero distance does not move at all",
            "p = point_from(30, 40, 2.1, 0)\nassert abs(p['x'] - 30) < 0.001 and abs(p['y'] - 40) < 0.001")]),
  demo=dict(kind="angles", caption="Turn the ship and watch the dashed line — that is pointFrom drawing 60 pixels ahead.")),

step("wrap_position", "wrapPosition", "wrap_position",
  "Space has no edges", "Fly off one side, come back on the other.",
  "<p>There are no walls out here. Fly off the right and you appear on the left; off the top and you come back at the bottom. The field is a loop in both directions.</p>"
  "<p>Use <code>while</code> rather than <code>if</code>. A rock nudged just past the edge only needs one wrap, but something that has jumped a long way in one frame might need more — and <code>while</code> handles both without you having to think about it.</p>",
  "thing — anything with an x and a y",
  "nothing; it changes the thing",
  ["While x is below 0, add FIELD_WIDTH.",
   "While x has reached FIELD_WIDTH, take FIELD_WIDTH off.",
   "Do the same for y with FIELD_HEIGHT."],
  js=dict(starter="function wrapPosition(thing) {\n    // off one edge, back on the other\n}\n",
    answer="function wrapPosition(thing) {\n    while (thing.x < 0) { thing.x = thing.x + FIELD_WIDTH; }\n    while (thing.x >= FIELD_WIDTH) { thing.x = thing.x - FIELD_WIDTH; }\n    while (thing.y < 0) { thing.y = thing.y + FIELD_HEIGHT; }\n    while (thing.y >= FIELD_HEIGHT) { thing.y = thing.y - FIELD_HEIGHT; }\n}\n",
    hints=["Four while loops, two for x and two for y.",
           "Going off the left means ADDING the width.",
           "Use >= for the far edge, so exactly FIELD_WIDTH wraps to 0."],
    tests=[("Something in the middle is left alone",
            "const thing = { x: 100, y: 100 };\nwrapPosition(thing);\nassert(thing.x === 100 && thing.y === 100);"),
           ("Off the left comes back on the right",
            "const thing = { x: -5, y: 100 };\nwrapPosition(thing);\nassert(thing.x === FIELD_WIDTH - 5, 'x is ' + thing.x);"),
           ("Off the right comes back on the left",
            "const thing = { x: FIELD_WIDTH + 5, y: 100 };\nwrapPosition(thing);\nassert(thing.x === 5, 'x is ' + thing.x);"),
           ("Off the top comes back at the bottom",
            "const thing = { x: 100, y: -5 };\nwrapPosition(thing);\nassert(thing.y === FIELD_HEIGHT - 5);"),
           ("Off the bottom comes back at the top",
            "const thing = { x: 100, y: FIELD_HEIGHT + 5 };\nwrapPosition(thing);\nassert(thing.y === 5);"),
           ("A corner wraps in both directions at once",
            "const thing = { x: -5, y: -5 };\nwrapPosition(thing);\nassert(thing.x === FIELD_WIDTH - 5 && thing.y === FIELD_HEIGHT - 5);"),
           ("A huge jump still lands on the field",
            "const thing = { x: FIELD_WIDTH * 3 + 7, y: -FIELD_HEIGHT * 2 - 3 };\nwrapPosition(thing);\nassert(thing.x >= 0 && thing.x < FIELD_WIDTH, 'x is ' + thing.x + ' — did you use while rather than if?');\nassert(thing.y >= 0 && thing.y < FIELD_HEIGHT, 'y is ' + thing.y);"),
           ("Nothing can ever escape",
            "const thing = { x: 10, y: 10, dx: 411, dy: -389 };\nfor (let frame = 0; frame < 3000; frame++) {\n    thing.x = thing.x + thing.dx * 0.05;\n    thing.y = thing.y + thing.dy * 0.05;\n    wrapPosition(thing);\n    assert(thing.x >= 0 && thing.x < FIELD_WIDTH, 'it escaped sideways at frame ' + frame);\n    assert(thing.y >= 0 && thing.y < FIELD_HEIGHT, 'it escaped up or down at frame ' + frame);\n}")]),
  py=dict(starter="def wrap_position(thing):\n    # off one edge, back on the other\n    pass\n",
    answer="def wrap_position(thing):\n    while thing[\"x\"] < 0:\n        thing[\"x\"] += FIELD_WIDTH\n    while thing[\"x\"] >= FIELD_WIDTH:\n        thing[\"x\"] -= FIELD_WIDTH\n    while thing[\"y\"] < 0:\n        thing[\"y\"] += FIELD_HEIGHT\n    while thing[\"y\"] >= FIELD_HEIGHT:\n        thing[\"y\"] -= FIELD_HEIGHT\n",
    hints=["Four while loops, two for x and two for y.",
           "Going off the left means ADDING the width.",
           "Use >= for the far edge, so exactly FIELD_WIDTH wraps to 0."],
    tests=[("Something in the middle is left alone",
            "thing = {'x': 100, 'y': 100}\nwrap_position(thing)\nassert thing == {'x': 100, 'y': 100}"),
           ("Off the left comes back on the right",
            "thing = {'x': -5, 'y': 100}\nwrap_position(thing)\nassert thing['x'] == FIELD_WIDTH - 5"),
           ("Off the right comes back on the left",
            "thing = {'x': FIELD_WIDTH + 5, 'y': 100}\nwrap_position(thing)\nassert thing['x'] == 5"),
           ("Off the top comes back at the bottom",
            "thing = {'x': 100, 'y': -5}\nwrap_position(thing)\nassert thing['y'] == FIELD_HEIGHT - 5"),
           ("Off the bottom comes back at the top",
            "thing = {'x': 100, 'y': FIELD_HEIGHT + 5}\nwrap_position(thing)\nassert thing['y'] == 5"),
           ("A corner wraps in both directions at once",
            "thing = {'x': -5, 'y': -5}\nwrap_position(thing)\nassert thing['x'] == FIELD_WIDTH - 5 and thing['y'] == FIELD_HEIGHT - 5"),
           ("A huge jump still lands on the field",
            "thing = {'x': FIELD_WIDTH * 3 + 7, 'y': -FIELD_HEIGHT * 2 - 3}\nwrap_position(thing)\nassert 0 <= thing['x'] < FIELD_WIDTH, 'did you use while rather than if?'\nassert 0 <= thing['y'] < FIELD_HEIGHT"),
           ("Nothing can ever escape",
            "thing = {'x': 10, 'y': 10, 'dx': 411, 'dy': -389}\nfor frame in range(3000):\n    thing['x'] += thing['dx'] * 0.05\n    thing['y'] += thing['dy'] * 0.05\n    wrap_position(thing)\n    assert 0 <= thing['x'] < FIELD_WIDTH, f'escaped sideways at frame {frame}'\n    assert 0 <= thing['y'] < FIELD_HEIGHT, f'escaped up or down at frame {frame}'")]),
  demo=dict(kind="drift", caption="Thrust a few times and fly off an edge — you come straight back on the other side."),
  warning="Use while, not if. A single if handles a small nudge but not a big jump, and the bug only shows up when something is moving fast."),

step("thrust_ship", "thrustShip", "thrust_ship",
  "Fire the engine", "The ship really flies.",
  "<p>The engine does not move the ship. It changes the ship's <strong>speed</strong> — exactly like gravity in Flappy, but pointing wherever the nose is.</p>"
  "<p>And crucially, the old speed stays. Turn around and thrust and you do not stop dead: you slow down, stop, and then start going the other way. Everyone's first go at Asteroids ends in a wall because of that, and it is the whole character of the game.</p>"
  "<p>Then cap the total speed, or holding the key down for ten seconds sends the ship across the screen faster than the eye can follow.</p>",
  "ship, seconds",
  "nothing; it changes the ship's dx and dy",
  ["Add cos(angle) × THRUST × seconds to dx.",
   "Add sin(angle) × THRUST × seconds to dy.",
   "Work out the total speed with Pythagoras: √(dx² + dy²).",
   "If that is over MAX_SPEED, scale BOTH dx and dy down so the total is exactly MAX_SPEED."],
  js=dict(starter="function thrustShip(ship, seconds) {\n    // push along the angle, then cap the total speed\n}\n",
    answer="function thrustShip(ship, seconds) {\n    ship.dx = ship.dx + Math.cos(ship.angle) * THRUST * seconds;\n    ship.dy = ship.dy + Math.sin(ship.angle) * THRUST * seconds;\n\n    const speed = Math.sqrt(ship.dx * ship.dx + ship.dy * ship.dy);\n    if (speed > MAX_SPEED) {\n        ship.dx = ship.dx / speed * MAX_SPEED;\n        ship.dy = ship.dy / speed * MAX_SPEED;\n    }\n}\n",
    hints=["ADD to dx and dy — never set them. The old speed has to survive.",
           "The total speed is √(dx² + dy²), just like the distance between two points.",
           "To cap it, divide each by the speed (making the total 1) and multiply by MAX_SPEED."],
    tests=[("Thrusting to the right speeds up sideways",
            "const ship = { x: 0, y: 0, angle: 0, dx: 0, dy: 0 };\nthrustShip(ship, 0.1);\nassert(ship.dx > 0, 'dx is ' + ship.dx);\nassert(Math.abs(ship.dy) < 0.001, 'pointing right should not move it up or down');"),
           ("Thrusting down speeds up downwards",
            "const ship = { x: 0, y: 0, angle: Math.PI / 2, dx: 0, dy: 0 };\nthrustShip(ship, 0.1);\nassert(ship.dy > 0);"),
           ("The old speed is kept",
            "const ship = { x: 0, y: 0, angle: 0, dx: 50, dy: 0 };\nthrustShip(ship, 0.1);\nassert(ship.dx > 50, 'dx is ' + ship.dx + ' — thrusting ADDS to the speed you already had');"),
           ("Thrusting backwards slows you down first",
            "const ship = { x: 0, y: 0, angle: Math.PI, dx: 100, dy: 0 };\nthrustShip(ship, 0.1);\nassert(ship.dx < 100 && ship.dx > 0, 'dx is ' + ship.dx + ' — you should be slowing, not stopped or reversed yet');"),
           ("Longer thrust means more speed",
            "const quick = { x: 0, y: 0, angle: 0, dx: 0, dy: 0 };\nconst slow = { x: 0, y: 0, angle: 0, dx: 0, dy: 0 };\nthrustShip(quick, 0.2);\nthrustShip(slow, 0.1);\nassert(quick.dx > slow.dx);"),
           ("The speed is capped",
            "const ship = { x: 0, y: 0, angle: 0, dx: 0, dy: 0 };\nfor (let i = 0; i < 200; i++) { thrustShip(ship, 0.1); }\nconst speed = Math.sqrt(ship.dx * ship.dx + ship.dy * ship.dy);\nassert(speed <= MAX_SPEED + 0.001, 'reached ' + Math.round(speed));"),
           ("Capping keeps the direction",
            "const ship = { x: 0, y: 0, angle: 0.7, dx: 0, dy: 0 };\nfor (let i = 0; i < 200; i++) { thrustShip(ship, 0.1); }\nconst angle = Math.atan2(ship.dy, ship.dx);\nassert(Math.abs(angle - 0.7) < 0.01, 'the ship is capped but now flying at ' + angle.toFixed(2) + ' instead of 0.7 — scale BOTH dx and dy by the same amount');"),
           ("It is capped in every direction",
            "for (let step = 0; step < 8; step++) {\n    const ship = { x: 0, y: 0, angle: step / 8 * Math.PI * 2, dx: 0, dy: 0 };\n    for (let i = 0; i < 100; i++) { thrustShip(ship, 0.1); }\n    const speed = Math.sqrt(ship.dx * ship.dx + ship.dy * ship.dy);\n    assert(speed <= MAX_SPEED + 0.001);\n}")]),
  py=dict(starter="def thrust_ship(ship, seconds):\n    # push along the angle, then cap the total speed\n    pass\n",
    answer="def thrust_ship(ship, seconds):\n    ship[\"dx\"] += math.cos(ship[\"angle\"]) * THRUST * seconds\n    ship[\"dy\"] += math.sin(ship[\"angle\"]) * THRUST * seconds\n\n    speed = math.sqrt(ship[\"dx\"] ** 2 + ship[\"dy\"] ** 2)\n    if speed > MAX_SPEED:\n        ship[\"dx\"] = ship[\"dx\"] / speed * MAX_SPEED\n        ship[\"dy\"] = ship[\"dy\"] / speed * MAX_SPEED\n",
    hints=["ADD to dx and dy - never set them. The old speed has to survive.",
           "The total speed is math.sqrt(dx ** 2 + dy ** 2).",
           "To cap it, divide each by the speed and multiply by MAX_SPEED."],
    tests=[("Thrusting to the right speeds up sideways",
            "ship = {'x': 0, 'y': 0, 'angle': 0, 'dx': 0, 'dy': 0}\nthrust_ship(ship, 0.1)\nassert ship['dx'] > 0 and abs(ship['dy']) < 0.001"),
           ("Thrusting down speeds up downwards",
            "ship = {'x': 0, 'y': 0, 'angle': math.pi / 2, 'dx': 0, 'dy': 0}\nthrust_ship(ship, 0.1)\nassert ship['dy'] > 0"),
           ("The old speed is kept",
            "ship = {'x': 0, 'y': 0, 'angle': 0, 'dx': 50, 'dy': 0}\nthrust_ship(ship, 0.1)\nassert ship['dx'] > 50, 'thrusting ADDS to the speed you already had'"),
           ("Thrusting backwards slows you down first",
            "ship = {'x': 0, 'y': 0, 'angle': math.pi, 'dx': 100, 'dy': 0}\nthrust_ship(ship, 0.1)\nassert 0 < ship['dx'] < 100"),
           ("Longer thrust means more speed",
            "quick = {'x': 0, 'y': 0, 'angle': 0, 'dx': 0, 'dy': 0}\nslow = {'x': 0, 'y': 0, 'angle': 0, 'dx': 0, 'dy': 0}\nthrust_ship(quick, 0.2)\nthrust_ship(slow, 0.1)\nassert quick['dx'] > slow['dx']"),
           ("The speed is capped",
            "ship = {'x': 0, 'y': 0, 'angle': 0, 'dx': 0, 'dy': 0}\nfor _ in range(200):\n    thrust_ship(ship, 0.1)\nspeed = math.sqrt(ship['dx'] ** 2 + ship['dy'] ** 2)\nassert speed <= MAX_SPEED + 0.001, f'reached {speed:.0f}'"),
           ("Capping keeps the direction",
            "ship = {'x': 0, 'y': 0, 'angle': 0.7, 'dx': 0, 'dy': 0}\nfor _ in range(200):\n    thrust_ship(ship, 0.1)\nangle = math.atan2(ship['dy'], ship['dx'])\nassert abs(angle - 0.7) < 0.01, 'scale BOTH dx and dy by the same amount'"),
           ("It is capped in every direction",
            "for step in range(8):\n    ship = {'x': 0, 'y': 0, 'angle': step / 8 * math.pi * 2, 'dx': 0, 'dy': 0}\n    for _ in range(100):\n        thrust_ship(ship, 0.1)\n    assert math.sqrt(ship['dx'] ** 2 + ship['dy'] ** 2) <= MAX_SPEED + 0.001")]),
  demo=dict(kind="drift", caption="Turn, thrust, and try to stop again. It is harder than it looks."),
  warning="Scale dx and dy by the SAME amount when you cap the speed. Cap them one at a time and the ship quietly turns as it speeds up."),

step("split_rock", "splitRock", "split_rock",
  "Break the rocks", "Shooting makes more rocks, not fewer.",
  "<p>Here is the idea that makes Asteroids a game rather than a shooting gallery: hitting a rock does not remove it, it <strong>divides</strong> it.</p>"
  "<p>A big rock becomes two mediums, a medium becomes two smalls, and only the smallest ones actually disappear. So clearing a wave means firing at least fourteen times for four rocks — and the screen gets busier and faster before it gets emptier.</p>",
  "rock",
  "a list of the smaller rocks it leaves behind",
  ["If the rock is already the smallest size, it leaves nothing: an empty list.",
   "Otherwise make TWO rocks, one size smaller, both in the same place.",
   "make-rock gives each its own random direction."],
  js=dict(starter="function splitRock(rock) {\n    // two of the next size down — or nothing at all\n}\n",
    answer="function splitRock(rock) {\n    if (rock.size <= 1) {\n        return [];\n    }\n    return [\n        makeRock(rock.x, rock.y, rock.size - 1),\n        makeRock(rock.x, rock.y, rock.size - 1)\n    ];\n}\n",
    hints=["Deal with the smallest size first: return an empty list.",
           "makeRock(x, y, size) is written for you and picks a random direction.",
           "Both new rocks start where the old one was."],
    tests=[("A big rock becomes two",
            "const rock = makeRock(100, 100, 3);\nassert(splitRock(rock).length === 2, 'gave ' + splitRock(rock).length);"),
           ("They are one size smaller",
            "const pieces = splitRock(makeRock(100, 100, 3));\nassert(pieces[0].size === 2 && pieces[1].size === 2);"),
           ("A medium rock becomes two smalls",
            "const pieces = splitRock(makeRock(100, 100, 2));\nassert(pieces.length === 2);\nassert(pieces[0].size === 1);"),
           ("The smallest rock leaves nothing",
            "assert(splitRock(makeRock(100, 100, 1)).length === 0, 'the little ones just disappear');"),
           ("The pieces start where the rock was",
            "const pieces = splitRock(makeRock(137, 42, 3));\nassert(pieces[0].x === 137 && pieces[0].y === 42);"),
           ("The pieces drift their own ways",
            "const pieces = splitRock(makeRock(100, 100, 3));\nassert(pieces[0].dx !== pieces[1].dx || pieces[0].dy !== pieces[1].dy, 'two pieces flying in exactly the same direction would look like one');"),
           ("Smaller rocks move faster",
            "const big = makeRock(0, 0, 3);\nconst small = makeRock(0, 0, 1);\nconst bigSpeed = Math.sqrt(big.dx * big.dx + big.dy * big.dy);\nconst smallSpeed = Math.sqrt(small.dx * small.dx + small.dy * small.dy);\nassert(smallSpeed > bigSpeed, 'the little ones are meant to be the hard ones');"),
           ("Breaking one big rock all the way down takes seven shots",
            "let toBreak = [makeRock(100, 100, 3)];\nlet shots = 0;\nwhile (toBreak.length > 0 && shots < 50) {\n    const rock = toBreak.pop();\n    shots = shots + 1;\n    toBreak = toBreak.concat(splitRock(rock));\n}\nassert(shots === 7, 'it took ' + shots + ' shots — one big, two medium and four small is seven');")]),
  py=dict(starter="def split_rock(rock):\n    # two of the next size down - or nothing at all\n    pass\n",
    answer="def split_rock(rock):\n    if rock[\"size\"] <= 1:\n        return []\n    return [make_rock(rock[\"x\"], rock[\"y\"], rock[\"size\"] - 1),\n            make_rock(rock[\"x\"], rock[\"y\"], rock[\"size\"] - 1)]\n",
    hints=["Deal with the smallest size first: return an empty list.",
           "make_rock(x, y, size) is written for you and picks a random direction.",
           "Both new rocks start where the old one was."],
    tests=[("A big rock becomes two",
            "assert len(split_rock(make_rock(100, 100, 3))) == 2"),
           ("They are one size smaller",
            "pieces = split_rock(make_rock(100, 100, 3))\nassert pieces[0]['size'] == 2 and pieces[1]['size'] == 2"),
           ("A medium rock becomes two smalls",
            "pieces = split_rock(make_rock(100, 100, 2))\nassert len(pieces) == 2 and pieces[0]['size'] == 1"),
           ("The smallest rock leaves nothing",
            "assert split_rock(make_rock(100, 100, 1)) == []"),
           ("The pieces start where the rock was",
            "pieces = split_rock(make_rock(137, 42, 3))\nassert pieces[0]['x'] == 137 and pieces[0]['y'] == 42"),
           ("The pieces drift their own ways",
            "pieces = split_rock(make_rock(100, 100, 3))\nassert pieces[0]['dx'] != pieces[1]['dx'] or pieces[0]['dy'] != pieces[1]['dy']"),
           ("Smaller rocks move faster",
            "big = make_rock(0, 0, 3)\nsmall = make_rock(0, 0, 1)\nassert math.sqrt(small['dx'] ** 2 + small['dy'] ** 2) > math.sqrt(big['dx'] ** 2 + big['dy'] ** 2)"),
           ("Breaking one big rock all the way down takes seven shots",
            "to_break = [make_rock(100, 100, 3)]\nshots = 0\nfor _ in range(50):\n    if not to_break:\n        break\n    rock = to_break.pop()\n    shots += 1\n    to_break.extend(split_rock(rock))\nassert shots == 7, f'it took {shots} shots - one big, two medium and four small is seven'")]),
  demo=dict(kind="split", caption="Press Shoot it and watch one rock become two — then shoot those.")),

step("hit_rocks", "hitRocks", "hit_rocks",
  "Shoot them down", "The whole game works!",
  "<p>Every shot against every rock. The first rock a bullet touches is replaced by whatever it splits into, the bullet is used up, and the score goes up.</p>"
  "<p>Note the scoring: the <em>smallest</em> rocks are worth the most. A big slow rock is 20 points; a little fast one is 100. That is the game telling you where the skill is.</p>",
  "state",
  "how many rocks were hit this frame",
  ["Keep a list of the bullets that survive, and a count of hits.",
   "For each bullet, look for the first rock it touches — touches(bullet, rock, 1, ROCK_RADIUS[rock.size]).",
   "If it hit nothing, the bullet carries on.",
   "If it hit something: score ROCK_SCORE for that rock's size, take the rock out of the list, and add whatever it splits into.",
   "Put the surviving bullets back and return the count."],
  js=dict(starter="function hitRocks(state) {\n    // every bullet against every rock — one rock each\n}\n",
    answer="function hitRocks(state) {\n    const survivingBullets = [];\n    let hits = 0;\n\n    for (let b = 0; b < state.bullets.length; b++) {\n        const bullet = state.bullets[b];\n        let hitIndex = -1;\n\n        for (let r = 0; r < state.rocks.length; r++) {\n            if (touches(bullet, state.rocks[r], 1, ROCK_RADIUS[state.rocks[r].size])) {\n                hitIndex = r;\n                break;\n            }\n        }\n\n        if (hitIndex === -1) {\n            survivingBullets.push(bullet);\n        } else {\n            const rock = state.rocks[hitIndex];\n            state.score = state.score + ROCK_SCORE[rock.size];\n            state.rocks.splice(hitIndex, 1);\n            state.rocks = state.rocks.concat(splitRock(rock));\n            hits = hits + 1;\n        }\n    }\n\n    state.bullets = survivingBullets;\n    return hits;\n}\n",
    hints=["Two loops: bullets on the outside, rocks on the inside.",
           "touches(a, b, radiusA, radiusB) is written for you — a bullet's radius is 1.",
           "splice(index, 1) takes one rock out of the list."],
    tests=[("A bullet on a rock breaks it",
            "const state = createGame();\nstate.rocks = [makeRock(100, 100, 3)];\nstate.bullets = [{ x: 100, y: 100, dx: 0, dy: 0, life: 1 }];\nassert(hitRocks(state) === 1);"),
           ("The rock is replaced by its pieces",
            "const state = createGame();\nstate.rocks = [makeRock(100, 100, 3)];\nstate.bullets = [{ x: 100, y: 100, dx: 0, dy: 0, life: 1 }];\nhitRocks(state);\nassert(state.rocks.length === 2, 'there are ' + state.rocks.length + ' rocks — one big should become two medium');\nassert(state.rocks[0].size === 2);"),
           ("The bullet is used up",
            "const state = createGame();\nstate.rocks = [makeRock(100, 100, 3)];\nstate.bullets = [{ x: 100, y: 100, dx: 0, dy: 0, life: 1 }];\nhitRocks(state);\nassert(state.bullets.length === 0, 'the bullet must disappear, or it will shred the whole wave');"),
           ("A hit scores",
            "const state = createGame();\nstate.score = 0;\nstate.rocks = [makeRock(100, 100, 3)];\nstate.bullets = [{ x: 100, y: 100, dx: 0, dy: 0, life: 1 }];\nhitRocks(state);\nassert(state.score === ROCK_SCORE[3], 'score is ' + state.score);"),
           ("Small rocks are worth more than big ones",
            "assert(ROCK_SCORE[1] > ROCK_SCORE[3], 'the little ones are harder to hit');"),
           ("Shooting the smallest rock leaves nothing behind",
            "const state = createGame();\nstate.rocks = [makeRock(100, 100, 1)];\nstate.bullets = [{ x: 100, y: 100, dx: 0, dy: 0, life: 1 }];\nhitRocks(state);\nassert(state.rocks.length === 0);"),
           ("A bullet in empty space hits nothing",
            "const state = createGame();\nstate.rocks = [makeRock(300, 300, 3)];\nstate.bullets = [{ x: 20, y: 20, dx: 0, dy: 0, life: 1 }];\nassert(hitRocks(state) === 0);\nassert(state.bullets.length === 1, 'that bullet is still flying');"),
           ("One bullet breaks one rock, not two",
            "const state = createGame();\nstate.rocks = [makeRock(100, 100, 1), makeRock(102, 100, 1)];\nstate.bullets = [{ x: 101, y: 100, dx: 0, dy: 0, life: 1 }];\nhitRocks(state);\nassert(state.rocks.length === 1, 'one shot should only ever break one rock');"),
           ("A whole wave can be cleared",
            "const state = createGame();\nlet shots = 0;\nwhile (state.rocks.length > 0 && shots < 200) {\n    const rock = state.rocks[0];\n    state.bullets = [{ x: rock.x, y: rock.y, dx: 0, dy: 0, life: 1 }];\n    hitRocks(state);\n    shots = shots + 1;\n}\nassert(state.rocks.length === 0, 'the wave should be clearable');\nassert(state.score > 0);")]),
  py=dict(starter="def hit_rocks(state):\n    # every bullet against every rock - one rock each\n    pass\n",
    answer="def hit_rocks(state):\n    surviving = []\n    hits = 0\n\n    for bullet in state[\"bullets\"]:\n        hit_index = -1\n        for r, rock in enumerate(state[\"rocks\"]):\n            if touches(bullet, rock, 1, ROCK_RADIUS[rock[\"size\"]]):\n                hit_index = r\n                break\n\n        if hit_index == -1:\n            surviving.append(bullet)\n        else:\n            rock = state[\"rocks\"].pop(hit_index)\n            state[\"score\"] += ROCK_SCORE[rock[\"size\"]]\n            state[\"rocks\"].extend(split_rock(rock))\n            hits += 1\n\n    state[\"bullets\"] = surviving\n    return hits\n",
    hints=["Two loops: bullets on the outside, rocks on the inside.",
           "touches(a, b, radius_a, radius_b) is written for you - a bullet's radius is 1.",
           "list.pop(index) takes one rock out AND hands it to you."],
    tests=[("A bullet on a rock breaks it",
            "state = create_game()\nstate['rocks'] = [make_rock(100, 100, 3)]\nstate['bullets'] = [{'x': 100, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nassert hit_rocks(state) == 1"),
           ("The rock is replaced by its pieces",
            "state = create_game()\nstate['rocks'] = [make_rock(100, 100, 3)]\nstate['bullets'] = [{'x': 100, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nhit_rocks(state)\nassert len(state['rocks']) == 2 and state['rocks'][0]['size'] == 2"),
           ("The bullet is used up",
            "state = create_game()\nstate['rocks'] = [make_rock(100, 100, 3)]\nstate['bullets'] = [{'x': 100, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nhit_rocks(state)\nassert state['bullets'] == []"),
           ("A hit scores",
            "state = create_game()\nstate['score'] = 0\nstate['rocks'] = [make_rock(100, 100, 3)]\nstate['bullets'] = [{'x': 100, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nhit_rocks(state)\nassert state['score'] == ROCK_SCORE[3]"),
           ("Small rocks are worth more than big ones",
            "assert ROCK_SCORE[1] > ROCK_SCORE[3]"),
           ("Shooting the smallest rock leaves nothing behind",
            "state = create_game()\nstate['rocks'] = [make_rock(100, 100, 1)]\nstate['bullets'] = [{'x': 100, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nhit_rocks(state)\nassert state['rocks'] == []"),
           ("A bullet in empty space hits nothing",
            "state = create_game()\nstate['rocks'] = [make_rock(300, 300, 3)]\nstate['bullets'] = [{'x': 20, 'y': 20, 'dx': 0, 'dy': 0, 'life': 1}]\nassert hit_rocks(state) == 0\nassert len(state['bullets']) == 1"),
           ("One bullet breaks one rock, not two",
            "state = create_game()\nstate['rocks'] = [make_rock(100, 100, 1), make_rock(102, 100, 1)]\nstate['bullets'] = [{'x': 101, 'y': 100, 'dx': 0, 'dy': 0, 'life': 1}]\nhit_rocks(state)\nassert len(state['rocks']) == 1"),
           ("A whole wave can be cleared",
            "state = create_game()\nfor _ in range(200):\n    if not state['rocks']:\n        break\n    rock = state['rocks'][0]\n    state['bullets'] = [{'x': rock['x'], 'y': rock['y'], 'dx': 0, 'dy': 0, 'life': 1}]\n    hit_rocks(state)\nassert state['rocks'] == [] and state['score'] > 0")]),
  demo=dict(kind="final", flags=dict(robot=True), caption="A robot pilot flies the finished game. Click the page to take over with the arrows and SPACE."),
  warning="Remove the bullet as soon as it hits. Leave it in and one shot will chew straight through the whole wave."),
]

write_workshop("asteroids", "Asteroids", STEPS)
