"""The five steps of "Build Bubble Shooter", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("bubble_centre", "bubbleCentre", "bubble_centre",
  "Where does a bubble sit?", "The ceiling of bubbles appears.",
  "<p>The bubbles live on a grid, but they are <em>circles</em> — and a circle is drawn from its middle, not its corner.</p>"
  "<p>So this gives back the MIDDLE of a cell: step across and down as usual, then add half a cell. Forget that half and every bubble is drawn a quarter of a cell up and to the left of where it belongs, which looks subtly wrong in a way that is maddening to track down.</p>",
  "column, row", "the middle of that cell: { x, y }",
  ["x is column × CELL, plus half a cell.",
   "y is row × CELL, plus half a cell."],
  js=dict(starter="function bubbleCentre(column, row) {\n    return { x: 0, y: 0 };\n}\n",
    answer="function bubbleCentre(column, row) {\n    return {\n        x: column * CELL + CELL / 2,\n        y: row * CELL + CELL / 2\n    };\n}\n",
    hints=["column * CELL gets you to the left edge of the cell.",
           "Add CELL / 2 to get to the middle.",
           "x: column * CELL + CELL / 2"],
    tests=[("The first cell's middle is half a cell in",
            "const c = bubbleCentre(0, 0);\nassert(c.x === CELL / 2, 'x is ' + c.x + ' — a circle is drawn from its MIDDLE');\nassert(c.y === CELL / 2);"),
           ("The next column is one cell across",
            "assert(bubbleCentre(1, 0).x - bubbleCentre(0, 0).x === CELL);"),
           ("The next row is one cell down",
            "assert(bubbleCentre(0, 1).y - bubbleCentre(0, 0).y === CELL);"),
           ("A cell in the middle of the grid",
            "const c = bubbleCentre(3, 2);\nassert(c.x === 3 * CELL + CELL / 2, 'x is ' + c.x);\nassert(c.y === 2 * CELL + CELL / 2);"),
           ("Every bubble fits on the field",
            "for (let row = 0; row < ROWS; row++) {\n    for (let column = 0; column < COLUMNS; column++) {\n        const c = bubbleCentre(column, row);\n        assert(c.x - BUBBLE_RADIUS >= 0 && c.x + BUBBLE_RADIUS <= FIELD_WIDTH, 'the bubble at column ' + column + ' hangs off the side');\n    }\n}"),
           ("It agrees with cellAtPixel",
            "for (let row = 0; row < ROWS; row++) {\n    for (let column = 0; column < COLUMNS; column++) {\n        const c = bubbleCentre(column, row);\n        const back = cellAtPixel(c.x, c.y);\n        assert(back && back.column === column && back.row === row, 'the middle of (' + column + ',' + row + ') should be inside that very cell');\n    }\n}")]),
  py=dict(starter="def bubble_centre(column, row):\n    return {\"x\": 0, \"y\": 0}\n",
    answer="def bubble_centre(column, row):\n    return {\"x\": column * CELL + CELL / 2, \"y\": row * CELL + CELL / 2}\n",
    hints=["column * CELL gets you to the left edge of the cell.",
           "Add CELL / 2 to get to the middle.",
           "{\"x\": column * CELL + CELL / 2, \"y\": row * CELL + CELL / 2}"],
    tests=[("The first cell's middle is half a cell in",
            "c = bubble_centre(0, 0)\nassert c['x'] == CELL / 2 and c['y'] == CELL / 2"),
           ("The next column is one cell across",
            "assert bubble_centre(1, 0)['x'] - bubble_centre(0, 0)['x'] == CELL"),
           ("The next row is one cell down",
            "assert bubble_centre(0, 1)['y'] - bubble_centre(0, 0)['y'] == CELL"),
           ("A cell in the middle of the grid",
            "c = bubble_centre(3, 2)\nassert c['x'] == 3 * CELL + CELL / 2 and c['y'] == 2 * CELL + CELL / 2"),
           ("Every bubble fits on the field",
            "for row in range(ROWS):\n    for column in range(COLUMNS):\n        c = bubble_centre(column, row)\n        assert 0 <= c['x'] - BUBBLE_RADIUS and c['x'] + BUBBLE_RADIUS <= FIELD_WIDTH"),
           ("It agrees with cell_at_pixel",
            "for row in range(ROWS):\n    for column in range(COLUMNS):\n        c = bubble_centre(column, row)\n        assert cell_at_pixel(c['x'], c['y']) == (column, row)")]),
  demo=dict(kind="grid", caption="Move the dashed box around and read the middle of each cell.")),

step("turn_shooter", "turnShooter", "turn_shooter",
  "Take aim", "The arrow swings.",
  "<p>Holding a key swings the aim round. That part is easy — the interesting part is the <strong>limits</strong>.</p>"
  "<p>The shooter must never point flat sideways, and certainly never downwards. A shot fired exactly horizontally would bounce between the two walls for ever and the game would simply stop, waiting for a bubble that is never going to land.</p>"
  "<p>Two lines of clamping turn an unplayable bug into a rule nobody notices.</p>",
  "state. change — -1 for left, 1 for right. seconds.",
  "nothing; it changes state.angle",
  ["Work out the new angle: the old one plus change × TURN_SPEED × seconds.",
   "If it is below MIN_ANGLE, hold it at MIN_ANGLE.",
   "If it is above MAX_ANGLE, hold it at MAX_ANGLE.",
   "Save it back."],
  js=dict(starter="function turnShooter(state, change, seconds) {\n    // swing the aim, but never past the limits\n}\n",
    answer="function turnShooter(state, change, seconds) {\n    let angle = state.angle + change * TURN_SPEED * seconds;\n    if (angle < MIN_ANGLE) { angle = MIN_ANGLE; }\n    if (angle > MAX_ANGLE) { angle = MAX_ANGLE; }\n    state.angle = angle;\n}\n",
    hints=["Work the new angle out into a variable, then clamp it, then save it.",
           "Math.max(MIN_ANGLE, Math.min(MAX_ANGLE, angle)) does both limits in one line.",
           "The time has to be part of the sum, or the aim moves at different speeds on different computers."],
    tests=[("Turning right increases the angle",
            "const state = createGame();\nstate.angle = -Math.PI / 2;\nturnShooter(state, 1, 0.1);\nassert(state.angle > -Math.PI / 2);"),
           ("Turning left decreases it",
            "const state = createGame();\nstate.angle = -Math.PI / 2;\nturnShooter(state, -1, 0.1);\nassert(state.angle < -Math.PI / 2);"),
           ("Not turning changes nothing",
            "const state = createGame();\nstate.angle = -Math.PI / 2;\nturnShooter(state, 0, 0.1);\nassert(state.angle === -Math.PI / 2);"),
           ("A longer frame turns further",
            "const slow = createGame();\nconst quick = createGame();\nslow.angle = -Math.PI / 2;\nquick.angle = -Math.PI / 2;\nturnShooter(slow, 1, 0.1);\nturnShooter(quick, 1, 0.2);\nassert(quick.angle > slow.angle, 'the time must be part of the sum');"),
           ("It stops at the left-hand limit",
            "const state = createGame();\nfor (let i = 0; i < 200; i++) { turnShooter(state, -1, 0.05); }\nassert(Math.abs(state.angle - MIN_ANGLE) < 0.0001, 'the aim reached ' + state.angle.toFixed(2) + ' — it must stop at ' + MIN_ANGLE.toFixed(2));"),
           ("It stops at the right-hand limit",
            "const state = createGame();\nfor (let i = 0; i < 200; i++) { turnShooter(state, 1, 0.05); }\nassert(Math.abs(state.angle - MAX_ANGLE) < 0.0001, 'the aim reached ' + state.angle.toFixed(2));"),
           ("The aim can never point downwards",
            "const state = createGame();\nfor (let i = 0; i < 400; i++) {\n    turnShooter(state, i % 2 === 0 ? 1 : -1, 0.4);\n    assert(Math.sin(state.angle) < 0, 'the shooter is pointing DOWN — a shot fired there would never land');\n}")]),
  py=dict(starter="def turn_shooter(state, change, seconds):\n    # swing the aim, but never past the limits\n    pass\n",
    answer="def turn_shooter(state, change, seconds):\n    angle = state[\"angle\"] + change * TURN_SPEED * seconds\n    state[\"angle\"] = max(MIN_ANGLE, min(MAX_ANGLE, angle))\n",
    hints=["Work the new angle out into a variable, then clamp it, then save it.",
           "max(MIN_ANGLE, min(MAX_ANGLE, angle)) does both limits in one line.",
           "The time has to be part of the sum."],
    tests=[("Turning right increases the angle",
            "state = create_game()\nstate['angle'] = -math.pi / 2\nturn_shooter(state, 1, 0.1)\nassert state['angle'] > -math.pi / 2"),
           ("Turning left decreases it",
            "state = create_game()\nstate['angle'] = -math.pi / 2\nturn_shooter(state, -1, 0.1)\nassert state['angle'] < -math.pi / 2"),
           ("Not turning changes nothing",
            "state = create_game()\nstate['angle'] = -math.pi / 2\nturn_shooter(state, 0, 0.1)\nassert state['angle'] == -math.pi / 2"),
           ("A longer frame turns further",
            "slow = create_game()\nquick = create_game()\nslow['angle'] = quick['angle'] = -math.pi / 2\nturn_shooter(slow, 1, 0.1)\nturn_shooter(quick, 1, 0.2)\nassert quick['angle'] > slow['angle']"),
           ("It stops at the left-hand limit",
            "state = create_game()\nfor _ in range(200):\n    turn_shooter(state, -1, 0.05)\nassert abs(state['angle'] - MIN_ANGLE) < 0.0001"),
           ("It stops at the right-hand limit",
            "state = create_game()\nfor _ in range(200):\n    turn_shooter(state, 1, 0.05)\nassert abs(state['angle'] - MAX_ANGLE) < 0.0001"),
           ("The aim can never point downwards",
            "state = create_game()\nfor i in range(400):\n    turn_shooter(state, 1 if i % 2 == 0 else -1, 0.4)\n    assert math.sin(state['angle']) < 0, 'a shot fired downwards would never land'")]),
  demo=dict(kind="final", caption="Aim left and right — the dashed line shows where the shot will go."),
  warning="Clamp the angle. Without limits a player can aim flat sideways, and that shot bounces between the walls until the end of time."),

step("same_group", "sameGroup", "same_group",
  "Which ones are joined?", "The game can see a group.",
  "<p>You have met this before: it is <strong>flood fill</strong>, exactly as in Minesweeper. Start at one bubble, look at its neighbours, and keep spreading while they hold the same kind.</p>"
  "<p>Two details make it work. Check <em>have I seen this one before?</em> inside the loop, or a group of three will chase itself round in circles for ever. And an empty cell has no group at all, so deal with that first — it is the case that reaches you when a shot lands somewhere unexpected.</p>",
  "grid, column, row",
  "a list of the joined cells of the same kind, including the one you started from",
  ["Look at what kind is in the starting cell. If it is EMPTY, there is no group: return an empty list.",
   "Keep a set of the cells you have seen, a list for the answer, and a to-do list holding the first cell.",
   "While the to-do list is not empty: take one off; skip it if you have seen it or it holds a different kind; otherwise mark it, keep it, and add its neighbours to the to-do list."],
  js=dict(starter="function sameGroup(grid, column, row) {\n    // flood fill, but only through bubbles of the same kind\n    return [];\n}\n",
    answer="function sameGroup(grid, column, row) {\n    const kind = grid[bubbleIndex(column, row)];\n    if (kind === EMPTY) {\n        return [];\n    }\n\n    const seen = {};\n    const group = [];\n    const todo = [{ column: column, row: row }];\n\n    while (todo.length > 0) {\n        const cell = todo.pop();\n        const index = bubbleIndex(cell.column, cell.row);\n\n        if (seen[index] || grid[index] !== kind) {\n            continue;\n        }\n        seen[index] = true;\n        group.push(cell);\n\n        const around = neighbours(cell.column, cell.row);\n        for (let i = 0; i < around.length; i++) {\n            todo.push(around[i]);\n        }\n    }\n    return group;\n}\n",
    hints=["neighbours(column, row) is written for you and never leaves the grid.",
           "The 'have I seen this?' check goes INSIDE the loop — that is what stops it going round for ever.",
           "An empty starting cell returns an empty list, before anything else happens."],
    tests=[("A lone bubble is a group of one",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\ngrid[bubbleIndex(3, 1)] = 2;\nassert(sameGroup(grid, 3, 1).length === 1);"),
           ("A row of three is one group",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\n[1, 2, 3].forEach(function (c) { grid[bubbleIndex(c, 0)] = 1; });\nassert(sameGroup(grid, 2, 0).length === 3, 'found ' + sameGroup(grid, 2, 0).length);"),
           ("A column of three is one group too",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\n[0, 1, 2].forEach(function (r) { grid[bubbleIndex(4, r)] = 3; });\nassert(sameGroup(grid, 4, 1).length === 3);"),
           ("A different kind next door is NOT in the group",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\ngrid[bubbleIndex(2, 0)] = 1;\ngrid[bubbleIndex(3, 0)] = 4;\nassert(sameGroup(grid, 2, 0).length === 1, 'a bubble of another kind must not join the group');"),
           ("An empty cell has no group",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\nassert(sameGroup(grid, 4, 4).length === 0);"),
           ("A big blob is found whole",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\nfor (let row = 0; row < 3; row++) {\n    for (let column = 0; column < 4; column++) {\n        grid[bubbleIndex(column, row)] = 2;\n    }\n}\nassert(sameGroup(grid, 1, 1).length === 12, 'found ' + sameGroup(grid, 1, 1).length + ' of 12');"),
           ("Starting anywhere in the group finds the same group",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\n[1, 2, 3].forEach(function (c) { grid[bubbleIndex(c, 0)] = 1; });\nassert(sameGroup(grid, 1, 0).length === sameGroup(grid, 3, 0).length);"),
           ("Nothing appears twice",
            "const grid = [];\nfor (let i = 0; i < COLUMNS * ROWS; i++) { grid.push(EMPTY); }\nfor (let row = 0; row < 3; row++) {\n    for (let column = 0; column < 3; column++) {\n        grid[bubbleIndex(column, row)] = 0;\n    }\n}\nconst group = sameGroup(grid, 1, 1);\nconst seen = {};\ngroup.forEach(function (cell) {\n    const key = bubbleIndex(cell.column, cell.row);\n    assert(!seen[key], 'cell ' + key + ' is in the list twice');\n    seen[key] = true;\n});")]),
  py=dict(starter="def same_group(grid, column, row):\n    # flood fill, but only through bubbles of the same kind\n    return []\n",
    answer="def same_group(grid, column, row):\n    kind = grid[bubble_index(column, row)]\n    if kind == EMPTY:\n        return []\n\n    seen = set()\n    group = []\n    todo = [(column, row)]\n\n    while todo:\n        c, r = todo.pop()\n        index = bubble_index(c, r)\n\n        if index in seen or grid[index] != kind:\n            continue\n        seen.add(index)\n        group.append((c, r))\n        todo.extend(neighbours(c, r))\n\n    return group\n",
    hints=["neighbours(column, row) is written for you and never leaves the grid.",
           "The 'have I seen this?' check goes INSIDE the loop.",
           "An empty starting cell returns an empty list, before anything else happens."],
    tests=[("A lone bubble is a group of one",
            "grid = [EMPTY] * (COLUMNS * ROWS)\ngrid[bubble_index(3, 1)] = 2\nassert len(same_group(grid, 3, 1)) == 1"),
           ("A row of three is one group",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2, 3):\n    grid[bubble_index(c, 0)] = 1\nassert len(same_group(grid, 2, 0)) == 3"),
           ("A column of three is one group too",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nfor r in (0, 1, 2):\n    grid[bubble_index(4, r)] = 3\nassert len(same_group(grid, 4, 1)) == 3"),
           ("A different kind next door is NOT in the group",
            "grid = [EMPTY] * (COLUMNS * ROWS)\ngrid[bubble_index(2, 0)] = 1\ngrid[bubble_index(3, 0)] = 4\nassert len(same_group(grid, 2, 0)) == 1"),
           ("An empty cell has no group",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nassert same_group(grid, 4, 4) == []"),
           ("A big blob is found whole",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nfor row in range(3):\n    for column in range(4):\n        grid[bubble_index(column, row)] = 2\nassert len(same_group(grid, 1, 1)) == 12"),
           ("Starting anywhere in the group finds the same group",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2, 3):\n    grid[bubble_index(c, 0)] = 1\nassert len(same_group(grid, 1, 0)) == len(same_group(grid, 3, 0))"),
           ("Nothing appears twice",
            "grid = [EMPTY] * (COLUMNS * ROWS)\nfor row in range(3):\n    for column in range(3):\n        grid[bubble_index(column, row)] = 0\ngroup = same_group(grid, 1, 1)\nassert len(group) == len(set(group))")]),
  demo=dict(kind="group", caption="Move the box onto a bubble — the outlines show everything joined to it."),
  warning="Check 'have I seen this cell?' inside the loop. Without it, two neighbouring bubbles put each other on the to-do list for ever."),

step("pop_group", "popGroup", "pop_group",
  "Pop!", "Bubbles burst.",
  "<p>The rule everybody knows: <strong>three or more</strong>. Two of a kind touching is not enough, and nothing at all happens.</p>"
  "<p>That refusal is the game. If pairs popped, you could clear the board by firing at random.</p>",
  "state, group — the cells found by same-group",
  "how many bubbles popped",
  ["If the group is smaller than MIN_POP, do nothing and return 0.",
   "Otherwise set every cell in the group to EMPTY.",
   "Score POINTS_PER_BUBBLE for each one, count them, and return how many."],
  js=dict(starter="function popGroup(state, group) {\n    // three or more, or nothing at all\n}\n",
    answer="function popGroup(state, group) {\n    if (group.length < MIN_POP) {\n        return 0;\n    }\n    for (let i = 0; i < group.length; i++) {\n        state.grid[bubbleIndex(group[i].column, group[i].row)] = EMPTY;\n    }\n    state.score = state.score + group.length * POINTS_PER_BUBBLE;\n    state.popped = state.popped + group.length;\n    return group.length;\n}\n",
    hints=["The guard comes first: too small, return 0, and change nothing at all.",
           "EMPTY is what an empty cell holds.",
           "Score for every bubble in the group, not just one."],
    tests=[("Three pop",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\n[1, 2, 3].forEach(function (c) { state.grid[bubbleIndex(c, 0)] = 1; });\nconst group = sameGroup(state.grid, 2, 0);\nassert(popGroup(state, group) === 3);"),
           ("The cells really are emptied",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\n[1, 2, 3].forEach(function (c) { state.grid[bubbleIndex(c, 0)] = 1; });\npopGroup(state, sameGroup(state.grid, 2, 0));\nassert(state.grid[bubbleIndex(2, 0)] === EMPTY);"),
           ("Two do NOT pop",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\n[1, 2].forEach(function (c) { state.grid[bubbleIndex(c, 0)] = 1; });\nassert(popGroup(state, sameGroup(state.grid, 1, 0)) === 0, 'a pair is not enough');"),
           ("A pair is left exactly where it was",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\n[1, 2].forEach(function (c) { state.grid[bubbleIndex(c, 0)] = 1; });\npopGroup(state, sameGroup(state.grid, 1, 0));\nassert(state.grid[bubbleIndex(1, 0)] === 1, 'nothing should have changed');"),
           ("Popping scores",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.score = 0;\n[1, 2, 3].forEach(function (c) { state.grid[bubbleIndex(c, 0)] = 1; });\npopGroup(state, sameGroup(state.grid, 2, 0));\nassert(state.score === 3 * POINTS_PER_BUBBLE, 'score is ' + state.score);"),
           ("A bigger group scores more",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.score = 0;\nfor (let c = 0; c < 6; c++) { state.grid[bubbleIndex(c, 0)] = 1; }\npopGroup(state, sameGroup(state.grid, 2, 0));\nassert(state.score === 6 * POINTS_PER_BUBBLE);"),
           ("An empty group does nothing",
            "const state = createGame();\nconst before = state.score;\nassert(popGroup(state, []) === 0);\nassert(state.score === before);")]),
  py=dict(starter="def pop_group(state, group):\n    # three or more, or nothing at all\n    pass\n",
    answer="def pop_group(state, group):\n    if len(group) < MIN_POP:\n        return 0\n    for column, row in group:\n        state[\"grid\"][bubble_index(column, row)] = EMPTY\n    state[\"score\"] += len(group) * POINTS_PER_BUBBLE\n    state[\"popped\"] += len(group)\n    return len(group)\n",
    hints=["The guard comes first: too small, return 0, and change nothing at all.",
           "EMPTY is what an empty cell holds.",
           "Score for every bubble in the group, not just one."],
    tests=[("Three pop",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2, 3):\n    state['grid'][bubble_index(c, 0)] = 1\nassert pop_group(state, same_group(state['grid'], 2, 0)) == 3"),
           ("The cells really are emptied",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2, 3):\n    state['grid'][bubble_index(c, 0)] = 1\npop_group(state, same_group(state['grid'], 2, 0))\nassert state['grid'][bubble_index(2, 0)] == EMPTY"),
           ("Two do NOT pop",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2):\n    state['grid'][bubble_index(c, 0)] = 1\nassert pop_group(state, same_group(state['grid'], 1, 0)) == 0"),
           ("A pair is left exactly where it was",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nfor c in (1, 2):\n    state['grid'][bubble_index(c, 0)] = 1\npop_group(state, same_group(state['grid'], 1, 0))\nassert state['grid'][bubble_index(1, 0)] == 1"),
           ("Popping scores",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['score'] = 0\nfor c in (1, 2, 3):\n    state['grid'][bubble_index(c, 0)] = 1\npop_group(state, same_group(state['grid'], 2, 0))\nassert state['score'] == 3 * POINTS_PER_BUBBLE"),
           ("A bigger group scores more",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['score'] = 0\nfor c in range(6):\n    state['grid'][bubble_index(c, 0)] = 1\npop_group(state, same_group(state['grid'], 2, 0))\nassert state['score'] == 6 * POINTS_PER_BUBBLE"),
           ("An empty group does nothing",
            "state = create_game()\nbefore = state['score']\nassert pop_group(state, []) == 0\nassert state['score'] == before")]),
  demo=dict(kind="drop", caption="Press Pop the group and watch the three at the top left burst.")),

step("drop_floaters", "dropFloaters", "drop_floaters",
  "Cut them loose", "The whole game works!",
  "<p>The most satisfying rule in the game, and the cleverest one.</p>"
  "<p>It is the <em>same search again</em>, asked a completely different question. Instead of \"which bubbles of the same kind are joined to this one?\", ask <strong>\"which bubbles are joined to the ceiling?\"</strong> — starting from the whole top row, and ignoring what kind they are.</p>"
  "<p>Whatever the search never reaches must be dangling in mid-air. Down it all comes, and each one is worth more than a popped bubble, because knocking out a whole cluster with one shot deserves it.</p>",
  "state",
  "how many bubbles fell",
  ["Start a to-do list holding every bubble in the TOP row.",
   "Spread out through the neighbours exactly as before, but do not care what kind they are. Mark everything you reach as HELD.",
   "Then look at every cell: anything that holds a bubble but was never marked is floating.",
   "Empty those, score POINTS_PER_DROP for each, and return how many fell."],
  js=dict(starter="function dropFloaters(state) {\n    // what is joined to the ceiling stays; everything else falls\n}\n",
    answer="function dropFloaters(state) {\n    const held = {};\n    const todo = [];\n\n    for (let column = 0; column < COLUMNS; column++) {\n        if (state.grid[bubbleIndex(column, 0)] !== EMPTY) {\n            todo.push({ column: column, row: 0 });\n        }\n    }\n\n    while (todo.length > 0) {\n        const cell = todo.pop();\n        const index = bubbleIndex(cell.column, cell.row);\n\n        if (held[index] || state.grid[index] === EMPTY) {\n            continue;\n        }\n        held[index] = true;\n\n        const around = neighbours(cell.column, cell.row);\n        for (let i = 0; i < around.length; i++) {\n            todo.push(around[i]);\n        }\n    }\n\n    let fell = 0;\n    for (let i = 0; i < state.grid.length; i++) {\n        if (state.grid[i] !== EMPTY && !held[i]) {\n            state.grid[i] = EMPTY;\n            fell = fell + 1;\n        }\n    }\n\n    if (fell > 0) {\n        state.score = state.score + fell * POINTS_PER_DROP;\n        state.dropped = state.dropped + fell;\n    }\n    return fell;\n}\n",
    hints=["Start the to-do list with EVERY bubble in row 0, not just one.",
           "This search ignores the kind — any bubble at all keeps the search going.",
           "Do the dropping in a second pass, after the search has finished."],
    tests=[("A bubble on the ceiling stays",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.grid[bubbleIndex(0, 0)] = 1;\nassert(dropFloaters(state) === 0);\nassert(state.grid[bubbleIndex(0, 0)] === 1);"),
           ("A bubble floating in mid-air falls",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.grid[bubbleIndex(5, 5)] = 2;\nassert(dropFloaters(state) === 1, 'nothing is holding that one up');\nassert(state.grid[bubbleIndex(5, 5)] === EMPTY);"),
           ("A chain hanging from the ceiling stays",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nfor (let row = 0; row < 5; row++) { state.grid[bubbleIndex(3, row)] = 1; }\nassert(dropFloaters(state) === 0, 'every one of those is joined to the top');"),
           ("Different kinds still hold each other up",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.grid[bubbleIndex(3, 0)] = 0;\nstate.grid[bubbleIndex(3, 1)] = 4;\nassert(dropFloaters(state) === 0, 'a bubble of any kind can hold up any other — this search ignores the kind');"),
           ("Cutting the thread brings the whole cluster down",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.grid[bubbleIndex(6, 0)] = 1;\nstate.grid[bubbleIndex(6, 1)] = 2;\n[5, 6, 7].forEach(function (c) { state.grid[bubbleIndex(c, 2)] = 2; });\nassert(dropFloaters(state) === 0, 'it is all still hanging on');\nstate.grid[bubbleIndex(6, 1)] = EMPTY;\nassert(dropFloaters(state) === 3, 'with the thread cut, all three should fall');"),
           ("Falling scores",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nstate.score = 0;\nstate.grid[bubbleIndex(5, 5)] = 2;\nstate.grid[bubbleIndex(6, 5)] = 2;\ndropFloaters(state);\nassert(state.score === 2 * POINTS_PER_DROP, 'score is ' + state.score);"),
           ("An empty board drops nothing",
            "const state = createGame();\nstate.grid = state.grid.map(function () { return EMPTY; });\nassert(dropFloaters(state) === 0);"),
           ("A full ceiling never falls",
            "const state = createGame();\nassert(dropFloaters(state) === 0, 'a freshly filled ceiling is all connected to the top');")]),
  py=dict(starter="def drop_floaters(state):\n    # what is joined to the ceiling stays; everything else falls\n    pass\n",
    answer="def drop_floaters(state):\n    held = set()\n    todo = [(column, 0) for column in range(COLUMNS)\n            if state[\"grid\"][bubble_index(column, 0)] != EMPTY]\n\n    while todo:\n        c, r = todo.pop()\n        index = bubble_index(c, r)\n\n        if index in held or state[\"grid\"][index] == EMPTY:\n            continue\n        held.add(index)\n        todo.extend(neighbours(c, r))\n\n    fell = 0\n    for i, kind in enumerate(state[\"grid\"]):\n        if kind != EMPTY and i not in held:\n            state[\"grid\"][i] = EMPTY\n            fell += 1\n\n    if fell:\n        state[\"score\"] += fell * POINTS_PER_DROP\n        state[\"dropped\"] += fell\n    return fell\n",
    hints=["Start the to-do list with EVERY bubble in row 0, not just one.",
           "This search ignores the kind - any bubble at all keeps the search going.",
           "Do the dropping in a second pass, after the search has finished."],
    tests=[("A bubble on the ceiling stays",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['grid'][bubble_index(0, 0)] = 1\nassert drop_floaters(state) == 0\nassert state['grid'][bubble_index(0, 0)] == 1"),
           ("A bubble floating in mid-air falls",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['grid'][bubble_index(5, 5)] = 2\nassert drop_floaters(state) == 1\nassert state['grid'][bubble_index(5, 5)] == EMPTY"),
           ("A chain hanging from the ceiling stays",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nfor row in range(5):\n    state['grid'][bubble_index(3, row)] = 1\nassert drop_floaters(state) == 0"),
           ("Different kinds still hold each other up",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['grid'][bubble_index(3, 0)] = 0\nstate['grid'][bubble_index(3, 1)] = 4\nassert drop_floaters(state) == 0, 'this search ignores the kind'"),
           ("Cutting the thread brings the whole cluster down",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['grid'][bubble_index(6, 0)] = 1\nstate['grid'][bubble_index(6, 1)] = 2\nfor c in (5, 6, 7):\n    state['grid'][bubble_index(c, 2)] = 2\nassert drop_floaters(state) == 0\nstate['grid'][bubble_index(6, 1)] = EMPTY\nassert drop_floaters(state) == 3"),
           ("Falling scores",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nstate['score'] = 0\nstate['grid'][bubble_index(5, 5)] = 2\nstate['grid'][bubble_index(6, 5)] = 2\ndrop_floaters(state)\nassert state['score'] == 2 * POINTS_PER_DROP"),
           ("An empty board drops nothing",
            "state = create_game()\nstate['grid'] = [EMPTY] * (COLUMNS * ROWS)\nassert drop_floaters(state) == 0"),
           ("A full ceiling never falls",
            "assert drop_floaters(create_game()) == 0")]),
  demo=dict(kind="drop", caption="Press Cut the thread, then Let them fall — the whole cluster on the right drops."),
  warning="Start from EVERY bubble in the top row. Start from just one and everything hanging from a different part of the ceiling is wrongly thrown away."),
]

write_workshop("bubbles", "Bubble Shooter", STEPS)
