"""The seven steps of "Build Connect Four", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("cell_index", "cellIndex", "cell_index",
  "Number the holes", "The board has places for counters.",
  "<p>Seven columns and six rows — 42 holes — stored as one flat <strong>list</strong>. Row 0 is the TOP, so row 5 is the bottom where counters land.</p>",
  "column (0 to 6), row (0 to 5)",
  "the position of that hole in the flat list of 42",
  ["Skip a whole row of holes for every row above: row * COLUMNS.",
   "Add the column.", "Return the answer."],
  js=dict(starter="function cellIndex(column, row) {\n    // skip whole rows, then add the column\n}\n",
    answer="function cellIndex(column, row) {\n    return row * COLUMNS + column;\n}\n",
    hints=["One line.", "A row is COLUMNS holes wide.", "return row * COLUMNS + column;"],
    tests=[("The top-left hole is 0", "assert(cellIndex(0, 0) === 0, 'gave ' + cellIndex(0, 0));"),
           ("The top-right hole is 6", "assert(cellIndex(6, 0) === 6, 'gave ' + cellIndex(6, 0));"),
           ("The bottom-left hole is 35", "assert(cellIndex(0, 5) === 35, 'gave ' + cellIndex(0, 5));"),
           ("The bottom-right hole is 41", "assert(cellIndex(6, 5) === 41, 'gave ' + cellIndex(6, 5));"),
           ("One row down adds COLUMNS", "assert(cellIndex(2, 3) - cellIndex(2, 2) === COLUMNS);"),
           ("All 42 holes get different numbers",
            "const seen = {};\nfor (let r = 0; r < ROWS; r++) { for (let c = 0; c < COLUMNS; c++) { seen[cellIndex(c, r)] = true; } }\nassert(Object.keys(seen).length === 42, 'only ' + Object.keys(seen).length + ' different numbers');")]),
  py=dict(starter="def cell_index(column, row):\n    # skip whole rows, then add the column\n    pass\n",
    answer="def cell_index(column, row):\n    return row * COLUMNS + column\n",
    hints=["One line.", "A row is COLUMNS holes wide.", "return row * COLUMNS + column"],
    tests=[("The top-left hole is 0", "got = cell_index(0, 0)\nassert got == 0, f'gave {got}'"),
           ("The top-right hole is 6", "assert cell_index(6, 0) == 6"),
           ("The bottom-left hole is 35", "got = cell_index(0, 5)\nassert got == 35, f'gave {got}'"),
           ("The bottom-right hole is 41", "assert cell_index(6, 5) == 41"),
           ("One row down adds COLUMNS", "assert cell_index(2, 3) - cell_index(2, 2) == COLUMNS"),
           ("All 42 holes get different numbers",
            "seen = {cell_index(c, r) for r in range(ROWS) for c in range(COLUMNS)}\nassert len(seen) == 42, f'only {len(seen)} different numbers'")]),
  demo=dict(kind="grid", caption="Your function numbers all 42 holes.")),

step("drop_row", "dropRow", "drop_row",
  "Where does it land?", "Counters fall to the bottom.",
  "<p>This is what makes Connect Four different from noughts and crosses: you do not choose a square, you choose a <strong>column</strong>, and gravity does the rest.</p>"
  "<p>So the game has to work out which row a counter would stop in — the lowest free one.</p>",
  "board - the 42 holes. column - which column.",
  "the row the counter would land in, or -1 when the column is full",
  ["Start at the BOTTOM row (ROWS - 1) and walk upwards.",
   "The first empty hole you meet is where the counter stops — return that row.",
   "If you get all the way to the top without finding one, the column is full: return -1."],
  js=dict(starter="function dropRow(board, column) {\n    // walk up from the bottom looking for the first empty hole\n}\n",
    answer="function dropRow(board, column) {\n    for (let row = ROWS - 1; row >= 0; row--) {\n        if (board[cellIndex(column, row)] === EMPTY) {\n            return row;\n        }\n    }\n    return -1;\n}\n",
    hints=["Count DOWNWARDS in the loop: for (let row = ROWS - 1; row >= 0; row--)",
           "Check board[cellIndex(column, row)] === EMPTY.",
           "return -1; goes after the loop, for a full column."],
    tests=[("On an empty board a counter falls to the bottom row",
            "const board = new Array(CELL_COUNT).fill(EMPTY);\nassert(dropRow(board, 3) === ROWS - 1, 'gave ' + dropRow(board, 3) + ', expected ' + (ROWS - 1));"),
           ("It lands on top of a counter already there",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nboard[cellIndex(3, ROWS - 1)] = 'R';\nassert(dropRow(board, 3) === ROWS - 2, 'gave ' + dropRow(board, 3));"),
           ("A full column gives -1",
            "const board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let row = 0; row < ROWS; row++) { board[cellIndex(2, row)] = 'Y'; }\nassert(dropRow(board, 2) === -1, 'gave ' + dropRow(board, 2));"),
           ("Other columns are not affected",
            "const board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let row = 0; row < ROWS; row++) { board[cellIndex(2, row)] = 'Y'; }\nassert(dropRow(board, 1) === ROWS - 1, 'column 1 is still empty');"),
           ("A column with one gap at the top",
            "const board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let row = 1; row < ROWS; row++) { board[cellIndex(0, row)] = 'R'; }\nassert(dropRow(board, 0) === 0, 'only the top hole is free — gave ' + dropRow(board, 0));")]),
  py=dict(starter="def drop_row(board, column):\n    # walk up from the bottom looking for the first empty hole\n    pass\n",
    answer="def drop_row(board, column):\n    for row in range(ROWS - 1, -1, -1):\n        if board[cell_index(column, row)] == EMPTY:\n            return row\n    return -1\n",
    hints=["range(ROWS - 1, -1, -1) counts downwards: 5, 4, 3, 2, 1, 0.",
           "Check board[cell_index(column, row)] == EMPTY.",
           "return -1 goes after the loop, for a full column."],
    tests=[("On an empty board a counter falls to the bottom row",
            "board = [EMPTY] * CELL_COUNT\ngot = drop_row(board, 3)\nassert got == ROWS - 1, f'gave {got}, expected {ROWS - 1}'"),
           ("It lands on top of a counter already there",
            "board = [EMPTY] * CELL_COUNT\nboard[cell_index(3, ROWS - 1)] = 'R'\nassert drop_row(board, 3) == ROWS - 2"),
           ("A full column gives -1",
            "board = [EMPTY] * CELL_COUNT\nfor row in range(ROWS):\n    board[cell_index(2, row)] = 'Y'\nassert drop_row(board, 2) == -1"),
           ("Other columns are not affected",
            "board = [EMPTY] * CELL_COUNT\nfor row in range(ROWS):\n    board[cell_index(2, row)] = 'Y'\nassert drop_row(board, 1) == ROWS - 1"),
           ("A column with one gap at the top",
            "board = [EMPTY] * CELL_COUNT\nfor row in range(1, ROWS):\n    board[cell_index(0, row)] = 'R'\nassert drop_row(board, 0) == 0")]),
  demo=dict(kind="drop", caption="Aim at a column and watch your function say which row a counter would reach.")),

step("drop_piece", "dropPiece", "drop_piece",
  "Drop a counter", "The board fills up.",
  "<p>Now put the counter where it lands. As always, build a <strong>new</strong> board — the computer will want to try drops without really making them.</p>",
  "board, column, mark - 'R' for you or 'Y' for the computer",
  "a NEW board with the counter added (unchanged if the column is full)",
  ["Ask drop-row where the counter would land.",
   "If that is -1 the column is full: return a copy, unchanged.",
   "Otherwise copy the board, put the mark in that hole, and return the copy."],
  js=dict(starter="function dropPiece(board, column, mark) {\n    // find the row, then put the mark there on a COPY\n}\n",
    answer="function dropPiece(board, column, mark) {\n    const row = dropRow(board, column);\n    if (row === -1) {\n        return board.slice();\n    }\n    const next = board.slice();\n    next[cellIndex(column, row)] = mark;\n    return next;\n}\n",
    hints=["Reuse dropRow — you already wrote it.",
           "board.slice() makes the copy.",
           "next[cellIndex(column, row)] = mark;"],
    tests=[("The counter lands at the bottom",
            "const board = dropPiece(new Array(CELL_COUNT).fill(EMPTY), 3, 'R');\nassert(board[cellIndex(3, ROWS - 1)] === 'R', 'the bottom hole of column 3 should hold R');"),
           ("Two drops stack up",
            "let board = dropPiece(new Array(CELL_COUNT).fill(EMPTY), 3, 'R');\nboard = dropPiece(board, 3, 'Y');\nassert(board[cellIndex(3, ROWS - 2)] === 'Y', 'the second counter sits on the first');"),
           ("Only one hole changes",
            "const board = dropPiece(new Array(CELL_COUNT).fill(EMPTY), 3, 'R');\nassert(board.filter(m => m !== EMPTY).length === 1);"),
           ("A full column leaves the board alone",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let i = 0; i < ROWS; i++) { board = dropPiece(board, 0, 'R'); }\nconst after = dropPiece(board, 0, 'Y');\nassert(after.filter(m => m === 'Y').length === 0, 'nothing should fit in a full column');"),
           ("The board you were given is not changed",
            "const before = new Array(CELL_COUNT).fill(EMPTY);\ndropPiece(before, 3, 'R');\nassert(before.every(m => m === EMPTY), 'you changed the board you were given');")]),
  py=dict(starter="def drop_piece(board, column, mark):\n    # find the row, then put the mark there on a COPY\n    pass\n",
    answer="def drop_piece(board, column, mark):\n    row = drop_row(board, column)\n    next_board = list(board)\n    if row != -1:\n        next_board[cell_index(column, row)] = mark\n    return next_board\n",
    hints=["Reuse drop_row — you already wrote it.",
           "list(board) makes the copy.",
           "next_board[cell_index(column, row)] = mark"],
    tests=[("The counter lands at the bottom",
            "board = drop_piece([EMPTY] * CELL_COUNT, 3, 'R')\nassert board[cell_index(3, ROWS - 1)] == 'R'"),
           ("Two drops stack up",
            "board = drop_piece([EMPTY] * CELL_COUNT, 3, 'R')\nboard = drop_piece(board, 3, 'Y')\nassert board[cell_index(3, ROWS - 2)] == 'Y'"),
           ("Only one hole changes",
            "board = drop_piece([EMPTY] * CELL_COUNT, 3, 'R')\nassert sum(1 for m in board if m != EMPTY) == 1"),
           ("A full column leaves the board alone",
            "board = [EMPTY] * CELL_COUNT\nfor _ in range(ROWS):\n    board = drop_piece(board, 0, 'R')\nafter = drop_piece(board, 0, 'Y')\nassert 'Y' not in after, 'nothing should fit in a full column'"),
           ("The board you were given is not changed",
            "before = [EMPTY] * CELL_COUNT\ndrop_piece(before, 3, 'R')\nassert all(m == EMPTY for m in before)")]),
  demo=dict(kind="drop", caption="Press Fill it a few times and watch the column stack up.")),

step("count_in_direction", "countInDirection", "count_in_direction",
  "Count along a line", "The game can look in any direction.",
  "<p>To find four in a row you need to be able to count counters going <em>any</em> way: right, down, and both diagonals.</p>"
  "<p>This function starts at a hole and walks in one direction, counting how many of your counters it passes — <strong>not</strong> counting the starting hole itself.</p>",
  "board, column, row - where to start. dx, dy - the step. mark - whose counters to count.",
  "how many of that mark are in a row in that direction",
  ["Start the count at 0, and take one step from the starting hole.",
   "While the hole is on the board AND holds the mark: add one and step again.",
   "Return the count."],
  js=dict(starter="function countInDirection(board, column, row, dx, dy, mark) {\n    let found = 0;\n    // step again and again while the mark keeps going\n    return found;\n}\n",
    answer="function countInDirection(board, column, row, dx, dy, mark) {\n    let found = 0;\n    let c = column + dx;\n    let r = row + dy;\n    while (isInsideBoard(c, r) && board[cellIndex(c, r)] === mark) {\n        found = found + 1;\n        c = c + dx;\n        r = r + dy;\n    }\n    return found;\n}\n",
    hints=["Take the first step BEFORE the loop, so the starting hole is not counted.",
           "The while condition has two parts: still on the board, and still the same mark.",
           "Do not forget to step again inside the loop, or it will never end."],
    tests=[("Three counters to the right",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[1,2,3].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nassert(countInDirection(board, 0, 5, 1, 0, 'R') === 3, 'gave ' + countInDirection(board, 0, 5, 1, 0, 'R'));"),
           ("The starting hole is not counted",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nboard[cellIndex(0, 5)] = 'R';\nassert(countInDirection(board, 0, 5, 1, 0, 'R') === 0, 'only the starting hole holds a counter, and it does not count');"),
           ("It stops at a different mark",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nboard[cellIndex(1, 5)] = 'R';\nboard[cellIndex(2, 5)] = 'Y';\nboard[cellIndex(3, 5)] = 'R';\nassert(countInDirection(board, 0, 5, 1, 0, 'R') === 1, 'the Y blocks the run — gave ' + countInDirection(board, 0, 5, 1, 0, 'R'));"),
           ("It stops at the edge of the board",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let c = 0; c < COLUMNS; c++) { board[cellIndex(c, 5)] = 'R'; }\nassert(countInDirection(board, 0, 5, 1, 0, 'R') === COLUMNS - 1, 'gave ' + countInDirection(board, 0, 5, 1, 0, 'R'));"),
           ("It counts upwards too",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[3,4,5].forEach(r => { board[cellIndex(2, r)] = 'Y'; });\nassert(countInDirection(board, 2, 2, 0, 1, 'Y') === 3, 'gave ' + countInDirection(board, 2, 2, 0, 1, 'Y'));"),
           ("It counts along a diagonal",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[[1,4],[2,3],[3,2]].forEach(p => { board[cellIndex(p[0], p[1])] = 'R'; });\nassert(countInDirection(board, 0, 5, 1, -1, 'R') === 3, 'gave ' + countInDirection(board, 0, 5, 1, -1, 'R'));")]),
  py=dict(starter="def count_in_direction(board, column, row, dx, dy, mark):\n    found = 0\n    # step again and again while the mark keeps going\n    return found\n",
    answer="def count_in_direction(board, column, row, dx, dy, mark):\n    found = 0\n    c, r = column + dx, row + dy\n    while is_inside_board(c, r) and board[cell_index(c, r)] == mark:\n        found += 1\n        c += dx\n        r += dy\n    return found\n",
    hints=["Take the first step BEFORE the loop, so the starting hole is not counted.",
           "`c, r = column + dx, row + dy` sets both at once.",
           "Step again inside the loop, or it will never end."],
    tests=[("Three counters to the right",
            "board = [EMPTY] * CELL_COUNT\nfor c in (1, 2, 3):\n    board[cell_index(c, 5)] = 'R'\ngot = count_in_direction(board, 0, 5, 1, 0, 'R')\nassert got == 3, f'gave {got}'"),
           ("The starting hole is not counted",
            "board = [EMPTY] * CELL_COUNT\nboard[cell_index(0, 5)] = 'R'\nassert count_in_direction(board, 0, 5, 1, 0, 'R') == 0"),
           ("It stops at a different mark",
            "board = [EMPTY] * CELL_COUNT\nboard[cell_index(1, 5)] = 'R'\nboard[cell_index(2, 5)] = 'Y'\nboard[cell_index(3, 5)] = 'R'\ngot = count_in_direction(board, 0, 5, 1, 0, 'R')\nassert got == 1, f'the Y blocks the run - gave {got}'"),
           ("It stops at the edge of the board",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(COLUMNS):\n    board[cell_index(c, 5)] = 'R'\nassert count_in_direction(board, 0, 5, 1, 0, 'R') == COLUMNS - 1"),
           ("It counts upwards too",
            "board = [EMPTY] * CELL_COUNT\nfor r in (3, 4, 5):\n    board[cell_index(2, r)] = 'Y'\nassert count_in_direction(board, 2, 2, 0, 1, 'Y') == 3"),
           ("It counts along a diagonal",
            "board = [EMPTY] * CELL_COUNT\nfor c, r in [(1,4),(2,3),(3,2)]:\n    board[cell_index(c, r)] = 'R'\nassert count_in_direction(board, 0, 5, 1, -1, 'R') == 3")]),
  demo=dict(kind="game", caption="Play a few counters — this function is what the win check is made of."),
  warning="Step once before the loop starts. If you count the hole you are standing on, every line will come out one too long."),

step("is_win_at", "isWinAt", "is_win_at",
  "Four in a row!", "The game can be won.",
  "<p>Here is the neat bit. You do not have to search the whole board — only the counter that was <em>just dropped</em> can have made a new line.</p>"
  "<p>So from that counter, look both ways along each of the four directions and add them up, plus one for the counter itself.</p>"
  "<pre class=\"mini-code\">   . . R R R . .        going right: 2 counters\n         ^             going left:  0 counters\n     just dropped      2 + 0 + 1 = 3 — not yet!</pre>",
  "board, column, row - the counter just dropped. mark - whose it is.",
  "True if it is part of a line of WIN_LENGTH or more",
  ["For each direction in DIRECTIONS (across, down, and both diagonals):",
   "    count one way with count-in-direction,",
   "    count the OPPOSITE way (use -dx and -dy),",
   "    add them together and add 1 for the counter itself.",
   "If any direction reaches WIN_LENGTH, it is a win."],
  js=dict(starter="function isWinAt(board, column, row, mark) {\n    // look both ways along each of the four directions\n}\n",
    answer="function isWinAt(board, column, row, mark) {\n    for (let i = 0; i < DIRECTIONS.length; i++) {\n        const dx = DIRECTIONS[i][0];\n        const dy = DIRECTIONS[i][1];\n        const total = 1 +\n            countInDirection(board, column, row, dx, dy, mark) +\n            countInDirection(board, column, row, -dx, -dy, mark);\n        if (total >= WIN_LENGTH) {\n            return true;\n        }\n    }\n    return false;\n}\n",
    hints=["DIRECTIONS holds the four [dx, dy] pairs you need.",
           "The opposite direction is -dx and -dy — that is why one loop covers both ways.",
           "Do not forget the + 1 for the counter you just dropped."],
    tests=[("Four across is a win",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2,3].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nassert(isWinAt(board, 3, 5, 'R') === true, 'four along the bottom is a win');"),
           ("Three across is not",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nassert(isWinAt(board, 2, 5, 'R') === false, 'three is not four');"),
           ("A counter in the MIDDLE of a line still wins",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2,3].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nassert(isWinAt(board, 1, 5, 'R') === true, 'you must look BOTH ways, not just one');"),
           ("Four going down is a win",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[2,3,4,5].forEach(r => { board[cellIndex(1, r)] = 'Y'; });\nassert(isWinAt(board, 1, 2, 'Y') === true);"),
           ("Four on a diagonal is a win",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[[0,5],[1,4],[2,3],[3,2]].forEach(p => { board[cellIndex(p[0], p[1])] = 'R'; });\nassert(isWinAt(board, 3, 2, 'R') === true, 'diagonals count too');"),
           ("The other player's counters do not help",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nboard[cellIndex(3, 5)] = 'Y';\nassert(isWinAt(board, 3, 5, 'Y') === false);"),
           ("An empty board has no win",
            "assert(isWinAt(new Array(CELL_COUNT).fill(EMPTY), 3, 5, 'R') === false);")]),
  py=dict(starter="def is_win_at(board, column, row, mark):\n    # look both ways along each of the four directions\n    pass\n",
    answer="def is_win_at(board, column, row, mark):\n    for dx, dy in DIRECTIONS:\n        total = (1\n                 + count_in_direction(board, column, row, dx, dy, mark)\n                 + count_in_direction(board, column, row, -dx, -dy, mark))\n        if total >= WIN_LENGTH:\n            return True\n    return False\n",
    hints=["`for dx, dy in DIRECTIONS` unpacks each direction.",
           "The opposite direction is -dx, -dy.",
           "Do not forget the + 1 for the counter you just dropped."],
    tests=[("Four across is a win",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(4):\n    board[cell_index(c, 5)] = 'R'\nassert is_win_at(board, 3, 5, 'R') is True"),
           ("Three across is not",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(3):\n    board[cell_index(c, 5)] = 'R'\nassert is_win_at(board, 2, 5, 'R') is False"),
           ("A counter in the MIDDLE of a line still wins",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(4):\n    board[cell_index(c, 5)] = 'R'\nassert is_win_at(board, 1, 5, 'R') is True, 'you must look BOTH ways'"),
           ("Four going down is a win",
            "board = [EMPTY] * CELL_COUNT\nfor r in (2, 3, 4, 5):\n    board[cell_index(1, r)] = 'Y'\nassert is_win_at(board, 1, 2, 'Y') is True"),
           ("Four on a diagonal is a win",
            "board = [EMPTY] * CELL_COUNT\nfor c, r in [(0,5),(1,4),(2,3),(3,2)]:\n    board[cell_index(c, r)] = 'R'\nassert is_win_at(board, 3, 2, 'R') is True"),
           ("The other player's counters do not help",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(3):\n    board[cell_index(c, 5)] = 'R'\nboard[cell_index(3, 5)] = 'Y'\nassert is_win_at(board, 3, 5, 'Y') is False"),
           ("An empty board has no win",
            "assert is_win_at([EMPTY] * CELL_COUNT, 3, 5, 'R') is False")]),
  demo=dict(kind="game", caption="Try to get four in a row — your function decides when you have.")),

step("computer_column", "computerColumn", "computer_column",
  "Give the computer a brain", "You have an opponent!",
  "<p>Three rules make a surprisingly tough player:</p>"
  "<p><strong>1.</strong> Win if you can. <strong>2.</strong> Block if you must. <strong>3.</strong> Otherwise play near the middle — the middle column belongs to more possible lines than any other.</p>"
  "<p>There is one extra trap to avoid: never drop a counter that lets the player win by landing <em>on top of it</em>.</p>",
  "board - the 42 holes",
  "the column to play, or -1 if the board is full",
  ["Get the playable columns. If there are none, return -1.",
   "1. If dropping there would win for the COMPUTER, play it.",
   "2. Otherwise if dropping there would win for the PLAYER, play it to block.",
   "3. Otherwise sort the columns by how close they are to the middle (column 3),",
   "   and take the first one that does NOT let the player win on top of it."],
  js=dict(starter="function computerColumn(board) {\n    const open = playableColumns(board);\n    // win, block, then middle-ish and safe\n}\n",
    answer="function computerColumn(board) {\n    const open = playableColumns(board);\n    if (open.length === 0) {\n        return -1;\n    }\n\n    for (let i = 0; i < open.length; i++) {\n        const column = open[i];\n        const row = dropRow(board, column);\n        if (isWinAt(dropPiece(board, column, COMPUTER), column, row, COMPUTER)) {\n            return column;\n        }\n    }\n    for (let i = 0; i < open.length; i++) {\n        const column = open[i];\n        const row = dropRow(board, column);\n        if (isWinAt(dropPiece(board, column, PLAYER), column, row, PLAYER)) {\n            return column;\n        }\n    }\n\n    const middleFirst = open.slice().sort(function (a, b) {\n        return Math.abs(a - 3) - Math.abs(b - 3);\n    });\n    for (let i = 0; i < middleFirst.length; i++) {\n        const column = middleFirst[i];\n        const after = dropPiece(board, column, COMPUTER);\n        const replyRow = dropRow(after, column);\n        if (replyRow === -1 || !isWinAt(dropPiece(after, column, PLAYER), column, replyRow, PLAYER)) {\n            return column;\n        }\n    }\n    return middleFirst[0];\n}\n",
    hints=["To try a drop: isWinAt(dropPiece(board, column, MARK), column, dropRow(board, column), MARK)",
           "Remember to work out the row BEFORE the drop — that is where the counter lands.",
           "Sorting by Math.abs(column - 3) puts the middle column first."],
    tests=[("It takes a winning drop",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2].forEach(c => { board[cellIndex(c, 5)] = 'Y'; });\nassert(computerColumn(board) === 3, 'Y can win in column 3 — gave ' + computerColumn(board));"),
           ("It blocks the player",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2].forEach(c => { board[cellIndex(c, 5)] = 'R'; });\nassert(computerColumn(board) === 3, 'R would win in column 3 — gave ' + computerColumn(board));"),
           ("Winning beats blocking",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\n[0,1,2].forEach(c => { board[cellIndex(c, 5)] = 'Y'; });\n[0,1,2].forEach(c => { board[cellIndex(c, 4)] = 'R'; });\nassert(isWinAt(dropPiece(board, 3, COMPUTER), 3, 5, COMPUTER), 'setup check');\nassert(computerColumn(board) === 3, 'it should win rather than block');"),
           ("On an empty board it plays near the middle",
            "const move = computerColumn(new Array(CELL_COUNT).fill(EMPTY));\nassert(move === 3, 'the middle column is the strongest — gave ' + move);"),
           ("It never picks a full column",
            "let board = new Array(CELL_COUNT).fill(EMPTY);\nfor (let r = 0; r < ROWS; r++) { board[cellIndex(3, r)] = 'R'; }\nassert(computerColumn(board) !== 3, 'column 3 is full');"),
           ("It says -1 when the board is full",
            "assert(computerColumn(new Array(CELL_COUNT).fill('R')) === -1);"),
           ("It always returns a playable column",
            "for (let go = 0; go < 30; go++) {\n    let board = new Array(CELL_COUNT).fill(EMPTY);\n    board = dropPiece(board, 2, 'R');\n    board = dropPiece(board, 4, 'Y');\n    const move = computerColumn(board);\n    assert(dropRow(board, move) !== -1, 'column ' + move + ' has no room');\n}")]),
  py=dict(starter="def computer_column(board):\n    open_columns = playable_columns(board)\n    # win, block, then middle-ish and safe\n    pass\n",
    answer="def computer_column(board):\n    open_columns = playable_columns(board)\n    if not open_columns:\n        return -1\n\n    for column in open_columns:\n        row = drop_row(board, column)\n        if is_win_at(drop_piece(board, column, COMPUTER), column, row, COMPUTER):\n            return column\n    for column in open_columns:\n        row = drop_row(board, column)\n        if is_win_at(drop_piece(board, column, PLAYER), column, row, PLAYER):\n            return column\n\n    middle_first = sorted(open_columns, key=lambda column: abs(column - 3))\n    for column in middle_first:\n        after = drop_piece(board, column, COMPUTER)\n        reply_row = drop_row(after, column)\n        if reply_row == -1 or not is_win_at(drop_piece(after, column, PLAYER), column, reply_row, PLAYER):\n            return column\n    return middle_first[0]\n",
    hints=["To try a drop: is_win_at(drop_piece(board, column, MARK), column, drop_row(board, column), MARK)",
           "Work out the row BEFORE the drop — that is where the counter lands.",
           "sorted(open_columns, key=lambda c: abs(c - 3)) puts the middle first."],
    tests=[("It takes a winning drop",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(3):\n    board[cell_index(c, 5)] = 'Y'\ngot = computer_column(board)\nassert got == 3, f'Y can win in column 3 - gave {got}'"),
           ("It blocks the player",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(3):\n    board[cell_index(c, 5)] = 'R'\ngot = computer_column(board)\nassert got == 3, f'R would win in column 3 - gave {got}'"),
           ("Winning beats blocking",
            "board = [EMPTY] * CELL_COUNT\nfor c in range(3):\n    board[cell_index(c, 5)] = 'Y'\n    board[cell_index(c, 4)] = 'R'\nassert computer_column(board) == 3, 'it should win rather than block'"),
           ("On an empty board it plays near the middle",
            "got = computer_column([EMPTY] * CELL_COUNT)\nassert got == 3, f'the middle column is strongest - gave {got}'"),
           ("It never picks a full column",
            "board = [EMPTY] * CELL_COUNT\nfor r in range(ROWS):\n    board[cell_index(3, r)] = 'R'\nassert computer_column(board) != 3"),
           ("It says -1 when the board is full", "assert computer_column(['R'] * CELL_COUNT) == -1"),
           ("It always returns a playable column",
            "board = drop_piece(drop_piece([EMPTY] * CELL_COUNT, 2, 'R'), 4, 'Y')\nfor _ in range(30):\n    move = computer_column(board)\n    assert drop_row(board, move) != -1, f'column {move} has no room'")]),
  demo=dict(kind="game", caption="Now it fights back. Beating it takes a trap it cannot see."),
  warning="Work out the landing row BEFORE dropping. After the drop that row already holds the counter, and the win check needs the spot the counter is in."),

step("action_for_key", "actionForKey", "action_for_key",
  "Wire up the keyboard", "You can play without a mouse — the game is finished!",
  "<p>Left and right slide the counter above the board, and space drops it.</p>",
  "key - the key name from the browser",
  "\"left\", \"right\", \"drop\", \"pause\", \"restart\" - or nothing",
  ["Lowercase the key first.", "Left/right (or A/D) aim.",
   "Space, Enter or Down drops; p pauses; r starts a new round."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // return the action name, or null\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter' || k === 'arrowdown') { return 'drop'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["One if per action.", "Several keys can drop: space, Enter and the down arrow.",
           "The last line is: return null;"],
    tests=[("Left and right aim",
            "assert(actionForKey('ArrowLeft') === 'left' && actionForKey('ArrowRight') === 'right');"),
           ("A and D aim too", "assert(actionForKey('a') === 'left' && actionForKey('d') === 'right');"),
           ("Capitals still work", "assert(actionForKey('A') === 'left', 'did you lowercase the key?');"),
           ("Space drops", "assert(actionForKey(' ') === 'drop', 'gave ' + actionForKey(' '));"),
           ("Enter and Down drop too", "assert(actionForKey('Enter') === 'drop' && actionForKey('ArrowDown') === 'drop');"),
           ("P pauses and R restarts", "assert(actionForKey('p') === 'pause' && actionForKey('r') === 'restart');"),
           ("An unused key gives null", "assert(actionForKey('q') === null);")]),
  py=dict(starter="def action_for_key(key):\n    k = str(key).lower()\n    # a dictionary from key names to action names, then .get(k)\n    pass\n",
    answer="def action_for_key(key):\n    k = str(key).lower()\n    keys = {\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"drop\", \"spacebar\": \"drop\", \"enter\": \"drop\", \"arrowdown\": \"drop\", \"s\": \"drop\",\n        \"p\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(k)\n",
    hints=["A dictionary IS the lookup table.", "Several keys can share the drop action.",
           "keys.get(k) gives None for anything missing."],
    tests=[("Left and right aim",
            "assert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("A and D aim too", "assert action_for_key('a') == 'left' and action_for_key('d') == 'right'"),
           ("Capitals still work", "assert action_for_key('A') == 'left'"),
           ("Space drops", "got = action_for_key(' ')\nassert got == 'drop', f'gave {got!r}'"),
           ("Enter and Down drop too",
            "assert action_for_key('Enter') == 'drop' and action_for_key('ArrowDown') == 'drop'"),
           ("P pauses and R restarts", "assert action_for_key('p') == 'pause' and action_for_key('r') == 'restart'"),
           ("An unused key gives None", "assert action_for_key('q') is None")]),
  demo=dict(kind="final", caption="Click the page, then aim with the arrows and drop with space.")),
]

write_workshop("connect4", "Connect Four", STEPS)
