"""The eight steps of "Build Flappy", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("apply_gravity", "applyGravity", "apply_gravity",
  "Make the bird fall", "Gravity! The bird drops out of the sky.",
  "<p>Here is the idea that makes every falling thing in every game work.</p>"
  "<p>Gravity does not move the bird. It changes the bird's <strong>speed</strong>. Each frame the bird falls a little faster than the frame before, which is exactly what real falling looks like.</p>"
  "<p>So there are two sums, in this order: first speed changes, then position changes.</p>",
  "bird — something with y and dy. seconds — how long this frame took.",
  "nothing; it changes the bird",
  ["Add GRAVITY × seconds to the bird's dy.",
   "If dy is now bigger than MAX_FALL_SPEED, hold it there.",
   "Move the bird: add dy × seconds to its y."],
  js=dict(starter="function applyGravity(bird, seconds) {\n    // 1. speed up\n    // 2. don't fall TOO fast\n    // 3. move\n}\n",
    answer="function applyGravity(bird, seconds) {\n    bird.dy = bird.dy + GRAVITY * seconds;\n    if (bird.dy > MAX_FALL_SPEED) {\n        bird.dy = MAX_FALL_SPEED;\n    }\n    bird.y = bird.y + bird.dy * seconds;\n}\n",
    hints=["dy is the speed; y is the place. Gravity changes the speed.",
           "The order matters: change dy first, then use it to move y.",
           "bird.dy = bird.dy + GRAVITY * seconds;"],
    tests=[("Gravity speeds the bird up",
            "const bird = { y: 100, dy: 0 };\napplyGravity(bird, 0.1);\nassert(Math.abs(bird.dy - 90) < 0.001, 'dy is ' + bird.dy);"),
           ("A falling bird moves down",
            "const bird = { y: 100, dy: 200 };\napplyGravity(bird, 0.1);\nassert(bird.y > 100, 'the bird should have fallen');"),
           ("A flapping bird still rises for a moment",
            "const bird = { y: 100, dy: -300 };\napplyGravity(bird, 0.1);\nassert(bird.y < 100, 'y is ' + bird.y + ' — a bird moving upwards should go UP');"),
           ("It falls further every frame",
            "const bird = { y: 0, dy: 0 };\nconst before = bird.y;\napplyGravity(bird, 0.1);\nconst first = bird.y - before;\nconst mid = bird.y;\napplyGravity(bird, 0.1);\nconst second = bird.y - mid;\nassert(second > first, 'each frame should be a bigger drop than the last — that is what gravity means');"),
           ("It never falls faster than MAX_FALL_SPEED",
            "const bird = { y: 0, dy: 0 };\nfor (let i = 0; i < 200; i++) { applyGravity(bird, 0.1); }\nassert(bird.dy <= MAX_FALL_SPEED, 'dy reached ' + bird.dy);"),
           ("A longer frame falls further",
            "const slow = { y: 0, dy: 0 };\nconst fast = { y: 0, dy: 0 };\napplyGravity(slow, 0.05);\napplyGravity(fast, 0.1);\nassert(fast.y > slow.y, 'the time has to be part of both sums');")]),
  py=dict(starter="def apply_gravity(bird, seconds):\n    # 1. speed up\n    # 2. don't fall TOO fast\n    # 3. move\n    pass\n",
    answer="def apply_gravity(bird, seconds):\n    bird[\"dy\"] += GRAVITY * seconds\n    if bird[\"dy\"] > MAX_FALL_SPEED:\n        bird[\"dy\"] = MAX_FALL_SPEED\n    bird[\"y\"] += bird[\"dy\"] * seconds\n",
    hints=["dy is the speed; y is the place. Gravity changes the speed.",
           "The order matters: change dy first, then use it to move y.",
           "bird[\"dy\"] += GRAVITY * seconds"],
    tests=[("Gravity speeds the bird up",
            "bird = {'y': 100, 'dy': 0}\napply_gravity(bird, 0.1)\nassert abs(bird['dy'] - 90) < 0.001, f\"dy is {bird['dy']}\""),
           ("A falling bird moves down",
            "bird = {'y': 100, 'dy': 200}\napply_gravity(bird, 0.1)\nassert bird['y'] > 100"),
           ("A flapping bird still rises for a moment",
            "bird = {'y': 100, 'dy': -300}\napply_gravity(bird, 0.1)\nassert bird['y'] < 100, 'a bird moving upwards should go UP'"),
           ("It falls further every frame",
            "bird = {'y': 0, 'dy': 0}\napply_gravity(bird, 0.1)\nfirst = bird['y']\nmid = bird['y']\napply_gravity(bird, 0.1)\nsecond = bird['y'] - mid\nassert second > first, 'each frame should be a bigger drop than the last'"),
           ("It never falls faster than MAX_FALL_SPEED",
            "bird = {'y': 0, 'dy': 0}\nfor _ in range(200):\n    apply_gravity(bird, 0.1)\nassert bird['dy'] <= MAX_FALL_SPEED, f\"dy reached {bird['dy']}\""),
           ("A longer frame falls further",
            "slow = {'y': 0, 'dy': 0}\nfast = {'y': 0, 'dy': 0}\napply_gravity(slow, 0.05)\napply_gravity(fast, 0.1)\nassert fast['y'] > slow['y']")]),
  demo=dict(kind="fall", caption="The bird falls faster and faster, then starts again from the top."),
  warning="Speed first, then position. Move the bird before changing dy and the fall is subtly wrong — and much harder to debug than to get right."),

step("flap", "flap", "flap",
  "Flap!", "The bird can fly.",
  "<p>The player has exactly one control in this whole game.</p>"
  "<p>The important word here is <strong>set</strong>, not add. <code>dy = FLAP_SPEED</code> means every flap feels identical whether the bird was climbing or plummeting. If you added to dy instead, a bird that had been falling for a while would barely respond — and the game would feel broken without anyone being able to say why.</p>",
  "bird",
  "nothing; it changes bird.dy",
  ["Set the bird's dy to FLAP_SPEED. One line."],
  js=dict(starter="function flap(bird) {\n    // straight up, every time\n}\n",
    answer="function flap(bird) {\n    bird.dy = FLAP_SPEED;\n}\n",
    hints=["FLAP_SPEED is already a negative number — on a canvas, up is negative.",
           "One line, one equals sign.", "bird.dy = FLAP_SPEED;"],
    tests=[("A flap sends the bird upwards",
            "const bird = { y: 100, dy: 0 };\nflap(bird);\nassert(bird.dy < 0, 'dy is ' + bird.dy + ' — up is NEGATIVE on a canvas');"),
           ("A flap sets the speed exactly",
            "const bird = { y: 100, dy: 0 };\nflap(bird);\nassert(bird.dy === FLAP_SPEED, 'dy is ' + bird.dy);"),
           ("It works just as well on a plummeting bird",
            "const bird = { y: 100, dy: 400 };\nflap(bird);\nassert(bird.dy === FLAP_SPEED, 'dy is ' + bird.dy + ' — did you ADD to dy instead of setting it?');"),
           ("Two flaps in a row are not twice as strong",
            "const bird = { y: 100, dy: 0 };\nflap(bird);\nflap(bird);\nassert(bird.dy === FLAP_SPEED, 'every flap is the same size');"),
           ("It does not teleport the bird",
            "const bird = { y: 100, dy: 0 };\nflap(bird);\nassert(bird.y === 100, 'a flap changes the SPEED — gravity does the moving');")]),
  py=dict(starter="def flap(bird):\n    # straight up, every time\n    pass\n",
    answer="def flap(bird):\n    bird[\"dy\"] = FLAP_SPEED\n",
    hints=["FLAP_SPEED is already negative - on a canvas, up is negative.",
           "One line, one equals sign.", "bird[\"dy\"] = FLAP_SPEED"],
    tests=[("A flap sends the bird upwards",
            "bird = {'y': 100, 'dy': 0}\nflap(bird)\nassert bird['dy'] < 0, 'up is NEGATIVE on a canvas'"),
           ("A flap sets the speed exactly",
            "bird = {'y': 100, 'dy': 0}\nflap(bird)\nassert bird['dy'] == FLAP_SPEED"),
           ("It works just as well on a plummeting bird",
            "bird = {'y': 100, 'dy': 400}\nflap(bird)\nassert bird['dy'] == FLAP_SPEED, 'did you ADD to dy instead of setting it?'"),
           ("Two flaps in a row are not twice as strong",
            "bird = {'y': 100, 'dy': 0}\nflap(bird)\nflap(bird)\nassert bird['dy'] == FLAP_SPEED"),
           ("It does not teleport the bird",
            "bird = {'y': 100, 'dy': 0}\nflap(bird)\nassert bird['y'] == 100, 'a flap changes the SPEED - gravity does the moving'")]),
  demo=dict(kind="fly", caption="Press FLAP! and keep the bird in the air as long as you can.")),

step("pipe_rects", "pipeRects", "pipe_rects",
  "Build a pipe", "Pipes appear in the sky.",
  "<p>A pipe is stored as just two numbers: its <code>x</code>, and <code>gapY</code> — the top of the hole you fly through.</p>"
  "<p>Everything else is worked out from those. The top half runs from the ceiling down to the gap. The bottom half starts where the gap ends and runs to the ground.</p>",
  "pipe — x and gapY",
  "an object with a top rectangle and a bottom rectangle",
  ["The top piece starts at y 0 and its height is gapY.",
   "The bottom piece starts at gapY + GAP_HEIGHT.",
   "Its height reaches down to GROUND_Y.",
   "Both are PIPE_WIDTH wide and both start at the pipe's x."],
  js=dict(starter="function pipeRects(pipe) {\n    return {\n        top: { x: pipe.x, y: 0, width: PIPE_WIDTH, height: 0 },\n        bottom: { x: pipe.x, y: 0, width: PIPE_WIDTH, height: 0 }\n    };\n}\n",
    answer="function pipeRects(pipe) {\n    return {\n        top: { x: pipe.x, y: 0, width: PIPE_WIDTH, height: pipe.gapY },\n        bottom: {\n            x: pipe.x,\n            y: pipe.gapY + GAP_HEIGHT,\n            width: PIPE_WIDTH,\n            height: GROUND_Y - (pipe.gapY + GAP_HEIGHT)\n        }\n    };\n}\n",
    hints=["The top piece's height IS gapY — it fills everything above the gap.",
           "The bottom piece begins at gapY + GAP_HEIGHT.",
           "Its height is GROUND_Y minus where it begins."],
    tests=[("The top piece starts at the ceiling",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(r.top.y === 0, 'the top piece hangs from the ceiling');"),
           ("The top piece reaches the gap",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(r.top.height === 150, 'height is ' + r.top.height);"),
           ("The bottom piece starts below the gap",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(r.bottom.y === 150 + GAP_HEIGHT, 'y is ' + r.bottom.y);"),
           ("The bottom piece reaches the ground",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(Math.abs(r.bottom.y + r.bottom.height - GROUND_Y) < 0.001, 'it should stop exactly at the ground');"),
           ("Both halves are at the pipe's x",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(r.top.x === 100 && r.bottom.x === 100);"),
           ("Both halves are PIPE_WIDTH wide",
            "const r = pipeRects({ x: 100, gapY: 150 });\nassert(r.top.width === PIPE_WIDTH && r.bottom.width === PIPE_WIDTH);"),
           ("The gap really is GAP_HEIGHT tall",
            "const r = pipeRects({ x: 100, gapY: 90 });\nassert(r.bottom.y - (r.top.y + r.top.height) === GAP_HEIGHT, 'the hole must be exactly GAP_HEIGHT — otherwise the game is unplayable');")]),
  py=dict(starter="def pipe_rects(pipe):\n    return {\n        \"top\": {\"x\": pipe[\"x\"], \"y\": 0, \"width\": PIPE_WIDTH, \"height\": 0},\n        \"bottom\": {\"x\": pipe[\"x\"], \"y\": 0, \"width\": PIPE_WIDTH, \"height\": 0},\n    }\n",
    answer="def pipe_rects(pipe):\n    return {\n        \"top\": {\"x\": pipe[\"x\"], \"y\": 0, \"width\": PIPE_WIDTH, \"height\": pipe[\"gap_y\"]},\n        \"bottom\": {\n            \"x\": pipe[\"x\"],\n            \"y\": pipe[\"gap_y\"] + GAP_HEIGHT,\n            \"width\": PIPE_WIDTH,\n            \"height\": GROUND_Y - (pipe[\"gap_y\"] + GAP_HEIGHT),\n        },\n    }\n",
    hints=["The top piece's height IS gap_y - it fills everything above the gap.",
           "The bottom piece begins at gap_y + GAP_HEIGHT.",
           "Its height is GROUND_Y minus where it begins."],
    tests=[("The top piece starts at the ceiling",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert r['top']['y'] == 0"),
           ("The top piece reaches the gap",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert r['top']['height'] == 150"),
           ("The bottom piece starts below the gap",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert r['bottom']['y'] == 150 + GAP_HEIGHT"),
           ("The bottom piece reaches the ground",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert abs(r['bottom']['y'] + r['bottom']['height'] - GROUND_Y) < 0.001"),
           ("Both halves are at the pipe's x",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert r['top']['x'] == 100 and r['bottom']['x'] == 100"),
           ("Both halves are PIPE_WIDTH wide",
            "r = pipe_rects({'x': 100, 'gap_y': 150})\nassert r['top']['width'] == PIPE_WIDTH and r['bottom']['width'] == PIPE_WIDTH"),
           ("The gap really is GAP_HEIGHT tall",
            "r = pipe_rects({'x': 100, 'gap_y': 90})\nassert r['bottom']['y'] - (r['top']['y'] + r['top']['height']) == GAP_HEIGHT")]),
  demo=dict(kind="pipe", caption="Slide the gap up and down and watch both halves resize themselves.")),

step("overlaps", "overlaps", "overlaps",
  "Do two boxes touch?", "The game can tell when you have crashed.",
  "<p>This one function is the crash test for the whole game, and it is used in almost every game ever written.</p>"
  "<p>Rather than working out when two boxes DO touch, it is far easier to list the four ways they can MISS: one is entirely left of the other, entirely right, entirely above, or entirely below. If none of those escapes is true, they must be touching.</p>",
  "a, b — two rectangles with x, y, width, height",
  "True if they overlap",
  ["a is left of b if a.x + a.width is not past b.x.",
   "a is right of b if a.x is not before b.x + b.width.",
   "The same two tests again with y and height.",
   "They touch when none of those four is true."],
  js=dict(starter="function overlaps(a, b) {\n    // they touch unless one is completely past the other\n}\n",
    answer="function overlaps(a, b) {\n    return a.x < b.x + b.width &&\n           a.x + a.width > b.x &&\n           a.y < b.y + b.height &&\n           a.y + a.height > b.y;\n}\n",
    hints=["Four comparisons joined with &&.",
           "a.x < b.x + b.width means 'a starts before b ends'.",
           "Do the same pair of tests for y that you did for x."],
    tests=[("Two boxes on top of each other overlap",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 5, y: 5, width: 10, height: 10 }) === true);"),
           ("Boxes far apart do not",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 100, y: 100, width: 10, height: 10 }) === false);"),
           ("Side by side but not touching",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 20, y: 0, width: 10, height: 10 }) === false);"),
           ("One above the other does not count",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 0, y: 40, width: 10, height: 10 }) === false, 'they line up across, but not down');"),
           ("Lined up across but apart down is still a miss",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 5, y: 40, width: 10, height: 10 }) === false, 'you must check BOTH directions');"),
           ("Just touching edges does not count",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 10, y: 0, width: 10, height: 10 }) === false, 'edge to edge is a squeak past, not a crash');"),
           ("A tiny overlap does count",
            "assert(overlaps({ x: 0, y: 0, width: 10, height: 10 }, { x: 9, y: 0, width: 10, height: 10 }) === true);"),
           ("The real bird and a real pipe agree",
            "const bird = { y: 10, dy: 0 };\nassert(hitsPipe(bird, { x: BIRD_X, gapY: 200 }) === true, 'the bird is high up and the pipe is tall');\nassert(hitsPipe({ y: 220, dy: 0 }, { x: BIRD_X, gapY: 200 }) === false, 'this bird is in the gap');")]),
  py=dict(starter="def overlaps(a, b):\n    # they touch unless one is completely past the other\n    pass\n",
    answer="def overlaps(a, b):\n    return (a[\"x\"] < b[\"x\"] + b[\"width\"]\n            and a[\"x\"] + a[\"width\"] > b[\"x\"]\n            and a[\"y\"] < b[\"y\"] + b[\"height\"]\n            and a[\"y\"] + a[\"height\"] > b[\"y\"])\n",
    hints=["Four comparisons joined with `and`.",
           "a['x'] < b['x'] + b['width'] means 'a starts before b ends'.",
           "Do the same pair of tests for y that you did for x."],
    tests=[("Two boxes on top of each other overlap",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 5, 'y': 5, 'width': 10, 'height': 10}) is True"),
           ("Boxes far apart do not",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 100, 'y': 100, 'width': 10, 'height': 10}) is False"),
           ("Side by side but not touching",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 20, 'y': 0, 'width': 10, 'height': 10}) is False"),
           ("One above the other does not count",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 0, 'y': 40, 'width': 10, 'height': 10}) is False"),
           ("Lined up across but apart down is still a miss",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 5, 'y': 40, 'width': 10, 'height': 10}) is False, 'check BOTH directions'"),
           ("Just touching edges does not count",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 10, 'y': 0, 'width': 10, 'height': 10}) is False"),
           ("A tiny overlap does count",
            "assert overlaps({'x': 0, 'y': 0, 'width': 10, 'height': 10}, {'x': 9, 'y': 0, 'width': 10, 'height': 10}) is True"),
           ("The real bird and a real pipe agree",
            "assert hits_pipe({'y': 10, 'dy': 0}, {'x': BIRD_X, 'gap_y': 200}) is True\nassert hits_pipe({'y': 220, 'dy': 0}, {'x': BIRD_X, 'gap_y': 200}) is False")]),
  demo=dict(kind="overlap", caption="Move the bird and the pipe around each other and watch the answer flip."),
  warning="Both directions matter. A test that only looks at x would say a bird at the top of the sky has crashed into a pipe way below it."),

step("move_pipes", "movePipes", "move_pipes",
  "Slide the pipes past", "The world starts moving.",
  "<p>The bird never actually goes anywhere — it only goes up and down. It is the <em>pipes</em> that move, and that is what makes it feel like flying.</p>"
  "<p>This function does two jobs at once: move everything left, and throw away anything that has gone off the left-hand edge. Forget the second job and the list grows for ever until the game slows to a crawl.</p>",
  "pipes — the list. distance — how far to move them.",
  "a NEW list, moved, without the pipes that have gone",
  ["Make an empty list for the answer.",
   "For each pipe, make a copy whose x is distance smaller. Keep gapY and passed.",
   "Only add it to the answer if its right-hand edge (x + PIPE_WIDTH) is still above 0.",
   "Return the new list."],
  js=dict(starter="function movePipes(pipes, distance) {\n    // move them all left, drop the ones that have gone\n}\n",
    answer="function movePipes(pipes, distance) {\n    const moved = [];\n    for (let i = 0; i < pipes.length; i++) {\n        const pipe = pipes[i];\n        const shifted = { x: pipe.x - distance, gapY: pipe.gapY, passed: pipe.passed };\n        if (shifted.x + PIPE_WIDTH > 0) {\n            moved.push(shifted);\n        }\n    }\n    return moved;\n}\n",
    hints=["Moving left means SUBTRACTING from x.",
           "Copy gapY and passed too, or the pipe forgets where its hole is.",
           "A pipe is gone when x + PIPE_WIDTH is no longer above 0."],
    tests=[("Pipes move to the left",
            "const moved = movePipes([{ x: 200, gapY: 100, passed: false }], 50);\nassert(moved[0].x === 150, 'x is ' + moved[0].x);"),
           ("The gap goes with the pipe",
            "const moved = movePipes([{ x: 200, gapY: 137, passed: false }], 50);\nassert(moved[0].gapY === 137, 'the hole has to move with the pipe');"),
           ("Pipes that have scrolled away are dropped",
            "const moved = movePipes([{ x: 10, gapY: 100, passed: true }], 100);\nassert(moved.length === 0, 'that pipe is off the left of the screen');"),
           ("A pipe still half on screen is kept",
            "const moved = movePipes([{ x: 10, gapY: 100, passed: true }], 30);\nassert(moved.length === 1, 'part of it is still visible');"),
           ("Several pipes all move",
            "const moved = movePipes([{ x: 100, gapY: 1, passed: false }, { x: 300, gapY: 2, passed: false }], 40);\nassert(moved.length === 2);\nassert(moved[0].x === 60 && moved[1].x === 260);"),
           ("The 'passed' flag is not forgotten",
            "const moved = movePipes([{ x: 200, gapY: 100, passed: true }], 10);\nassert(moved[0].passed === true, 'lose this and the pipe scores over and over');"),
           ("The list you were given is left alone",
            "const before = [{ x: 200, gapY: 100, passed: false }];\nmovePipes(before, 50);\nassert(before[0].x === 200, 'make copies — do not edit the list you were handed');")]),
  py=dict(starter="def move_pipes(pipes, distance):\n    # move them all left, drop the ones that have gone\n    pass\n",
    answer="def move_pipes(pipes, distance):\n    moved = []\n    for pipe in pipes:\n        shifted = {\"x\": pipe[\"x\"] - distance, \"gap_y\": pipe[\"gap_y\"], \"passed\": pipe[\"passed\"]}\n        if shifted[\"x\"] + PIPE_WIDTH > 0:\n            moved.append(shifted)\n    return moved\n",
    hints=["Moving left means SUBTRACTING from x.",
           "Copy gap_y and passed too, or the pipe forgets where its hole is.",
           "A pipe is gone when x + PIPE_WIDTH is no longer above 0."],
    tests=[("Pipes move to the left",
            "moved = move_pipes([{'x': 200, 'gap_y': 100, 'passed': False}], 50)\nassert moved[0]['x'] == 150"),
           ("The gap goes with the pipe",
            "moved = move_pipes([{'x': 200, 'gap_y': 137, 'passed': False}], 50)\nassert moved[0]['gap_y'] == 137"),
           ("Pipes that have scrolled away are dropped",
            "moved = move_pipes([{'x': 10, 'gap_y': 100, 'passed': True}], 100)\nassert moved == []"),
           ("A pipe still half on screen is kept",
            "moved = move_pipes([{'x': 10, 'gap_y': 100, 'passed': True}], 30)\nassert len(moved) == 1"),
           ("Several pipes all move",
            "moved = move_pipes([{'x': 100, 'gap_y': 1, 'passed': False}, {'x': 300, 'gap_y': 2, 'passed': False}], 40)\nassert len(moved) == 2 and moved[0]['x'] == 60 and moved[1]['x'] == 260"),
           ("The 'passed' flag is not forgotten",
            "moved = move_pipes([{'x': 200, 'gap_y': 100, 'passed': True}], 10)\nassert moved[0]['passed'] is True, 'lose this and the pipe scores over and over'"),
           ("The list you were given is left alone",
            "before = [{'x': 200, 'gap_y': 100, 'passed': False}]\nmove_pipes(before, 50)\nassert before[0]['x'] == 200, 'make copies'")]),
  demo=dict(kind="scroll", caption="Pipes stream past for ever, but the list never grows past a few."),
  warning="Throw away the pipes that have scrolled off. A list that only ever grows is the classic way to make a game get slower the longer it is played."),

step("is_crashed", "isCrashed", "is_crashed",
  "Have we crashed?", "The game can end.",
  "<p>Three ways to lose: hit the ground, hit the ceiling, or hit a pipe.</p>"
  "<p>Notice that this function only <em>answers a question</em> — it does not end the game itself. Keeping the question and the consequence apart is what lets the same function be used by the game, by the demo beside you, and by the tests.</p>",
  "state",
  "True if the bird has hit anything",
  ["The ground: the bird's y plus BIRD_SIZE has reached GROUND_Y.",
   "The ceiling: the bird's y is above 0.",
   "The pipes: hits-pipe says yes for any pipe in the list.",
   "Otherwise, False."],
  js=dict(starter="function isCrashed(state) {\n    // ground, ceiling, pipes\n}\n",
    answer="function isCrashed(state) {\n    if (state.bird.y + BIRD_SIZE >= GROUND_Y) {\n        return true;\n    }\n    if (state.bird.y < 0) {\n        return true;\n    }\n    for (let i = 0; i < state.pipes.length; i++) {\n        if (hitsPipe(state.bird, state.pipes[i])) {\n            return true;\n        }\n    }\n    return false;\n}\n",
    hints=["The bird's y is its TOP, so the ground test needs + BIRD_SIZE.",
           "hitsPipe is already written for you — just call it in a loop.",
           "return false; at the very end, once nothing has hit."],
    tests=[("A bird in clear sky is fine",
            "assert(isCrashed({ bird: { y: 200, dy: 0 }, pipes: [] }) === false);"),
           ("Hitting the ground is a crash",
            "assert(isCrashed({ bird: { y: GROUND_Y - BIRD_SIZE + 1, dy: 0 }, pipes: [] }) === true, 'the bird has touched the floor');"),
           ("Flying off the top is a crash",
            "assert(isCrashed({ bird: { y: -2, dy: 0 }, pipes: [] }) === true);"),
           ("Just above the ground is not",
            "assert(isCrashed({ bird: { y: GROUND_Y - BIRD_SIZE - 5, dy: 0 }, pipes: [] }) === false);"),
           ("Flying into a pipe is a crash",
            "assert(isCrashed({ bird: { y: 10, dy: 0 }, pipes: [{ x: BIRD_X, gapY: 200, passed: false }] }) === true);"),
           ("Flying through the gap is safe",
            "assert(isCrashed({ bird: { y: 220, dy: 0 }, pipes: [{ x: BIRD_X, gapY: 200, passed: false }] }) === false, 'the bird is right in the middle of the hole');"),
           ("Every pipe is checked, not just the first",
            "const state = { bird: { y: 10, dy: 0 }, pipes: [{ x: 250, gapY: 200, passed: false }, { x: BIRD_X, gapY: 200, passed: false }] };\nassert(isCrashed(state) === true, 'the second pipe is the one it hit');")]),
  py=dict(starter="def is_crashed(state):\n    # ground, ceiling, pipes\n    pass\n",
    answer="def is_crashed(state):\n    if state[\"bird\"][\"y\"] + BIRD_SIZE >= GROUND_Y:\n        return True\n    if state[\"bird\"][\"y\"] < 0:\n        return True\n    return any(hits_pipe(state[\"bird\"], pipe) for pipe in state[\"pipes\"])\n",
    hints=["The bird's y is its TOP, so the ground test needs + BIRD_SIZE.",
           "hits_pipe is already written for you.",
           "any(...) is True when at least one pipe was hit."],
    tests=[("A bird in clear sky is fine",
            "assert is_crashed({'bird': {'y': 200, 'dy': 0}, 'pipes': []}) is False"),
           ("Hitting the ground is a crash",
            "assert is_crashed({'bird': {'y': GROUND_Y - BIRD_SIZE + 1, 'dy': 0}, 'pipes': []}) is True"),
           ("Flying off the top is a crash",
            "assert is_crashed({'bird': {'y': -2, 'dy': 0}, 'pipes': []}) is True"),
           ("Just above the ground is not",
            "assert is_crashed({'bird': {'y': GROUND_Y - BIRD_SIZE - 5, 'dy': 0}, 'pipes': []}) is False"),
           ("Flying into a pipe is a crash",
            "assert is_crashed({'bird': {'y': 10, 'dy': 0}, 'pipes': [{'x': BIRD_X, 'gap_y': 200, 'passed': False}]}) is True"),
           ("Flying through the gap is safe",
            "assert is_crashed({'bird': {'y': 220, 'dy': 0}, 'pipes': [{'x': BIRD_X, 'gap_y': 200, 'passed': False}]}) is False"),
           ("Every pipe is checked, not just the first",
            "state = {'bird': {'y': 10, 'dy': 0}, 'pipes': [{'x': 250, 'gap_y': 200, 'passed': False}, {'x': BIRD_X, 'gap_y': 200, 'passed': False}]}\nassert is_crashed(state) is True")]),
  demo=dict(kind="mini", flags=dict(robot=True), caption="A robot pilot flies the practice sky — it starts again whenever it crashes.")),

step("score_passed_pipes", "scorePassedPipes", "score_passed_pipes",
  "Count the pipes", "The whole game works!",
  "<p>The score goes up by one for every pipe the bird gets past. The problem is that the game asks this question sixty times a second, and the pipe stays behind the bird for a long time.</p>"
  "<p>The answer is the <code>passed</code> flag: score the pipe once, then mark it, and never score it again. That little flag is the difference between a score of 1 and a score of 200.</p>",
  "state",
  "nothing; it changes the score",
  ["Look at every pipe.",
   "Skip any that are already marked passed.",
   "A pipe is behind the bird when its x plus PIPE_WIDTH is less than BIRD_X.",
   "When it is: mark it passed and add 1 to the score."],
  js=dict(starter="function scorePassedPipes(state) {\n    // one point per pipe — but only once each!\n}\n",
    answer="function scorePassedPipes(state) {\n    for (let i = 0; i < state.pipes.length; i++) {\n        const pipe = state.pipes[i];\n        if (!pipe.passed && pipe.x + PIPE_WIDTH < BIRD_X) {\n            pipe.passed = true;\n            state.score = state.score + 1;\n        }\n    }\n}\n",
    hints=["Two things have to be true: not already passed, AND behind the bird.",
           "Set pipe.passed = true BEFORE or after the score — but do set it.",
           "The right-hand edge of the pipe is pipe.x + PIPE_WIDTH."],
    tests=[("Getting past a pipe scores a point",
            "const state = { score: 0, bird: { y: 200, dy: 0 }, pipes: [{ x: 10, gapY: 100, passed: false }] };\nscorePassedPipes(state);\nassert(state.score === 1, 'score is ' + state.score);"),
           ("A pipe still ahead scores nothing",
            "const state = { score: 0, bird: { y: 200, dy: 0 }, pipes: [{ x: 200, gapY: 100, passed: false }] };\nscorePassedPipes(state);\nassert(state.score === 0);"),
           ("The pipe is marked as counted",
            "const state = { score: 0, bird: { y: 200, dy: 0 }, pipes: [{ x: 10, gapY: 100, passed: false }] };\nscorePassedPipes(state);\nassert(state.pipes[0].passed === true);"),
           ("The same pipe never scores twice",
            "const state = { score: 0, bird: { y: 200, dy: 0 }, pipes: [{ x: 10, gapY: 100, passed: false }] };\nfor (let i = 0; i < 60; i++) { scorePassedPipes(state); }\nassert(state.score === 1, 'score is ' + state.score + ' — one pipe is worth ONE point, however many frames go by');"),
           ("Two pipes are worth two points",
            "const state = { score: 0, bird: { y: 200, dy: 0 }, pipes: [{ x: 5, gapY: 100, passed: false }, { x: 12, gapY: 100, passed: false }] };\nscorePassedPipes(state);\nassert(state.score === 2);"),
           ("A pipe already marked is left alone",
            "const state = { score: 7, bird: { y: 200, dy: 0 }, pipes: [{ x: 10, gapY: 100, passed: true }] };\nscorePassedPipes(state);\nassert(state.score === 7);")]),
  py=dict(starter="def score_passed_pipes(state):\n    # one point per pipe - but only once each!\n    pass\n",
    answer="def score_passed_pipes(state):\n    for pipe in state[\"pipes\"]:\n        if not pipe[\"passed\"] and pipe[\"x\"] + PIPE_WIDTH < BIRD_X:\n            pipe[\"passed\"] = True\n            state[\"score\"] += 1\n",
    hints=["Two things have to be true: not already passed, AND behind the bird.",
           "Set pipe['passed'] = True, or it will score every frame.",
           "The right-hand edge of the pipe is pipe['x'] + PIPE_WIDTH."],
    tests=[("Getting past a pipe scores a point",
            "state = {'score': 0, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 10, 'gap_y': 100, 'passed': False}]}\nscore_passed_pipes(state)\nassert state['score'] == 1"),
           ("A pipe still ahead scores nothing",
            "state = {'score': 0, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 200, 'gap_y': 100, 'passed': False}]}\nscore_passed_pipes(state)\nassert state['score'] == 0"),
           ("The pipe is marked as counted",
            "state = {'score': 0, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 10, 'gap_y': 100, 'passed': False}]}\nscore_passed_pipes(state)\nassert state['pipes'][0]['passed'] is True"),
           ("The same pipe never scores twice",
            "state = {'score': 0, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 10, 'gap_y': 100, 'passed': False}]}\nfor _ in range(60):\n    score_passed_pipes(state)\nassert state['score'] == 1, f\"score is {state['score']}\""),
           ("Two pipes are worth two points",
            "state = {'score': 0, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 5, 'gap_y': 100, 'passed': False}, {'x': 12, 'gap_y': 100, 'passed': False}]}\nscore_passed_pipes(state)\nassert state['score'] == 2"),
           ("A pipe already marked is left alone",
            "state = {'score': 7, 'bird': {'y': 200, 'dy': 0}, 'pipes': [{'x': 10, 'gap_y': 100, 'passed': True}]}\nscore_passed_pipes(state)\nassert state['score'] == 7")]),
  demo=dict(kind="game", flags=dict(robot=True), caption="The robot flies the real game and the score climbs — every function you wrote is running here."),
  warning="Without the `passed` flag the score jumps by sixty a second. With it, one pipe is one point."),

step("action_for_key", "actionForKey", "action_for_key",
  "Take the controls", "You can play it yourself.",
  "<p>One function left, and it is the shortest in the game — because there is only one thing a player can do.</p>",
  "key — the name of the key that was pressed",
  "an action name, or nothing at all",
  ["Space, the up arrow or W → 'flap'.", "P → 'pause'.", "R → 'restart'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // space, up, w, p, r\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === ' ' || k === 'spacebar' || k === 'arrowup' || k === 'w') { return 'flap'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["The space bar's key is a single space: ' '.",
           "The up arrow is called 'ArrowUp' — toLowerCase() makes it 'arrowup'.",
           "Three ifs and a return null;"],
    tests=[("Space flaps", "assert(actionForKey(' ') === 'flap');"),
           ("The up arrow flaps", "assert(actionForKey('ArrowUp') === 'flap');"),
           ("W flaps too", "assert(actionForKey('w') === 'flap');"),
           ("Capital letters work",
            "assert(actionForKey('W') === 'flap');\nassert(actionForKey('R') === 'restart');"),
           ("P pauses and R restarts",
            "assert(actionForKey('p') === 'pause');\nassert(actionForKey('r') === 'restart');"),
           ("Other keys do nothing",
            "assert(actionForKey('z') === null, 'gave ' + actionForKey('z'));\nassert(actionForKey('ArrowDown') === null, 'there is no way to make the bird dive');")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \" \": \"flap\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \" \": \"flap\", \"spacebar\": \"flap\", \"arrowup\": \"flap\", \"w\": \"flap\",\n        \"p\": \"pause\", \"r\": \"restart\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["A dictionary is the neatest way.",
           "keys.get(...) gives None for anything not listed.",
           "Do not forget \" \" for the space bar."],
    tests=[("Space flaps", "assert action_for_key(' ') == 'flap'"),
           ("The up arrow flaps", "assert action_for_key('ArrowUp') == 'flap'"),
           ("W flaps too", "assert action_for_key('w') == 'flap'"),
           ("Capital letters work",
            "assert action_for_key('W') == 'flap'\nassert action_for_key('R') == 'restart'"),
           ("P pauses and R restarts",
            "assert action_for_key('p') == 'pause'\nassert action_for_key('r') == 'restart'"),
           ("Other keys do nothing",
            "assert action_for_key('z') is None\nassert action_for_key('ArrowDown') is None")]),
  demo=dict(kind="final", caption="Click the page, then press SPACE. How many pipes can you get through?")),
]

write_workshop("flappy", "Flappy", STEPS)
