"""The six steps of "Build Hundred Floors", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("screen_y", "screenY", "screen_y",
  "Where does the camera look?", "The shaft can be drawn.",
  "<p>Here is the idea the whole game rests on, and it is worth getting straight before anything else: <strong>the shaft does not move. The camera does.</strong></p>"
  "<p>Every platform is given a place in the world when it is made, and it stays there for ever. What changes is how far down we are looking. To draw something you take the camera's depth off its world position.</p>"
  "<p>You could have written this game the other way round, sliding every platform upwards. It seems simpler — right up until you notice that a player standing on a platform has to be dragged along with it, so speeding up the view would physically fling the player into the ceiling. Moving the camera touches nobody.</p>",
  "state, worldY — where something is in the world",
  "the y to draw it at",
  ["Take the camera's depth off the world position. That is the whole function."],
  js=dict(starter="function screenY(state, worldY) {\n    // the world position, minus how far down we are looking\n}\n",
    answer="function screenY(state, worldY) {\n    return worldY - state.camera;\n}\n",
    hints=["The camera is state.camera — how far down the shaft we are looking.",
           "Something at the same depth as the camera appears at the very top.",
           "return worldY - state.camera;"],
    tests=[("At the start the camera is at the top",
            "const state = createGame();\nassert(state.camera === 0);\nassert(screenY(state, 100) === 100, 'with the camera at 0, world and screen are the same');"),
           ("Looking further down moves things up the screen",
            "const state = createGame();\nstate.camera = 50;\nassert(screenY(state, 100) === 50, 'gave ' + screenY(state, 100));"),
           ("Something at the camera's own depth is at the very top",
            "const state = createGame();\nstate.camera = 137;\nassert(screenY(state, 137) === 0);"),
           ("Something above the camera has a negative screen y",
            "const state = createGame();\nstate.camera = 200;\nassert(screenY(state, 150) < 0, 'that is off the top of the screen');"),
           ("The gap between two things never changes",
            "const state = createGame();\nstate.camera = 0;\nconst apart = screenY(state, 300) - screenY(state, 200);\nstate.camera = 500;\nassert(screenY(state, 300) - screenY(state, 200) === apart, 'moving the camera must not stretch the world');"),
           ("The player starts in view",
            "const state = createGame();\nconst y = screenY(state, state.player.y);\nassert(y > 0 && y < FIELD_HEIGHT, 'the player should be on screen, but is at ' + y);")]),
  py=dict(starter="def screen_y(state, world_y):\n    # the world position, minus how far down we are looking\n    pass\n",
    answer="def screen_y(state, world_y):\n    return world_y - state[\"camera\"]\n",
    hints=["The camera is state['camera'] - how far down the shaft we are looking.",
           "Something at the same depth as the camera appears at the very top.",
           "return world_y - state['camera']"],
    tests=[("At the start the camera is at the top",
            "state = create_game()\nassert state['camera'] == 0\nassert screen_y(state, 100) == 100"),
           ("Looking further down moves things up the screen",
            "state = create_game()\nstate['camera'] = 50\nassert screen_y(state, 100) == 50"),
           ("Something at the camera's own depth is at the very top",
            "state = create_game()\nstate['camera'] = 137\nassert screen_y(state, 137) == 0"),
           ("Something above the camera has a negative screen y",
            "state = create_game()\nstate['camera'] = 200\nassert screen_y(state, 150) < 0"),
           ("The gap between two things never changes",
            "state = create_game()\nstate['camera'] = 0\napart = screen_y(state, 300) - screen_y(state, 200)\nstate['camera'] = 500\nassert screen_y(state, 300) - screen_y(state, 200) == apart"),
           ("The player starts in view",
            "state = create_game()\ny = screen_y(state, state['player']['y'])\nassert 0 < y < FIELD_HEIGHT")]),
  demo=dict(kind="kinds", caption="One of every kind of platform, all drawn through screenY.")),

step("random_kind", "randomKind", "random_kind",
  "Deal a platform", "The shaft fills with six different kinds.",
  "<p>Six kinds of platform, but they are not equally likely — plain ones are common and 锯齿 spikes are rarer, and the deeper you go the nastier the mixture gets.</p>"
  "<p>The way to do that is <strong>weighted random choice</strong>, and it is genuinely useful. Picture a row of buckets of different widths and a dart thrown at random: a wide bucket catches more darts.</p>"
  "<ol><li>Add up all the weights — that is how wide the whole row of buckets is.</li>"
  "<li>Pick a random number somewhere in that total — that is where the dart lands.</li>"
  "<li>Walk along, taking each weight off your number. The moment it goes below zero, you are standing in that bucket.</li></ol>",
  "floor — how deep we are",
  "one of the six kinds",
  ["Ask kind-weights for the list of kinds and their weights.",
   "Add all the weights together.",
   "Pick a random number from 0 up to that total.",
   "Walk the list, taking each weight off your number. As soon as it drops below 0, return that kind."],
  js=dict(starter="function randomKind(floor) {\n    const weights = kindWeights(floor);\n    // add them up, throw a dart, walk along\n    return PLAIN;\n}\n",
    answer="function randomKind(floor) {\n    const weights = kindWeights(floor);\n\n    let total = 0;\n    for (let i = 0; i < weights.length; i++) {\n        total = total + weights[i].weight;\n    }\n\n    let ticket = Math.random() * total;\n    for (let i = 0; i < weights.length; i++) {\n        ticket = ticket - weights[i].weight;\n        if (ticket < 0) {\n            return weights[i].kind;\n        }\n    }\n    return PLAIN;\n}\n",
    hints=["kindWeights(floor) gives you a list of { kind, weight }.",
           "Math.random() * total throws the dart somewhere in the whole row.",
           "Take each weight off the ticket, and return as soon as it goes below zero."],
    tests=[("It always gives back a real kind",
            "for (let i = 0; i < 300; i++) {\n    const kind = randomKind(1);\n    assert(kind >= PLAIN && kind <= CRUMBLING, 'gave ' + kind);\n}"),
           ("Every kind turns up sooner or later",
            "const seen = {};\nfor (let i = 0; i < 3000; i++) { seen[randomKind(20)] = true; }\nassert(Object.keys(seen).length === 6, 'only ' + Object.keys(seen).length + ' of the six kinds ever appeared');"),
           ("Plain platforms are the commonest",
            "const counts = {};\nfor (let i = 0; i < 4000; i++) {\n    const kind = randomKind(1);\n    counts[kind] = (counts[kind] || 0) + 1;\n}\nfor (let kind = 1; kind <= CRUMBLING; kind++) {\n    assert(counts[PLAIN] > (counts[kind] || 0), 'plain should be commoner than kind ' + kind);\n}"),
           ("Spikes get likelier the deeper you go",
            "let shallow = 0;\nlet deep = 0;\nfor (let i = 0; i < 4000; i++) {\n    if (randomKind(1) === SPIKED) { shallow = shallow + 1; }\n    if (randomKind(60) === SPIKED) { deep = deep + 1; }\n}\nassert(deep > shallow * 1.5, 'floor 60 had ' + deep + ' spikes and floor 1 had ' + shallow + ' — it should get much nastier');"),
           ("The weights really are respected",
            "const counts = {};\nfor (let i = 0; i < 8000; i++) {\n    const kind = randomKind(1);\n    counts[kind] = (counts[kind] || 0) + 1;\n}\nconst weights = kindWeights(1);\nlet total = 0;\nweights.forEach(function (w) { total = total + w.weight; });\nweights.forEach(function (w) {\n    const expected = w.weight / total * 8000;\n    const got = counts[w.kind] || 0;\n    assert(Math.abs(got - expected) < expected * 0.35 + 40,\n           'kind ' + w.kind + ' came up ' + got + ' times but should be near ' + Math.round(expected));\n});"),
           ("Two shafts in a row are different",
            "let same = 0;\nfor (let i = 0; i < 40; i++) {\n    if (randomKind(30) === randomKind(30)) { same = same + 1; }\n}\nassert(same < 40, 'it should not give the same answer every single time');")]),
  py=dict(starter="def random_kind(floor):\n    weights = kind_weights(floor)\n    # add them up, throw a dart, walk along\n    return PLAIN\n",
    answer="def random_kind(floor):\n    weights = kind_weights(floor)\n\n    total = sum(weight for kind, weight in weights)\n    ticket = random.uniform(0, total)\n\n    for kind, weight in weights:\n        ticket -= weight\n        if ticket < 0:\n            return kind\n    return PLAIN\n",
    hints=["kind_weights(floor) gives you a list of (kind, weight) pairs.",
           "random.uniform(0, total) throws the dart somewhere in the whole row.",
           "Take each weight off the ticket, and return as soon as it goes below zero."],
    tests=[("It always gives back a real kind",
            "for _ in range(300):\n    assert PLAIN <= random_kind(1) <= CRUMBLING"),
           ("Every kind turns up sooner or later",
            "seen = {random_kind(20) for _ in range(3000)}\nassert len(seen) == 6, f'only {len(seen)} of the six kinds appeared'"),
           ("Plain platforms are the commonest",
            "import collections\ncounts = collections.Counter(random_kind(1) for _ in range(4000))\nfor kind in range(1, CRUMBLING + 1):\n    assert counts[PLAIN] > counts[kind]"),
           ("Spikes get likelier the deeper you go",
            "shallow = sum(1 for _ in range(4000) if random_kind(1) == SPIKED)\ndeep = sum(1 for _ in range(4000) if random_kind(60) == SPIKED)\nassert deep > shallow * 1.5, f'floor 60 had {deep} spikes, floor 1 had {shallow}'"),
           ("The weights really are respected",
            "import collections\ncounts = collections.Counter(random_kind(1) for _ in range(8000))\nweights = kind_weights(1)\ntotal = sum(w for k, w in weights)\nfor kind, weight in weights:\n    expected = weight / total * 8000\n    assert abs(counts[kind] - expected) < expected * 0.35 + 40, \\\n        f'kind {kind} came up {counts[kind]} times, expected near {expected:.0f}'"),
           ("Two shafts in a row are different",
            "same = sum(1 for _ in range(40) if random_kind(30) == random_kind(30))\nassert same < 40")]),
  demo=dict(kind="kinds", caption="Step through the six kinds and read what each one is.")),

step("is_over", "isOver", "is_over",
  "Are you standing on it?", "You stop balancing on thin air.",
  "<p>A small function with a surprisingly big effect. Are you over this platform?</p>"
  "<p>The obvious answer is \"do our rectangles overlap?\" — and it is wrong. With that rule you can stand balanced on <em>half a pixel</em> of platform, hanging in mid-air and refusing to fall, while the shaft carries you up into the ceiling spikes. It looks like the game has frozen.</p>"
  "<p>Use the player's <strong>middle</strong> instead. You fall the moment you walk past the edge, which is exactly what a player expects.</p>",
  "player, platform",
  "True if the player's middle is above the platform",
  ["Work out the middle of the player: their x plus half their width.",
   "That has to be past the platform's left edge and before its right edge."],
  js=dict(starter="function isOver(player, platform) {\n    // the player's MIDDLE has to be above the platform\n}\n",
    answer="function isOver(player, platform) {\n    const middle = player.x + PLAYER_WIDTH / 2;\n    return middle > platform.x && middle < platform.x + PLATFORM_WIDTH;\n}\n",
    hints=["The middle of the player is player.x + PLAYER_WIDTH / 2.",
           "The platform runs from platform.x to platform.x + PLATFORM_WIDTH.",
           "Both comparisons, joined with &&."],
    tests=[("Standing in the middle counts",
            "const platform = { x: 100, y: 0 };\nassert(isOver({ x: 121 }, platform) === true);"),
           ("Standing well to the side does not",
            "const platform = { x: 100, y: 0 };\nassert(isOver({ x: 250 }, platform) === false);"),
           ("Just over the left edge counts",
            "const platform = { x: 100, y: 0 };\nassert(isOver({ x: 92 }, platform) === true, 'the middle is at 102, which is on the platform');"),
           ("Balancing on a sliver does NOT count",
            "const platform = { x: 100, y: 0 };\nassert(isOver({ x: 81 }, platform) === false, 'only the last pixel of the player overlaps — the middle is at 91, off the edge, so they must fall');"),
           ("Nor does hanging off the right",
            "const platform = { x: 100, y: 0 };\nassert(isOver({ x: 161 }, platform) === false, 'the middle is at 171, past the right-hand edge at 162');"),
           ("A player can only be over one platform at a time",
            "const left = { x: 100, y: 0 };\nconst right = { x: 162, y: 0 };\nfor (let x = 60; x < 240; x++) {\n    const both = isOver({ x: x }, left) && isOver({ x: x }, right);\n    assert(!both, 'at x ' + x + ' the player is somehow on both platforms at once');\n}"),
           ("It agrees with stillOnPlatform",
            "const platform = { x: 100, y: 0 };\nassert(stillOnPlatform({ x: 121 }, platform) === isOver({ x: 121 }, platform));")]),
  py=dict(starter="def is_over(player, platform):\n    # the player's MIDDLE has to be above the platform\n    pass\n",
    answer="def is_over(player, platform):\n    middle = player[\"x\"] + PLAYER_WIDTH / 2\n    return platform[\"x\"] < middle < platform[\"x\"] + PLATFORM_WIDTH\n",
    hints=["The middle of the player is player['x'] + PLAYER_WIDTH / 2.",
           "Python lets you write a < b < c, which reads beautifully here.",
           "return platform['x'] < middle < platform['x'] + PLATFORM_WIDTH"],
    tests=[("Standing in the middle counts",
            "assert is_over({'x': 121}, {'x': 100, 'y': 0}) is True"),
           ("Standing well to the side does not",
            "assert is_over({'x': 250}, {'x': 100, 'y': 0}) is False"),
           ("Just over the left edge counts",
            "assert is_over({'x': 92}, {'x': 100, 'y': 0}) is True"),
           ("Balancing on a sliver does NOT count",
            "assert is_over({'x': 81}, {'x': 100, 'y': 0}) is False, 'the middle is off the edge, so they must fall'"),
           ("Nor does hanging off the right",
            "assert is_over({'x': 161}, {'x': 100, 'y': 0}) is False"),
           ("A player can only be over one platform at a time",
            "left = {'x': 100, 'y': 0}\nright = {'x': 162, 'y': 0}\nfor x in range(60, 240):\n    assert not (is_over({'x': x}, left) and is_over({'x': x}, right)), f'both at x {x}'"),
           ("It agrees with still_on_platform",
            "p = {'x': 121}\nplatform = {'x': 100, 'y': 0}\nassert still_on_platform(p, platform) == is_over(p, platform)")]),
  demo=dict(kind="land", caption="Walk off the edge and you fall the moment your middle passes it."),
  warning="Use the middle, not the whole body. Any-overlap-counts lets a player balance on half a pixel and hang in the air for ever."),

step("lands_on", "landsOn", "lands_on",
  "Did you land on it?", "You can stand on things.",
  "<p>The most important test in the game: has the player's feet just crossed the top of this platform?</p>"
  "<p>The tempting version is \"are the feet near the top?\" — and it breaks. At full speed the player falls seven pixels in a single frame, and a platform is ten thick. A fast fall skips straight past the \"near\" window and lands on nothing.</p>"
  "<p>So ask a better question: were the feet <strong>above</strong> the platform last frame, and are they <strong>level with or below</strong> it now? That cannot be skipped over, however fast the fall.</p>",
  "player — with y, dy and lastFeet. platform.",
  "True if the player just landed on it",
  ["If the player is not falling (dy is 0 or less), it is not a landing — going up through a platform is allowed.",
   "Work out where the feet are now: y plus PLAYER_HEIGHT.",
   "If the feet were already below the platform's top last frame, we did not land on it.",
   "If the feet have not reached it yet, we have not landed either.",
   "Otherwise it comes down to whether we are over it — use is-over."],
  js=dict(starter="function landsOn(player, platform) {\n    // falling, crossed the top this frame, and over it\n}\n",
    answer="function landsOn(player, platform) {\n    if (player.dy <= 0) {\n        return false;\n    }\n    const rect = platformRect(platform);\n    const feet = player.y + PLAYER_HEIGHT;\n\n    if (player.lastFeet > rect.y || feet < rect.y) {\n        return false;\n    }\n    return isOver(player, platform);\n}\n",
    hints=["player.lastFeet is where the feet were at the start of the frame.",
           "'Crossed it' means lastFeet was above the top AND feet is now at or below it.",
           "Finish with isOver(player, platform) — the function you just wrote."],
    tests=[("Falling onto a platform is a landing",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 121, y: 180, dy: 200, lastFeet: 200 };\nassert(landsOn(player, platform) === true, 'the feet went from 200 to 204, crossing the top at 200');"),
           ("Still above it is not a landing",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 121, y: 100, dy: 200, lastFeet: 120 };\nassert(landsOn(player, platform) === false, 'the feet are nowhere near it yet');"),
           ("Already below it is not a landing",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 121, y: 300, dy: 200, lastFeet: 310 };\nassert(landsOn(player, platform) === false, 'the feet were already past it last frame');"),
           ("Rising up through it is allowed",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 121, y: 180, dy: -200, lastFeet: 210 };\nassert(landsOn(player, platform) === false, 'a spring has thrown the player upwards — they should pass straight through');"),
           ("Falling past it to one side is not a landing",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 250, y: 180, dy: 200, lastFeet: 200 };\nassert(landsOn(player, platform) === false);"),
           ("A very fast fall is still caught",
            "const platform = { x: 100, y: 200 };\n/* the feet jumped from 190 all the way to 230 in one frame */\nconst player = { x: 121, y: 206, dy: MAX_FALL_SPEED, lastFeet: 190 };\nassert(landsOn(player, platform) === true, 'the feet leapt right over the platform in one frame, but they still crossed it');"),
           ("Landing exactly on the edge of the top counts",
            "const platform = { x: 100, y: 200 };\nconst player = { x: 121, y: 176, dy: 100, lastFeet: 199 };\nassert(landsOn(player, platform) === true);"),
           ("A real game lands on things",
            "const state = createGame();\n/* drop the player from a standstill, squarely above a real platform */\nconst platform = state.platforms[1];\nstate.player.riding = null;\nstate.player.x = platform.x + PLATFORM_WIDTH / 2 - PLAYER_WIDTH / 2;\nstate.player.y = platform.y - 90;\nstate.player.dy = 0;\nstate.player.lastFeet = state.player.y + PLAYER_HEIGHT;\nstate.steering = 0;\nlet landed = false;\nfor (let frame = 0; frame < 90 && !landed; frame++) {\n    updateGame(state, 16);\n    if (state.player.riding) { landed = true; }\n}\nassert(landed, 'the player was dropped straight onto a platform and never landed on it');")]),
  py=dict(starter="def lands_on(player, platform):\n    # falling, crossed the top this frame, and over it\n    pass\n",
    answer="def lands_on(player, platform):\n    if player[\"dy\"] <= 0:\n        return False\n    rect = platform_rect(platform)\n    feet = player[\"y\"] + PLAYER_HEIGHT\n\n    if player[\"last_feet\"] > rect[\"y\"] or feet < rect[\"y\"]:\n        return False\n    return is_over(player, platform)\n",
    hints=["player['last_feet'] is where the feet were at the start of the frame.",
           "'Crossed it' means last_feet was above the top AND feet is now at or below it.",
           "Finish with is_over(player, platform) - the function you just wrote."],
    tests=[("Falling onto a platform is a landing",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 180, 'dy': 200, 'last_feet': 200}\nassert lands_on(player, platform) is True"),
           ("Still above it is not a landing",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 100, 'dy': 200, 'last_feet': 120}\nassert lands_on(player, platform) is False"),
           ("Already below it is not a landing",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 300, 'dy': 200, 'last_feet': 310}\nassert lands_on(player, platform) is False"),
           ("Rising up through it is allowed",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 180, 'dy': -200, 'last_feet': 210}\nassert lands_on(player, platform) is False, 'a spring has thrown the player upwards'"),
           ("Falling past it to one side is not a landing",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 250, 'y': 180, 'dy': 200, 'last_feet': 200}\nassert lands_on(player, platform) is False"),
           ("A very fast fall is still caught",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 206, 'dy': MAX_FALL_SPEED, 'last_feet': 190}\nassert lands_on(player, platform) is True, 'the feet leapt over it in one frame, but still crossed it'"),
           ("Landing exactly on the edge of the top counts",
            "platform = {'x': 100, 'y': 200}\nplayer = {'x': 121, 'y': 176, 'dy': 100, 'last_feet': 199}\nassert lands_on(player, platform) is True"),
           ("A real game lands on things",
            "state = create_game()\n# drop the player from a standstill, squarely above a real platform\nplatform = state['platforms'][1]\nstate['player']['riding'] = None\nstate['player']['x'] = platform['x'] + PLATFORM_WIDTH / 2 - PLAYER_WIDTH / 2\nstate['player']['y'] = platform['y'] - 90\nstate['player']['dy'] = 0\nstate['player']['last_feet'] = state['player']['y'] + PLAYER_HEIGHT\nstate['steering'] = 0\nlanded = False\nfor _ in range(90):\n    update_game(state, 16)\n    if state['player']['riding']:\n        landed = True\n        break\nassert landed, 'the player was dropped straight onto a platform and never landed'")]),
  demo=dict(kind="land", caption="A still shaft to practise on. Walk about and watch the landings."),
  warning="Compare where the feet WERE with where they are NOW. A 'near the top' test misses fast falls, and the player drops straight through solid platforms."),

step("land_on_platform", "landOnPlatform", "land_on_platform",
  "What kind did you land on?", "The 锯齿 start to hurt.",
  "<p>Now the fun part — and the heart of the whole game. You have landed; what happens next depends entirely on <em>what you landed on</em>.</p>"
  "<ul><li><strong>plain</strong> — nothing at all, and that is a relief.</li>"
  "<li><strong>锯齿 spiked</strong> — it costs you SPIKE_DAMAGE blood. This is the one to avoid.</li>"
  "<li><strong>spring</strong> — it throws you straight back up, and you are airborne again at once.</li>"
  "<li><strong>crumbling</strong> — it starts falling apart the moment you touch it.</li>"
  "<li><strong>sliding</strong> — it carries you sideways while you stand on it (that is handled while you walk).</li></ul>"
  "<p>Whatever the kind, first stand the player neatly on top and count the floor.</p>",
  "state, platform",
  "nothing; it changes the player and the platform",
  ["Put the player exactly on top: the platform's y, minus PLAYER_HEIGHT. Stop them falling and remember what they are riding.",
   "If this platform is deeper than any reached before, that is a new floor: remember it and score 10.",
   "Spiked? hurt the player by SPIKE_DAMAGE.",
   "Spring? set dy to SPRING_SPEED, stop riding (you are in the air again), and count the bounce.",
   "Crumbling? start its timer at CRUMBLE_SECONDS."],
  js=dict(starter="function landOnPlatform(state, platform) {\n    // stand on top, count the floor, then do what this KIND does\n}\n",
    answer="function landOnPlatform(state, platform) {\n    const rect = platformRect(platform);\n\n    state.player.y = rect.y - PLAYER_HEIGHT;\n    state.player.dy = 0;\n    state.player.riding = platform;\n\n    if (platform.floor > state.floor) {\n        state.floor = platform.floor;\n        state.score = state.score + 10;\n    }\n\n    if (platform.kind === SPIKED) {\n        hurt(state, SPIKE_DAMAGE);\n\n    } else if (platform.kind === SPRING) {\n        state.player.dy = SPRING_SPEED;\n        state.player.riding = null;\n        state.bounces = state.bounces + 1;\n\n    } else if (platform.kind === CRUMBLING) {\n        platform.crumbling = CRUMBLE_SECONDS;\n    }\n}\n",
    hints=["Standing on top means y = the platform's y MINUS the player's height.",
           "hurt(state, amount) is written for you.",
           "A spring has to clear riding as well as setting dy — you are in the air again."],
    tests=[("Landing stands you on top",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: PLAIN, floor: 9, crumbling: 0 };\nstate.player.x = 121;\nlandOnPlatform(state, platform);\nassert(state.player.y === 300 - PLAYER_HEIGHT, 'y is ' + state.player.y);\nassert(state.player.dy === 0);"),
           ("Landing counts a new floor",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: PLAIN, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.floor === 9);\nassert(state.score === 10);"),
           ("Landing on a floor you have already had scores nothing",
            "const state = createGame();\nstate.floor = 20;\nstate.score = 0;\nconst platform = { x: 100, y: 300, kind: PLAIN, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.score === 0, 'you have already been to floor 9');"),
           ("A plain platform does nothing else",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: PLAIN, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.health === MAX_HEALTH, 'a plain platform is safe');\nassert(state.player.riding === platform);"),
           ("锯齿 spikes cost blood",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: SPIKED, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.health === MAX_HEALTH - SPIKE_DAMAGE, 'blood is ' + state.health);"),
           ("A spring throws you back up",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: SPRING, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.player.dy === SPRING_SPEED, 'dy is ' + state.player.dy);\nassert(state.player.dy < 0, 'upwards is negative');\nassert(state.player.riding === null, 'you are in the air again, not standing on it');"),
           ("A crumbling platform starts falling apart",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: CRUMBLING, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(platform.crumbling === CRUMBLE_SECONDS, 'its timer should have started');"),
           ("A sliding platform is safe to land on",
            "const state = createGame();\nconst platform = { x: 100, y: 300, kind: SLIDE_LEFT, floor: 9, crumbling: 0 };\nlandOnPlatform(state, platform);\nassert(state.health === MAX_HEALTH, 'it carries you along, it does not hurt you');\nassert(state.player.riding === platform);"),
           ("Enough spikes finish you off",
            "const state = createGame();\nfor (let i = 0; i < MAX_HEALTH; i++) {\n    landOnPlatform(state, { x: 100, y: 300, kind: SPIKED, floor: 1, crumbling: 0 });\n}\nassert(state.health === 0);\nassert(isDead(state) === true);")]),
  py=dict(starter="def land_on_platform(state, platform):\n    # stand on top, count the floor, then do what this KIND does\n    pass\n",
    answer="def land_on_platform(state, platform):\n    rect = platform_rect(platform)\n\n    state[\"player\"][\"y\"] = rect[\"y\"] - PLAYER_HEIGHT\n    state[\"player\"][\"dy\"] = 0\n    state[\"player\"][\"riding\"] = platform\n\n    if platform[\"floor\"] > state[\"floor\"]:\n        state[\"floor\"] = platform[\"floor\"]\n        state[\"score\"] += 10\n\n    if platform[\"kind\"] == SPIKED:\n        hurt(state, SPIKE_DAMAGE)\n\n    elif platform[\"kind\"] == SPRING:\n        state[\"player\"][\"dy\"] = SPRING_SPEED\n        state[\"player\"][\"riding\"] = None\n        state[\"bounces\"] += 1\n\n    elif platform[\"kind\"] == CRUMBLING:\n        platform[\"crumbling\"] = CRUMBLE_SECONDS\n",
    hints=["Standing on top means y = the platform's y MINUS the player's height.",
           "hurt(state, amount) is written for you.",
           "A spring has to clear riding as well as setting dy - you are in the air again."],
    tests=[("Landing stands you on top",
            "state = create_game()\nplatform = {'x': 100, 'y': 300, 'kind': PLAIN, 'floor': 9, 'crumbling': 0}\nstate['player']['x'] = 121\nland_on_platform(state, platform)\nassert state['player']['y'] == 300 - PLAYER_HEIGHT\nassert state['player']['dy'] == 0"),
           ("Landing counts a new floor",
            "state = create_game()\nland_on_platform(state, {'x': 100, 'y': 300, 'kind': PLAIN, 'floor': 9, 'crumbling': 0})\nassert state['floor'] == 9 and state['score'] == 10"),
           ("Landing on a floor you have already had scores nothing",
            "state = create_game()\nstate['floor'] = 20\nstate['score'] = 0\nland_on_platform(state, {'x': 100, 'y': 300, 'kind': PLAIN, 'floor': 9, 'crumbling': 0})\nassert state['score'] == 0"),
           ("A plain platform does nothing else",
            "state = create_game()\nplatform = {'x': 100, 'y': 300, 'kind': PLAIN, 'floor': 9, 'crumbling': 0}\nland_on_platform(state, platform)\nassert state['health'] == MAX_HEALTH\nassert state['player']['riding'] is platform"),
           ("锯齿 spikes cost blood",
            "state = create_game()\nland_on_platform(state, {'x': 100, 'y': 300, 'kind': SPIKED, 'floor': 9, 'crumbling': 0})\nassert state['health'] == MAX_HEALTH - SPIKE_DAMAGE"),
           ("A spring throws you back up",
            "state = create_game()\nland_on_platform(state, {'x': 100, 'y': 300, 'kind': SPRING, 'floor': 9, 'crumbling': 0})\nassert state['player']['dy'] == SPRING_SPEED < 0\nassert state['player']['riding'] is None"),
           ("A crumbling platform starts falling apart",
            "state = create_game()\nplatform = {'x': 100, 'y': 300, 'kind': CRUMBLING, 'floor': 9, 'crumbling': 0}\nland_on_platform(state, platform)\nassert platform['crumbling'] == CRUMBLE_SECONDS"),
           ("A sliding platform is safe to land on",
            "state = create_game()\nplatform = {'x': 100, 'y': 300, 'kind': SLIDE_LEFT, 'floor': 9, 'crumbling': 0}\nland_on_platform(state, platform)\nassert state['health'] == MAX_HEALTH\nassert state['player']['riding'] is platform"),
           ("Enough spikes finish you off",
            "state = create_game()\nfor _ in range(MAX_HEALTH):\n    land_on_platform(state, {'x': 100, 'y': 300, 'kind': SPIKED, 'floor': 1, 'crumbling': 0})\nassert state['health'] == 0 and is_dead(state) is True")]),
  demo=dict(kind="land", caption="Six platforms, one of each kind. Land on the 锯齿 one and watch the blood bar."),
  warning="A spring must clear `riding` as well as setting dy. Leave the player marked as standing on it and they will be glued to a platform that is trying to throw them off."),

step("is_dead", "isDead", "is_dead",
  "Two ways to go", "The game can end.",
  "<p>The last rule, and it says exactly what the game is about.</p>"
  "<p><strong>Run out of blood</strong> — too many 锯齿.<br>"
  "<strong>Fall off the bottom of the screen</strong> — you missed every platform on the way down.</p>"
  "<p>Note the second one has to be measured on the SCREEN, not in the world. In the world you are always falling deeper; what matters is whether the camera has lost you.</p>",
  "state",
  "True if the player is finished",
  ["No blood left is death.",
   "So is being below the bottom of the screen — use screen-y to find out where the player actually appears."],
  js=dict(starter="function isDead(state) {\n    // no blood left, or fallen off the bottom of the screen\n}\n",
    answer="function isDead(state) {\n    return state.health <= 0 || screenY(state, state.player.y) > FIELD_HEIGHT;\n}\n",
    hints=["Two things joined with || — either one is enough.",
           "Use screenY(state, state.player.y), not the world position.",
           "FIELD_HEIGHT is the bottom of the screen."],
    tests=[("A fresh game is not over",
            "assert(isDead(createGame()) === false);"),
           ("No blood left is death",
            "const state = createGame();\nstate.health = 0;\nassert(isDead(state) === true);"),
           ("Falling off the bottom is death",
            "const state = createGame();\nstate.player.y = state.camera + FIELD_HEIGHT + 1;\nassert(isDead(state) === true, 'the player is below the bottom of the screen');"),
           ("Being near the bottom is still alive",
            "const state = createGame();\nstate.player.y = state.camera + FIELD_HEIGHT - 20;\nassert(isDead(state) === false, 'still on screen, still in the game');"),
           ("It is the SCREEN that matters, not the world",
            "const state = createGame();\nstate.camera = 5000;\nstate.player.y = 5100;\nassert(isDead(state) === false, 'a world y of 5100 sounds enormous, but with the camera at 5000 the player is 100 pixels down the screen and perfectly fine');"),
           ("One point of blood is enough to live on",
            "const state = createGame();\nstate.health = 1;\nassert(isDead(state) === false);")]),
  py=dict(starter="def is_dead(state):\n    # no blood left, or fallen off the bottom of the screen\n    pass\n",
    answer="def is_dead(state):\n    return state[\"health\"] <= 0 or screen_y(state, state[\"player\"][\"y\"]) > FIELD_HEIGHT\n",
    hints=["Two things joined with `or` - either one is enough.",
           "Use screen_y(state, state['player']['y']), not the world position.",
           "FIELD_HEIGHT is the bottom of the screen."],
    tests=[("A fresh game is not over",
            "assert is_dead(create_game()) is False"),
           ("No blood left is death",
            "state = create_game()\nstate['health'] = 0\nassert is_dead(state) is True"),
           ("Falling off the bottom is death",
            "state = create_game()\nstate['player']['y'] = state['camera'] + FIELD_HEIGHT + 1\nassert is_dead(state) is True"),
           ("Being near the bottom is still alive",
            "state = create_game()\nstate['player']['y'] = state['camera'] + FIELD_HEIGHT - 20\nassert is_dead(state) is False"),
           ("It is the SCREEN that matters, not the world",
            "state = create_game()\nstate['camera'] = 5000\nstate['player']['y'] = 5100\nassert is_dead(state) is False, 'with the camera at 5000 the player is 100 pixels down the screen'"),
           ("One point of blood is enough to live on",
            "state = create_game()\nstate['health'] = 1\nassert is_dead(state) is False")]),
  demo=dict(kind="final", flags=dict(robot=True), caption="A robot climber plays the finished game. Click the page and take over with ← and →.")),
]

write_workshop("floors", "Hundred Floors", STEPS)
