"""The seven steps of "Build Frogger", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("lane_direction", "laneDirection", "lane_direction",
  "Which way does the traffic go?", "The road knows its own directions.",
  "<p>If every lane went the same way the game would be dull and easy. So the rows take turns: odd rows drive right, even rows drive left.</p>"
  "<p>The tool for this is <strong>remainder</strong> — <code>row % 2</code> is 1 for odd rows and 0 for even ones. You will use that trick in almost every grid program you ever write.</p>",
  "row", "1 for rightwards, -1 for leftwards",
  ["Work out row % 2.", "If it is 1, the row goes right: return 1.", "Otherwise return -1."],
  js=dict(starter="function laneDirection(row) {\n    // odd rows go right, even rows go left\n}\n",
    answer="function laneDirection(row) {\n    return row % 2 === 1 ? 1 : -1;\n}\n",
    hints=["% gives the remainder: 7 % 2 is 1, and 8 % 2 is 0.",
           "An if works perfectly well — you do not have to use ? :",
           "return row % 2 === 1 ? 1 : -1;"],
    tests=[("Row 1 drives right", "assert(laneDirection(1) === 1);"),
           ("Row 2 drives left", "assert(laneDirection(2) === -1, 'gave ' + laneDirection(2));"),
           ("Row 3 drives right", "assert(laneDirection(3) === 1);"),
           ("Every row is 1 or -1",
            "for (let row = 0; row < ROWS; row++) { const d = laneDirection(row);\n    assert(d === 1 || d === -1, 'row ' + row + ' gave ' + d); }"),
           ("No two rows next to each other go the same way",
            "for (let row = 1; row < ROWS; row++) {\n    assert(laneDirection(row) !== laneDirection(row - 1), 'rows ' + (row - 1) + ' and ' + row + ' both go the same way');\n}")]),
  py=dict(starter="def lane_direction(row):\n    # odd rows go right, even rows go left\n    pass\n",
    answer="def lane_direction(row):\n    return 1 if row % 2 == 1 else -1\n",
    hints=["% gives the remainder: 7 % 2 is 1, and 8 % 2 is 0.",
           "An if works perfectly well.", "return 1 if row % 2 == 1 else -1"],
    tests=[("Row 1 drives right", "assert lane_direction(1) == 1"),
           ("Row 2 drives left", "assert lane_direction(2) == -1"),
           ("Row 3 drives right", "assert lane_direction(3) == 1"),
           ("Every row is 1 or -1",
            "for row in range(ROWS):\n    assert lane_direction(row) in (1, -1), f'row {row} gave {lane_direction(row)}'"),
           ("No two rows next to each other go the same way",
            "for row in range(1, ROWS):\n    assert lane_direction(row) != lane_direction(row - 1)")]),
  demo=dict(kind="lanes", caption="Walk up and down the rows and watch the traffic turn around.")),

step("lane_speed", "laneSpeed", "lane_speed",
  "How fast is each lane?", "Every row moves at its own pace.",
  "<p>Two lanes moving at exactly the same speed look wrong — the traffic seems to march in step. Giving each row its own speed makes the road look alive.</p>"
  "<p>The cap matters just as much: without it, level 30 would be uncrossable and the game would stop being a game.</p>",
  "row, level", "pixels per second",
  ["Start with 34.", "Add 9 for every row — that is what makes each lane different.",
   "Add 8 for every level after the first.", "Never go above 190."],
  js=dict(starter="function laneSpeed(row, level) {\n    // 34, plus 9 a row, plus 8 a level — but never over 190\n}\n",
    answer="function laneSpeed(row, level) {\n    const speed = 34 + row * 9 + (level - 1) * 8;\n    return speed > 190 ? 190 : speed;\n}\n",
    hints=["Work the sum out into a variable first, then cap it.",
           "Level 1 must add nothing, so use (level - 1).",
           "Math.min(190, speed) is the short way to write the cap."],
    tests=[("Row 1 at level 1 crawls along",
            "assert(laneSpeed(1, 1) === 43, 'gave ' + laneSpeed(1, 1));"),
           ("Higher rows are faster",
            "assert(laneSpeed(5, 1) > laneSpeed(2, 1), 'each row should have its own speed');"),
           ("Higher levels are faster",
            "assert(laneSpeed(3, 4) > laneSpeed(3, 1));"),
           ("Every lane in a level is different",
            "const speeds = [];\nfor (let row = 1; row <= 9; row++) { speeds.push(laneSpeed(row, 1)); }\nassert(new Set(speeds).size === speeds.length, 'two lanes move at the same speed: ' + speeds.join(','));"),
           ("It never goes above 190",
            "for (let level = 1; level <= 40; level++) {\n    for (let row = 0; row < ROWS; row++) {\n        assert(laneSpeed(row, level) <= 190, 'row ' + row + ' level ' + level + ' gave ' + laneSpeed(row, level));\n    }\n}"),
           ("Speeds are always positive",
            "for (let row = 0; row < ROWS; row++) { assert(laneSpeed(row, 1) > 0); }")]),
  py=dict(starter="def lane_speed(row, level):\n    # 34, plus 9 a row, plus 8 a level - but never over 190\n    pass\n",
    answer="def lane_speed(row, level):\n    return min(190, 34 + row * 9 + (level - 1) * 8)\n",
    hints=["min(190, something) is the cap.",
           "Level 1 must add nothing, so use (level - 1).",
           "return min(190, 34 + row * 9 + (level - 1) * 8)"],
    tests=[("Row 1 at level 1 crawls along", "assert lane_speed(1, 1) == 43"),
           ("Higher rows are faster", "assert lane_speed(5, 1) > lane_speed(2, 1)"),
           ("Higher levels are faster", "assert lane_speed(3, 4) > lane_speed(3, 1)"),
           ("Every lane in a level is different",
            "speeds = [lane_speed(r, 1) for r in range(1, 10)]\nassert len(set(speeds)) == len(speeds), f'two lanes move together: {speeds}'"),
           ("It never goes above 190",
            "for level in range(1, 41):\n    for row in range(ROWS):\n        assert lane_speed(row, level) <= 190"),
           ("Speeds are always positive",
            "assert all(lane_speed(row, 1) > 0 for row in range(ROWS))")]),
  demo=dict(kind="lanes", caption="Step through the rows and read each lane's speed.")),

step("wrap_car", "wrapCar", "wrap_car",
  "Make the road a loop", "The traffic never runs out.",
  "<p>Cars drive off the edge of the screen. If nothing catches them, the road empties out after a few seconds and the game is over in the boring sense.</p>"
  "<p>The fix is a trick you will meet again and again: when something leaves one side, put it back on the other. The road becomes an endless loop with only a handful of cars in it.</p>",
  "car — { row, x, width }", "nothing; it changes car.x",
  ["If the car's x is past FIELD_WIDTH, put it just off the left: x becomes -width.",
   "If the car's right-hand edge (x + width) is left of 0, put it at FIELD_WIDTH."],
  js=dict(starter="function wrapCar(car) {\n    // off one side, back on the other\n}\n",
    answer="function wrapCar(car) {\n    if (car.x > FIELD_WIDTH) {\n        car.x = -car.width;\n    }\n    if (car.x + car.width < 0) {\n        car.x = FIELD_WIDTH;\n    }\n}\n",
    hints=["Two ifs — cars go both ways, so both edges need catching.",
           "Set x to -car.width, not 0, or the car would pop into view.",
           "A car has gone off the left when x + width is below 0."],
    tests=[("A car in the middle is left alone",
            "const car = { row: 1, x: 100, width: 38 };\nwrapCar(car);\nassert(car.x === 100);"),
           ("A car off the right comes back on the left",
            "const car = { row: 1, x: FIELD_WIDTH + 5, width: 38 };\nwrapCar(car);\nassert(car.x < 0, 'x is ' + car.x + ' — it should be waiting off the left edge');"),
           ("A car off the left comes back on the right",
            "const car = { row: 2, x: -50, width: 38 };\nwrapCar(car);\nassert(car.x === FIELD_WIDTH, 'x is ' + car.x);"),
           ("A car half off the edge is left alone",
            "const car = { row: 1, x: FIELD_WIDTH - 10, width: 38 };\nwrapCar(car);\nassert(car.x === FIELD_WIDTH - 10, 'it is still partly visible, so leave it');"),
           ("It comes back completely off screen, not halfway",
            "const car = { row: 1, x: FIELD_WIDTH + 1, width: 38 };\nwrapCar(car);\nassert(car.x + car.width <= 0, 'the whole car should still be hidden, ready to drive in');"),
           ("A whole road stays full for ever",
            "const cars = makeTraffic();\nfor (let frame = 0; frame < 4000; frame++) { moveCars(cars, 0.016, 3); }\nassert(cars.length === makeTraffic().length, 'no car may be lost');\nassert(cars.every(c => c.x > -200 && c.x < FIELD_WIDTH + 200), 'a car has escaped down the road for ever');")]),
  py=dict(starter="def wrap_car(car):\n    # off one side, back on the other\n    pass\n",
    answer="def wrap_car(car):\n    if car[\"x\"] > FIELD_WIDTH:\n        car[\"x\"] = -car[\"width\"]\n    if car[\"x\"] + car[\"width\"] < 0:\n        car[\"x\"] = FIELD_WIDTH\n",
    hints=["Two ifs - cars go both ways.",
           "Set x to -car['width'], not 0, or the car would pop into view.",
           "A car has gone off the left when x + width is below 0."],
    tests=[("A car in the middle is left alone",
            "car = {'row': 1, 'x': 100, 'width': 38}\nwrap_car(car)\nassert car['x'] == 100"),
           ("A car off the right comes back on the left",
            "car = {'row': 1, 'x': FIELD_WIDTH + 5, 'width': 38}\nwrap_car(car)\nassert car['x'] < 0"),
           ("A car off the left comes back on the right",
            "car = {'row': 2, 'x': -50, 'width': 38}\nwrap_car(car)\nassert car['x'] == FIELD_WIDTH"),
           ("A car half off the edge is left alone",
            "car = {'row': 1, 'x': FIELD_WIDTH - 10, 'width': 38}\nwrap_car(car)\nassert car['x'] == FIELD_WIDTH - 10"),
           ("It comes back completely off screen, not halfway",
            "car = {'row': 1, 'x': FIELD_WIDTH + 1, 'width': 38}\nwrap_car(car)\nassert car['x'] + car['width'] <= 0"),
           ("A whole road stays full for ever",
            "cars = make_traffic()\nfor _ in range(4000):\n    move_cars(cars, 0.016, 3)\nassert len(cars) == len(make_traffic())\nassert all(-200 < c['x'] < FIELD_WIDTH + 200 for c in cars)")]),
  demo=dict(kind="traffic", caption="Watch the traffic loop round for ever — and speed it up with the level buttons.")),

step("move_frog", "moveFrog", "move_frog",
  "Hop!", "The frog can move.",
  "<p>The frog moves one whole square at a time — no sliding. That is what makes it feel like hopping.</p>"
  "<p>The clever bit is <code>highestRow</code>. Scoring for every forward hop would let a player bounce between two rows for ever and win. Scoring only for a row they have <em>never reached before</em> fixes that in one line.</p>",
  "state. dColumn, dRow — the hop, e.g. 0 and -1 for 'up'.",
  "True if the frog moved",
  ["Do nothing if the game is over or paused.",
   "Work out the new column and row.",
   "If either is off the field, return false and do not move.",
   "Move the frog.",
   "If the new row is higher than any row reached before, remember it and add 10 points."],
  js=dict(starter="function moveFrog(state, dColumn, dRow) {\n    // work out where it lands, stay on the field, score a NEW row\n}\n",
    answer="function moveFrog(state, dColumn, dRow) {\n    if (state.isOver || state.isPaused) {\n        return false;\n    }\n    const column = state.frog.column + dColumn;\n    const row = state.frog.row + dRow;\n\n    if (column < 0 || column >= COLUMNS || row < 0 || row >= ROWS) {\n        return false;\n    }\n\n    state.frog.column = column;\n    state.frog.row = row;\n\n    if (row < state.highestRow) {\n        state.highestRow = row;\n        state.score = state.score + 10;\n    }\n    return true;\n}\n",
    hints=["Work out where it WOULD land before you move it.",
           "Row 0 is the top, so 'higher up' means a SMALLER row number.",
           "if (row < state.highestRow) { ... }"],
    tests=[("Hopping forward moves the frog",
            "const state = createGame();\nconst before = state.frog.row;\nmoveFrog(state, 0, -1);\nassert(state.frog.row === before - 1, 'row is ' + state.frog.row);"),
           ("Hopping sideways moves the frog",
            "const state = createGame();\nconst before = state.frog.column;\nmoveFrog(state, 1, 0);\nassert(state.frog.column === before + 1);"),
           ("The frog cannot hop off the left",
            "const state = createGame();\nstate.frog.column = 0;\nassert(moveFrog(state, -1, 0) === false);\nassert(state.frog.column === 0, 'it should have stayed put');"),
           ("The frog cannot hop off the right",
            "const state = createGame();\nstate.frog.column = COLUMNS - 1;\nmoveFrog(state, 1, 0);\nassert(state.frog.column === COLUMNS - 1);"),
           ("The frog cannot hop off the bottom",
            "const state = createGame();\nstate.frog.row = ROWS - 1;\nassert(moveFrog(state, 0, 1) === false);"),
           ("A new row forward scores 10",
            "const state = createGame();\nmoveFrog(state, 0, -1);\nassert(state.score === 10, 'score is ' + state.score);"),
           ("Hopping back and forth does not score twice",
            "const state = createGame();\nmoveFrog(state, 0, -1);\nmoveFrog(state, 0, 1);\nmoveFrog(state, 0, -1);\nassert(state.score === 10, 'score is ' + state.score + ' — a row only pays once');"),
           ("Hopping sideways scores nothing",
            "const state = createGame();\nmoveFrog(state, 1, 0);\nassert(state.score === 0);")]),
  py=dict(starter="def move_frog(state, d_column, d_row):\n    # work out where it lands, stay on the field, score a NEW row\n    pass\n",
    answer="def move_frog(state, d_column, d_row):\n    if state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n    column = state[\"frog\"][\"column\"] + d_column\n    row = state[\"frog\"][\"row\"] + d_row\n\n    if not (0 <= column < COLUMNS) or not (0 <= row < ROWS):\n        return False\n\n    state[\"frog\"][\"column\"] = column\n    state[\"frog\"][\"row\"] = row\n\n    if row < state[\"highest_row\"]:\n        state[\"highest_row\"] = row\n        state[\"score\"] += 10\n    return True\n",
    hints=["Work out where it WOULD land before you move it.",
           "0 <= column < COLUMNS is the neat Python way to check both edges.",
           "Row 0 is the top, so 'higher up' means a SMALLER row number."],
    tests=[("Hopping forward moves the frog",
            "state = create_game()\nbefore = state['frog']['row']\nmove_frog(state, 0, -1)\nassert state['frog']['row'] == before - 1"),
           ("Hopping sideways moves the frog",
            "state = create_game()\nbefore = state['frog']['column']\nmove_frog(state, 1, 0)\nassert state['frog']['column'] == before + 1"),
           ("The frog cannot hop off the left",
            "state = create_game()\nstate['frog']['column'] = 0\nassert move_frog(state, -1, 0) is False\nassert state['frog']['column'] == 0"),
           ("The frog cannot hop off the right",
            "state = create_game()\nstate['frog']['column'] = COLUMNS - 1\nmove_frog(state, 1, 0)\nassert state['frog']['column'] == COLUMNS - 1"),
           ("The frog cannot hop off the bottom",
            "state = create_game()\nstate['frog']['row'] = ROWS - 1\nassert move_frog(state, 0, 1) is False"),
           ("A new row forward scores 10",
            "state = create_game()\nmove_frog(state, 0, -1)\nassert state['score'] == 10"),
           ("Hopping back and forth does not score twice",
            "state = create_game()\nmove_frog(state, 0, -1)\nmove_frog(state, 0, 1)\nmove_frog(state, 0, -1)\nassert state['score'] == 10, 'a row only pays once'"),
           ("Hopping sideways scores nothing",
            "state = create_game()\nmove_frog(state, 1, 0)\nassert state['score'] == 0")]),
  demo=dict(kind="hop", caption="An empty road to practise on. Hop about and watch the score."),
  warning="Score only for a row the frog has never reached. Score every forward hop and a player can farm points by bouncing on the spot."),

step("is_squashed", "isSquashed", "is_squashed",
  "Squashed?", "The traffic becomes dangerous.",
  "<p>Now the two worlds meet. The frog is on a grid; the cars are at any pixel. Turn both into rectangles and the question becomes easy.</p>"
  "<p>There is a small trick worth copying: only the cars in the frog's own row can possibly hit it, so skip the rest. That is nine times less work, sixty times a second.</p>",
  "state", "True if a car has caught the frog",
  ["Work out the frog's rectangle with frog-rect.",
   "Look at every car. Skip any that is not in the frog's row.",
   "If overlaps() says its rectangle touches the frog's, return True.",
   "Otherwise, False."],
  js=dict(starter="function isSquashed(state) {\n    // only the cars in the frog's own row can reach it\n}\n",
    answer="function isSquashed(state) {\n    const frog = frogRect(state.frog);\n    for (let i = 0; i < state.cars.length; i++) {\n        const car = state.cars[i];\n        if (car.row === state.frog.row && overlaps(frog, carRect(car))) {\n            return true;\n        }\n    }\n    return false;\n}\n",
    hints=["frogRect, carRect and overlaps are all written for you.",
           "Check the row FIRST — it is much cheaper than the rectangle test.",
           "return false; goes after the loop, not inside it."],
    tests=[("A frog on the empty bank is safe",
            "const state = createGame();\nassert(isSquashed(state) === false, 'the bottom bank has no traffic at all');"),
           ("A frog standing under a car is squashed",
            "const state = createGame();\nstate.frog = { column: 2, row: 1 };\nstate.cars = [{ row: 1, x: frogRect(state.frog).x, width: 38 }];\nassert(isSquashed(state) === true);"),
           ("A car in another row cannot touch it",
            "const state = createGame();\nstate.frog = { column: 2, row: 1 };\nstate.cars = [{ row: 4, x: frogRect(state.frog).x, width: 38 }];\nassert(isSquashed(state) === false, 'that car is three rows away');"),
           ("A car in the same row but far along misses",
            "const state = createGame();\nstate.frog = { column: 0, row: 1 };\nstate.cars = [{ row: 1, x: 200, width: 38 }];\nassert(isSquashed(state) === false);"),
           ("Every car is checked, not just the first",
            "const state = createGame();\nstate.frog = { column: 2, row: 1 };\nstate.cars = [{ row: 1, x: 250, width: 38 }, { row: 1, x: frogRect(state.frog).x, width: 38 }];\nassert(isSquashed(state) === true, 'the second car is the one that got it');"),
           ("The safe island really is safe",
            "const state = createGame();\nstate.frog = { column: 4, row: MEDIAN_ROW };\nfor (let frame = 0; frame < 2000; frame++) {\n    moveCars(state.cars, 0.016, 5);\n    assert(isSquashed(state) === false, 'nothing may ever hit the frog on the middle island');\n}")]),
  py=dict(starter="def is_squashed(state):\n    # only the cars in the frog's own row can reach it\n    pass\n",
    answer="def is_squashed(state):\n    frog = frog_rect(state[\"frog\"])\n    for car in state[\"cars\"]:\n        if car[\"row\"] == state[\"frog\"][\"row\"] and overlaps(frog, car_rect(car)):\n            return True\n    return False\n",
    hints=["frog_rect, car_rect and overlaps are all written for you.",
           "Check the row FIRST - it is much cheaper than the rectangle test.",
           "return False goes after the loop, not inside it."],
    tests=[("A frog on the empty bank is safe",
            "assert is_squashed(create_game()) is False"),
           ("A frog standing under a car is squashed",
            "state = create_game()\nstate['frog'] = {'column': 2, 'row': 1}\nstate['cars'] = [{'row': 1, 'x': frog_rect(state['frog'])['x'], 'width': 38}]\nassert is_squashed(state) is True"),
           ("A car in another row cannot touch it",
            "state = create_game()\nstate['frog'] = {'column': 2, 'row': 1}\nstate['cars'] = [{'row': 4, 'x': frog_rect(state['frog'])['x'], 'width': 38}]\nassert is_squashed(state) is False"),
           ("A car in the same row but far along misses",
            "state = create_game()\nstate['frog'] = {'column': 0, 'row': 1}\nstate['cars'] = [{'row': 1, 'x': 200, 'width': 38}]\nassert is_squashed(state) is False"),
           ("Every car is checked, not just the first",
            "state = create_game()\nstate['frog'] = {'column': 2, 'row': 1}\nstate['cars'] = [{'row': 1, 'x': 250, 'width': 38}, {'row': 1, 'x': frog_rect(state['frog'])['x'], 'width': 38}]\nassert is_squashed(state) is True"),
           ("The safe island really is safe",
            "state = create_game()\nstate['frog'] = {'column': 4, 'row': MEDIAN_ROW}\nfor _ in range(2000):\n    move_cars(state['cars'], 0.016, 5)\n    assert is_squashed(state) is False")]),
  demo=dict(kind="game", caption="The real road. Hop across it — the note tells you the moment you are hit.")),

step("reach_home", "reachHome", "reach_home",
  "Getting home", "A crossing is worth something.",
  "<p>The reward for a whole crossing. A hundred points, the level goes up so the traffic speeds up, and the frog starts again from the bottom.</p>"
  "<p>Notice the order: score, count, level, <em>then</em> put the frog back. Reset it first and the frog would no longer be on the home row, so nothing else would happen.</p>",
  "state", "True if the frog just got home",
  ["If the frog is not on HOME_ROW, return False.",
   "Add 100 to the score.", "Add 1 to the crossings and 1 to the level.",
   "Call reset-frog to put it back at the bottom.", "Return True."],
  js=dict(starter="function reachHome(state) {\n    // 100 points, next level, back to the start\n}\n",
    answer="function reachHome(state) {\n    if (state.frog.row !== HOME_ROW) {\n        return false;\n    }\n    state.score = state.score + 100;\n    state.crossings = state.crossings + 1;\n    state.level = state.level + 1;\n    resetFrog(state);\n    return true;\n}\n",
    hints=["The very first line is a guard: not home yet? return false.",
           "resetFrog is already written for you.",
           "Reset the frog LAST, once everything has been counted."],
    tests=[("Reaching the top counts as a crossing",
            "const state = createGame();\nstate.frog.row = HOME_ROW;\nassert(reachHome(state) === true);\nassert(state.crossings === 1);"),
           ("A crossing is worth 100",
            "const state = createGame();\nstate.frog.row = HOME_ROW;\nreachHome(state);\nassert(state.score === 100, 'score is ' + state.score);"),
           ("The next level is faster",
            "const state = createGame();\nstate.frog.row = HOME_ROW;\nreachHome(state);\nassert(state.level === 2);\nassert(laneSpeed(3, state.level) > laneSpeed(3, 1), 'the traffic should now be quicker');"),
           ("The frog goes back to the start",
            "const state = createGame();\nstate.frog.row = HOME_ROW;\nreachHome(state);\nassert(state.frog.row === START_ROW, 'the frog is at row ' + state.frog.row);"),
           ("It can score again on the way back up",
            "const state = createGame();\nstate.frog.row = HOME_ROW;\nreachHome(state);\nassert(state.highestRow === START_ROW, 'the new crossing has to start from scratch');"),
           ("A frog halfway across has not got home",
            "const state = createGame();\nstate.frog.row = 4;\nassert(reachHome(state) === false);\nassert(state.score === 0);")]),
  py=dict(starter="def reach_home(state):\n    # 100 points, next level, back to the start\n    pass\n",
    answer="def reach_home(state):\n    if state[\"frog\"][\"row\"] != HOME_ROW:\n        return False\n    state[\"score\"] += 100\n    state[\"crossings\"] += 1\n    state[\"level\"] += 1\n    reset_frog(state)\n    return True\n",
    hints=["The very first line is a guard: not home yet? return False.",
           "reset_frog is already written for you.",
           "Reset the frog LAST, once everything has been counted."],
    tests=[("Reaching the top counts as a crossing",
            "state = create_game()\nstate['frog']['row'] = HOME_ROW\nassert reach_home(state) is True\nassert state['crossings'] == 1"),
           ("A crossing is worth 100",
            "state = create_game()\nstate['frog']['row'] = HOME_ROW\nreach_home(state)\nassert state['score'] == 100"),
           ("The next level is faster",
            "state = create_game()\nstate['frog']['row'] = HOME_ROW\nreach_home(state)\nassert state['level'] == 2\nassert lane_speed(3, state['level']) > lane_speed(3, 1)"),
           ("The frog goes back to the start",
            "state = create_game()\nstate['frog']['row'] = HOME_ROW\nreach_home(state)\nassert state['frog']['row'] == START_ROW"),
           ("It can score again on the way back up",
            "state = create_game()\nstate['frog']['row'] = HOME_ROW\nreach_home(state)\nassert state['highest_row'] == START_ROW"),
           ("A frog halfway across has not got home",
            "state = create_game()\nstate['frog']['row'] = 4\nassert reach_home(state) is False\nassert state['score'] == 0")]),
  demo=dict(kind="game", caption="Get all the way to the top and watch the score jump by 100.")),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function. Four directions, a pause and a restart — and the game is yours.</p>",
  "key", "an action name, or nothing at all",
  ["Up arrow or W → 'up'. Down or S → 'down'.",
   "Left or A → 'left'. Right or D → 'right'.",
   "P or space → 'pause'. R → 'restart'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // four directions, pause, restart\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === 'p' || k === ' ' || k === 'spacebar') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["The arrows are 'ArrowUp', 'ArrowDown', 'ArrowLeft' and 'ArrowRight'.",
           "toLowerCase() up front means you only ever compare lower-case names.",
           "Six ifs and a return null;"],
    tests=[("The arrows hop",
            "assert(actionForKey('ArrowUp') === 'up');\nassert(actionForKey('ArrowDown') === 'down');\nassert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("WASD hops too",
            "assert(actionForKey('w') === 'up');\nassert(actionForKey('s') === 'down');\nassert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("Capital letters work",
            "assert(actionForKey('W') === 'up');\nassert(actionForKey('R') === 'restart');"),
           ("P and space pause",
            "assert(actionForKey('p') === 'pause');\nassert(actionForKey(' ') === 'pause');"),
           ("R starts a new game", "assert(actionForKey('r') === 'restart');"),
           ("Other keys do nothing",
            "assert(actionForKey('z') === null);\nassert(actionForKey('Enter') === null);")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowup\": \"up\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \"p\": \"pause\", \" \": \"pause\", \"spacebar\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["A dictionary is much tidier than six ifs.",
           "keys.get(...) gives None for anything not listed.",
           "Remember \" \" for the space bar."],
    tests=[("The arrows hop",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD hops too",
            "assert action_for_key('w') == 'up'\nassert action_for_key('s') == 'down'\nassert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("Capital letters work",
            "assert action_for_key('W') == 'up'\nassert action_for_key('R') == 'restart'"),
           ("P and space pause",
            "assert action_for_key('p') == 'pause'\nassert action_for_key(' ') == 'pause'"),
           ("R starts a new game", "assert action_for_key('r') == 'restart'"),
           ("Other keys do nothing",
            "assert action_for_key('z') is None\nassert action_for_key('Enter') is None")]),
  demo=dict(kind="final", caption="Click the page, then cross the road with the arrow keys.")),
]

write_workshop("frogger", "Frogger", STEPS)
