"""The five steps of "Build Hangman", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("masked_word", "maskedWord", "masked_word",
  "Hide the word", "The blanks appear.",
  "<p>The first thing the player ever sees: the word with everything they have not guessed replaced by underscores.</p>"
  "<p>Joining the letters with spaces matters more than it looks — <code>_ _ _ _</code> can be counted at a glance, but <code>____</code> cannot.</p>",
  "word — the hidden word. guessed — the letters tried so far.",
  "a string like \"_ A _ _ E\"",
  ["Go through the word one letter at a time.",
   "If that letter is in `guessed`, show it.",
   "If not, show an underscore.",
   "Join everything with a space between."],
  js=dict(starter="function maskedWord(word, guessed) {\n    // a letter if it has been guessed, otherwise an underscore\n}\n",
    answer="function maskedWord(word, guessed) {\n    const shown = [];\n    for (let i = 0; i < word.length; i++) {\n        if (guessed.indexOf(word.charAt(i)) !== -1) {\n            shown.push(word.charAt(i));\n        } else {\n            shown.push('_');\n        }\n    }\n    return shown.join(' ');\n}\n",
    hints=["word.charAt(i) gives one letter of the word.",
           "guessed.indexOf(letter) !== -1 means 'this letter has been guessed'.",
           "Collect the pieces in a list, then join(' ') them at the end."],
    tests=[("Nothing guessed shows all blanks",
            "assert(maskedWord('CAT', '') === '_ _ _', 'gave \"' + maskedWord('CAT', '') + '\"');"),
           ("A guessed letter shows through",
            "assert(maskedWord('CAT', 'A') === '_ A _', 'gave \"' + maskedWord('CAT', 'A') + '\"');"),
           ("The whole word can be revealed",
            "assert(maskedWord('CAT', 'CAT') === 'C A T');"),
           ("A letter that appears twice shows both times",
            "assert(maskedWord('BOOK', 'O') === '_ O O _', 'gave \"' + maskedWord('BOOK', 'O') + '\" — every O must appear');"),
           ("Guesses that are not in the word change nothing",
            "assert(maskedWord('CAT', 'XYZ') === '_ _ _');"),
           ("Letters are separated by spaces",
            "assert(maskedWord('HI', '').indexOf(' ') !== -1, 'a row of underscores has to be countable');"),
           ("A long word works too",
            "assert(maskedWord('ELEPHANT', 'E') === 'E _ E _ _ _ _ _');")]),
  py=dict(starter="def masked_word(word, guessed):\n    # a letter if it has been guessed, otherwise an underscore\n    pass\n",
    answer="def masked_word(word, guessed):\n    return \" \".join(letter if letter in guessed else \"_\" for letter in word)\n",
    hints=["`for letter in word` walks the word one letter at a time.",
           "`letter in guessed` is True when that letter has been guessed.",
           "\" \".join(...) puts a space between everything."],
    tests=[("Nothing guessed shows all blanks",
            "got = masked_word('CAT', '')\nassert got == '_ _ _', f'gave {got!r}'"),
           ("A guessed letter shows through",
            "assert masked_word('CAT', 'A') == '_ A _'"),
           ("The whole word can be revealed",
            "assert masked_word('CAT', 'CAT') == 'C A T'"),
           ("A letter that appears twice shows both times",
            "assert masked_word('BOOK', 'O') == '_ O O _', 'every O must appear'"),
           ("Guesses that are not in the word change nothing",
            "assert masked_word('CAT', 'XYZ') == '_ _ _'"),
           ("Letters are separated by spaces",
            "assert ' ' in masked_word('HI', '')"),
           ("A long word works too",
            "assert masked_word('ELEPHANT', 'E') == 'E _ E _ _ _ _ _'")]),
  demo=dict(kind="mask", caption="Guess letters and watch the blanks fill in.")),

step("is_word_complete", "isWordComplete", "is_word_complete",
  "Is it finished?", "The game knows when you have won.",
  "<p>The word is complete when every one of its letters has been guessed.</p>"
  "<p>Note what this does <em>not</em> say. It says nothing about wrong guesses, and nothing about the letters you tried that were not in the word. Only: is anything still hidden?</p>",
  "word, guessed",
  "True if nothing is still hidden",
  ["Look at every letter of the word.",
   "If one of them has NOT been guessed, the word is not finished.",
   "If you get all the way through, it is."],
  js=dict(starter="function isWordComplete(word, guessed) {\n    // is every letter of the word in the guesses?\n}\n",
    answer="function isWordComplete(word, guessed) {\n    for (let i = 0; i < word.length; i++) {\n        if (guessed.indexOf(word.charAt(i)) === -1) {\n            return false;\n        }\n    }\n    return true;\n}\n",
    hints=["Look for a letter that is MISSING — one is enough to say no.",
           "return false; as soon as you find one.",
           "return true; goes after the loop."],
    tests=[("A fully guessed word is complete",
            "assert(isWordComplete('CAT', 'CAT') === true);"),
           ("A half-guessed word is not",
            "assert(isWordComplete('CAT', 'CA') === false);"),
           ("Nothing guessed is not complete",
            "assert(isWordComplete('CAT', '') === false);"),
           ("The order of the guesses does not matter",
            "assert(isWordComplete('CAT', 'TAC') === true, 'you can guess the letters in any order');"),
           ("Extra wrong guesses do not stop a win",
            "assert(isWordComplete('CAT', 'XYZCAT') === true, 'wrong guesses have nothing to do with it');"),
           ("A repeated letter only needs guessing once",
            "assert(isWordComplete('BOOK', 'BOK') === true, 'guessing O once reveals both of them');"),
           ("A long word works too",
            "assert(isWordComplete('ELEPHANT', 'ELPHANT') === true);\nassert(isWordComplete('ELEPHANT', 'ELPHAN') === false);")]),
  py=dict(starter="def is_word_complete(word, guessed):\n    # is every letter of the word in the guesses?\n    pass\n",
    answer="def is_word_complete(word, guessed):\n    return all(letter in guessed for letter in word)\n",
    hints=["all(...) is True only when every single check is.",
           "`letter in guessed` for each letter of the word.",
           "return all(letter in guessed for letter in word)"],
    tests=[("A fully guessed word is complete",
            "assert is_word_complete('CAT', 'CAT') is True"),
           ("A half-guessed word is not",
            "assert is_word_complete('CAT', 'CA') is False"),
           ("Nothing guessed is not complete",
            "assert is_word_complete('CAT', '') is False"),
           ("The order of the guesses does not matter",
            "assert is_word_complete('CAT', 'TAC') is True"),
           ("Extra wrong guesses do not stop a win",
            "assert is_word_complete('CAT', 'XYZCAT') is True"),
           ("A repeated letter only needs guessing once",
            "assert is_word_complete('BOOK', 'BOK') is True"),
           ("A long word works too",
            "assert is_word_complete('ELEPHANT', 'ELPHANT') is True\nassert is_word_complete('ELEPHANT', 'ELPHAN') is False")]),
  demo=dict(kind="mask", caption="Keep guessing until every blank is filled.")),

step("wrong_letters", "wrongLetters", "wrong_letters",
  "Count the mistakes", "The drawing starts to appear.",
  "<p>Every guess that was <em>not</em> in the word costs a life, and draws another line of the picture.</p>"
  "<p>Working this out from the guesses each time — rather than keeping a separate counter — means the two can never disagree with each other. One source of truth is always worth more than two that need keeping in step.</p>",
  "state", "a string of the wrong guesses, in order",
  ["Start with an empty string.",
   "Go through every letter that has been guessed.",
   "If it does NOT appear in the word, add it to the answer."],
  js=dict(starter="function wrongLetters(state) {\n    // the guesses that were not in the word\n}\n",
    answer="function wrongLetters(state) {\n    let wrong = '';\n    for (let i = 0; i < state.guessed.length; i++) {\n        const letter = state.guessed.charAt(i);\n        if (state.word.indexOf(letter) === -1) {\n            wrong = wrong + letter;\n        }\n    }\n    return wrong;\n}\n",
    hints=["Walk state.guessed, and check each letter against state.word.",
           "state.word.indexOf(letter) === -1 means 'not in the word'.",
           "Glue the wrong ones onto a string with +."],
    tests=[("No guesses means no mistakes",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nassert(wrongLetters(state) === '');"),
           ("A right guess is not a mistake",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'A';\nassert(wrongLetters(state) === '');"),
           ("A wrong guess is",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'X';\nassert(wrongLetters(state) === 'X');"),
           ("Only the wrong ones are collected",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'XAYTZ';\nassert(wrongLetters(state) === 'XYZ', 'gave \"' + wrongLetters(state) + '\"');"),
           ("They stay in the order they were guessed",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'ZXY';\nassert(wrongLetters(state) === 'ZXY');"),
           ("The lives count follows it",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'XY';\nassert(livesLeft(state) === MAX_WRONG - 2, 'lives is ' + livesLeft(state));"),
           ("Six mistakes uses every life",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'BDFGHJ';\nassert(wrongCount(state) === 6);\nassert(livesLeft(state) === 0);")]),
  py=dict(starter="def wrong_letters(state):\n    # the guesses that were not in the word\n    pass\n",
    answer="def wrong_letters(state):\n    return \"\".join(letter for letter in state[\"guessed\"] if letter not in state[\"word\"])\n",
    hints=["Walk state['guessed'], and check each letter against state['word'].",
           "`letter not in state['word']` means it was a mistake.",
           "\"\".join(...) glues the wrong ones back into a string."],
    tests=[("No guesses means no mistakes",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nassert wrong_letters(state) == ''"),
           ("A right guess is not a mistake",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'A'})\nassert wrong_letters(state) == ''"),
           ("A wrong guess is",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'X'})\nassert wrong_letters(state) == 'X'"),
           ("Only the wrong ones are collected",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'XAYTZ'})\nassert wrong_letters(state) == 'XYZ'"),
           ("They stay in the order they were guessed",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'ZXY'})\nassert wrong_letters(state) == 'ZXY'"),
           ("The lives count follows it",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'XY'})\nassert lives_left(state) == MAX_WRONG - 2"),
           ("Six mistakes uses every life",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'BDFGHJ'})\nassert wrong_count(state) == 6 and lives_left(state) == 0")]),
  demo=dict(kind="wrong", caption="Every wrong guess crosses off a life and draws another line.")),

step("guess_letter", "guessLetter", "guess_letter",
  "Make a guess", "The game works!",
  "<p>The move itself. Most of it is politely refusing things:</p>"
  "<ul><li>Not a letter? Ignore it — the number keys must not cost a life.</li>"
  "<li>Already guessed? Ignore it too. Pressing E twice is a slip, not a mistake.</li></ul>"
  "<p>Then add the letter and see where the game stands. Notice the order in <code>gameStatus</code>: a win is checked <em>before</em> a loss, so completing the word on your very last life counts as a win.</p>",
  "state, letter", "True if it counted as a new guess",
  ["Refuse if the game is over or paused.",
   "Turn the letter into a capital.",
   "Refuse anything that is not a single letter A-Z.",
   "Refuse a letter that has already been guessed.",
   "Add it to the guesses.",
   "Ask game-status. 'won' means won and over; 'lost' means over."],
  js=dict(starter="function guessLetter(state, letter) {\n    // refuse the silly ones, then add it and see where we stand\n}\n",
    answer="function guessLetter(state, letter) {\n    if (state.isOver || state.isPaused) {\n        return false;\n    }\n    const upper = String(letter).toUpperCase();\n\n    if (LETTERS.indexOf(upper) === -1 || upper.length !== 1) {\n        return false;\n    }\n    if (state.guessed.indexOf(upper) !== -1) {\n        return false;\n    }\n\n    state.guessed = state.guessed + upper;\n\n    const status = gameStatus(state);\n    if (status === 'won') {\n        state.isWon = true;\n        state.isOver = true;\n        state.wins = state.wins + 1;\n    } else if (status === 'lost') {\n        state.isOver = true;\n        state.losses = state.losses + 1;\n    }\n    return true;\n}\n",
    hints=["toUpperCase() first, so 'a' and 'A' are the same guess.",
           "LETTERS.indexOf(upper) === -1 catches digits and punctuation.",
           "gameStatus(state) is written for you — use it rather than checking twice."],
    tests=[("A new letter is accepted",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nassert(guessLetter(state, 'A') === true);\nassert(state.guessed === 'A');"),
           ("Small letters work too",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nguessLetter(state, 'a');\nassert(state.guessed === 'A', 'guesses are stored as capitals');"),
           ("The same letter twice is free",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nguessLetter(state, 'X');\nassert(guessLetter(state, 'X') === false, 'a slip must not cost a second life');\nassert(wrongCount(state) === 1, 'lives lost: ' + wrongCount(state));"),
           ("Numbers and symbols are ignored",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nassert(guessLetter(state, '5') === false);\nassert(guessLetter(state, '!') === false);\nassert(state.guessed === '');"),
           ("Finishing the word wins",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'CA';\nguessLetter(state, 'T');\nassert(state.isWon === true && state.isOver === true);"),
           ("Six mistakes lose",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'BDFGH';\nguessLetter(state, 'J');\nassert(state.isOver === true);\nassert(state.isWon === false);"),
           ("Winning on the very last life still counts as a win",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = 'BDFGHCA';\nassert(livesLeft(state) === 1, 'lives is ' + livesLeft(state));\nguessLetter(state, 'T');\nassert(state.isWon === true, 'that finished the word — it is a win, not a loss');"),
           ("A finished game ignores guesses",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nstate.isOver = true;\nassert(guessLetter(state, 'A') === false);")]),
  py=dict(starter="def guess_letter(state, letter):\n    # refuse the silly ones, then add it and see where we stand\n    pass\n",
    answer="def guess_letter(state, letter):\n    if state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n    upper = str(letter).upper()\n\n    if len(upper) != 1 or upper not in LETTERS:\n        return False\n    if upper in state[\"guessed\"]:\n        return False\n\n    state[\"guessed\"] += upper\n\n    status = game_status(state)\n    if status == \"won\":\n        state[\"is_won\"] = True\n        state[\"is_over\"] = True\n        state[\"wins\"] += 1\n    elif status == \"lost\":\n        state[\"is_over\"] = True\n        state[\"losses\"] += 1\n    return True\n",
    hints=[".upper() first, so 'a' and 'A' are the same guess.",
           "`upper not in LETTERS` catches digits and punctuation.",
           "game_status(state) is written for you - use it rather than checking twice."],
    tests=[("A new letter is accepted",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nassert guess_letter(state, 'A') is True\nassert state['guessed'] == 'A'"),
           ("Small letters work too",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nguess_letter(state, 'a')\nassert state['guessed'] == 'A'"),
           ("The same letter twice is free",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nguess_letter(state, 'X')\nassert guess_letter(state, 'X') is False\nassert wrong_count(state) == 1"),
           ("Numbers and symbols are ignored",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nassert guess_letter(state, '5') is False\nassert guess_letter(state, '!') is False\nassert state['guessed'] == ''"),
           ("Finishing the word wins",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'CA'})\nguess_letter(state, 'T')\nassert state['is_won'] is True and state['is_over'] is True"),
           ("Six mistakes lose",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'BDFGH'})\nguess_letter(state, 'J')\nassert state['is_over'] is True and state['is_won'] is False"),
           ("Winning on the very last life still counts as a win",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': 'BDFGHCA'})\nassert lives_left(state) == 1\nguess_letter(state, 'T')\nassert state['is_won'] is True, 'that finished the word - it is a win'"),
           ("A finished game ignores guesses",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': '', 'is_over': True})\nassert guess_letter(state, 'A') is False")]),
  demo=dict(kind="game", caption="Play properly. Try the vowels first — it is usually a good opening."),
  warning="Check for a WIN before a LOSS. Do it the other way round and a player who finishes the word on their last life is told they lost."),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function, and it works differently from every other game in this collection.</p>"
  "<p>Everywhere else a key turns into a <em>word</em> like 'left' or 'fire'. Here, twenty-six of the keys are actions in their own right — so the letter itself is handed straight back.</p>",
  "key", "'new', 'pause', a single capital letter, or nothing",
  ["Enter (or the 1 key) → 'new'.", "Escape → 'pause'.",
   "Any single letter → that letter, as a capital.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key);\n    // enter, escape, or the letter itself\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key);\n\n    if (k.toLowerCase() === 'enter' || k === '1') { return 'new'; }\n    if (k.toLowerCase() === 'escape') { return 'pause'; }\n\n    const upper = k.toUpperCase();\n    if (upper.length === 1 && LETTERS.indexOf(upper) !== -1) {\n        return upper;\n    }\n    return null;\n}\n",
    hints=["Check the named keys first, before you look at letters.",
           "'Enter' and 'Escape' are the key names the browser gives you.",
           "A letter comes back as itself, in capitals."],
    tests=[("A letter comes back as itself",
            "assert(actionForKey('a') === 'A');\nassert(actionForKey('Z') === 'Z');"),
           ("Enter starts a new word",
            "assert(actionForKey('Enter') === 'new');"),
           ("Escape pauses",
            "assert(actionForKey('Escape') === 'pause');"),
           ("Numbers are not letters",
            "assert(actionForKey('5') === null, 'gave ' + actionForKey('5'));"),
           ("Named keys are not treated as letters",
            "assert(actionForKey('ArrowUp') === null, 'ArrowUp is not a letter — gave ' + actionForKey('ArrowUp'));\nassert(actionForKey('Shift') === null);\nassert(actionForKey('Tab') === null);"),
           ("Every letter of the alphabet works",
            "for (let i = 0; i < LETTERS.length; i++) {\n    const letter = LETTERS.charAt(i);\n    assert(actionForKey(letter.toLowerCase()) === letter, letter + ' did not come back');\n}"),
           ("What comes back can be guessed straight away",
            "const state = createGame();\nstate.word = 'CAT';\nstate.guessed = '';\nguessLetter(state, actionForKey('c'));\nassert(state.guessed === 'C');")]),
  py=dict(starter="def action_for_key(key):\n    text = str(key)\n    # enter, escape, or the letter itself\n    return None\n",
    answer="def action_for_key(key):\n    text = str(key)\n\n    if text.lower() == \"enter\" or text == \"1\":\n        return \"new\"\n    if text.lower() == \"escape\":\n        return \"pause\"\n\n    upper = text.upper()\n    if len(upper) == 1 and upper in LETTERS:\n        return upper\n    return None\n",
    hints=["Check the named keys first, before you look at letters.",
           "'Enter' and 'Escape' are the key names the browser gives you.",
           "A letter comes back as itself, in capitals."],
    tests=[("A letter comes back as itself",
            "assert action_for_key('a') == 'A'\nassert action_for_key('Z') == 'Z'"),
           ("Enter starts a new word", "assert action_for_key('Enter') == 'new'"),
           ("Escape pauses", "assert action_for_key('Escape') == 'pause'"),
           ("Numbers are not letters", "assert action_for_key('5') is None"),
           ("Named keys are not treated as letters",
            "assert action_for_key('ArrowUp') is None\nassert action_for_key('Shift') is None\nassert action_for_key('Tab') is None"),
           ("Every letter of the alphabet works",
            "for letter in LETTERS:\n    assert action_for_key(letter.lower()) == letter"),
           ("What comes back can be guessed straight away",
            "state = create_game()\nstate.update({'word': 'CAT', 'guessed': ''})\nguess_letter(state, action_for_key('c'))\nassert state['guessed'] == 'C'")]),
  demo=dict(kind="final", caption="Click the page and just type. Any letter is a guess.")),
]

write_workshop("hangman", "Hangman", STEPS)
