"""The seven steps of "Build Space Invaders", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("alien_rect", "alienRect", "alien_rect",
  "Where is each alien?", "The fleet appears.",
  "<p>There are 24 aliens, but they do <strong>not</strong> each remember where they are. The whole fleet has one <code>fleetX</code> and one <code>fleetY</code>, and every alien works out its own place from its column and row.</p>"
  "<p>That is the trick that made this game possible on a 1978 computer, and it is still a good idea: change one number and all 24 move together.</p>",
  "alien — { column, row }. state — the game.",
  "a rectangle: x, y, width, height",
  ["x starts at the fleet's x, then add column × (ALIEN_WIDTH + ALIEN_GAP_X).",
   "y starts at the fleet's y, then add row × (ALIEN_HEIGHT + ALIEN_GAP_Y).",
   "Every alien is ALIEN_WIDTH by ALIEN_HEIGHT."],
  js=dict(starter="function alienRect(alien, state) {\n    return {\n        x: state.fleetX,\n        y: state.fleetY,\n        width: ALIEN_WIDTH,\n        height: ALIEN_HEIGHT\n    };\n}\n",
    answer="function alienRect(alien, state) {\n    return {\n        x: state.fleetX + alien.column * (ALIEN_WIDTH + ALIEN_GAP_X),\n        y: state.fleetY + alien.row * (ALIEN_HEIGHT + ALIEN_GAP_Y),\n        width: ALIEN_WIDTH,\n        height: ALIEN_HEIGHT\n    };\n}\n",
    hints=["Column 0 must sit exactly at the fleet's x.",
           "A whole alien AND a gap have to be skipped for each column.",
           "x: state.fleetX + alien.column * (ALIEN_WIDTH + ALIEN_GAP_X)"],
    tests=[("The first alien sits at the fleet's own corner",
            "const state = createGame();\nconst r = alienRect({ column: 0, row: 0 }, state);\nassert(r.x === state.fleetX, 'x is ' + r.x);\nassert(r.y === state.fleetY);"),
           ("Every alien is the same size",
            "const state = createGame();\nconst r = alienRect({ column: 3, row: 2 }, state);\nassert(r.width === ALIEN_WIDTH && r.height === ALIEN_HEIGHT);"),
           ("The next column is one alien and one gap across",
            "const state = createGame();\nconst gap = alienRect({ column: 1, row: 0 }, state).x - alienRect({ column: 0, row: 0 }, state).x;\nassert(gap === ALIEN_WIDTH + ALIEN_GAP_X, 'the gap between columns is ' + gap);"),
           ("The next row is one alien and one gap down",
            "const state = createGame();\nconst gap = alienRect({ column: 0, row: 1 }, state).y - alienRect({ column: 0, row: 0 }, state).y;\nassert(gap === ALIEN_HEIGHT + ALIEN_GAP_Y);"),
           ("Moving the fleet moves every alien",
            "const state = createGame();\nconst before = alienRect({ column: 4, row: 2 }, state).x;\nstate.fleetX = state.fleetX + 30;\nconst after = alienRect({ column: 4, row: 2 }, state).x;\nassert(after - before === 30, 'one number should move the whole fleet');"),
           ("A whole fleet fits on the field",
            "const state = createGame();\nconst last = alienRect({ column: ALIEN_COLUMNS - 1, row: 0 }, state);\nassert(last.x + last.width <= FIELD_WIDTH, 'the right-hand alien is off the field');")]),
  py=dict(starter="def alien_rect(alien, state):\n    return {\n        \"x\": state[\"fleet_x\"],\n        \"y\": state[\"fleet_y\"],\n        \"width\": ALIEN_WIDTH,\n        \"height\": ALIEN_HEIGHT,\n    }\n",
    answer="def alien_rect(alien, state):\n    return {\n        \"x\": state[\"fleet_x\"] + alien[\"column\"] * (ALIEN_WIDTH + ALIEN_GAP_X),\n        \"y\": state[\"fleet_y\"] + alien[\"row\"] * (ALIEN_HEIGHT + ALIEN_GAP_Y),\n        \"width\": ALIEN_WIDTH,\n        \"height\": ALIEN_HEIGHT,\n    }\n",
    hints=["Column 0 must sit exactly at the fleet's x.",
           "A whole alien AND a gap have to be skipped for each column.",
           "\"x\": state[\"fleet_x\"] + alien[\"column\"] * (ALIEN_WIDTH + ALIEN_GAP_X)"],
    tests=[("The first alien sits at the fleet's own corner",
            "state = create_game()\nr = alien_rect({'column': 0, 'row': 0}, state)\nassert r['x'] == state['fleet_x'] and r['y'] == state['fleet_y']"),
           ("Every alien is the same size",
            "state = create_game()\nr = alien_rect({'column': 3, 'row': 2}, state)\nassert r['width'] == ALIEN_WIDTH and r['height'] == ALIEN_HEIGHT"),
           ("The next column is one alien and one gap across",
            "state = create_game()\ngap = alien_rect({'column': 1, 'row': 0}, state)['x'] - alien_rect({'column': 0, 'row': 0}, state)['x']\nassert gap == ALIEN_WIDTH + ALIEN_GAP_X"),
           ("The next row is one alien and one gap down",
            "state = create_game()\ngap = alien_rect({'column': 0, 'row': 1}, state)['y'] - alien_rect({'column': 0, 'row': 0}, state)['y']\nassert gap == ALIEN_HEIGHT + ALIEN_GAP_Y"),
           ("Moving the fleet moves every alien",
            "state = create_game()\nbefore = alien_rect({'column': 4, 'row': 2}, state)['x']\nstate['fleet_x'] += 30\nassert alien_rect({'column': 4, 'row': 2}, state)['x'] - before == 30"),
           ("A whole fleet fits on the field",
            "state = create_game()\nlast = alien_rect({'column': ALIEN_COLUMNS - 1, 'row': 0}, state)\nassert last['x'] + last['width'] <= FIELD_WIDTH")]),
  demo=dict(kind="fleet", caption="Move the dashed box around the fleet and read the numbers underneath.")),

step("fleet_speed", "fleetSpeed", "fleet_speed",
  "The aliens speed up", "The fleet gets faster as it thins out.",
  "<p>Everyone remembers this from the arcade: the fewer aliens are left, the faster they come. In 1978 that happened by accident — the computer simply had fewer aliens to draw, so it drew them more often.</p>"
  "<p>It turned out to be brilliant game design, so now everybody does it on purpose.</p>",
  "state", "pixels per second",
  ["Work out how many have been shot: all of them minus aliens-left.",
   "Start at 22, add 5 for every alien shot, and 12 for every wave after the first.",
   "Never go above 260."],
  js=dict(starter="function fleetSpeed(state) {\n    // faster with every alien you shoot\n}\n",
    answer="function fleetSpeed(state) {\n    const shot = ALIEN_COLUMNS * ALIEN_ROWS - aliensLeft(state);\n    const speed = 22 + shot * 5 + (state.wave - 1) * 12;\n    return speed > 260 ? 260 : speed;\n}\n",
    hints=["aliensLeft(state) is written for you — count backwards from the full fleet.",
           "Wave 1 must add nothing, so use (state.wave - 1).",
           "Math.min(260, speed) is the short way to write the cap."],
    tests=[("A full fleet crawls",
            "const state = createGame();\nassert(fleetSpeed(state) === 22, 'gave ' + fleetSpeed(state));"),
           ("Shooting one speeds them up",
            "const state = createGame();\nstate.aliens[0].alive = false;\nassert(fleetSpeed(state) === 27, 'gave ' + fleetSpeed(state));"),
           ("The last alien is fast",
            "const state = createGame();\nfor (let i = 1; i < state.aliens.length; i++) { state.aliens[i].alive = false; }\nassert(fleetSpeed(state) > 100, 'gave ' + fleetSpeed(state) + ' — the last one should be sprinting');"),
           ("A later wave starts faster",
            "const a = createGame();\nconst b = createGame();\nb.wave = 4;\nassert(fleetSpeed(b) > fleetSpeed(a));"),
           ("It never goes above 260",
            "const state = createGame();\nstate.wave = 30;\nstate.aliens.forEach(a => { a.alive = false; });\nassert(fleetSpeed(state) === 260, 'gave ' + fleetSpeed(state));"),
           ("The speed only ever goes up as aliens die",
            "const state = createGame();\nlet last = fleetSpeed(state);\nfor (let i = 0; i < state.aliens.length; i++) {\n    state.aliens[i].alive = false;\n    const now = fleetSpeed(state);\n    assert(now >= last, 'shooting an alien must never slow the fleet down');\n    last = now;\n}")]),
  py=dict(starter="def fleet_speed(state):\n    # faster with every alien you shoot\n    pass\n",
    answer="def fleet_speed(state):\n    shot = ALIEN_COLUMNS * ALIEN_ROWS - aliens_left(state)\n    return min(260, 22 + shot * 5 + (state[\"wave\"] - 1) * 12)\n",
    hints=["aliens_left(state) is written for you - count backwards from the full fleet.",
           "Wave 1 must add nothing, so use (state['wave'] - 1).",
           "min(260, speed) is the cap."],
    tests=[("A full fleet crawls",
            "state = create_game()\nassert fleet_speed(state) == 22"),
           ("Shooting one speeds them up",
            "state = create_game()\nstate['aliens'][0]['alive'] = False\nassert fleet_speed(state) == 27"),
           ("The last alien is fast",
            "state = create_game()\nfor alien in state['aliens'][1:]:\n    alien['alive'] = False\nassert fleet_speed(state) > 100"),
           ("A later wave starts faster",
            "a = create_game()\nb = create_game()\nb['wave'] = 4\nassert fleet_speed(b) > fleet_speed(a)"),
           ("It never goes above 260",
            "state = create_game()\nstate['wave'] = 30\nfor alien in state['aliens']:\n    alien['alive'] = False\nassert fleet_speed(state) == 260"),
           ("The speed only ever goes up as aliens die",
            "state = create_game()\nlast = fleet_speed(state)\nfor alien in state['aliens']:\n    alien['alive'] = False\n    now = fleet_speed(state)\n    assert now >= last, 'shooting an alien must never slow the fleet down'\n    last = now")]),
  demo=dict(kind="march", caption="Press Shoot some and watch what happens to the marching speed.")),

step("move_fleet", "moveFleet", "move_fleet",
  "March!", "The fleet advances.",
  "<p>The whole fleet slides sideways together. When it touches a wall it turns round <em>and drops a row</em> — that drop is what eventually brings the aliens down onto you.</p>"
  "<p>One subtlety: measure the fleet by the aliens still <strong>alive</strong>. Shoot out the left-hand column and the fleet should be able to march further left, not keep bouncing off an invisible wall.</p>",
  "state, seconds", "nothing; it moves the fleet",
  ["Move fleetX by direction × fleet-speed × seconds.",
   "Ask fleet-edges where the living aliens now reach. If there are none, stop.",
   "If the right edge is past FIELD_WIDTH - 6 and we are going right: turn around and add FLEET_DROP to fleetY.",
   "If the left edge is before 6 and we are going left: turn around and drop."],
  js=dict(starter="function moveFleet(state, seconds) {\n    // slide sideways; at a wall, turn round AND drop\n}\n",
    answer="function moveFleet(state, seconds) {\n    state.fleetX = state.fleetX + state.fleetDirection * fleetSpeed(state) * seconds;\n\n    const edges = fleetEdges(state);\n    if (edges === null) {\n        return;\n    }\n    if (edges.right > FIELD_WIDTH - 6 && state.fleetDirection === 1) {\n        state.fleetDirection = -1;\n        state.fleetY = state.fleetY + FLEET_DROP;\n    } else if (edges.left < 6 && state.fleetDirection === -1) {\n        state.fleetDirection = 1;\n        state.fleetY = state.fleetY + FLEET_DROP;\n    }\n}\n",
    hints=["fleetEdges(state) is written for you — it only measures living aliens.",
           "Check the direction as well as the edge, or the fleet will get stuck flipping at the wall.",
           "Turning round and dropping always happen together."],
    tests=[("The fleet slides sideways",
            "const state = createGame();\nconst before = state.fleetX;\nmoveFleet(state, 0.5);\nassert(state.fleetX > before, 'it should have moved right');"),
           ("It turns round at the right-hand wall",
            "const state = createGame();\nstate.fleetX = FIELD_WIDTH - FLEET_WIDTH;\nstate.fleetDirection = 1;\nmoveFleet(state, 0.5);\nassert(state.fleetDirection === -1, 'it should be heading back');"),
           ("Turning round drops it a row",
            "const state = createGame();\nconst before = state.fleetY;\nstate.fleetX = FIELD_WIDTH - FLEET_WIDTH;\nstate.fleetDirection = 1;\nmoveFleet(state, 0.5);\nassert(state.fleetY === before + FLEET_DROP, 'y is ' + state.fleetY);"),
           ("It turns round at the left-hand wall too",
            "const state = createGame();\nstate.fleetX = 0;\nstate.fleetDirection = -1;\nmoveFleet(state, 0.5);\nassert(state.fleetDirection === 1);"),
           ("It does not flip twice at the same wall",
            "const state = createGame();\nstate.fleetX = FIELD_WIDTH - FLEET_WIDTH;\nstate.fleetDirection = 1;\nmoveFleet(state, 0.5);\nconst afterFirst = state.fleetY;\nmoveFleet(state, 0.01);\nassert(state.fleetY === afterFirst, 'it dropped twice at one wall — check the direction as well as the edge');"),
           ("Dead columns let the fleet go further",
            "const state = createGame();\nstate.aliens.forEach(a => { if (a.column >= 3) { a.alive = false; } });\nstate.fleetX = FIELD_WIDTH - FLEET_WIDTH;\nstate.fleetDirection = 1;\nmoveFleet(state, 0.1);\nassert(state.fleetDirection === 1, 'only half the fleet is left — there is plenty of room still');"),
           ("A whole game of marching never leaves the field",
            "const state = createGame();\nfor (let frame = 0; frame < 3000; frame++) {\n    moveFleet(state, 0.016);\n    const edges = fleetEdges(state);\n    assert(edges.left > -20 && edges.right < FIELD_WIDTH + 20, 'the fleet marched off the field at frame ' + frame);\n}")]),
  py=dict(starter="def move_fleet(state, seconds):\n    # slide sideways; at a wall, turn round AND drop\n    pass\n",
    answer="def move_fleet(state, seconds):\n    state[\"fleet_x\"] += state[\"fleet_direction\"] * fleet_speed(state) * seconds\n\n    edges = fleet_edges(state)\n    if edges is None:\n        return\n    if edges[\"right\"] > FIELD_WIDTH - 6 and state[\"fleet_direction\"] == 1:\n        state[\"fleet_direction\"] = -1\n        state[\"fleet_y\"] += FLEET_DROP\n    elif edges[\"left\"] < 6 and state[\"fleet_direction\"] == -1:\n        state[\"fleet_direction\"] = 1\n        state[\"fleet_y\"] += FLEET_DROP\n",
    hints=["fleet_edges(state) is written for you - it only measures living aliens.",
           "Check the direction as well as the edge, or the fleet gets stuck flipping.",
           "Turning round and dropping always happen together."],
    tests=[("The fleet slides sideways",
            "state = create_game()\nbefore = state['fleet_x']\nmove_fleet(state, 0.5)\nassert state['fleet_x'] > before"),
           ("It turns round at the right-hand wall",
            "state = create_game()\nstate['fleet_x'] = FIELD_WIDTH - FLEET_WIDTH\nstate['fleet_direction'] = 1\nmove_fleet(state, 0.5)\nassert state['fleet_direction'] == -1"),
           ("Turning round drops it a row",
            "state = create_game()\nbefore = state['fleet_y']\nstate['fleet_x'] = FIELD_WIDTH - FLEET_WIDTH\nstate['fleet_direction'] = 1\nmove_fleet(state, 0.5)\nassert state['fleet_y'] == before + FLEET_DROP"),
           ("It turns round at the left-hand wall too",
            "state = create_game()\nstate['fleet_x'] = 0\nstate['fleet_direction'] = -1\nmove_fleet(state, 0.5)\nassert state['fleet_direction'] == 1"),
           ("It does not flip twice at the same wall",
            "state = create_game()\nstate['fleet_x'] = FIELD_WIDTH - FLEET_WIDTH\nstate['fleet_direction'] = 1\nmove_fleet(state, 0.5)\nafter_first = state['fleet_y']\nmove_fleet(state, 0.01)\nassert state['fleet_y'] == after_first, 'it dropped twice at one wall'"),
           ("Dead columns let the fleet go further",
            "state = create_game()\nfor a in state['aliens']:\n    if a['column'] >= 3:\n        a['alive'] = False\nstate['fleet_x'] = FIELD_WIDTH - FLEET_WIDTH\nstate['fleet_direction'] = 1\nmove_fleet(state, 0.1)\nassert state['fleet_direction'] == 1"),
           ("A whole game of marching never leaves the field",
            "state = create_game()\nfor frame in range(3000):\n    move_fleet(state, 0.016)\n    edges = fleet_edges(state)\n    assert -20 < edges['left'] and edges['right'] < FIELD_WIDTH + 20, f'off the field at frame {frame}'")]),
  demo=dict(kind="march", caption="The fleet marches by itself. Shoot some columns out and watch it use the extra room."),
  warning="Check the DIRECTION as well as the edge. Without that the fleet flips back and forth at the wall, dropping a row every frame, and the game is over in a second."),

step("fire_bullet", "fireBullet", "fire_bullet",
  "Shoot back", "You can fight.",
  "<p>The famous rule of Space Invaders: <strong>one bullet at a time</strong>. You cannot fire again until your shot has hit something or left the screen.</p>"
  "<p>That one restriction is the entire game. Take it away and you would just hold the fire button down and win. With it, every shot is a decision.</p>",
  "state", "True if a shot was fired",
  ["Refuse if the game is over, paused, or a bullet is already in the air.",
   "Add a bullet just above the middle of the ship.",
   "Count the shot, and return True."],
  js=dict(starter="function fireBullet(state) {\n    // only one bullet in the air at a time!\n}\n",
    answer="function fireBullet(state) {\n    if (state.isOver || state.isPaused || state.bullets.length > 0) {\n        return false;\n    }\n    state.bullets.push({\n        x: state.shipX + SHIP_WIDTH / 2 - BULLET_WIDTH / 2,\n        y: SHIP_Y - BULLET_HEIGHT\n    });\n    state.shots = state.shots + 1;\n    return true;\n}\n",
    hints=["state.bullets.length > 0 means a shot is already flying.",
           "The middle of the ship is shipX + SHIP_WIDTH / 2.",
           "Start the bullet just ABOVE the ship: SHIP_Y - BULLET_HEIGHT."],
    tests=[("Firing puts a bullet in the air",
            "const state = createGame();\nassert(fireBullet(state) === true);\nassert(state.bullets.length === 1);"),
           ("You cannot fire twice at once",
            "const state = createGame();\nfireBullet(state);\nassert(fireBullet(state) === false, 'one bullet at a time is the whole game');\nassert(state.bullets.length === 1);"),
           ("Once the shot has gone you may fire again",
            "const state = createGame();\nfireBullet(state);\nstate.bullets = [];\nassert(fireBullet(state) === true);"),
           ("The bullet starts at the middle of the ship",
            "const state = createGame();\nstate.shipX = 100;\nfireBullet(state);\nconst middle = state.bullets[0].x + BULLET_WIDTH / 2;\nassert(Math.abs(middle - (100 + SHIP_WIDTH / 2)) < 0.001, 'the shot came out at ' + middle);"),
           ("The bullet starts above the ship, not inside it",
            "const state = createGame();\nfireBullet(state);\nassert(state.bullets[0].y + BULLET_HEIGHT <= SHIP_Y);"),
           ("Shots are counted",
            "const state = createGame();\nfireBullet(state);\nstate.bullets = [];\nfireBullet(state);\nassert(state.shots === 2, 'shots is ' + state.shots);"),
           ("A finished game cannot fire",
            "const state = createGame();\nstate.isOver = true;\nassert(fireBullet(state) === false);")]),
  py=dict(starter="def fire_bullet(state):\n    # only one bullet in the air at a time!\n    pass\n",
    answer="def fire_bullet(state):\n    if state[\"is_over\"] or state[\"is_paused\"] or state[\"bullets\"]:\n        return False\n    state[\"bullets\"].append({\n        \"x\": state[\"ship_x\"] + SHIP_WIDTH / 2 - BULLET_WIDTH / 2,\n        \"y\": SHIP_Y - BULLET_HEIGHT,\n    })\n    state[\"shots\"] += 1\n    return True\n",
    hints=["An empty list is False in Python, so `or state['bullets']` reads nicely.",
           "The middle of the ship is ship_x + SHIP_WIDTH / 2.",
           "Start the bullet just ABOVE the ship: SHIP_Y - BULLET_HEIGHT."],
    tests=[("Firing puts a bullet in the air",
            "state = create_game()\nassert fire_bullet(state) is True\nassert len(state['bullets']) == 1"),
           ("You cannot fire twice at once",
            "state = create_game()\nfire_bullet(state)\nassert fire_bullet(state) is False\nassert len(state['bullets']) == 1"),
           ("Once the shot has gone you may fire again",
            "state = create_game()\nfire_bullet(state)\nstate['bullets'] = []\nassert fire_bullet(state) is True"),
           ("The bullet starts at the middle of the ship",
            "state = create_game()\nstate['ship_x'] = 100\nfire_bullet(state)\nmiddle = state['bullets'][0]['x'] + BULLET_WIDTH / 2\nassert abs(middle - (100 + SHIP_WIDTH / 2)) < 0.001"),
           ("The bullet starts above the ship, not inside it",
            "state = create_game()\nfire_bullet(state)\nassert state['bullets'][0]['y'] + BULLET_HEIGHT <= SHIP_Y"),
           ("Shots are counted",
            "state = create_game()\nfire_bullet(state)\nstate['bullets'] = []\nfire_bullet(state)\nassert state['shots'] == 2"),
           ("A finished game cannot fire",
            "state = create_game()\nstate['is_over'] = True\nassert fire_bullet(state) is False")]),
  demo=dict(kind="shoot", caption="Move and fire. Notice you cannot shoot again until the last shot has gone.")),

step("move_bullets", "moveBullets", "move_bullets",
  "Move the shots", "Bullets fly.",
  "<p>The same function moves your bullets <em>and</em> the aliens' bombs — the only difference is which way you tell it to go. Pass a negative distance and things fly up; pass a positive one and they fall.</p>"
  "<p>One function, two jobs. That is what well-chosen inputs buy you.</p>",
  "bullets — the list. distance — how far to move them (negative is up).",
  "a NEW list, without the shots that have left the field",
  ["Make an empty list for the answer.",
   "For each shot, make a copy whose y has moved by distance.",
   "Keep it only if it is still on the field: its bottom is below 0 and its top is above FIELD_HEIGHT.",
   "Return the new list."],
  js=dict(starter="function moveBullets(bullets, distance) {\n    // move them, and forget the ones that have left\n}\n",
    answer="function moveBullets(bullets, distance) {\n    const moved = [];\n    for (let i = 0; i < bullets.length; i++) {\n        const bullet = { x: bullets[i].x, y: bullets[i].y + distance };\n        if (bullet.y + BULLET_HEIGHT > 0 && bullet.y < FIELD_HEIGHT) {\n            moved.push(bullet);\n        }\n    }\n    return moved;\n}\n",
    hints=["Make a copy of each bullet rather than editing the old one.",
           "A shot has gone off the top when y + BULLET_HEIGHT is no longer above 0.",
           "The same test, the other way round, catches the ones off the bottom."],
    tests=[("A negative distance sends shots up",
            "const moved = moveBullets([{ x: 10, y: 200 }], -50);\nassert(moved[0].y === 150, 'y is ' + moved[0].y);"),
           ("A positive distance sends them down",
            "const moved = moveBullets([{ x: 10, y: 200 }], 50);\nassert(moved[0].y === 250);"),
           ("Shots off the top are forgotten",
            "const moved = moveBullets([{ x: 10, y: 5 }], -50);\nassert(moved.length === 0, 'that one has left the screen');"),
           ("Shots off the bottom are forgotten too",
            "const moved = moveBullets([{ x: 10, y: FIELD_HEIGHT - 2 }], 50);\nassert(moved.length === 0);"),
           ("A shot still on screen is kept",
            "const moved = moveBullets([{ x: 10, y: 200 }], -50);\nassert(moved.length === 1);"),
           ("The x never changes",
            "const moved = moveBullets([{ x: 137, y: 200 }], -50);\nassert(moved[0].x === 137, 'bullets go straight up and down');"),
           ("Several shots all move",
            "const moved = moveBullets([{ x: 1, y: 100 }, { x: 2, y: 200 }], -10);\nassert(moved.length === 2 && moved[0].y === 90 && moved[1].y === 190);"),
           ("The list you were given is left alone",
            "const before = [{ x: 10, y: 200 }];\nmoveBullets(before, -50);\nassert(before[0].y === 200, 'make copies — do not edit the list you were handed');")]),
  py=dict(starter="def move_bullets(bullets, distance):\n    # move them, and forget the ones that have left\n    pass\n",
    answer="def move_bullets(bullets, distance):\n    moved = []\n    for bullet in bullets:\n        shifted = {\"x\": bullet[\"x\"], \"y\": bullet[\"y\"] + distance}\n        if shifted[\"y\"] + BULLET_HEIGHT > 0 and shifted[\"y\"] < FIELD_HEIGHT:\n            moved.append(shifted)\n    return moved\n",
    hints=["Make a copy of each bullet rather than editing the old one.",
           "A shot has gone off the top when y + BULLET_HEIGHT is no longer above 0.",
           "The same test, the other way round, catches the ones off the bottom."],
    tests=[("A negative distance sends shots up",
            "moved = move_bullets([{'x': 10, 'y': 200}], -50)\nassert moved[0]['y'] == 150"),
           ("A positive distance sends them down",
            "moved = move_bullets([{'x': 10, 'y': 200}], 50)\nassert moved[0]['y'] == 250"),
           ("Shots off the top are forgotten",
            "assert move_bullets([{'x': 10, 'y': 5}], -50) == []"),
           ("Shots off the bottom are forgotten too",
            "assert move_bullets([{'x': 10, 'y': FIELD_HEIGHT - 2}], 50) == []"),
           ("A shot still on screen is kept",
            "assert len(move_bullets([{'x': 10, 'y': 200}], -50)) == 1"),
           ("The x never changes",
            "moved = move_bullets([{'x': 137, 'y': 200}], -50)\nassert moved[0]['x'] == 137"),
           ("Several shots all move",
            "moved = move_bullets([{'x': 1, 'y': 100}, {'x': 2, 'y': 200}], -10)\nassert len(moved) == 2 and moved[0]['y'] == 90 and moved[1]['y'] == 190"),
           ("The list you were given is left alone",
            "before = [{'x': 10, 'y': 200}]\nmove_bullets(before, -50)\nassert before[0]['y'] == 200, 'make copies'")]),
  demo=dict(kind="shoot", caption="Fire away — the shots fly up and vanish off the top.")),

step("hit_aliens", "hitAliens", "hit_aliens",
  "Shoot them down", "The whole game works!",
  "<p>The moment the game has been building to. Every bullet is checked against every alien; the first one it touches dies, the bullet disappears, and the score goes up.</p>"
  "<p>Two details make this feel right. A bullet may only kill <em>one</em> alien — stop looking after the first. And the bullet must be removed, or it would keep flying and mow down the whole column.</p>",
  "state", "how many aliens were shot this frame",
  ["Start a count at 0 and an empty list of surviving bullets.",
   "For each bullet, look through the aliens for the first LIVING one it overlaps.",
   "If it finds one: kill the alien, add score-for-row points, count the hit, and stop looking.",
   "If it hit nothing, keep the bullet.",
   "Put the surviving bullets back into the state and return the count."],
  js=dict(starter="function hitAliens(state) {\n    // every bullet against every alien — one kill each\n}\n",
    answer="function hitAliens(state) {\n    let hits = 0;\n    const survivors = [];\n\n    for (let b = 0; b < state.bullets.length; b++) {\n        const bullet = state.bullets[b];\n        let hitSomething = false;\n\n        for (let a = 0; a < state.aliens.length; a++) {\n            const alien = state.aliens[a];\n            if (alien.alive && overlaps(bulletRect(bullet), alienRect(alien, state))) {\n                alien.alive = false;\n                state.score = state.score + scoreForRow(alien.row);\n                hits = hits + 1;\n                hitSomething = true;\n                break;\n            }\n        }\n\n        if (!hitSomething) {\n            survivors.push(bullet);\n        }\n    }\n\n    state.bullets = survivors;\n    return hits;\n}\n",
    hints=["Two loops: bullets on the outside, aliens on the inside.",
           "break; stops the inner loop as soon as one alien has been hit.",
           "Only keep a bullet if it hit nothing at all."],
    tests=[("A bullet on an alien kills it",
            "const state = createGame();\nconst rect = alienRect(state.aliens[7], state);\nstate.bullets = [{ x: rect.x + 10, y: rect.y + 5 }];\nassert(hitAliens(state) === 1);\nassert(state.aliens[7].alive === false);"),
           ("The bullet is used up",
            "const state = createGame();\nconst rect = alienRect(state.aliens[7], state);\nstate.bullets = [{ x: rect.x + 10, y: rect.y + 5 }];\nhitAliens(state);\nassert(state.bullets.length === 0, 'the bullet has to disappear, or it will mow down the whole column');"),
           ("A hit scores",
            "const state = createGame();\nconst alien = state.aliens[0];\nconst rect = alienRect(alien, state);\nstate.bullets = [{ x: rect.x + 10, y: rect.y + 5 }];\nhitAliens(state);\nassert(state.score === scoreForRow(alien.row), 'score is ' + state.score);"),
           ("A bullet in empty space hits nothing",
            "const state = createGame();\nstate.bullets = [{ x: 10, y: 300 }];\nassert(hitAliens(state) === 0);\nassert(state.bullets.length === 1, 'that bullet is still flying');"),
           ("A dead alien cannot be shot again",
            "const state = createGame();\nconst rect = alienRect(state.aliens[7], state);\nstate.aliens[7].alive = false;\nstate.bullets = [{ x: rect.x + 10, y: rect.y + 5 }];\nassert(hitAliens(state) === 0);"),
           ("One bullet kills one alien, not two",
            "const state = createGame();\nconst rect = alienRect(state.aliens[0], state);\nstate.bullets = [{ x: rect.x + 10, y: rect.y + 5 }];\nhitAliens(state);\nassert(aliensLeft(state) === ALIEN_COLUMNS * ALIEN_ROWS - 1, 'exactly one alien should be gone');"),
           ("The back row is worth more than the front",
            "assert(scoreForRow(0) > scoreForRow(ALIEN_ROWS - 1));")]),
  py=dict(starter="def hit_aliens(state):\n    # every bullet against every alien - one kill each\n    pass\n",
    answer="def hit_aliens(state):\n    hits = 0\n    survivors = []\n\n    for bullet in state[\"bullets\"]:\n        hit_something = False\n        for alien in state[\"aliens\"]:\n            if alien[\"alive\"] and overlaps(bullet_rect(bullet), alien_rect(alien, state)):\n                alien[\"alive\"] = False\n                state[\"score\"] += score_for_row(alien[\"row\"])\n                hits += 1\n                hit_something = True\n                break\n        if not hit_something:\n            survivors.append(bullet)\n\n    state[\"bullets\"] = survivors\n    return hits\n",
    hints=["Two loops: bullets on the outside, aliens on the inside.",
           "break stops the inner loop as soon as one alien has been hit.",
           "Only keep a bullet if it hit nothing at all."],
    tests=[("A bullet on an alien kills it",
            "state = create_game()\nrect = alien_rect(state['aliens'][7], state)\nstate['bullets'] = [{'x': rect['x'] + 10, 'y': rect['y'] + 5}]\nassert hit_aliens(state) == 1\nassert state['aliens'][7]['alive'] is False"),
           ("The bullet is used up",
            "state = create_game()\nrect = alien_rect(state['aliens'][7], state)\nstate['bullets'] = [{'x': rect['x'] + 10, 'y': rect['y'] + 5}]\nhit_aliens(state)\nassert state['bullets'] == []"),
           ("A hit scores",
            "state = create_game()\nalien = state['aliens'][0]\nrect = alien_rect(alien, state)\nstate['bullets'] = [{'x': rect['x'] + 10, 'y': rect['y'] + 5}]\nhit_aliens(state)\nassert state['score'] == score_for_row(alien['row'])"),
           ("A bullet in empty space hits nothing",
            "state = create_game()\nstate['bullets'] = [{'x': 10, 'y': 300}]\nassert hit_aliens(state) == 0\nassert len(state['bullets']) == 1"),
           ("A dead alien cannot be shot again",
            "state = create_game()\nrect = alien_rect(state['aliens'][7], state)\nstate['aliens'][7]['alive'] = False\nstate['bullets'] = [{'x': rect['x'] + 10, 'y': rect['y'] + 5}]\nassert hit_aliens(state) == 0"),
           ("One bullet kills one alien, not two",
            "state = create_game()\nrect = alien_rect(state['aliens'][0], state)\nstate['bullets'] = [{'x': rect['x'] + 10, 'y': rect['y'] + 5}]\nhit_aliens(state)\nassert aliens_left(state) == ALIEN_COLUMNS * ALIEN_ROWS - 1"),
           ("The back row is worth more than the front",
            "assert score_for_row(0) > score_for_row(ALIEN_ROWS - 1)")]),
  demo=dict(kind="game", flags=dict(robot=True), caption="A robot gunner clears the fleet — every function you have written is running here."),
  warning="Remove the bullet when it hits. Leave it in and one shot will wipe out an entire column on its way up."),

step("action_for_key", "actionForKey", "action_for_key",
  "Take command", "The game is yours.",
  "<p>The last function: two directions and a fire button.</p>"
  "<p>The arrows are held down to steer, but firing happens once per press — the page handles that difference. All this function has to do is name the action.</p>",
  "key", "an action name, or nothing at all",
  ["Left or A → 'left'. Right or D → 'right'.",
   "Space, up or W → 'fire'.", "P → 'pause'. R → 'restart'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // steer, fire, pause, restart\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'arrowup' || k === 'w') { return 'fire'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["The space bar's key is a single space: ' '.",
           "Both space and the up arrow should fire — players expect either.",
           "Five ifs and a return null;"],
    tests=[("The arrows steer",
            "assert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("A and D steer too",
            "assert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("Space fires", "assert(actionForKey(' ') === 'fire');"),
           ("The up arrow fires too", "assert(actionForKey('ArrowUp') === 'fire');"),
           ("Capital letters work",
            "assert(actionForKey('A') === 'left');\nassert(actionForKey('R') === 'restart');"),
           ("P pauses and R restarts",
            "assert(actionForKey('p') === 'pause');\nassert(actionForKey('r') === 'restart');"),
           ("Other keys do nothing",
            "assert(actionForKey('z') === null);\nassert(actionForKey('ArrowDown') === null, 'there is nowhere to go downwards');")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowleft\": \"left\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"fire\", \"spacebar\": \"fire\", \"arrowup\": \"fire\", \"w\": \"fire\",\n        \"p\": \"pause\", \"r\": \"restart\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["A dictionary is tidier than five ifs.",
           "keys.get(...) gives None for anything not listed.",
           "Remember \" \" for the space bar."],
    tests=[("The arrows steer",
            "assert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("A and D steer too",
            "assert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("Space fires", "assert action_for_key(' ') == 'fire'"),
           ("The up arrow fires too", "assert action_for_key('ArrowUp') == 'fire'"),
           ("Capital letters work",
            "assert action_for_key('A') == 'left'\nassert action_for_key('R') == 'restart'"),
           ("P pauses and R restarts",
            "assert action_for_key('p') == 'pause'\nassert action_for_key('r') == 'restart'"),
           ("Other keys do nothing",
            "assert action_for_key('z') is None\nassert action_for_key('ArrowDown') is None")]),
  demo=dict(kind="final", caption="Click the page, then defend the Earth with the arrow keys and space.")),
]

write_workshop("invaders", "Space Invaders", STEPS)
