"""The seven steps of "Build Lights Out", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("light_index", "lightIndex", "light_index",
  "Number the squares", "The board has places to put lights.",
  "<p>Twenty-five lights sit in a 5 x 5 grid, but they are stored as one flat <strong>list</strong> of 25 true/false values. So the game needs to turn \"column 2, row 1\" into \"light number 7\".</p>"
  "<pre class=\"mini-code\"> 0  1  2  3  4\n 5  6  7  8  9\n10 11 12 13 14\n15 16 17 18 19\n20 21 22 23 24</pre>",
  "column, row - each 0 to GRID_SIZE - 1",
  "the position of that light in the flat list of 25",
  ["Skip a whole row of lights for every row above this one: row * GRID_SIZE.",
   "Add the column.", "Return the answer."],
  js=dict(
    starter="function lightIndex(column, row) {\n    // skip whole rows, then add the column\n}\n",
    answer="function lightIndex(column, row) {\n    return row * GRID_SIZE + column;\n}\n",
    hints=["One line.", "Skipping `row` rows means skipping row * GRID_SIZE lights.",
           "return row * GRID_SIZE + column;"],
    tests=[("The first light is number 0", "assert(lightIndex(0, 0) === 0, 'gave ' + lightIndex(0, 0));"),
           ("Column 2 of row 1 is number 7", "assert(lightIndex(2, 1) === 7, 'gave ' + lightIndex(2, 1) + ', expected 7');"),
           ("The last light is number 24", "assert(lightIndex(4, 4) === 24, 'gave ' + lightIndex(4, 4));"),
           ("One step down adds a whole row", "assert(lightIndex(1, 3) - lightIndex(1, 2) === GRID_SIZE);"),
           ("All 25 squares get different numbers",
            "const seen = {};\nfor (let r = 0; r < GRID_SIZE; r++) { for (let c = 0; c < GRID_SIZE; c++) { seen[lightIndex(c, r)] = true; } }\nassert(Object.keys(seen).length === 25, 'only ' + Object.keys(seen).length + ' different numbers');")]),
  py=dict(
    starter="def light_index(column, row):\n    # skip whole rows, then add the column\n    pass\n",
    answer="def light_index(column, row):\n    return row * GRID_SIZE + column\n",
    hints=["One line.", "Skipping `row` rows means skipping row * GRID_SIZE lights.",
           "return row * GRID_SIZE + column"],
    tests=[("The first light is number 0", "got = light_index(0, 0)\nassert got == 0, f'gave {got}'"),
           ("Column 2 of row 1 is number 7", "got = light_index(2, 1)\nassert got == 7, f'gave {got}, expected 7'"),
           ("The last light is number 24", "assert light_index(4, 4) == 24"),
           ("One step down adds a whole row", "assert light_index(1, 3) - light_index(1, 2) == GRID_SIZE"),
           ("All 25 squares get different numbers",
            "seen = {light_index(c, r) for r in range(GRID_SIZE) for c in range(GRID_SIZE)}\nassert len(seen) == 25, f'only {len(seen)} different numbers'")]),
  demo=dict(kind="grid", caption="Your function numbers every square on the board.")),

step("is_on_board", "isOnBoard", "is_on_board",
  "Stay on the board", "The game knows where the edges are.",
  "<p>A light in the middle has four neighbours, but a corner light has only two. Before the game touches a square it has to ask whether that square exists at all.</p>",
  "column, row",
  "True if both are between 0 and GRID_SIZE - 1",
  ["column must be 0 or more, and less than GRID_SIZE.",
   "row must be the same.", "Return True only when both are."],
  js=dict(
    starter="function isOnBoard(column, row) {\n    // four checks joined with &&\n}\n",
    answer="function isOnBoard(column, row) {\n    return column >= 0 && column < GRID_SIZE && row >= 0 && row < GRID_SIZE;\n}\n",
    hints=["Join the checks with &&.", "The last column is GRID_SIZE - 1, so use < and not <=.",
           "return column >= 0 && column < GRID_SIZE && row >= 0 && row < GRID_SIZE;"],
    tests=[("The middle is on the board", "assert(isOnBoard(2, 2) === true);"),
           ("Every corner is on the board", "assert(isOnBoard(0, 0) && isOnBoard(4, 0) && isOnBoard(0, 4) && isOnBoard(4, 4));"),
           ("One step left of the board is off it", "assert(isOnBoard(-1, 2) === false, 'gave ' + isOnBoard(-1, 2));"),
           ("One step right of the board is off it", "assert(isOnBoard(5, 2) === false, 'column 4 is the last one INSIDE');"),
           ("Above the top and below the bottom are off it", "assert(isOnBoard(2, -1) === false && isOnBoard(2, 5) === false);")]),
  py=dict(
    starter="def is_on_board(column, row):\n    # two chained comparisons joined with and\n    pass\n",
    answer="def is_on_board(column, row):\n    return 0 <= column < GRID_SIZE and 0 <= row < GRID_SIZE\n",
    hints=["Python can chain comparisons: 0 <= column < GRID_SIZE.",
           "Join the two halves with `and`.",
           "return 0 <= column < GRID_SIZE and 0 <= row < GRID_SIZE"],
    tests=[("The middle is on the board", "assert is_on_board(2, 2) is True"),
           ("Every corner is on the board", "assert all(is_on_board(c, r) for c, r in [(0,0),(4,0),(0,4),(4,4)])"),
           ("One step left of the board is off it", "assert is_on_board(-1, 2) is False"),
           ("One step right of the board is off it", "assert is_on_board(5, 2) is False, 'column 4 is the last one INSIDE'"),
           ("Above the top and below the bottom are off it", "assert is_on_board(2, -1) is False and is_on_board(2, 5) is False")]),
  demo=dict(kind="cross", caption="Move the cursor into a corner — the cross gets smaller at the edges.")),

step("neighbours", "neighbours", "neighbours",
  "Find the cross", "Pressing a light knows what it touches.",
  "<p>Pressing a square flips <strong>five</strong> lights: the one you pressed, and the four around it. At the edges some of those five do not exist, so the list is shorter.</p>"
  "<pre class=\"mini-code\">    .  #  .\n    #  #  #        pressing the middle\n    .  #  .        flips this cross</pre>",
  "column, row - the square that was pressed",
  "a list of the squares to flip: the square itself, plus the up, down, left and right neighbours that are still on the board",
  ["Write down the five steps: no step at all, then up, down, left and right.",
   "For each step, work out the square it lands on.",
   "Keep it only if is-on-board says it exists.",
   "Return the list of squares."],
  js=dict(
    starter="function neighbours(column, row) {\n    const steps = [[0, 0], [0, -1], [0, 1], [-1, 0], [1, 0]];\n    // keep the steps that stay on the board\n}\n",
    answer="function neighbours(column, row) {\n    const steps = [[0, 0], [0, -1], [0, 1], [-1, 0], [1, 0]];\n    const found = [];\n    steps.forEach(function (step) {\n        const c = column + step[0];\n        const r = row + step[1];\n        if (isOnBoard(c, r)) {\n            found.push([c, r]);\n        }\n    });\n    return found;\n}\n",
    hints=["Loop over the five steps.", "Add the step to the column and row, then check isOnBoard.",
           "Push [c, r] — a little array holding the column and the row."],
    tests=[("The middle of the board flips five lights",
            "assert(neighbours(2, 2).length === 5, 'gave ' + neighbours(2, 2).length + ' squares');"),
           ("A corner flips only three",
            "assert(neighbours(0, 0).length === 3, 'a corner has two neighbours plus itself, so 3 — gave ' + neighbours(0, 0).length);"),
           ("An edge flips four",
            "assert(neighbours(2, 0).length === 4, 'gave ' + neighbours(2, 0).length);"),
           ("The pressed square is always included",
            "const found = neighbours(3, 1).map(s => s.join(','));\nassert(found.indexOf('3,1') !== -1, 'the square you pressed must be in the list');"),
           ("Every square it returns is on the board",
            "for (let r = 0; r < GRID_SIZE; r++) { for (let c = 0; c < GRID_SIZE; c++) {\n    neighbours(c, r).forEach(s => assert(isOnBoard(s[0], s[1]), 'returned ' + s + ' which is off the board'));\n} }"),
           ("It returns the four true neighbours of the middle",
            "const found = neighbours(2, 2).map(s => s.join(',')).sort().join(' ');\nassert(found === '1,2 2,1 2,2 2,3 3,2', 'gave ' + found);")]),
  py=dict(
    starter="def neighbours(column, row):\n    steps = [(0, 0), (0, -1), (0, 1), (-1, 0), (1, 0)]\n    # keep the steps that stay on the board\n    pass\n",
    answer="def neighbours(column, row):\n    steps = [(0, 0), (0, -1), (0, 1), (-1, 0), (1, 0)]\n    return [(column + dx, row + dy) for dx, dy in steps if is_on_board(column + dx, row + dy)]\n",
    hints=["`for dx, dy in steps` unpacks each step into two names.",
           "A list comprehension can end with an `if`.",
           "Build (column + dx, row + dy) and keep it when is_on_board says yes."],
    tests=[("The middle of the board flips five lights",
            "got = neighbours(2, 2)\nassert len(got) == 5, f'gave {len(got)} squares'"),
           ("A corner flips only three",
            "got = neighbours(0, 0)\nassert len(got) == 3, f'a corner has two neighbours plus itself - gave {len(got)}'"),
           ("An edge flips four", "assert len(neighbours(2, 0)) == 4"),
           ("The pressed square is always included",
            "assert (3, 1) in neighbours(3, 1), 'the square you pressed must be in the list'"),
           ("Every square it returns is on the board",
            "for r in range(GRID_SIZE):\n    for c in range(GRID_SIZE):\n        for square in neighbours(c, r):\n            assert is_on_board(square[0], square[1]), f'returned {square}, which is off the board'"),
           ("It returns the four true neighbours of the middle",
            "assert sorted(neighbours(2, 2)) == [(1, 2), (2, 1), (2, 2), (2, 3), (3, 2)], f'gave {sorted(neighbours(2, 2))}'")]),
  demo=dict(kind="cross", caption="The lit cross IS your function's answer. Move it to an edge and watch it shrink.")),

step("press_light", "pressLight", "press_light",
  "Flip the cross", "Pressing a square changes the board.",
  "<p>Now put the two together: press a square, and every light in its cross swaps over — on becomes off and off becomes on.</p>"
  "<p>Notice something lovely about this game: pressing the same square twice puts everything back. Every move is its own undo.</p>",
  "lights - the list of 25 values. column, row - the square pressed.",
  "a NEW list with those lights flipped",
  ["Copy the list.",
   "For every square in the cross, work out its index and flip the value there.",
   "Return the copy."],
  js=dict(
    starter="function pressLight(lights, column, row) {\n    const changed = lights.slice();\n    // flip every light in the cross\n}\n",
    answer="function pressLight(lights, column, row) {\n    const changed = lights.slice();\n    neighbours(column, row).forEach(function (square) {\n        const index = lightIndex(square[0], square[1]);\n        changed[index] = !changed[index];\n    });\n    return changed;\n}\n",
    hints=["lights.slice() gives you a copy to work on.",
           "neighbours(column, row) gives the squares; lightIndex turns each into a place in the list.",
           "!value flips true to false and false to true."],
    tests=[("Pressing the middle flips five lights",
            "const before = new Array(LIGHT_COUNT).fill(false);\nconst after = pressLight(before, 2, 2);\nassert(after.filter(v => v).length === 5, 'gave ' + after.filter(v => v).length + ' lights on');"),
           ("Pressing a corner flips three",
            "const after = pressLight(new Array(LIGHT_COUNT).fill(false), 0, 0);\nassert(after.filter(v => v).length === 3, 'gave ' + after.filter(v => v).length);"),
           ("It flips the right squares",
            "const after = pressLight(new Array(LIGHT_COUNT).fill(false), 2, 2);\n[[2,2],[2,1],[2,3],[1,2],[3,2]].forEach(s => assert(after[lightIndex(s[0], s[1])] === true, 'square ' + s + ' should be on'));"),
           ("Pressing twice puts everything back",
            "const before = new Array(LIGHT_COUNT).fill(false);\nbefore[7] = true;\nconst twice = pressLight(pressLight(before, 1, 1), 1, 1);\nassert(JSON.stringify(twice) === JSON.stringify(before), 'pressing the same square twice must undo itself');"),
           ("Lights already on are turned off",
            "const before = new Array(LIGHT_COUNT).fill(true);\nconst after = pressLight(before, 2, 2);\nassert(after[lightIndex(2, 2)] === false, 'a lit square should go out');"),
           ("The list you were given is not changed",
            "const before = new Array(LIGHT_COUNT).fill(false);\npressLight(before, 2, 2);\nassert(before.every(v => v === false), 'you changed the list you were given instead of a copy');")]),
  py=dict(
    starter="def press_light(lights, column, row):\n    changed = list(lights)\n    # flip every light in the cross\n    pass\n",
    answer="def press_light(lights, column, row):\n    changed = list(lights)\n    for c, r in neighbours(column, row):\n        index = light_index(c, r)\n        changed[index] = not changed[index]\n    return changed\n",
    hints=["list(lights) gives you a copy to work on.",
           "`for c, r in neighbours(column, row)` unpacks each square.",
           "`not value` flips True to False and False to True."],
    tests=[("Pressing the middle flips five lights",
            "after = press_light([False] * LIGHT_COUNT, 2, 2)\nassert sum(after) == 5, f'gave {sum(after)} lights on'"),
           ("Pressing a corner flips three",
            "after = press_light([False] * LIGHT_COUNT, 0, 0)\nassert sum(after) == 3, f'gave {sum(after)}'"),
           ("It flips the right squares",
            "after = press_light([False] * LIGHT_COUNT, 2, 2)\nfor c, r in [(2,2),(2,1),(2,3),(1,2),(3,2)]:\n    assert after[light_index(c, r)] is True, f'square {(c, r)} should be on'"),
           ("Pressing twice puts everything back",
            "before = [False] * LIGHT_COUNT\nbefore[7] = True\nassert press_light(press_light(before, 1, 1), 1, 1) == before, 'pressing twice must undo itself'"),
           ("Lights already on are turned off",
            "after = press_light([True] * LIGHT_COUNT, 2, 2)\nassert after[light_index(2, 2)] is False"),
           ("The list you were given is not changed",
            "before = [False] * LIGHT_COUNT\npress_light(before, 2, 2)\nassert not any(before), 'you changed the list you were given instead of a copy'")]),
  demo=dict(kind="game", caption="Press squares and watch the crosses flip. (Nothing checks for a win yet.)")),

step("is_solved", "isSolved", "is_solved",
  "Have you won?", "Turning every light off wins the game.",
  "<p>The puzzle is solved when not one light is left on.</p>",
  "lights - the list of 25 values",
  "True if every one is off",
  ["Look at every light.", "A single one still on means not solved.",
   "If you get through them all, it is solved."],
  js=dict(
    starter="function isSolved(lights) {\n    // is every light off?\n}\n",
    answer="function isSolved(lights) {\n    for (let i = 0; i < lights.length; i++) {\n        if (lights[i]) {\n            return false;\n        }\n    }\n    return true;\n}\n",
    hints=["A for loop that returns false the moment it finds a lit one.",
           "return true; goes AFTER the loop.",
           "lights.every(light => !light) does the same in one line."],
    tests=[("A dark board is solved",
            "assert(isSolved(new Array(LIGHT_COUNT).fill(false)) === true);"),
           ("A board with one light on is not",
            "const lights = new Array(LIGHT_COUNT).fill(false);\nlights[12] = true;\nassert(isSolved(lights) === false, 'light 12 is still on');"),
           ("A fully lit board is not solved",
            "assert(isSolved(new Array(LIGHT_COUNT).fill(true)) === false);"),
           ("The very last light counts too",
            "const lights = new Array(LIGHT_COUNT).fill(false);\nlights[LIGHT_COUNT - 1] = true;\nassert(isSolved(lights) === false, 'do not stop looking before the end');")]),
  py=dict(
    starter="def is_solved(lights):\n    # is every light off?\n    pass\n",
    answer="def is_solved(lights):\n    return not any(lights)\n",
    hints=["any(lights) is True when at least one light is on.",
           "So the puzzle is solved when NOT any of them are on.",
           "return not any(lights)"],
    tests=[("A dark board is solved", "assert is_solved([False] * LIGHT_COUNT) is True"),
           ("A board with one light on is not",
            "lights = [False] * LIGHT_COUNT\nlights[12] = True\nassert is_solved(lights) is False"),
           ("A fully lit board is not solved", "assert is_solved([True] * LIGHT_COUNT) is False"),
           ("The very last light counts too",
            "lights = [False] * LIGHT_COUNT\nlights[-1] = True\nassert is_solved(lights) is False, 'do not stop looking before the end'")]),
  demo=dict(kind="game", caption="Turn every light off and your function ends the game.")),

step("create_puzzle", "createPuzzle", "create_puzzle",
  "Scramble a puzzle", "Every new game is solvable.",
  "<p>Here is the clever bit. You could turn random lights on to make a puzzle — but then some puzzles would be <strong>impossible</strong>, because not every pattern of lights can be switched off.</p>"
  "<p>Instead, start with the board already solved and press random squares. Since pressing is its own undo, whatever you press can always be pressed back. Every puzzle built this way can be solved.</p>",
  "presses - how many random presses to scramble with",
  "a list of 25 lights",
  ["Start with a list of LIGHT_COUNT lights, all off.",
   "Repeat `presses` times: pick a random column and row, and press there.",
   "Return the scrambled lights."],
  js=dict(
    starter="function createPuzzle(presses) {\n    // start dark, then press random squares\n}\n",
    answer="function createPuzzle(presses) {\n    let lights = [];\n    for (let i = 0; i < LIGHT_COUNT; i++) {\n        lights.push(false);\n    }\n    for (let press = 0; press < presses; press++) {\n        const column = Math.floor(Math.random() * GRID_SIZE);\n        const row = Math.floor(Math.random() * GRID_SIZE);\n        lights = pressLight(lights, column, row);\n    }\n    return lights;\n}\n",
    hints=["Build the dark board first: a list of LIGHT_COUNT falses.",
           "Math.floor(Math.random() * GRID_SIZE) picks a random column.",
           "pressLight returns a NEW list, so remember to store it: lights = pressLight(...)"],
    tests=[("It gives back 25 lights",
            "assert(createPuzzle(5).length === LIGHT_COUNT, 'gave ' + createPuzzle(5).length);"),
           ("Every value is true or false",
            "assert(createPuzzle(5).every(v => v === true || v === false), 'a light was neither on nor off');"),
           ("Pressing nothing leaves the board dark",
            "assert(createPuzzle(0).every(v => v === false), 'with no presses every light should be off');"),
           ("One press lights a cross",
            "const lit = createPuzzle(1).filter(v => v).length;\nassert(lit === 3 || lit === 4 || lit === 5, 'one press should light 3, 4 or 5 squares, not ' + lit);"),
           ("Different puzzles come out different",
            "const first = createPuzzle(8).join('');\nlet different = false;\nfor (let i = 0; i < 20; i++) { if (createPuzzle(8).join('') !== first) { different = true; } }\nassert(different, 'twenty puzzles came out the same — are you pressing random squares?');")]),
  py=dict(
    starter="def create_puzzle(presses):\n    # start dark, then press random squares\n    pass\n",
    answer="def create_puzzle(presses):\n    lights = [False] * LIGHT_COUNT\n    for _ in range(presses):\n        lights = press_light(lights, random.randrange(GRID_SIZE), random.randrange(GRID_SIZE))\n    return lights\n",
    hints=["[False] * LIGHT_COUNT builds the dark board in one go.",
           "random.randrange(GRID_SIZE) picks a random column (random is already imported).",
           "press_light returns a NEW list, so store it: lights = press_light(...)"],
    tests=[("It gives back 25 lights", "assert len(create_puzzle(5)) == LIGHT_COUNT"),
           ("Every value is True or False",
            "assert all(isinstance(v, bool) for v in create_puzzle(5))"),
           ("Pressing nothing leaves the board dark",
            "assert not any(create_puzzle(0)), 'with no presses every light should be off'"),
           ("One press lights a cross",
            "lit = sum(create_puzzle(1))\nassert lit in (3, 4, 5), f'one press should light 3, 4 or 5 squares, not {lit}'"),
           ("Different puzzles come out different",
            "first = create_puzzle(8)\nassert any(create_puzzle(8) != first for _ in range(20)), 'twenty puzzles came out the same'")]),
  demo=dict(kind="game", caption="Press New a few times — every puzzle your function makes can be solved."),
  warning="Build the puzzle by PRESSING, never by turning random lights on. That is what makes it solvable."),

step("action_for_key", "actionForKey", "action_for_key",
  "Wire up the keyboard", "You can play without a mouse — the game is finished!",
  "<p>Arrows move a dashed cursor and the space bar presses. The browser gives us a key name; the game needs an action name.</p>",
  "key - the key name from the browser",
  "\"up\", \"down\", \"left\", \"right\", \"press\", \"pause\", \"restart\" - or nothing",
  ["Lowercase the key first.", "Arrows or WASD move the cursor.",
   "Space or Enter presses; p pauses; r restarts; anything else is nothing."],
  js=dict(
    starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // return the action name, or null\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter') { return 'press'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["One if per action.", "Keys can share an action with ||.", "The last line is: return null;"],
    tests=[("The arrows move the cursor",
            "assert(actionForKey('ArrowUp') === 'up' && actionForKey('ArrowDown') === 'down' && actionForKey('ArrowLeft') === 'left' && actionForKey('ArrowRight') === 'right');"),
           ("WASD works too", "assert(actionForKey('w') === 'up' && actionForKey('d') === 'right');"),
           ("Capitals still work", "assert(actionForKey('W') === 'up', 'did you lowercase the key?');"),
           ("Space presses the square", "assert(actionForKey(' ') === 'press', 'gave ' + actionForKey(' '));"),
           ("Enter presses too", "assert(actionForKey('Enter') === 'press');"),
           ("P pauses and R restarts", "assert(actionForKey('p') === 'pause' && actionForKey('r') === 'restart');"),
           ("An unused key gives null", "assert(actionForKey('q') === null, 'gave ' + actionForKey('q'));")]),
  py=dict(
    starter="def action_for_key(key):\n    k = str(key).lower()\n    # a dictionary from key names to action names, then .get(k)\n    pass\n",
    answer="def action_for_key(key):\n    k = str(key).lower()\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"press\", \"spacebar\": \"press\", \"enter\": \"press\",\n        \"p\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(k)\n",
    hints=["A dictionary IS the lookup table.", "Several keys can share an action.",
           "keys.get(k) gives None for anything missing."],
    tests=[("The arrows move the cursor",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD works too", "assert action_for_key('w') == 'up' and action_for_key('d') == 'right'"),
           ("Capitals still work", "assert action_for_key('W') == 'up', 'did you lowercase the key?'"),
           ("Space presses the square", "got = action_for_key(' ')\nassert got == 'press', f'gave {got!r}'"),
           ("Enter presses too", "assert action_for_key('Enter') == 'press'"),
           ("P pauses and R restarts", "assert action_for_key('p') == 'pause' and action_for_key('r') == 'restart'"),
           ("An unused key gives None", "got = action_for_key('q')\nassert got is None, f'gave {got!r}'")]),
  demo=dict(kind="final", caption="Click the page, then play with the arrow keys and space."),
  warning="Return null (JavaScript) or None (Python) for keys the game does not use."),
]

write_workshop("lights", "Lights Out", STEPS)
