"""The five steps of "Build Match Three", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("are_neighbours", "areNeighbours", "are_neighbours",
  "Are they next door?", "The game knows which swaps are allowed.",
  "<p>You may only swap two shapes that are <strong>touching along an edge</strong> — not diagonally, and certainly not from opposite corners of the board.</p>"
  "<p>There is a lovely one-line way to say that. Add up how far apart the two squares are across and down. Neighbours come to exactly 1. Diagonals come to 2. A square with itself comes to 0. One sum, three cases, all correct.</p>",
  "a, b — two squares, each with a column and a row",
  "True if they touch along an edge",
  ["Work out the difference in columns, ignoring the sign.",
   "Do the same for the rows.",
   "They are neighbours when the two differences add up to exactly 1."],
  js=dict(starter="function areNeighbours(a, b) {\n    // exactly one square apart, in total\n}\n",
    answer="function areNeighbours(a, b) {\n    const across = Math.abs(a.column - b.column);\n    const down = Math.abs(a.row - b.row);\n    return across + down === 1;\n}\n",
    hints=["Math.abs(...) throws away the minus sign, so the order does not matter.",
           "Add the two distances together.",
           "return across + down === 1;"],
    tests=[("Left and right are neighbours",
            "assert(areNeighbours({ column: 3, row: 4 }, { column: 4, row: 4 }) === true);"),
           ("Up and down are too",
            "assert(areNeighbours({ column: 3, row: 4 }, { column: 3, row: 5 }) === true);"),
           ("It works in either order",
            "assert(areNeighbours({ column: 4, row: 4 }, { column: 3, row: 4 }) === true, 'a and b can be given round the other way');"),
           ("Diagonals are NOT neighbours",
            "assert(areNeighbours({ column: 3, row: 4 }, { column: 4, row: 5 }) === false, 'a diagonal is 1 across AND 1 down, which comes to 2');"),
           ("A square is not its own neighbour",
            "assert(areNeighbours({ column: 3, row: 4 }, { column: 3, row: 4 }) === false);"),
           ("Two apart is too far",
            "assert(areNeighbours({ column: 3, row: 4 }, { column: 5, row: 4 }) === false);"),
           ("Opposite corners are certainly not",
            "assert(areNeighbours({ column: 0, row: 0 }, { column: 7, row: 7 }) === false);"),
           ("Every square has the right number of neighbours",
            "let corner = 0;\nlet middle = 0;\nfor (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 0; column < GRID_SIZE; column++) {\n        if (areNeighbours({ column: 0, row: 0 }, { column: column, row: row })) { corner++; }\n        if (areNeighbours({ column: 4, row: 4 }, { column: column, row: row })) { middle++; }\n    }\n}\nassert(corner === 2, 'a corner square has 2 neighbours, not ' + corner);\nassert(middle === 4, 'a middle square has 4 neighbours, not ' + middle);")]),
  py=dict(starter="def are_neighbours(a, b):\n    # exactly one square apart, in total\n    pass\n",
    answer="def are_neighbours(a, b):\n    across = abs(a[\"column\"] - b[\"column\"])\n    down = abs(a[\"row\"] - b[\"row\"])\n    return across + down == 1\n",
    hints=["abs(...) throws away the minus sign, so the order does not matter.",
           "Add the two distances together.",
           "return across + down == 1"],
    tests=[("Left and right are neighbours",
            "assert are_neighbours({'column': 3, 'row': 4}, {'column': 4, 'row': 4}) is True"),
           ("Up and down are too",
            "assert are_neighbours({'column': 3, 'row': 4}, {'column': 3, 'row': 5}) is True"),
           ("It works in either order",
            "assert are_neighbours({'column': 4, 'row': 4}, {'column': 3, 'row': 4}) is True"),
           ("Diagonals are NOT neighbours",
            "assert are_neighbours({'column': 3, 'row': 4}, {'column': 4, 'row': 5}) is False"),
           ("A square is not its own neighbour",
            "assert are_neighbours({'column': 3, 'row': 4}, {'column': 3, 'row': 4}) is False"),
           ("Two apart is too far",
            "assert are_neighbours({'column': 3, 'row': 4}, {'column': 5, 'row': 4}) is False"),
           ("Opposite corners are certainly not",
            "assert are_neighbours({'column': 0, 'row': 0}, {'column': 7, 'row': 7}) is False"),
           ("Every square has the right number of neighbours",
            "corner = sum(1 for r in range(GRID_SIZE) for c in range(GRID_SIZE)\n             if are_neighbours({'column': 0, 'row': 0}, {'column': c, 'row': r}))\nmiddle = sum(1 for r in range(GRID_SIZE) for c in range(GRID_SIZE)\n             if are_neighbours({'column': 4, 'row': 4}, {'column': c, 'row': r}))\nassert corner == 2, f'a corner has 2 neighbours, not {corner}'\nassert middle == 4, f'a middle square has 4 neighbours, not {middle}'")]),
  demo=dict(kind="shapes", caption="Move the cursor about — the note says whether the square to its right is a neighbour.")),

step("swap_gems", "swapGems", "swap_gems",
  "Trade places", "Shapes can be swapped.",
  "<p>Swapping two things needs somewhere to put the first one while you move the second. Here that is easy, because we are building a <strong>new board</strong> rather than editing the old one.</p>"
  "<p>That is not just tidiness. The game needs to try a swap, look at what it would do, and then <em>undo</em> it if it makes no line. Handing back a copy means undoing costs nothing at all — you simply throw the copy away.</p>",
  "board, a, b — two squares",
  "a NEW board with the two shapes exchanged",
  ["Copy the board.",
   "Work out both places with gem-index.",
   "In the copy, put the shape from the second place into the first, and the shape from the first into the second.",
   "Return the copy."],
  js=dict(starter="function swapGems(board, a, b) {\n    // a copy, with the two shapes exchanged\n}\n",
    answer="function swapGems(board, a, b) {\n    const copy = board.slice();\n    const first = gemIndex(a.column, a.row);\n    const second = gemIndex(b.column, b.row);\n\n    copy[first] = board[second];\n    copy[second] = board[first];\n    return copy;\n}\n",
    hints=["board.slice() copies a list.",
           "Read from the ORIGINAL board and write into the copy — then you never need a temporary variable.",
           "copy[first] = board[second];"],
    tests=[("The two shapes change places",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nconst a = { column: 0, row: 0 };\nconst b = { column: 1, row: 0 };\nconst swapped = swapGems(board, a, b);\nassert(swapped[gemIndex(0, 0)] === board[gemIndex(1, 0)]);\nassert(swapped[gemIndex(1, 0)] === board[gemIndex(0, 0)]);"),
           ("Nothing else moves",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nconst swapped = swapGems(board, { column: 0, row: 0 }, { column: 1, row: 0 });\nfor (let i = 2; i < CELL_COUNT; i++) {\n    assert(swapped[i] === board[i], 'square ' + i + ' should not have changed');\n}"),
           ("The board you were given is left alone",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nconst before = board.join(',');\nswapGems(board, { column: 0, row: 0 }, { column: 1, row: 0 });\nassert(board.join(',') === before, 'build a NEW board — the game needs to be able to undo a swap');"),
           ("Swapping twice puts everything back",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nconst a = { column: 2, row: 3 };\nconst b = { column: 2, row: 4 };\nconst there = swapGems(board, a, b);\nconst back = swapGems(there, a, b);\nassert(back.join(',') === board.join(','));"),
           ("It works up and down as well as across",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nconst swapped = swapGems(board, { column: 3, row: 3 }, { column: 3, row: 4 });\nassert(swapped[gemIndex(3, 3)] === board[gemIndex(3, 4)]);"),
           ("The board is still the right size",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nassert(swapGems(board, { column: 0, row: 0 }, { column: 1, row: 0 }).length === CELL_COUNT);")]),
  py=dict(starter="def swap_gems(board, a, b):\n    # a copy, with the two shapes exchanged\n    pass\n",
    answer="def swap_gems(board, a, b):\n    copy = list(board)\n    first = gem_index(a[\"column\"], a[\"row\"])\n    second = gem_index(b[\"column\"], b[\"row\"])\n\n    copy[first] = board[second]\n    copy[second] = board[first]\n    return copy\n",
    hints=["list(board) copies a list.",
           "Read from the ORIGINAL board and write into the copy.",
           "copy[first] = board[second]"],
    tests=[("The two shapes change places",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nswapped = swap_gems(board, {'column': 0, 'row': 0}, {'column': 1, 'row': 0})\nassert swapped[gem_index(0, 0)] == board[gem_index(1, 0)]\nassert swapped[gem_index(1, 0)] == board[gem_index(0, 0)]"),
           ("Nothing else moves",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nswapped = swap_gems(board, {'column': 0, 'row': 0}, {'column': 1, 'row': 0})\nassert swapped[2:] == board[2:]"),
           ("The board you were given is left alone",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nbefore = list(board)\nswap_gems(board, {'column': 0, 'row': 0}, {'column': 1, 'row': 0})\nassert board == before, 'build a NEW board'"),
           ("Swapping twice puts everything back",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\na = {'column': 2, 'row': 3}\nb = {'column': 2, 'row': 4}\nassert swap_gems(swap_gems(board, a, b), a, b) == board"),
           ("It works up and down as well as across",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nswapped = swap_gems(board, {'column': 3, 'row': 3}, {'column': 3, 'row': 4})\nassert swapped[gem_index(3, 3)] == board[gem_index(3, 4)]"),
           ("The board is still the right size",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nassert len(swap_gems(board, {'column': 0, 'row': 0}, {'column': 1, 'row': 0})) == CELL_COUNT")]),
  demo=dict(kind="shapes", caption="Press Swap right and watch two shapes trade places.")),

step("find_matches", "findMatches", "find_matches",
  "Spot the lines", "The game can see a match.",
  "<p>The heart of the game: find every shape that is part of a line of three or more, across or down.</p>"
  "<p>The trick is to keep a <strong>run</strong> as you walk along a row: how many of the same shape you have seen in a row so far. When the shape changes, the run has ended — and if it got to three or more, everything in it goes on the list.</p>"
  "<p>Two things catch people out. The run that ends at the very <em>edge</em> of the board still counts, so you must check it after the loop. And a shape in the middle of a cross belongs to a row AND a column, so the same square would be listed twice — which is why the marks go into a set first.</p>",
  "board", "a sorted list of the places to clear, with no repeats",
  ["Keep a set of marked places.",
   "For each row, build the list of places along it and scan it for runs.",
   "Do exactly the same for each column.",
   "A run of MIN_RUN or more means every place in it gets marked.",
   "Turn the set into a sorted list at the end."],
  js=dict(starter="function findMatches(board) {\n    const marked = {};\n    // scan every row, then every column\n    return [];\n}\n",
    answer="function findMatches(board) {\n    const marked = {};\n\n    const markRun = function (cells, start, length) {\n        if (length < MIN_RUN) {\n            return;\n        }\n        for (let i = start; i < start + length; i++) {\n            marked[cells[i]] = true;\n        }\n    };\n\n    for (let row = 0; row < GRID_SIZE; row++) {\n        const cells = [];\n        for (let column = 0; column < GRID_SIZE; column++) {\n            cells.push(gemIndex(column, row));\n        }\n        scanLine(board, cells, markRun);\n    }\n\n    for (let column = 0; column < GRID_SIZE; column++) {\n        const cells = [];\n        for (let row = 0; row < GRID_SIZE; row++) {\n            cells.push(gemIndex(column, row));\n        }\n        scanLine(board, cells, markRun);\n    }\n\n    const found = [];\n    for (let i = 0; i < CELL_COUNT; i++) {\n        if (marked[i]) { found.push(i); }\n    }\n    return found;\n}\n",
    hints=["scanLine(board, cells, markRun) does the hard part — it finds the runs along one line.",
           "Build the list of places for a row, then for a column, and hand each to scanLine.",
           "Using an object as the marker set means a square listed twice only appears once."],
    tests=[("An empty-looking board with no lines finds nothing",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push((i % 3) + (Math.floor(i / GRID_SIZE) % 2) * 3); }\nassert(Array.isArray(findMatches(board)), 'it must return a list');"),
           ("A row of three is found",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % 5 + 1); }\nboard[gemIndex(2, 3)] = 0;\nboard[gemIndex(3, 3)] = 0;\nboard[gemIndex(4, 3)] = 0;\nconst found = findMatches(board);\nassert(found.indexOf(gemIndex(2, 3)) !== -1 && found.indexOf(gemIndex(3, 3)) !== -1 && found.indexOf(gemIndex(4, 3)) !== -1, 'found ' + found);"),
           ("A column of three is found",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % 5 + 1); }\nboard[gemIndex(2, 1)] = 0;\nboard[gemIndex(2, 2)] = 0;\nboard[gemIndex(2, 3)] = 0;\nconst found = findMatches(board);\nassert(found.indexOf(gemIndex(2, 2)) !== -1, 'a line going down must count too');"),
           ("Two the same are NOT a match",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % 5 + 1); }\nboard[gemIndex(2, 3)] = 0;\nboard[gemIndex(3, 3)] = 0;\nassert(findMatches(board).indexOf(gemIndex(2, 3)) === -1, 'you need THREE in a line');"),
           ("A run of four is all found",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % 5 + 1); }\nfor (let column = 1; column <= 4; column++) { board[gemIndex(column, 2)] = 0; }\nconst found = findMatches(board);\nlet count = 0;\nfor (let column = 1; column <= 4; column++) {\n    if (found.indexOf(gemIndex(column, 2)) !== -1) { count++; }\n}\nassert(count === 4, 'only ' + count + ' of the four were found');"),
           ("A match at the very edge still counts",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push((i * 7) % 5 + 1); }\nboard[gemIndex(5, 0)] = 0;\nboard[gemIndex(6, 0)] = 0;\nboard[gemIndex(7, 0)] = 0;\nconst found = findMatches(board);\nassert(found.indexOf(gemIndex(7, 0)) !== -1, 'a run that ends at the edge of the board is still a run — did you check the last run after the loop?');"),
           ("A square in a cross is only listed once",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push((i * 7) % 5 + 1); }\nfor (let column = 2; column <= 4; column++) { board[gemIndex(column, 3)] = 0; }\nfor (let row = 2; row <= 4; row++) { board[gemIndex(3, row)] = 0; }\nconst found = findMatches(board);\nlet appearances = 0;\nfound.forEach(function (index) { if (index === gemIndex(3, 3)) { appearances++; } });\nassert(appearances === 1, 'the middle of the cross appears ' + appearances + ' times — it must appear once');"),
           ("Empty squares never match each other",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(EMPTY); }\nassert(findMatches(board).length === 0, 'a row of empty squares is not a line of three');")]),
  py=dict(starter="def find_matches(board):\n    marked = set()\n    # scan every row, then every column\n    return sorted(marked)\n",
    answer="def find_matches(board):\n    marked = set()\n\n    def mark_run(cells, start, length):\n        if length >= MIN_RUN:\n            marked.update(cells[start:start + length])\n\n    for row in range(GRID_SIZE):\n        scan_line(board, [gem_index(c, row) for c in range(GRID_SIZE)], mark_run)\n\n    for column in range(GRID_SIZE):\n        scan_line(board, [gem_index(column, r) for r in range(GRID_SIZE)], mark_run)\n\n    return sorted(marked)\n",
    hints=["scan_line(board, cells, mark_run) does the hard part.",
           "Build the list of places for a row, then for a column, and hand each to scan_line.",
           "A set never holds the same square twice, which is exactly what a cross needs."],
    tests=[("It returns a list",
            "board = [(i % 3) + (i // GRID_SIZE % 2) * 3 for i in range(CELL_COUNT)]\nassert isinstance(find_matches(board), list)"),
           ("A row of three is found",
            "board = [i % 5 + 1 for i in range(CELL_COUNT)]\nfor c in (2, 3, 4):\n    board[gem_index(c, 3)] = 0\nfound = find_matches(board)\nassert all(gem_index(c, 3) in found for c in (2, 3, 4)), f'found {found}'"),
           ("A column of three is found",
            "board = [i % 5 + 1 for i in range(CELL_COUNT)]\nfor r in (1, 2, 3):\n    board[gem_index(2, r)] = 0\nassert gem_index(2, 2) in find_matches(board)"),
           ("Two the same are NOT a match",
            "board = [i % 5 + 1 for i in range(CELL_COUNT)]\nboard[gem_index(2, 3)] = 0\nboard[gem_index(3, 3)] = 0\nassert gem_index(2, 3) not in find_matches(board)"),
           ("A run of four is all found",
            "board = [i % 5 + 1 for i in range(CELL_COUNT)]\nfor c in range(1, 5):\n    board[gem_index(c, 2)] = 0\nfound = find_matches(board)\nassert all(gem_index(c, 2) in found for c in range(1, 5))"),
           ("A match at the very edge still counts",
            "board = [(i * 7) % 5 + 1 for i in range(CELL_COUNT)]\nfor c in (5, 6, 7):\n    board[gem_index(c, 0)] = 0\nassert gem_index(7, 0) in find_matches(board), 'did you check the last run after the loop?'"),
           ("A square in a cross is only listed once",
            "board = [(i * 7) % 5 + 1 for i in range(CELL_COUNT)]\nfor c in range(2, 5):\n    board[gem_index(c, 3)] = 0\nfor r in range(2, 5):\n    board[gem_index(3, r)] = 0\nfound = find_matches(board)\nassert found.count(gem_index(3, 3)) == 1"),
           ("Empty squares never match each other",
            "assert find_matches([EMPTY] * CELL_COUNT) == []")]),
  demo=dict(kind="matches", caption="Press Make a row or Make a column — the boxes show what the function found."),
  warning="Check the run that ends at the edge of the board. Miss it and a match against the right-hand or bottom wall is invisible to the game."),

step("apply_gravity", "applyGravity", "apply_gravity",
  "Let them fall", "The board refills itself.",
  "<p>Shapes have vanished and there are holes. Everything above a hole slides down, and brand-new shapes drop in from the top.</p>"
  "<p>Rather than moving shapes one square at a time, there is a much simpler way: take a column, read it from the BOTTOM upwards collecting whatever is still there, then write that pile straight back at the bottom. Whatever is left at the top gets a new random shape. One pass, no shuffling.</p>",
  "board", "a NEW board with everything fallen and the gaps refilled",
  ["Copy the board to write into.",
   "For each column: read from the bottom row upwards, collecting the shapes that are not EMPTY.",
   "Write them back from the bottom up, in the order you collected them.",
   "Any place above the pile gets a random shape."],
  js=dict(starter="function applyGravity(board) {\n    const result = board.slice();\n    // one column at a time: collect from the bottom, write back from the bottom\n    return result;\n}\n",
    answer="function applyGravity(board) {\n    const result = board.slice();\n\n    for (let column = 0; column < GRID_SIZE; column++) {\n        const kept = [];\n        for (let row = GRID_SIZE - 1; row >= 0; row--) {\n            const shape = board[gemIndex(column, row)];\n            if (shape !== EMPTY) {\n                kept.push(shape);\n            }\n        }\n\n        for (let row = GRID_SIZE - 1; row >= 0; row--) {\n            const fromBottom = GRID_SIZE - 1 - row;\n            result[gemIndex(column, row)] =\n                fromBottom < kept.length ? kept[fromBottom] : randomShape();\n        }\n    }\n    return result;\n}\n",
    hints=["Collect from the bottom up, and write back from the bottom up — then the order takes care of itself.",
           "GRID_SIZE - 1 - row tells you how far up from the bottom a row is.",
           "randomShape() gives you a new one for the gaps at the top."],
    tests=[("No holes means nothing moves",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nassert(applyGravity(board).join(',') === board.join(','), 'a full board should come back unchanged');"),
           ("A shape falls into the hole below it",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(1); }\nboard[gemIndex(3, 2)] = 5;\nboard[gemIndex(3, 7)] = EMPTY;\nconst fallen = applyGravity(board);\nassert(fallen[gemIndex(3, 3)] === 5, 'the 5 should have dropped one row');"),
           ("The board comes back completely full",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(i % SHAPE_COUNT); }\nfor (let column = 0; column < GRID_SIZE; column++) { board[gemIndex(column, 4)] = EMPTY; }\nconst fallen = applyGravity(board);\nfor (let i = 0; i < CELL_COUNT; i++) {\n    assert(fallen[i] !== EMPTY, 'square ' + i + ' is still empty');\n}"),
           ("New shapes appear at the TOP, not the bottom",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(1); }\nboard[gemIndex(0, 7)] = EMPTY;\nboard[gemIndex(0, 6)] = 3;\nconst fallen = applyGravity(board);\nassert(fallen[gemIndex(0, 7)] === 3, 'the 3 should have fallen to the bottom of the column');"),
           ("An empty column fills up completely",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(1); }\nfor (let row = 0; row < GRID_SIZE; row++) { board[gemIndex(2, row)] = EMPTY; }\nconst fallen = applyGravity(board);\nfor (let row = 0; row < GRID_SIZE; row++) {\n    assert(fallen[gemIndex(2, row)] !== EMPTY);\n}"),
           ("The shapes stay in their own column",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(1); }\nboard[gemIndex(0, 0)] = 4;\nboard[gemIndex(0, 7)] = EMPTY;\nconst fallen = applyGravity(board);\nlet fours = 0;\nfor (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 1; column < GRID_SIZE; column++) {\n        if (fallen[gemIndex(column, row)] === 4) { fours++; }\n    }\n}\nassert(fours === 0, 'a shape must never slide sideways into another column');"),
           ("The board you were given is left alone",
            "const board = [];\nfor (let i = 0; i < CELL_COUNT; i++) { board.push(1); }\nboard[gemIndex(3, 7)] = EMPTY;\napplyGravity(board);\nassert(board[gemIndex(3, 7)] === EMPTY, 'build a NEW board');")]),
  py=dict(starter="def apply_gravity(board):\n    result = list(board)\n    # one column at a time: collect from the bottom, write back from the bottom\n    return result\n",
    answer="def apply_gravity(board):\n    result = list(board)\n\n    for column in range(GRID_SIZE):\n        kept = []\n        for row in range(GRID_SIZE - 1, -1, -1):\n            shape = board[gem_index(column, row)]\n            if shape != EMPTY:\n                kept.append(shape)\n\n        for row in range(GRID_SIZE - 1, -1, -1):\n            from_bottom = GRID_SIZE - 1 - row\n            result[gem_index(column, row)] = (kept[from_bottom]\n                                              if from_bottom < len(kept)\n                                              else random_shape())\n    return result\n",
    hints=["range(GRID_SIZE - 1, -1, -1) walks a column from the bottom upwards.",
           "GRID_SIZE - 1 - row tells you how far up from the bottom a row is.",
           "random_shape() gives you a new one for the gaps at the top."],
    tests=[("No holes means nothing moves",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nassert apply_gravity(board) == board"),
           ("A shape falls into the hole below it",
            "board = [1] * CELL_COUNT\nboard[gem_index(3, 2)] = 5\nboard[gem_index(3, 7)] = EMPTY\nfallen = apply_gravity(board)\nassert fallen[gem_index(3, 3)] == 5"),
           ("The board comes back completely full",
            "board = [i % SHAPE_COUNT for i in range(CELL_COUNT)]\nfor c in range(GRID_SIZE):\n    board[gem_index(c, 4)] = EMPTY\nassert EMPTY not in apply_gravity(board)"),
           ("New shapes appear at the TOP, not the bottom",
            "board = [1] * CELL_COUNT\nboard[gem_index(0, 7)] = EMPTY\nboard[gem_index(0, 6)] = 3\nfallen = apply_gravity(board)\nassert fallen[gem_index(0, 7)] == 3"),
           ("An empty column fills up completely",
            "board = [1] * CELL_COUNT\nfor r in range(GRID_SIZE):\n    board[gem_index(2, r)] = EMPTY\nfallen = apply_gravity(board)\nassert all(fallen[gem_index(2, r)] != EMPTY for r in range(GRID_SIZE))"),
           ("The shapes stay in their own column",
            "board = [1] * CELL_COUNT\nboard[gem_index(0, 0)] = 4\nboard[gem_index(0, 7)] = EMPTY\nfallen = apply_gravity(board)\nfours = sum(1 for r in range(GRID_SIZE) for c in range(1, GRID_SIZE)\n            if fallen[gem_index(c, r)] == 4)\nassert fours == 0, 'a shape must never slide sideways'"),
           ("The board you were given is left alone",
            "board = [1] * CELL_COUNT\nboard[gem_index(3, 7)] = EMPTY\napply_gravity(board)\nassert board[gem_index(3, 7)] == EMPTY")]),
  demo=dict(kind="matches", caption="Make a line, then press Let them fall and watch the board refill.")),

step("try_swap", "trySwap", "try_swap",
  "The move", "The whole game works!",
  "<p>Everything comes together. Swap the two shapes, look for a line — and if there is not one, <strong>put them straight back</strong>. That refusal is what makes the game a puzzle rather than a shuffling toy.</p>"
  "<p>Putting them back costs nothing here, because swap-gems handed you a copy and the real board was never touched. That is the payoff for the decision you made two steps ago.</p>",
  "state, a, b — the two squares to exchange",
  "True if the swap was allowed",
  ["Refuse if the game is over or paused, or if the two are not neighbours.",
   "Make the swapped board with swap-gems.",
   "If find-matches finds nothing, the move was not legal: count a bad swap and return False. The real board is untouched.",
   "Otherwise settle-board clears, drops and cascades — keep its board.",
   "Count the move, add up the shapes cleared, and remember the longest chain."],
  js=dict(starter="function trySwap(state, a, b) {\n    // swap, look for a line, and put them back if there is none\n}\n",
    answer="function trySwap(state, a, b) {\n    if (state.isOver || state.isPaused || !areNeighbours(a, b)) {\n        return false;\n    }\n\n    const swapped = swapGems(state.board, a, b);\n    if (findMatches(swapped).length === 0) {\n        state.badSwaps = state.badSwaps + 1;\n        return false;\n    }\n\n    const settled = settleBoard(state, swapped);\n    state.board = settled.board;\n    state.moves = state.moves + 1;\n    state.cleared = state.cleared + settled.cleared;\n    if (settled.chains > state.bestChain) {\n        state.bestChain = settled.chains;\n    }\n    return true;\n}\n",
    hints=["Do the cheap checks first: over, paused, not neighbours.",
           "settleBoard(state, board) is written for you — it does the clearing, the falling and the cascades.",
           "Only write to state.board once you know the swap was legal."],
    tests=[("A swap that makes no line is refused",
            "const state = createGame();\nconst before = state.board.join(',');\nlet refused = false;\nfor (let row = 0; row < GRID_SIZE && !refused; row++) {\n    for (let column = 0; column + 1 < GRID_SIZE && !refused; column++) {\n        const a = { column: column, row: row };\n        const b = { column: column + 1, row: row };\n        if (findMatches(swapGems(state.board, a, b)).length === 0) {\n            assert(trySwap(state, a, b) === false, 'that swap makes no line, so it must be refused');\n            refused = true;\n        }\n    }\n}\nassert(refused, 'the test could not find a bad swap to try');\nassert(state.board.join(',') === before, 'a refused swap must leave the board exactly as it was');"),
           ("Two squares that are not neighbours are refused",
            "const state = createGame();\nassert(trySwap(state, { column: 0, row: 0 }, { column: 5, row: 5 }) === false);"),
           ("A swap that makes a line is allowed",
            "const state = createGame();\nlet done = false;\nfor (let row = 0; row < GRID_SIZE && !done; row++) {\n    for (let column = 0; column + 1 < GRID_SIZE && !done; column++) {\n        const a = { column: column, row: row };\n        const b = { column: column + 1, row: row };\n        if (findMatches(swapGems(state.board, a, b)).length > 0) {\n            assert(trySwap(state, a, b) === true);\n            done = true;\n        }\n    }\n}\nassert(done, 'every fresh board has at least one good swap in it');"),
           ("A good swap scores",
            "const state = createGame();\nlet done = false;\nfor (let row = 0; row < GRID_SIZE && !done; row++) {\n    for (let column = 0; column + 1 < GRID_SIZE && !done; column++) {\n        const a = { column: column, row: row };\n        const b = { column: column + 1, row: row };\n        if (findMatches(swapGems(state.board, a, b)).length > 0) {\n            trySwap(state, a, b);\n            done = true;\n        }\n    }\n}\nassert(state.score > 0, 'clearing shapes must be worth something');\nassert(state.moves === 1);"),
           ("A refused swap does not count as a move",
            "const state = createGame();\ntrySwap(state, { column: 0, row: 0 }, { column: 5, row: 5 });\nassert(state.moves === 0);"),
           ("The board is always full after a move",
            "const state = createGame();\nfor (let attempt = 0; attempt < 15; attempt++) {\n    for (let row = 0; row < GRID_SIZE; row++) {\n        for (let column = 0; column + 1 < GRID_SIZE; column++) {\n            trySwap(state, { column: column, row: row }, { column: column + 1, row: row });\n        }\n    }\n}\nfor (let i = 0; i < CELL_COUNT; i++) {\n    assert(state.board[i] !== EMPTY, 'square ' + i + ' was left empty');\n}"),
           ("No lines are left sitting on the board",
            "const state = createGame();\nfor (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 0; column + 1 < GRID_SIZE; column++) {\n        trySwap(state, { column: column, row: row }, { column: column + 1, row: row });\n    }\n}\nassert(findMatches(state.board).length === 0, 'everything that matched should already have been cleared');")]),
  py=dict(starter="def try_swap(state, a, b):\n    # swap, look for a line, and put them back if there is none\n    pass\n",
    answer="def try_swap(state, a, b):\n    if state[\"is_over\"] or state[\"is_paused\"] or not are_neighbours(a, b):\n        return False\n\n    swapped = swap_gems(state[\"board\"], a, b)\n    if not find_matches(swapped):\n        state[\"bad_swaps\"] += 1\n        return False\n\n    board, cleared, chains = settle_board(state, swapped)\n    state[\"board\"] = board\n    state[\"moves\"] += 1\n    state[\"cleared\"] += cleared\n    if chains > state[\"best_chain\"]:\n        state[\"best_chain\"] = chains\n    return True\n",
    hints=["Do the cheap checks first: over, paused, not neighbours.",
           "settle_board(state, board) is written for you and gives back three things.",
           "Only write to state['board'] once you know the swap was legal."],
    tests=[("A swap that makes no line is refused",
            "state = create_game()\nbefore = list(state['board'])\nrefused = False\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE - 1):\n        a = {'column': column, 'row': row}\n        b = {'column': column + 1, 'row': row}\n        if not find_matches(swap_gems(state['board'], a, b)):\n            assert try_swap(state, a, b) is False\n            refused = True\n            break\n    if refused:\n        break\nassert refused, 'the test could not find a bad swap to try'\nassert state['board'] == before, 'a refused swap must leave the board as it was'"),
           ("Two squares that are not neighbours are refused",
            "state = create_game()\nassert try_swap(state, {'column': 0, 'row': 0}, {'column': 5, 'row': 5}) is False"),
           ("A swap that makes a line is allowed",
            "state = create_game()\ndone = False\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE - 1):\n        a = {'column': column, 'row': row}\n        b = {'column': column + 1, 'row': row}\n        if find_matches(swap_gems(state['board'], a, b)):\n            assert try_swap(state, a, b) is True\n            done = True\n            break\n    if done:\n        break\nassert done, 'every fresh board has at least one good swap in it'"),
           ("A good swap scores",
            "state = create_game()\ndone = False\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE - 1):\n        a = {'column': column, 'row': row}\n        b = {'column': column + 1, 'row': row}\n        if find_matches(swap_gems(state['board'], a, b)):\n            try_swap(state, a, b)\n            done = True\n            break\n    if done:\n        break\nassert state['score'] > 0 and state['moves'] == 1"),
           ("A refused swap does not count as a move",
            "state = create_game()\ntry_swap(state, {'column': 0, 'row': 0}, {'column': 5, 'row': 5})\nassert state['moves'] == 0"),
           ("The board is always full after a move",
            "state = create_game()\nfor _ in range(15):\n    for row in range(GRID_SIZE):\n        for column in range(GRID_SIZE - 1):\n            try_swap(state, {'column': column, 'row': row}, {'column': column + 1, 'row': row})\nassert EMPTY not in state['board']"),
           ("No lines are left sitting on the board",
            "state = create_game()\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE - 1):\n        try_swap(state, {'column': column, 'row': row}, {'column': column + 1, 'row': row})\nassert find_matches(state['board']) == []")]),
  demo=dict(kind="final", caption="Click the page. Move with the arrows, SPACE to pick a shape, then SPACE on its neighbour."),
  warning="Put the shapes back when the swap makes no line. Forget that and the board can be shuffled about for ever, and the puzzle disappears."),
]

write_workshop("match3", "Match Three", STEPS)
