"""The five steps of "Build Maze Runner", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("is_wall", "isWall", "is_wall",
  "Solid rock", "The maze knows where you can walk.",
  "<p>The maze is one long list of true/false: is this square solid rock?</p>"
  "<p>And the same rule as always — anything <em>outside</em> the maze counts as rock too. One line here, and no other function ever has to worry about walking off the edge of the world.</p>",
  "maze, x, y", "True if you cannot walk there",
  ["If x or y is outside the maze, return True.",
   "Otherwise look the square up in the maze list."],
  js=dict(starter="function isWall(maze, x, y) {\n    // outside the maze is solid too\n}\n",
    answer="function isWall(maze, x, y) {\n    if (!isInsideMaze(x, y)) {\n        return true;\n    }\n    return maze[mazeIndex(x, y)];\n}\n",
    hints=["isInsideMaze(x, y) is written for you.",
           "mazeIndex(x, y) turns a pair into a place in the list.",
           "Outside the maze returns true — not false."],
    tests=[("Solid rock is wall",
            "assert(isWall(solidMaze(), 5, 5) === true);"),
           ("A dug-out square is not",
            "const maze = solidMaze();\nmaze[mazeIndex(5, 5)] = false;\nassert(isWall(maze, 5, 5) === false);"),
           ("Outside the maze counts as wall",
            "const maze = solidMaze();\nassert(isWall(maze, -1, 5) === true);\nassert(isWall(maze, MAZE_WIDTH, 5) === true);\nassert(isWall(maze, 5, -1) === true);\nassert(isWall(maze, 5, MAZE_HEIGHT) === true);"),
           ("A real maze has open corridors",
            "const maze = carveMaze();\nassert(isWall(maze, 1, 1) === false, 'the starting room must be dug out');"),
           ("A real maze has a solid border",
            "const maze = carveMaze();\nfor (let x = 0; x < MAZE_WIDTH; x++) {\n    assert(isWall(maze, x, 0) && isWall(maze, x, MAZE_HEIGHT - 1), 'there is a hole in the top or bottom wall');\n}\nfor (let y = 0; y < MAZE_HEIGHT; y++) {\n    assert(isWall(maze, 0, y) && isWall(maze, MAZE_WIDTH - 1, y), 'there is a hole in the side wall');\n}")]),
  py=dict(starter="def is_wall(maze, x, y):\n    # outside the maze is solid too\n    pass\n",
    answer="def is_wall(maze, x, y):\n    if not is_inside_maze(x, y):\n        return True\n    return maze[maze_index(x, y)]\n",
    hints=["is_inside_maze(x, y) is written for you.",
           "maze_index(x, y) turns a pair into a place in the list.",
           "Outside the maze returns True - not False."],
    tests=[("Solid rock is wall", "assert is_wall(solid_maze(), 5, 5) is True"),
           ("A dug-out square is not",
            "maze = solid_maze()\nmaze[maze_index(5, 5)] = False\nassert is_wall(maze, 5, 5) is False"),
           ("Outside the maze counts as wall",
            "maze = solid_maze()\nassert is_wall(maze, -1, 5) is True\nassert is_wall(maze, MAZE_WIDTH, 5) is True\nassert is_wall(maze, 5, -1) is True\nassert is_wall(maze, 5, MAZE_HEIGHT) is True"),
           ("A real maze has open corridors",
            "assert is_wall(carve_maze(), 1, 1) is False"),
           ("A real maze has a solid border",
            "maze = carve_maze()\nfor x in range(MAZE_WIDTH):\n    assert is_wall(maze, x, 0) and is_wall(maze, x, MAZE_HEIGHT - 1)\nfor y in range(MAZE_HEIGHT):\n    assert is_wall(maze, 0, y) and is_wall(maze, MAZE_WIDTH - 1, y)")]),
  demo=dict(kind="rock", caption="Move the dashed box around a tiny hand-dug maze.")),

step("room_neighbours", "roomNeighbours", "room_neighbours",
  "Rooms and the walls between", "The digger knows where it could go next.",
  "<p>Here is the idea that makes maze-digging easy. The maze is stored so that <strong>rooms sit at odd coordinates</strong> — (1,1), (1,3), (3,1) and so on — and the square between two rooms is the wall that separates them.</p>"
  "<p>So a neighbouring room is <em>two</em> squares away, and the wall to knock through is the <em>one</em> square in between. This function returns both, so the digger has everything it needs.</p>",
  "x, y — a room",
  "a list of the neighbouring rooms and the wall between each",
  ["Try all four steps: up two, right two, down two, left two.",
   "Skip any that would land outside the maze.",
   "For each one that fits, give back the room's x and y, and the wall's x and y — which is halfway there."],
  js=dict(starter="function roomNeighbours(x, y) {\n    const steps = [[0, -2], [2, 0], [0, 2], [-2, 0]];\n    const found = [];\n    // the room two away, and the wall one away\n    return found;\n}\n",
    answer="function roomNeighbours(x, y) {\n    const steps = [[0, -2], [2, 0], [0, 2], [-2, 0]];\n    const found = [];\n    for (let i = 0; i < steps.length; i++) {\n        const nx = x + steps[i][0];\n        const ny = y + steps[i][1];\n        if (isInsideMaze(nx, ny)) {\n            found.push({\n                x: nx, y: ny,\n                wallX: x + steps[i][0] / 2,\n                wallY: y + steps[i][1] / 2\n            });\n        }\n    }\n    return found;\n}\n",
    hints=["The wall is exactly halfway, so divide the step by 2.",
           "isInsideMaze(nx, ny) keeps you on the board.",
           "wallX: x + steps[i][0] / 2"],
    tests=[("A room in the middle has four neighbours",
            "assert(roomNeighbours(5, 5).length === 4, 'gave ' + roomNeighbours(5, 5).length);"),
           ("The top-left room has only two",
            "assert(roomNeighbours(1, 1).length === 2, 'gave ' + roomNeighbours(1, 1).length + ' — two of its neighbours are off the maze');"),
           ("Neighbours really are two squares away",
            "roomNeighbours(5, 5).forEach(function (n) {\n    const distance = Math.abs(n.x - 5) + Math.abs(n.y - 5);\n    assert(distance === 2, 'that neighbour is ' + distance + ' away, not 2');\n});"),
           ("The wall is halfway between",
            "roomNeighbours(5, 5).forEach(function (n) {\n    assert(n.wallX === (5 + n.x) / 2, 'the wall x should be halfway');\n    assert(n.wallY === (5 + n.y) / 2, 'the wall y should be halfway');\n});"),
           ("Every neighbour it names is on the maze",
            "for (let y = 1; y < MAZE_HEIGHT; y += 2) {\n    for (let x = 1; x < MAZE_WIDTH; x += 2) {\n        roomNeighbours(x, y).forEach(function (n) {\n            assert(isInsideMaze(n.x, n.y), '(' + n.x + ',' + n.y + ') is off the maze');\n        });\n    }\n}"),
           ("Every neighbour is a room, not a wall square",
            "roomNeighbours(5, 5).forEach(function (n) {\n    assert(n.x % 2 === 1 && n.y % 2 === 1, 'rooms live at ODD coordinates');\n});")]),
  py=dict(starter="def room_neighbours(x, y):\n    found = []\n    # the room two away, and the wall one away\n    return found\n",
    answer="def room_neighbours(x, y):\n    found = []\n    for dx, dy in ((0, -2), (2, 0), (0, 2), (-2, 0)):\n        nx, ny = x + dx, y + dy\n        if is_inside_maze(nx, ny):\n            found.append((nx, ny, x + dx // 2, y + dy // 2))\n    return found\n",
    hints=["The wall is exactly halfway, so use dx // 2 and dy // 2.",
           "is_inside_maze(nx, ny) keeps you on the board.",
           "Give back a tuple: (room x, room y, wall x, wall y)."],
    tests=[("A room in the middle has four neighbours",
            "assert len(room_neighbours(5, 5)) == 4"),
           ("The top-left room has only two",
            "assert len(room_neighbours(1, 1)) == 2"),
           ("Neighbours really are two squares away",
            "for nx, ny, wx, wy in room_neighbours(5, 5):\n    assert abs(nx - 5) + abs(ny - 5) == 2"),
           ("The wall is halfway between",
            "for nx, ny, wx, wy in room_neighbours(5, 5):\n    assert wx == (5 + nx) // 2 and wy == (5 + ny) // 2"),
           ("Every neighbour it names is on the maze",
            "for y in range(1, MAZE_HEIGHT, 2):\n    for x in range(1, MAZE_WIDTH, 2):\n        for nx, ny, wx, wy in room_neighbours(x, y):\n            assert is_inside_maze(nx, ny)"),
           ("Every neighbour is a room, not a wall square",
            "for nx, ny, wx, wy in room_neighbours(5, 5):\n    assert nx % 2 == 1 and ny % 2 == 1, 'rooms live at ODD coordinates'")]),
  demo=dict(kind="rock", caption="The rooms are at odd coordinates — walk the box along row 1 and see.")),

step("carve_maze", "carveMaze", "carve_maze",
  "Dig the maze", "A brand-new maze, every game.",
  "<p>The big one. This is the <strong>recursive backtracker</strong>, and it is the algorithm behind most of the mazes you have ever played.</p>"
  "<p>It works exactly like walking through solid rock with a pick and a piece of string:</p>"
  "<ol><li>Dig out the first room and hold on to it (that is the stack).</li>"
  "<li>Look at the room you are standing in. Are any of its neighbours still solid?</li>"
  "<li>If yes: pick one at random, knock through the wall between, dig it out, and walk in. Hold on to that room too.</li>"
  "<li>If no: walk back one room along your string, and look again.</li>"
  "<li>When your string runs out, every room has been dug and the maze is finished.</li></ol>"
  "<p>What you get is a <em>perfect</em> maze: every room reachable, exactly one route between any two of them, no loops.</p>",
  "nothing", "a maze — a list where True means wall",
  ["Start with solid rock. Dig out room (1, 1) and put it on the stack.",
   "While the stack is not empty, look at the room on TOP of it.",
   "Shuffle its neighbours, and look for the first one that is still solid rock.",
   "If you find one: knock out the wall between, dig out the room, and push the room onto the stack.",
   "If there is none: pop the top room off the stack.",
   "When the stack is empty, return the maze."],
  js=dict(starter="function carveMaze() {\n    const maze = solidMaze();\n    // dig (1,1), then walk with a stack until it is empty\n    return maze;\n}\n",
    answer="function carveMaze() {\n    const maze = solidMaze();\n    const start = { x: 1, y: 1 };\n    maze[mazeIndex(start.x, start.y)] = false;\n\n    const stack = [start];\n    while (stack.length > 0) {\n        const here = stack[stack.length - 1];\n        const options = shuffle(roomNeighbours(here.x, here.y));\n\n        let dug = false;\n        for (let i = 0; i < options.length; i++) {\n            const next = options[i];\n            if (isWall(maze, next.x, next.y)) {\n                maze[mazeIndex(next.wallX, next.wallY)] = false;\n                maze[mazeIndex(next.x, next.y)] = false;\n                stack.push({ x: next.x, y: next.y });\n                dug = true;\n                break;\n            }\n        }\n\n        if (!dug) {\n            stack.pop();\n        }\n    }\n    return maze;\n}\n",
    hints=["stack[stack.length - 1] is the room you are standing in — LOOK at it, do not remove it yet.",
           "shuffle(list) is written for you; so are roomNeighbours and isWall.",
           "Knock out TWO squares: the wall between, and the room itself.",
           "Only pop when there was nowhere new to dig."],
    tests=[("The starting room is dug out",
            "const maze = carveMaze();\nassert(isWall(maze, 1, 1) === false);"),
           ("Every room gets dug out",
            "const maze = carveMaze();\nfor (let y = 1; y < MAZE_HEIGHT; y += 2) {\n    for (let x = 1; x < MAZE_WIDTH; x += 2) {\n        assert(isWall(maze, x, y) === false, 'room (' + x + ',' + y + ') was never dug');\n    }\n}"),
           ("The border stays solid",
            "const maze = carveMaze();\nfor (let x = 0; x < MAZE_WIDTH; x++) {\n    assert(isWall(maze, x, 0) && isWall(maze, x, MAZE_HEIGHT - 1));\n}\nfor (let y = 0; y < MAZE_HEIGHT; y++) {\n    assert(isWall(maze, 0, y) && isWall(maze, MAZE_WIDTH - 1, y));\n}"),
           ("Every room can be reached from the start",
            "const maze = carveMaze();\nfor (let y = 1; y < MAZE_HEIGHT; y += 2) {\n    for (let x = 1; x < MAZE_WIDTH; x += 2) {\n        assert(findPath(maze, { x: 1, y: 1 }, { x: x, y: y }).length > 0, 'room (' + x + ',' + y + ') is walled off');\n    }\n}"),
           ("The exit can be reached",
            "for (let trial = 0; trial < 12; trial++) {\n    const maze = carveMaze();\n    assert(shortestFromStart(maze) > 0, 'there is no way out of this maze');\n}"),
           ("Corners of the wall grid stay solid",
            "const maze = carveMaze();\nassert(isWall(maze, 2, 2) === true, 'the square where four walls meet can never be dug');\nassert(isWall(maze, 4, 6) === true);"),
           ("Two mazes in a row are different",
            "const a = carveMaze().join('');\nconst b = carveMaze().join('');\nassert(a !== b, 'each game should get its own maze');")]),
  py=dict(starter="def carve_maze():\n    maze = solid_maze()\n    # dig (1,1), then walk with a stack until it is empty\n    return maze\n",
    answer="def carve_maze():\n    maze = solid_maze()\n    maze[maze_index(1, 1)] = False\n\n    stack = [(1, 1)]\n    while stack:\n        x, y = stack[-1]\n        options = room_neighbours(x, y)\n        random.shuffle(options)\n\n        dug = False\n        for nx, ny, wall_x, wall_y in options:\n            if is_wall(maze, nx, ny):\n                maze[maze_index(wall_x, wall_y)] = False\n                maze[maze_index(nx, ny)] = False\n                stack.append((nx, ny))\n                dug = True\n                break\n\n        if not dug:\n            stack.pop()\n    return maze\n",
    hints=["stack[-1] is the room you are standing in - LOOK at it, do not remove it yet.",
           "random.shuffle(options) mixes the list up in place.",
           "Knock out TWO squares: the wall between, and the room itself.",
           "Only pop when there was nowhere new to dig."],
    tests=[("The starting room is dug out",
            "assert is_wall(carve_maze(), 1, 1) is False"),
           ("Every room gets dug out",
            "maze = carve_maze()\nfor y in range(1, MAZE_HEIGHT, 2):\n    for x in range(1, MAZE_WIDTH, 2):\n        assert is_wall(maze, x, y) is False, f'room ({x},{y}) was never dug'"),
           ("The border stays solid",
            "maze = carve_maze()\nfor x in range(MAZE_WIDTH):\n    assert is_wall(maze, x, 0) and is_wall(maze, x, MAZE_HEIGHT - 1)\nfor y in range(MAZE_HEIGHT):\n    assert is_wall(maze, 0, y) and is_wall(maze, MAZE_WIDTH - 1, y)"),
           ("Every room can be reached from the start",
            "maze = carve_maze()\nfor y in range(1, MAZE_HEIGHT, 2):\n    for x in range(1, MAZE_WIDTH, 2):\n        assert find_path(maze, {'x': 1, 'y': 1}, {'x': x, 'y': y}), f'room ({x},{y}) is walled off'"),
           ("The exit can be reached",
            "for _ in range(12):\n    assert shortest_from_start(carve_maze()) > 0"),
           ("Corners of the wall grid stay solid",
            "maze = carve_maze()\nassert is_wall(maze, 2, 2) is True, 'the square where four walls meet can never be dug'\nassert is_wall(maze, 4, 6) is True"),
           ("Two mazes in a row are different",
            "assert carve_maze() != carve_maze()")]),
  demo=dict(kind="carve", caption="Press the button and watch a brand-new maze appear, every time."),
  warning="LOOK at the top of the stack, do not pop it, until you are sure there is nowhere new to dig. Pop too early and the digger never walks back — leaving most of the maze solid rock."),

step("find_path", "findPath", "find_path",
  "Find the way out", "The maze can show you the shortest route.",
  "<p>The most useful algorithm in this whole collection: <strong>breadth-first search</strong>. It finds the shortest way through anything — a maze, a road map, a chess position, six degrees of separation.</p>"
  "<p>It works by spreading out evenly, like a ripple:</p>"
  "<ol><li>Put the starting square in a <strong>queue</strong>, and remember that you came to it from nowhere.</li>"
  "<li>Take the square at the FRONT of the queue.</li>"
  "<li>For each open neighbour you have never seen: remember which square you came from, and add it to the BACK of the queue.</li>"
  "<li>When you take the target off the queue, follow the 'came from' trail backwards to build the route.</li></ol>"
  "<p>The queue is the whole trick. Front in, back out means you always look at the nearest squares first — so the first time you arrive anywhere is by the shortest possible route.</p>",
  "maze. from, to — two squares.",
  "a list of squares from start to finish, or an empty list",
  ["Remember where you came from for each square. The start came from nowhere: -1.",
   "Keep a queue, starting with the first square, and take squares from the FRONT.",
   "If this square is the target, build the path and return it.",
   "Otherwise look at the four squares around it. If one is open and you have never seen it, note where it came from and add it to the BACK of the queue.",
   "If the queue empties out, there is no way through: return an empty list."],
  js=dict(starter="function findPath(maze, from, to) {\n    // breadth-first search: a queue, and a trail of where you came from\n    return [];\n}\n",
    answer="function findPath(maze, from, to) {\n    const cameFrom = {};\n    const startKey = mazeIndex(from.x, from.y);\n    cameFrom[startKey] = -1;\n\n    const queue = [from];\n    let head = 0;\n\n    while (head < queue.length) {\n        const here = queue[head];\n        head = head + 1;\n\n        if (here.x === to.x && here.y === to.y) {\n            return buildPath(cameFrom, from, to);\n        }\n\n        const steps = [[0, -1], [1, 0], [0, 1], [-1, 0]];\n        for (let i = 0; i < steps.length; i++) {\n            const nx = here.x + steps[i][0];\n            const ny = here.y + steps[i][1];\n            const key = mazeIndex(nx, ny);\n            if (!isWall(maze, nx, ny) && cameFrom[key] === undefined) {\n                cameFrom[key] = mazeIndex(here.x, here.y);\n                queue.push({ x: nx, y: ny });\n            }\n        }\n    }\n    return [];\n}\n",
    hints=["Walking the list forwards with a `head` counter is a queue: push on the end, read from the front.",
           "buildPath(cameFrom, from, to) is written for you.",
           "Check 'have I seen this square?' with cameFrom[key] === undefined — that is what stops it going round for ever."],
    tests=[("It finds a way through a real maze",
            "const maze = carveMaze();\nconst path = findPath(maze, { x: 1, y: 1 }, exitSquare());\nassert(path.length > 0, 'every maze has a way out');"),
           ("The path starts where you asked",
            "const maze = carveMaze();\nconst path = findPath(maze, { x: 1, y: 1 }, exitSquare());\nassert(path[0].x === 1 && path[0].y === 1, 'the route must start at the start');"),
           ("The path ends where you asked",
            "const maze = carveMaze();\nconst exit = exitSquare();\nconst path = findPath(maze, { x: 1, y: 1 }, exit);\nconst last = path[path.length - 1];\nassert(last.x === exit.x && last.y === exit.y);"),
           ("Every step of the path is one square",
            "const maze = carveMaze();\nconst path = findPath(maze, { x: 1, y: 1 }, exitSquare());\nfor (let i = 1; i < path.length; i++) {\n    const distance = Math.abs(path[i].x - path[i - 1].x) + Math.abs(path[i].y - path[i - 1].y);\n    assert(distance === 1, 'step ' + i + ' jumps ' + distance + ' squares');\n}"),
           ("The path never goes through rock",
            "const maze = carveMaze();\nconst path = findPath(maze, { x: 1, y: 1 }, exitSquare());\npath.forEach(function (square) {\n    assert(isWall(maze, square.x, square.y) === false, 'the route walks through a wall!');\n});"),
           ("Standing on the target gives a path of one",
            "const maze = carveMaze();\nconst path = findPath(maze, { x: 1, y: 1 }, { x: 1, y: 1 });\nassert(path.length === 1, 'gave ' + path.length);"),
           ("It really is the SHORTEST route",
            "const maze = solidMaze();\n/* dig a long way round and a short way through */\nfor (let x = 1; x <= 5; x++) { maze[mazeIndex(x, 1)] = false; }\nfor (let y = 1; y <= 5; y++) { maze[mazeIndex(1, y)] = false; maze[mazeIndex(5, y)] = false; }\nfor (let x = 1; x <= 5; x++) { maze[mazeIndex(x, 5)] = false; }\nmaze[mazeIndex(3, 1)] = false;\nfor (let y = 1; y <= 5; y++) { maze[mazeIndex(3, y)] = false; }\nconst path = findPath(maze, { x: 1, y: 1 }, { x: 3, y: 5 });\nassert(path.length === 7, 'the shortest way is 7 squares, but it found ' + path.length + ' — is your queue really a queue?');"),
           ("A walled-off square gives nothing",
            "const maze = solidMaze();\nmaze[mazeIndex(1, 1)] = false;\nmaze[mazeIndex(9, 9)] = false;\nassert(findPath(maze, { x: 1, y: 1 }, { x: 9, y: 9 }).length === 0, 'there is no way through solid rock');")]),
  py=dict(starter="def find_path(maze, start, goal):\n    # breadth-first search: a queue, and a trail of where you came from\n    return []\n",
    answer="def find_path(maze, start, goal):\n    came_from = {maze_index(start[\"x\"], start[\"y\"]): -1}\n    queue = deque([start])\n\n    while queue:\n        here = queue.popleft()\n\n        if here[\"x\"] == goal[\"x\"] and here[\"y\"] == goal[\"y\"]:\n            return build_path(came_from, goal)\n\n        for dx, dy in ((0, -1), (1, 0), (0, 1), (-1, 0)):\n            nx, ny = here[\"x\"] + dx, here[\"y\"] + dy\n            key = maze_index(nx, ny)\n            if not is_wall(maze, nx, ny) and key not in came_from:\n                came_from[key] = maze_index(here[\"x\"], here[\"y\"])\n                queue.append({\"x\": nx, \"y\": ny})\n    return []\n",
    hints=["deque is already imported. popleft() takes from the FRONT — that is what makes it a queue.",
           "build_path(came_from, goal) is written for you.",
           "`key not in came_from` is how you check you have never seen a square before."],
    tests=[("It finds a way through a real maze",
            "maze = carve_maze()\nassert find_path(maze, {'x': 1, 'y': 1}, exit_square())"),
           ("The path starts where you asked",
            "maze = carve_maze()\npath = find_path(maze, {'x': 1, 'y': 1}, exit_square())\nassert path[0] == {'x': 1, 'y': 1}"),
           ("The path ends where you asked",
            "maze = carve_maze()\ngoal = exit_square()\npath = find_path(maze, {'x': 1, 'y': 1}, goal)\nassert path[-1] == goal"),
           ("Every step of the path is one square",
            "maze = carve_maze()\npath = find_path(maze, {'x': 1, 'y': 1}, exit_square())\nfor i in range(1, len(path)):\n    d = abs(path[i]['x'] - path[i-1]['x']) + abs(path[i]['y'] - path[i-1]['y'])\n    assert d == 1, f'step {i} jumps {d} squares'"),
           ("The path never goes through rock",
            "maze = carve_maze()\nfor square in find_path(maze, {'x': 1, 'y': 1}, exit_square()):\n    assert is_wall(maze, square['x'], square['y']) is False"),
           ("Standing on the target gives a path of one",
            "maze = carve_maze()\nassert len(find_path(maze, {'x': 1, 'y': 1}, {'x': 1, 'y': 1})) == 1"),
           ("It really is the SHORTEST route",
            "maze = solid_maze()\nfor x in range(1, 6):\n    maze[maze_index(x, 1)] = False\n    maze[maze_index(x, 5)] = False\nfor y in range(1, 6):\n    maze[maze_index(1, y)] = False\n    maze[maze_index(5, y)] = False\n    maze[maze_index(3, y)] = False\npath = find_path(maze, {'x': 1, 'y': 1}, {'x': 3, 'y': 5})\nassert len(path) == 7, f'the shortest way is 7 squares, but it found {len(path)}'"),
           ("A walled-off square gives nothing",
            "maze = solid_maze()\nmaze[maze_index(1, 1)] = False\nmaze[maze_index(9, 9)] = False\nassert find_path(maze, {'x': 1, 'y': 1}, {'x': 9, 'y': 9}) == []")]),
  demo=dict(kind="game", caption="Press Hint and the shortest way out lights up as a trail of dots."),
  warning="Take from the FRONT of the queue, not the back. Take from the back and you have a stack, not a queue — it still finds a way out, but a wandering one, not the shortest."),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function. Four directions, a hint, and a new maze.</p>",
  "key", "an action name, or nothing at all",
  ["The arrows or WASD walk.",
   "H or space → 'hint'. N or Enter → 'new'. P → 'pause'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // walk, hint, new, pause\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === 'h' || k === ' ' || k === 'spacebar') { return 'hint'; }\n    if (k === 'n' || k === 'enter') { return 'new'; }\n    if (k === 'p') { return 'pause'; }\n\n    return null;\n}\n",
    hints=["H for hint, and the space bar as well since it is the easiest key to hit.",
           "toLowerCase() up front means capitals work too.",
           "Seven ifs and a return null;"],
    tests=[("The arrows walk",
            "assert(actionForKey('ArrowUp') === 'up');\nassert(actionForKey('ArrowDown') === 'down');\nassert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("WASD walks too",
            "assert(actionForKey('w') === 'up');\nassert(actionForKey('s') === 'down');\nassert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("H and space both ask for a hint",
            "assert(actionForKey('h') === 'hint');\nassert(actionForKey(' ') === 'hint');"),
           ("N and Enter both dig a new maze",
            "assert(actionForKey('n') === 'new');\nassert(actionForKey('Enter') === 'new');"),
           ("Capital letters work",
            "assert(actionForKey('H') === 'hint');\nassert(actionForKey('N') === 'new');"),
           ("Other keys do nothing",
            "assert(actionForKey('q') === null);\nassert(actionForKey('Tab') === null);")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowup\": \"up\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \"h\": \"hint\", \" \": \"hint\", \"spacebar\": \"hint\",\n        \"n\": \"new\", \"enter\": \"new\", \"p\": \"pause\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["H for hint, and the space bar as well.",
           "A dictionary is tidier than seven ifs.",
           "keys.get(...) gives None for anything not listed."],
    tests=[("The arrows walk",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD walks too",
            "assert action_for_key('w') == 'up'\nassert action_for_key('s') == 'down'\nassert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("H and space both ask for a hint",
            "assert action_for_key('h') == 'hint'\nassert action_for_key(' ') == 'hint'"),
           ("N and Enter both dig a new maze",
            "assert action_for_key('n') == 'new'\nassert action_for_key('Enter') == 'new'"),
           ("Capital letters work",
            "assert action_for_key('H') == 'hint'\nassert action_for_key('N') == 'new'"),
           ("Other keys do nothing",
            "assert action_for_key('q') is None\nassert action_for_key('Tab') is None")]),
  demo=dict(kind="final", caption="Click the page, then find your way out with the arrow keys. H if you get lost.")),
]

write_workshop("maze", "Maze Runner", STEPS)
