"""The nine steps of "Build Memory Match", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("card_index", "cardIndex", "card_index",
  "Number the squares", "The board has places to put cards.",
  "<p>Sixteen cards lie in a 4 x 4 grid, but they are stored as one flat <strong>list</strong> of sixteen. So the game needs a way to turn \"column 2, row 1\" into \"card number 6\".</p>"
  "<pre class=\"mini-code\"> 0  1  2  3\n 4  5  6  7\n 8  9 10 11\n12 13 14 15</pre>"
  "<p>Every row holds GRID_COLUMNS cards, so skipping a whole row means skipping that many places.</p>",
  "column - 0 to 3, left to right. row - 0 to 3, top to bottom.",
  "the position of that card in the flat list of sixteen",
  ["Skip a whole row of cards for every row above this one: row * GRID_COLUMNS.",
   "Add the column.",
   "Return the answer."],
  js=dict(
    starter="function cardIndex(column, row) {\n    // skip whole rows, then add the column\n}\n",
    answer="function cardIndex(column, row) {\n    return row * GRID_COLUMNS + column;\n}\n",
    hints=["The whole function is one line.",
           "Skipping `row` rows means skipping row * GRID_COLUMNS cards.",
           "return row * GRID_COLUMNS + column;"],
    tests=[("The first card is number 0", "assert(cardIndex(0, 0) === 0, 'cardIndex(0,0) gave ' + cardIndex(0, 0));"),
           ("Column 2 of row 1 is number 6", "assert(cardIndex(2, 1) === 6, 'cardIndex(2,1) gave ' + cardIndex(2, 1) + ', expected 6');"),
           ("The last card is number 15", "assert(cardIndex(3, 3) === 15, 'cardIndex(3,3) gave ' + cardIndex(3, 3));"),
           ("Moving one column right adds 1", "assert(cardIndex(1, 2) - cardIndex(0, 2) === 1, 'one step right should add 1');"),
           ("Moving one row down adds a whole row", "assert(cardIndex(0, 2) - cardIndex(0, 1) === GRID_COLUMNS, 'one step down should add GRID_COLUMNS');"),
           ("Every square gets a different number",
            "const seen = {};\nfor (let r = 0; r < GRID_ROWS; r++) { for (let c = 0; c < GRID_COLUMNS; c++) { seen[cardIndex(c, r)] = true; } }\nassert(Object.keys(seen).length === 16, 'only ' + Object.keys(seen).length + ' different numbers - two squares share one');")]),
  py=dict(
    starter="def card_index(column, row):\n    # skip whole rows, then add the column\n    pass\n",
    answer="def card_index(column, row):\n    return row * GRID_COLUMNS + column\n",
    hints=["The whole function is one line.",
           "Skipping `row` rows means skipping row * GRID_COLUMNS cards.",
           "return row * GRID_COLUMNS + column"],
    tests=[("The first card is number 0", "got = card_index(0, 0)\nassert got == 0, f'card_index(0,0) gave {got}'"),
           ("Column 2 of row 1 is number 6", "got = card_index(2, 1)\nassert got == 6, f'card_index(2,1) gave {got}, expected 6'"),
           ("The last card is number 15", "assert card_index(3, 3) == 15"),
           ("Moving one column right adds 1", "assert card_index(1, 2) - card_index(0, 2) == 1"),
           ("Moving one row down adds a whole row", "assert card_index(0, 2) - card_index(0, 1) == GRID_COLUMNS"),
           ("Every square gets a different number",
            "seen = {card_index(c, r) for r in range(GRID_ROWS) for c in range(GRID_COLUMNS)}\nassert len(seen) == 16, f'only {len(seen)} different numbers - two squares share one'")]),
  demo=dict(kind="grid", caption="Your function numbers every square on the board.")),

step("create_deck", "createDeck", "create_deck",
  "Deal the cards", "The cards exist — eight pairs, shuffled.",
  "<p>Eight symbols, each on two cards, mixed into a random order. A card remembers three things: which symbol it hides, whether it is face up, and whether it has been matched.</p>",
  "nothing",
  "a list of 16 cards, every symbol from 0 to PAIR_COUNT-1 appearing exactly twice, in a random order",
  ["Build a list holding every symbol number twice.",
   "Shuffle it.",
   "Turn each symbol into a card that starts face down and unmatched."],
  js=dict(
    starter="function createDeck() {\n    // every symbol twice, shuffled, turned into cards\n}\n",
    answer="function createDeck() {\n    const symbols = [];\n    for (let symbol = 0; symbol < PAIR_COUNT; symbol++) {\n        symbols.push(symbol);\n        symbols.push(symbol);\n    }\n    return shuffle(symbols).map(function (symbol) {\n        return { symbol: symbol, faceUp: false, matched: false };\n    });\n}\n",
    hints=["Push each symbol number twice inside a loop.",
           "shuffle(list) is written for you and returns a mixed copy.",
           "Turn the shuffled numbers into objects: { symbol: symbol, faceUp: false, matched: false }"],
    tests=[("There are sixteen cards", "const deck = createDeck();\nassert(deck.length === 16, 'got ' + deck.length + ' cards');"),
           ("Every card starts face down and unmatched",
            "const deck = createDeck();\nassert(deck.every(c => c.faceUp === false && c.matched === false), 'a card started face up or matched');"),
           ("Every symbol appears exactly twice",
            "const counts = {};\ncreateDeck().forEach(c => { counts[c.symbol] = (counts[c.symbol] || 0) + 1; });\nassert(Object.keys(counts).length === PAIR_COUNT, 'expected ' + PAIR_COUNT + ' different symbols, got ' + Object.keys(counts).length);\nassert(Object.values(counts).every(n => n === 2), 'some symbol does not appear exactly twice');"),
           ("The symbols are 0 up to PAIR_COUNT - 1",
            "assert(createDeck().every(c => c.symbol >= 0 && c.symbol < PAIR_COUNT), 'a symbol was out of range');"),
           ("The deck really is shuffled",
            "const first = createDeck().map(c => c.symbol).join('');\nlet different = false;\nfor (let i = 0; i < 20; i++) { if (createDeck().map(c => c.symbol).join('') !== first) { different = true; } }\nassert(different, 'twenty decks came out in the same order - did you shuffle?');")]),
  py=dict(
    starter="def create_deck():\n    # every symbol twice, shuffled, turned into cards\n    pass\n",
    answer="def create_deck():\n    symbols = list(range(PAIR_COUNT)) * 2\n    random.shuffle(symbols)\n    return [{\"symbol\": symbol, \"face_up\": False, \"matched\": False} for symbol in symbols]\n",
    hints=["list(range(PAIR_COUNT)) * 2 repeats the whole list - one of each, twice.",
           "random.shuffle(symbols) mixes a list in place (random is already imported).",
           "A list comprehension turns each symbol into a card dictionary."],
    tests=[("There are sixteen cards", "deck = create_deck()\nassert len(deck) == 16, f'got {len(deck)} cards'"),
           ("Every card starts face down and unmatched",
            "deck = create_deck()\nassert all(not c['face_up'] and not c['matched'] for c in deck), 'a card started face up or matched'"),
           ("Every symbol appears exactly twice",
            "symbols = [c['symbol'] for c in create_deck()]\nassert len(set(symbols)) == PAIR_COUNT, f'expected {PAIR_COUNT} different symbols, got {len(set(symbols))}'\nassert all(symbols.count(s) == 2 for s in set(symbols)), 'some symbol does not appear exactly twice'"),
           ("The symbols are 0 up to PAIR_COUNT - 1",
            "assert all(0 <= c['symbol'] < PAIR_COUNT for c in create_deck())"),
           ("The deck really is shuffled",
            "first = [c['symbol'] for c in create_deck()]\nassert any([c['symbol'] for c in create_deck()] != first for _ in range(20)), 'twenty decks came out the same - did you shuffle?'")]),
  demo=dict(kind="deck", caption="Your deck, dealt face up so you can check the pairs.")),

step("is_match", "isMatch", "is_match",
  "Do they match?", "The game can tell a pair from a miss.",
  "<p>When two cards are face up the game asks one question: are they the same symbol?</p>"
  "<p>The two turned-up cards are remembered in <code>picked</code>, a list of their <em>positions</em> in the deck — so look each one up before comparing.</p>",
  "state - the game",
  "True if exactly two cards are picked and their symbols are equal",
  ["If there are not exactly two picked cards, the answer is False.",
   "Look up both cards in the deck using the numbers in picked.",
   "Return whether their symbols are equal."],
  js=dict(
    starter="function isMatch(state) {\n    // exactly two picked cards, showing the same symbol?\n}\n",
    answer="function isMatch(state) {\n    if (state.picked.length !== 2) {\n        return false;\n    }\n    const first = state.cards[state.picked[0]];\n    const second = state.cards[state.picked[1]];\n    return first.symbol === second.symbol;\n}\n",
    hints=["Deal with the \"not two cards\" case first and return false.",
           "state.cards[state.picked[0]] is the first turned-up card.",
           "Compare the two symbols with ==="],
    tests=[("Two of the same symbol match",
            "const state = { cards: [{symbol: 3}, {symbol: 3}], picked: [0, 1] };\nassert(isMatch(state) === true, 'two 3s should match');"),
           ("Two different symbols do not",
            "const state = { cards: [{symbol: 3}, {symbol: 5}], picked: [0, 1] };\nassert(isMatch(state) === false, 'a 3 and a 5 should not match');"),
           ("One card picked is not a match",
            "assert(isMatch({ cards: [{symbol: 1}], picked: [0] }) === false, 'one card cannot be a pair');"),
           ("No cards picked is not a match",
            "assert(isMatch({ cards: [], picked: [] }) === false, 'nothing picked cannot be a pair');"),
           ("It looks the cards up, wherever they are",
            "const state = { cards: [{symbol: 0}, {symbol: 7}, {symbol: 2}, {symbol: 7}], picked: [1, 3] };\nassert(isMatch(state) === true, 'cards 1 and 3 are both 7s');")]),
  py=dict(
    starter="def is_match(state):\n    # exactly two picked cards, showing the same symbol?\n    pass\n",
    answer="def is_match(state):\n    if len(state[\"picked\"]) != 2:\n        return False\n    first = state[\"cards\"][state[\"picked\"][0]]\n    second = state[\"cards\"][state[\"picked\"][1]]\n    return first[\"symbol\"] == second[\"symbol\"]\n",
    hints=["Deal with the \"not two cards\" case first and return False.",
           "state[\"cards\"][state[\"picked\"][0]] is the first turned-up card.",
           "Compare the two symbols with =="],
    tests=[("Two of the same symbol match",
            "state = {'cards': [{'symbol': 3}, {'symbol': 3}], 'picked': [0, 1]}\nassert is_match(state) is True, 'two 3s should match'"),
           ("Two different symbols do not",
            "state = {'cards': [{'symbol': 3}, {'symbol': 5}], 'picked': [0, 1]}\nassert is_match(state) is False, 'a 3 and a 5 should not match'"),
           ("One card picked is not a match",
            "assert is_match({'cards': [{'symbol': 1}], 'picked': [0]}) is False"),
           ("No cards picked is not a match",
            "assert is_match({'cards': [], 'picked': []}) is False"),
           ("It looks the cards up, wherever they are",
            "state = {'cards': [{'symbol': 0}, {'symbol': 7}, {'symbol': 2}, {'symbol': 7}], 'picked': [1, 3]}\nassert is_match(state) is True")]),
  demo=dict(kind="pair", caption="Change the two symbols and watch your function decide.")),

step("can_flip", "canFlip", "can_flip",
  "What may be turned over?", "The game stops you cheating.",
  "<p>Not every card may be turned over. You cannot turn one that is already up, or one that has been matched, or a third card while two are showing — and nothing moves while the game is paused, finished, or while the two wrong cards are still being looked at.</p>",
  "state - the game. index - which card.",
  "True if that card may be turned face up right now",
  ["Say no if the game is over or paused.",
   "Say no while the peek timer is still running, or two cards are already picked.",
   "Say no if the index is not a real card.",
   "Otherwise say yes when the card is neither face up nor matched."],
  js=dict(
    starter="function canFlip(state, index) {\n    // four reasons to say no, then yes\n}\n",
    answer="function canFlip(state, index) {\n    if (state.isOver || state.isPaused) {\n        return false;\n    }\n    if (state.peekTimer > 0 || state.picked.length >= 2) {\n        return false;\n    }\n    const card = state.cards[index];\n    if (card === undefined) {\n        return false;\n    }\n    return !card.faceUp && !card.matched;\n}\n",
    hints=["Write the four \"no\" checks first, each returning false.",
           "state.cards[index] is undefined when the index is not a real card.",
           "The last line is: return !card.faceUp && !card.matched;"],
    tests=[("A fresh face-down card may be turned",
            "const state = createGame();\nassert(canFlip(state, 0) === true, 'the first card of a new game should be flippable');"),
           ("A card that is already face up may not",
            "const state = createGame();\nstate.cards[0].faceUp = true;\nassert(canFlip(state, 0) === false, 'it is already up');"),
           ("A matched card may not",
            "const state = createGame();\nstate.cards[0].matched = true;\nassert(canFlip(state, 0) === false, 'it has already been found');"),
           ("A third card may not be turned",
            "const state = createGame();\nstate.picked = [1, 2];\nassert(canFlip(state, 0) === false, 'only two cards at a time');"),
           ("Nothing may be turned while the wrong pair is showing",
            "const state = createGame();\nstate.peekTimer = 500;\nassert(canFlip(state, 0) === false, 'wait for the cards to turn back');"),
           ("Nothing may be turned when the game is over or paused",
            "const over = createGame(); over.isOver = true;\nconst paused = createGame(); paused.isPaused = true;\nassert(canFlip(over, 0) === false && canFlip(paused, 0) === false, 'a finished or paused game does not move');"),
           ("A card that does not exist may not be turned",
            "assert(canFlip(createGame(), 99) === false, 'there is no card 99');")]),
  py=dict(
    starter="def can_flip(state, index):\n    # four reasons to say no, then yes\n    pass\n",
    answer="def can_flip(state, index):\n    if state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n    if state[\"peek_timer\"] > 0 or len(state[\"picked\"]) >= 2:\n        return False\n    if index < 0 or index >= len(state[\"cards\"]):\n        return False\n    card = state[\"cards\"][index]\n    return not card[\"face_up\"] and not card[\"matched\"]\n",
    hints=["Write the \"no\" checks first, each returning False.",
           "Check the index is really on the board before looking the card up.",
           "The last line is: return not card[\"face_up\"] and not card[\"matched\"]"],
    tests=[("A fresh face-down card may be turned",
            "state = create_game()\nassert can_flip(state, 0) is True"),
           ("A card that is already face up may not",
            "state = create_game()\nstate['cards'][0]['face_up'] = True\nassert can_flip(state, 0) is False"),
           ("A matched card may not",
            "state = create_game()\nstate['cards'][0]['matched'] = True\nassert can_flip(state, 0) is False"),
           ("A third card may not be turned",
            "state = create_game()\nstate['picked'] = [1, 2]\nassert can_flip(state, 0) is False, 'only two cards at a time'"),
           ("Nothing may be turned while the wrong pair is showing",
            "state = create_game()\nstate['peek_timer'] = 500\nassert can_flip(state, 0) is False"),
           ("Nothing may be turned when the game is over or paused",
            "over = create_game(); over['is_over'] = True\npaused = create_game(); paused['is_paused'] = True\nassert can_flip(over, 0) is False and can_flip(paused, 0) is False"),
           ("A card that does not exist may not be turned",
            "assert can_flip(create_game(), 99) is False")]),
  demo=dict(kind="game", caption="Try to break the rules — your function will not let you.")),

step("flip_card", "flipCard", "flip_card",
  "Turn a card over", "The game can be played!",
  "<p>This is the move itself. Turn the card face up, remember it, and if it was the second one, count the move and see whether it is a pair.</p>"
  "<p>Two helpers are already written: <code>keepMatch</code> makes a pair stay up for good, and the peek timer turns a wrong pair back down a moment later.</p>",
  "state - the game. index - which card.",
  "True if the card was turned over",
  ["If can-flip says no, do nothing and answer False.",
   "Turn the card face up and add its number to picked.",
   "If two cards are now picked: add one to moves, and either keep the match or start the peek timer (PEEK_MS)."],
  js=dict(
    starter="function flipCard(state, index) {\n    // 1. allowed?\n    // 2. turn it up and remember it\n    // 3. if that was the second card: count the move, match or peek\n}\n",
    answer="function flipCard(state, index) {\n    if (!canFlip(state, index)) {\n        return false;\n    }\n\n    state.cards[index].faceUp = true;\n    state.picked.push(index);\n\n    if (state.picked.length === 2) {\n        state.moves = state.moves + 1;\n        if (isMatch(state)) {\n            keepMatch(state);\n        } else {\n            state.peekTimer = PEEK_MS;\n        }\n    }\n    return true;\n}\n",
    hints=["Start with: if (!canFlip(state, index)) { return false; }",
           "state.picked.push(index) remembers which card was turned.",
           "Only when picked.length === 2 do you count a move and check for a match."],
    tests=[("Turning a card puts it face up",
            "const state = createGame();\nflipCard(state, 0);\nassert(state.cards[0].faceUp === true, 'the card is still face down');"),
           ("The turned card is remembered",
            "const state = createGame();\nflipCard(state, 3);\nassert(state.picked.join(',') === '3', 'picked is ' + JSON.stringify(state.picked));"),
           ("One card is not yet a move",
            "const state = createGame();\nflipCard(state, 0);\nassert(state.moves === 0, 'a move is a PAIR of cards');"),
           ("Two cards count as one move",
            "const state = createGame();\nflipCard(state, 0);\nflipCard(state, 1);\nassert(state.moves === 1, 'moves is ' + state.moves);"),
           ("A matching pair stays up and scores",
            "const state = createGame();\nstate.cards = [{symbol: 1, faceUp: false, matched: false}, {symbol: 1, faceUp: false, matched: false}];\nflipCard(state, 0);\nflipCard(state, 1);\nassert(state.cards[0].matched && state.cards[1].matched, 'a matching pair should stay up');\nassert(state.pairs === 1, 'pairs is ' + state.pairs);"),
           ("A wrong pair starts the peek timer",
            "const state = createGame();\nstate.cards = [{symbol: 1, faceUp: false, matched: false}, {symbol: 2, faceUp: false, matched: false}];\nflipCard(state, 0);\nflipCard(state, 1);\nassert(state.peekTimer > 0, 'the two wrong cards must show for a moment');\nassert(state.pairs === 0, 'that was not a pair');"),
           ("Turning a card that may not be turned answers false",
            "const state = createGame();\nstate.cards[0].matched = true;\nassert(flipCard(state, 0) === false, 'a matched card cannot be turned');")]),
  py=dict(
    starter="def flip_card(state, index):\n    # 1. allowed?\n    # 2. turn it up and remember it\n    # 3. if that was the second card: count the move, match or peek\n    pass\n",
    answer="def flip_card(state, index):\n    if not can_flip(state, index):\n        return False\n\n    state[\"cards\"][index][\"face_up\"] = True\n    state[\"picked\"].append(index)\n\n    if len(state[\"picked\"]) == 2:\n        state[\"moves\"] += 1\n        if is_match(state):\n            keep_match(state)\n        else:\n            state[\"peek_timer\"] = PEEK_MS\n    return True\n",
    hints=["Start with: if not can_flip(state, index): return False",
           "state[\"picked\"].append(index) remembers which card was turned.",
           "Only when len(picked) == 2 do you count a move and check for a match."],
    tests=[("Turning a card puts it face up",
            "state = create_game()\nflip_card(state, 0)\nassert state['cards'][0]['face_up'] is True"),
           ("The turned card is remembered",
            "state = create_game()\nflip_card(state, 3)\nassert state['picked'] == [3], f\"picked is {state['picked']}\""),
           ("One card is not yet a move",
            "state = create_game()\nflip_card(state, 0)\nassert state['moves'] == 0, 'a move is a PAIR of cards'"),
           ("Two cards count as one move",
            "state = create_game()\nflip_card(state, 0)\nflip_card(state, 1)\nassert state['moves'] == 1, f\"moves is {state['moves']}\""),
           ("A matching pair stays up and scores",
            "state = create_game()\nstate['cards'] = [{'symbol': 1, 'face_up': False, 'matched': False}, {'symbol': 1, 'face_up': False, 'matched': False}]\nflip_card(state, 0)\nflip_card(state, 1)\nassert state['cards'][0]['matched'] and state['cards'][1]['matched']\nassert state['pairs'] == 1"),
           ("A wrong pair starts the peek timer",
            "state = create_game()\nstate['cards'] = [{'symbol': 1, 'face_up': False, 'matched': False}, {'symbol': 2, 'face_up': False, 'matched': False}]\nflip_card(state, 0)\nflip_card(state, 1)\nassert state['peek_timer'] > 0, 'the two wrong cards must show for a moment'\nassert state['pairs'] == 0"),
           ("Turning a card that may not be turned answers False",
            "state = create_game()\nstate['cards'][0]['matched'] = True\nassert flip_card(state, 0) is False")]),
  demo=dict(kind="game", caption="Now you can really play. Use the buttons to move and flip."),
  warning="Count the move when the SECOND card is turned, not the first — a move is a pair of cards."),

step("hide_unmatched", "hideUnmatched", "hide_unmatched",
  "Turn the wrong ones back", "Wrong pairs no longer stay up for ever.",
  "<p>A moment after two wrong cards are turned up, they go back face down — and the player has to remember what was there. That memory is the whole game.</p>",
  "state - the game",
  "nothing; it changes the cards",
  ["For every picked card that has not been matched, set it face down again.",
   "Empty the picked list.",
   "Set the peek timer back to 0."],
  js=dict(
    starter="function hideUnmatched(state) {\n    // turn the picked cards back down, forget them, stop the timer\n}\n",
    answer="function hideUnmatched(state) {\n    state.picked.forEach(function (index) {\n        if (!state.cards[index].matched) {\n            state.cards[index].faceUp = false;\n        }\n    });\n    state.picked = [];\n    state.peekTimer = 0;\n}\n",
    hints=["Loop over state.picked - those are the card numbers.",
           "Only turn a card down if it is not matched.",
           "Do not forget the last two lines: state.picked = []; and state.peekTimer = 0;"],
    tests=[("The two wrong cards go face down",
            "const state = createGame();\nstate.cards[0].faceUp = true;\nstate.cards[1].faceUp = true;\nstate.picked = [0, 1];\nhideUnmatched(state);\nassert(state.cards[0].faceUp === false && state.cards[1].faceUp === false, 'both should be face down again');"),
           ("The picked list is emptied",
            "const state = createGame();\nstate.picked = [0, 1];\nhideUnmatched(state);\nassert(state.picked.length === 0, 'picked is ' + JSON.stringify(state.picked));"),
           ("The timer is stopped",
            "const state = createGame();\nstate.picked = [0, 1];\nstate.peekTimer = 500;\nhideUnmatched(state);\nassert(state.peekTimer === 0, 'peekTimer is ' + state.peekTimer);"),
           ("Matched cards are left alone",
            "const state = createGame();\nstate.cards[0].faceUp = true;\nstate.cards[0].matched = true;\nstate.picked = [0];\nhideUnmatched(state);\nassert(state.cards[0].faceUp === true, 'a found pair must stay showing');"),
           ("Other cards are not touched",
            "const state = createGame();\nstate.cards[5].faceUp = true;\nstate.picked = [0, 1];\nhideUnmatched(state);\nassert(state.cards[5].faceUp === true, 'only the picked cards should change');")]),
  py=dict(
    starter="def hide_unmatched(state):\n    # turn the picked cards back down, forget them, stop the timer\n    pass\n",
    answer="def hide_unmatched(state):\n    for index in state[\"picked\"]:\n        if not state[\"cards\"][index][\"matched\"]:\n            state[\"cards\"][index][\"face_up\"] = False\n    state[\"picked\"] = []\n    state[\"peek_timer\"] = 0\n",
    hints=["Loop over state[\"picked\"] - those are the card numbers.",
           "Only turn a card down if it is not matched.",
           "Do not forget the last two lines."],
    tests=[("The two wrong cards go face down",
            "state = create_game()\nstate['cards'][0]['face_up'] = True\nstate['cards'][1]['face_up'] = True\nstate['picked'] = [0, 1]\nhide_unmatched(state)\nassert not state['cards'][0]['face_up'] and not state['cards'][1]['face_up']"),
           ("The picked list is emptied",
            "state = create_game()\nstate['picked'] = [0, 1]\nhide_unmatched(state)\nassert state['picked'] == []"),
           ("The timer is stopped",
            "state = create_game()\nstate['picked'] = [0, 1]\nstate['peek_timer'] = 500\nhide_unmatched(state)\nassert state['peek_timer'] == 0"),
           ("Matched cards are left alone",
            "state = create_game()\nstate['cards'][0]['face_up'] = True\nstate['cards'][0]['matched'] = True\nstate['picked'] = [0]\nhide_unmatched(state)\nassert state['cards'][0]['face_up'] is True, 'a found pair must stay showing'"),
           ("Other cards are not touched",
            "state = create_game()\nstate['cards'][5]['face_up'] = True\nstate['picked'] = [0, 1]\nhide_unmatched(state)\nassert state['cards'][5]['face_up'] is True")]),
  demo=dict(kind="game", caption="Pick two wrong cards and watch them turn back over.")),

step("is_game_won", "isGameWon", "is_game_won",
  "Have you won?", "The game knows when every pair is found.",
  "<p>The game is won when there is not a single unmatched card left on the table.</p>",
  "state - the game",
  "True if every card has been matched",
  ["Look at every card.", "If any is still unmatched, the answer is False.",
   "If you get through them all, the answer is True."],
  js=dict(
    starter="function isGameWon(state) {\n    // is every card matched?\n}\n",
    answer="function isGameWon(state) {\n    for (let i = 0; i < state.cards.length; i++) {\n        if (!state.cards[i].matched) {\n            return false;\n        }\n    }\n    return true;\n}\n",
    hints=["A for loop over state.cards, returning false the moment you find an unmatched card.",
           "return true; goes AFTER the loop.",
           "state.cards.every(c => c.matched) does the same job in one line."],
    tests=[("A brand-new game is not won",
            "assert(isGameWon(createGame()) === false, 'nothing has been found yet');"),
           ("A board with every card matched is won",
            "const state = createGame();\nstate.cards.forEach(c => { c.matched = true; });\nassert(isGameWon(state) === true, 'every pair has been found');"),
           ("One unmatched card means not won",
            "const state = createGame();\nstate.cards.forEach(c => { c.matched = true; });\nstate.cards[7].matched = false;\nassert(isGameWon(state) === false, 'card 7 is still hidden');"),
           ("Face up is not the same as matched",
            "const state = createGame();\nstate.cards.forEach(c => { c.faceUp = true; });\nassert(isGameWon(state) === false, 'turning cards up is not finding pairs');")]),
  py=dict(
    starter="def is_game_won(state):\n    # is every card matched?\n    pass\n",
    answer="def is_game_won(state):\n    return all(card[\"matched\"] for card in state[\"cards\"])\n",
    hints=["all(...) asks \"is this true of every item?\" in one word.",
           "all(card[\"matched\"] for card in state[\"cards\"])",
           "A for loop with an early `return False` works just as well."],
    tests=[("A brand-new game is not won", "assert is_game_won(create_game()) is False"),
           ("A board with every card matched is won",
            "state = create_game()\nfor card in state['cards']:\n    card['matched'] = True\nassert is_game_won(state) is True"),
           ("One unmatched card means not won",
            "state = create_game()\nfor card in state['cards']:\n    card['matched'] = True\nstate['cards'][7]['matched'] = False\nassert is_game_won(state) is False"),
           ("Face up is not the same as matched",
            "state = create_game()\nfor card in state['cards']:\n    card['face_up'] = True\nassert is_game_won(state) is False")]),
  demo=dict(kind="game", caption="Find all eight pairs and your function ends the game.")),

step("stars_for_moves", "starsForMoves", "stars_for_moves",
  "Award the stars", "Playing well is worth something.",
  "<p>Eight pairs cannot be found in fewer than eight moves, so a really sharp player finishes in about twelve. The rating: <strong>12 moves or fewer is three stars</strong>, 18 or fewer is two, and anything else is one — because everybody who finishes deserves a star.</p>",
  "moves - how many pairs were tried",
  "3, 2 or 1",
  ["12 or fewer: 3.", "18 or fewer: 2.", "Otherwise: 1."],
  js=dict(
    starter="function starsForMoves(moves) {\n    // 3 stars, 2 stars or 1 star\n}\n",
    answer="function starsForMoves(moves) {\n    if (moves <= 12) {\n        return 3;\n    }\n    if (moves <= 18) {\n        return 2;\n    }\n    return 1;\n}\n",
    hints=["Two ifs and a return - check the best score first.",
           "if (moves <= 12) { return 3; }",
           "The last line is just: return 1;"],
    tests=[("A perfect 8 moves is three stars", "assert(starsForMoves(8) === 3, 'gave ' + starsForMoves(8));"),
           ("12 moves is still three stars", "assert(starsForMoves(12) === 3, 'gave ' + starsForMoves(12));"),
           ("13 moves drops to two stars", "assert(starsForMoves(13) === 2, 'gave ' + starsForMoves(13));"),
           ("18 moves is still two stars", "assert(starsForMoves(18) === 2, 'gave ' + starsForMoves(18));"),
           ("19 moves is one star", "assert(starsForMoves(19) === 1, 'gave ' + starsForMoves(19));"),
           ("Everybody gets at least one star",
            "for (let moves = 0; moves < 200; moves++) { assert(starsForMoves(moves) >= 1, 'moves ' + moves + ' gave ' + starsForMoves(moves)); }")]),
  py=dict(
    starter="def stars_for_moves(moves):\n    # 3 stars, 2 stars or 1 star\n    pass\n",
    answer="def stars_for_moves(moves):\n    if moves <= 12:\n        return 3\n    if moves <= 18:\n        return 2\n    return 1\n",
    hints=["Two ifs and a return - check the best score first.",
           "if moves <= 12: return 3",
           "The last line is just: return 1"],
    tests=[("A perfect 8 moves is three stars", "got = stars_for_moves(8)\nassert got == 3, f'gave {got}'"),
           ("12 moves is still three stars", "assert stars_for_moves(12) == 3"),
           ("13 moves drops to two stars", "got = stars_for_moves(13)\nassert got == 2, f'gave {got}'"),
           ("18 moves is still two stars", "assert stars_for_moves(18) == 2"),
           ("19 moves is one star", "assert stars_for_moves(19) == 1"),
           ("Everybody gets at least one star",
            "for moves in range(200):\n    assert stars_for_moves(moves) >= 1, f'moves {moves} gave {stars_for_moves(moves)}'")]),
  demo=dict(kind="game", caption="Finish the board and see your rating.")),

step("action_for_key", "actionForKey", "action_for_key",
  "Wire up the keyboard", "You can play without a mouse — the game is finished!",
  "<p>Arrows move a dashed cursor around the grid and the space bar turns a card over. As always, the browser gives us a key name and the game needs the name of an action.</p>",
  "key - the key name from the browser",
  "\"up\", \"down\", \"left\", \"right\", \"flip\", \"pause\", \"restart\" - or nothing for other keys",
  ["Lowercase the key first.",
   "Arrows or WASD move the cursor.",
   "Space or Enter flips; p pauses; r restarts; anything else is nothing."],
  js=dict(
    starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // return the action name for this key, or null\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter') { return 'flip'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["One if per action, each returning straight away.",
           "Two or three keys can share an action with ||.",
           "The last line is: return null;"],
    tests=[("ArrowUp moves up", "assert(actionForKey('ArrowUp') === 'up', 'gave ' + actionForKey('ArrowUp'));"),
           ("W moves up too", "assert(actionForKey('w') === 'up');"),
           ("A capital W still works", "assert(actionForKey('W') === 'up', 'did you lowercase the key?');"),
           ("The arrows all work", "assert(actionForKey('ArrowDown') === 'down' && actionForKey('ArrowLeft') === 'left' && actionForKey('ArrowRight') === 'right');"),
           ("Space turns a card over", "assert(actionForKey(' ') === 'flip', 'gave ' + actionForKey(' '));"),
           ("Enter turns a card over too", "assert(actionForKey('Enter') === 'flip');"),
           ("P pauses and R restarts", "assert(actionForKey('p') === 'pause' && actionForKey('r') === 'restart');"),
           ("An unused key gives null", "assert(actionForKey('q') === null, 'gave ' + actionForKey('q'));")]),
  py=dict(
    starter="def action_for_key(key):\n    k = str(key).lower()\n    # a dictionary from key names to action names, then .get(k)\n    pass\n",
    answer="def action_for_key(key):\n    k = str(key).lower()\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"flip\", \"spacebar\": \"flip\", \"enter\": \"flip\",\n        \"p\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(k)\n",
    hints=["In Python a dictionary IS the lookup table.",
           "Several keys can share an action - just list them all.",
           "keys.get(k) returns None for anything that is not there."],
    tests=[("ArrowUp moves up", "got = action_for_key('ArrowUp')\nassert got == 'up', f'gave {got!r}'"),
           ("W moves up too", "assert action_for_key('w') == 'up'"),
           ("A capital W still works", "assert action_for_key('W') == 'up', 'did you lowercase the key?'"),
           ("The arrows all work", "assert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("Space turns a card over", "assert action_for_key(' ') == 'flip'"),
           ("Enter turns a card over too", "assert action_for_key('Enter') == 'flip'"),
           ("P pauses and R restarts", "assert action_for_key('p') == 'pause'\nassert action_for_key('r') == 'restart'"),
           ("An unused key gives None", "got = action_for_key('q')\nassert got is None, f'gave {got!r}'")]),
  demo=dict(kind="final", caption="Click the page, then play with the arrow keys and space."),
  warning="Return null (JavaScript) or None (Python) for keys the game does not use."),
]

write_workshop("memory", "Memory Match", STEPS)
