"""The seven steps of "Build Minesweeper", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("neighbours", "neighbours", "neighbours",
  "Who is next door?", "The board knows which squares touch.",
  "<p>Almost everything in Minesweeper is about the eight squares around a square. Write this one well and the rest of the game falls out of it.</p>"
  "<p>The neat way is to walk over the little 3×3 box around the square, skipping two things: the middle (that is the square itself) and anything that falls off the edge of the board. A corner has 3 neighbours, an edge has 5, and the middle has 8.</p>",
  "column, row",
  "a list of the squares touching it",
  ["Loop dRow from -1 to 1, and dColumn from -1 to 1 inside it.",
   "Skip the case where both are 0 — that is the square itself.",
   "Work out the neighbour's column and row.",
   "Only keep it if is-inside-grid says it is on the board."],
  js=dict(starter="function neighbours(column, row) {\n    const list = [];\n    // the 3x3 box around it, minus the middle, minus anything off the board\n    return list;\n}\n",
    answer="function neighbours(column, row) {\n    const list = [];\n    for (let dRow = -1; dRow <= 1; dRow++) {\n        for (let dColumn = -1; dColumn <= 1; dColumn++) {\n            if (dColumn === 0 && dRow === 0) {\n                continue;\n            }\n            const c = column + dColumn;\n            const r = row + dRow;\n            if (isInsideGrid(c, r)) {\n                list.push({ column: c, row: r });\n            }\n        }\n    }\n    return list;\n}\n",
    hints=["Two loops, both from -1 to 1.",
           "continue; skips the middle without leaving the loop.",
           "isInsideGrid(c, r) is already written for you."],
    tests=[("The middle of the board has 8 neighbours",
            "assert(neighbours(4, 4).length === 8, 'gave ' + neighbours(4, 4).length);"),
           ("A corner has only 3",
            "assert(neighbours(0, 0).length === 3, 'gave ' + neighbours(0, 0).length + ' — most of a corner\\'s box is off the board');"),
           ("An edge has 5",
            "assert(neighbours(4, 0).length === 5, 'gave ' + neighbours(4, 0).length);"),
           ("The other three corners work too",
            "assert(neighbours(GRID_SIZE - 1, 0).length === 3);\nassert(neighbours(0, GRID_SIZE - 1).length === 3);\nassert(neighbours(GRID_SIZE - 1, GRID_SIZE - 1).length === 3);"),
           ("A square is never its own neighbour",
            "assert(neighbours(4, 4).every(n => !(n.column === 4 && n.row === 4)), 'the middle of the box must be skipped');"),
           ("Every neighbour is on the board",
            "for (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 0; column < GRID_SIZE; column++) {\n        neighbours(column, row).forEach(function (n) {\n            assert(isInsideGrid(n.column, n.row), '(' + n.column + ',' + n.row + ') is off the board');\n        });\n    }\n}"),
           ("Neighbours are always right next door",
            "neighbours(4, 4).forEach(function (n) {\n    assert(Math.abs(n.column - 4) <= 1 && Math.abs(n.row - 4) <= 1, 'that square is not touching');\n});"),
           ("Being a neighbour goes both ways",
            "const mine = neighbours(3, 5);\nassert(mine.some(n => n.column === 4 && n.row === 5));\nassert(neighbours(4, 5).some(n => n.column === 3 && n.row === 5), 'if A touches B then B touches A');")]),
  py=dict(starter="def neighbours(column, row):\n    found = []\n    # the 3x3 box around it, minus the middle, minus anything off the board\n    return found\n",
    answer="def neighbours(column, row):\n    found = []\n    for d_row in (-1, 0, 1):\n        for d_column in (-1, 0, 1):\n            if d_column == 0 and d_row == 0:\n                continue\n            c = column + d_column\n            r = row + d_row\n            if is_inside_grid(c, r):\n                found.append((c, r))\n    return found\n",
    hints=["Two loops, both over (-1, 0, 1).",
           "continue skips the middle without leaving the loop.",
           "is_inside_grid(c, r) is already written for you."],
    tests=[("The middle of the board has 8 neighbours",
            "assert len(neighbours(4, 4)) == 8"),
           ("A corner has only 3",
            "got = len(neighbours(0, 0))\nassert got == 3, f'gave {got}'"),
           ("An edge has 5", "assert len(neighbours(4, 0)) == 5"),
           ("The other three corners work too",
            "assert len(neighbours(GRID_SIZE - 1, 0)) == 3\nassert len(neighbours(0, GRID_SIZE - 1)) == 3\nassert len(neighbours(GRID_SIZE - 1, GRID_SIZE - 1)) == 3"),
           ("A square is never its own neighbour",
            "assert (4, 4) not in neighbours(4, 4)"),
           ("Every neighbour is on the board",
            "for row in range(GRID_SIZE):\n    for column in range(GRID_SIZE):\n        for c, r in neighbours(column, row):\n            assert is_inside_grid(c, r), f'({c},{r}) is off the board'"),
           ("Neighbours are always right next door",
            "for c, r in neighbours(4, 4):\n    assert abs(c - 4) <= 1 and abs(r - 4) <= 1"),
           ("Being a neighbour goes both ways",
            "assert (4, 5) in neighbours(3, 5)\nassert (3, 5) in neighbours(4, 5), 'if A touches B then B touches A'")]),
  demo=dict(kind="grid", caption="Move around the board — the outlined squares are the neighbours of the dashed one.")),

step("count_mines", "countMines", "count_mines",
  "The numbers", "The board can tell you what it knows.",
  "<p>This is the number printed on a square, and it is the only information the game ever gives you. Everything a good player does is deduced from these numbers.</p>"
  "<p>Now that neighbours() exists, this is four lines.</p>",
  "state, column, row",
  "how many of its neighbours are mines (0 to 8)",
  ["Start a count at 0.",
   "Ask neighbours() for the squares around this one.",
   "For each, look it up in state.mines — add 1 if it is a mine.",
   "Return the count."],
  js=dict(starter="function countMines(state, column, row) {\n    // how many neighbours are mines?\n}\n",
    answer="function countMines(state, column, row) {\n    let count = 0;\n    const around = neighbours(column, row);\n    for (let i = 0; i < around.length; i++) {\n        if (state.mines[cellIndex(around[i].column, around[i].row)]) {\n            count = count + 1;\n        }\n    }\n    return count;\n}\n",
    hints=["Use the neighbours() you just wrote.",
           "cellIndex(column, row) finds a square's place in state.mines.",
           "Do NOT count the square itself — neighbours() already left it out."],
    tests=[("An empty board has no numbers",
            "const state = createGame();\nassert(countMines(state, 4, 4) === 0);"),
           ("One mine next door counts as one",
            "const state = createGame();\nstate.mines[cellIndex(3, 4)] = true;\nassert(countMines(state, 4, 4) === 1, 'gave ' + countMines(state, 4, 4));"),
           ("A diagonal mine counts too",
            "const state = createGame();\nstate.mines[cellIndex(3, 3)] = true;\nassert(countMines(state, 4, 4) === 1, 'corners touch as well as sides');"),
           ("A mine two squares away does not count",
            "const state = createGame();\nstate.mines[cellIndex(2, 4)] = true;\nassert(countMines(state, 4, 4) === 0);"),
           ("Eight mines give an 8",
            "const state = createGame();\nneighbours(4, 4).forEach(n => { state.mines[cellIndex(n.column, n.row)] = true; });\nassert(countMines(state, 4, 4) === 8, 'gave ' + countMines(state, 4, 4));"),
           ("A square does not count itself",
            "const state = createGame();\nstate.mines[cellIndex(4, 4)] = true;\nassert(countMines(state, 4, 4) === 0, 'a mine does not count itself');"),
           ("It works in a corner",
            "const state = createGame();\nstate.mines[cellIndex(1, 0)] = true;\nstate.mines[cellIndex(1, 1)] = true;\nassert(countMines(state, 0, 0) === 2);")]),
  py=dict(starter="def count_mines(state, column, row):\n    # how many neighbours are mines?\n    pass\n",
    answer="def count_mines(state, column, row):\n    return sum(1 for c, r in neighbours(column, row) if state[\"mines\"][cell_index(c, r)])\n",
    hints=["Use the neighbours() you just wrote.",
           "cell_index(column, row) finds a square's place in state['mines'].",
           "sum(1 for ... if ...) counts the ones that match."],
    tests=[("An empty board has no numbers",
            "state = create_game()\nassert count_mines(state, 4, 4) == 0"),
           ("One mine next door counts as one",
            "state = create_game()\nstate['mines'][cell_index(3, 4)] = True\nassert count_mines(state, 4, 4) == 1"),
           ("A diagonal mine counts too",
            "state = create_game()\nstate['mines'][cell_index(3, 3)] = True\nassert count_mines(state, 4, 4) == 1"),
           ("A mine two squares away does not count",
            "state = create_game()\nstate['mines'][cell_index(2, 4)] = True\nassert count_mines(state, 4, 4) == 0"),
           ("Eight mines give an 8",
            "state = create_game()\nfor c, r in neighbours(4, 4):\n    state['mines'][cell_index(c, r)] = True\nassert count_mines(state, 4, 4) == 8"),
           ("A square does not count itself",
            "state = create_game()\nstate['mines'][cell_index(4, 4)] = True\nassert count_mines(state, 4, 4) == 0"),
           ("It works in a corner",
            "state = create_game()\nstate['mines'][cell_index(1, 0)] = True\nstate['mines'][cell_index(1, 1)] = True\nassert count_mines(state, 0, 0) == 2")]),
  demo=dict(kind="count", caption="An open board with the mines showing. Move around and check the numbers yourself.")),

step("place_mines", "placeMines", "place_mines",
  "Hide the mines", "A fair board.",
  "<p>Here is a rule almost every beginner gets wrong, and every good Minesweeper gets right: <strong>the mines are laid after the first click, not before</strong>.</p>"
  "<p>Lay them first and your opening move is a coin toss — you can lose a game before you have made a single decision. Laying them afterwards, avoiding the square you clicked <em>and its neighbours</em>, guarantees your first click always opens a nice big area.</p>",
  "state, safeColumn, safeRow — where the player just clicked",
  "nothing; it fills in state.mines",
  ["Build a set of banned squares: the one clicked and all its neighbours.",
   "Make a list of every other square — those are allowed to hold a mine.",
   "Shuffle that list.",
   "Set state.mines to all false, then turn on the first MINE_COUNT of the shuffled list.",
   "Remember that the mines are now placed."],
  js=dict(starter="function placeMines(state, safeColumn, safeRow) {\n    // never under the first click, or next to it\n}\n",
    answer="function placeMines(state, safeColumn, safeRow) {\n    const banned = {};\n    banned[cellIndex(safeColumn, safeRow)] = true;\n    neighbours(safeColumn, safeRow).forEach(function (cell) {\n        banned[cellIndex(cell.column, cell.row)] = true;\n    });\n\n    const allowed = [];\n    for (let i = 0; i < CELL_COUNT; i++) {\n        if (!banned[i]) { allowed.push(i); }\n    }\n\n    for (let i = allowed.length - 1; i > 0; i--) {\n        const j = Math.floor(Math.random() * (i + 1));\n        const swap = allowed[i];\n        allowed[i] = allowed[j];\n        allowed[j] = swap;\n    }\n\n    state.mines = [];\n    for (let i = 0; i < CELL_COUNT; i++) { state.mines.push(false); }\n    for (let i = 0; i < MINE_COUNT && i < allowed.length; i++) {\n        state.mines[allowed[i]] = true;\n    }\n    state.minesPlaced = true;\n}\n",
    hints=["Ban the clicked square AND its neighbours — that is what opens a big area.",
           "Shuffling then taking the first ten is the easiest way to pick ten at random with no repeats.",
           "Do not forget state.minesPlaced = true; at the end."],
    tests=[("It lays exactly MINE_COUNT mines",
            "const state = createGame();\nplaceMines(state, 4, 4);\nassert(state.mines.filter(Boolean).length === MINE_COUNT, 'laid ' + state.mines.filter(Boolean).length);"),
           ("The clicked square is never a mine",
            "for (let trial = 0; trial < 60; trial++) {\n    const state = createGame();\n    placeMines(state, 4, 4);\n    assert(state.mines[cellIndex(4, 4)] === false, 'you cannot lose on your first click');\n}"),
           ("Nor are any of its neighbours",
            "for (let trial = 0; trial < 60; trial++) {\n    const state = createGame();\n    placeMines(state, 4, 4);\n    neighbours(4, 4).forEach(function (n) {\n        assert(state.mines[cellIndex(n.column, n.row)] === false, 'the first click must open an AREA, not one square');\n    });\n}"),
           ("It works in a corner too",
            "const state = createGame();\nplaceMines(state, 0, 0);\nassert(state.mines.filter(Boolean).length === MINE_COUNT, 'a corner has fewer safe squares, but there is still room');\nassert(state.mines[cellIndex(0, 0)] === false);"),
           ("It remembers that the mines are down",
            "const state = createGame();\nplaceMines(state, 4, 4);\nassert(state.minesPlaced === true);"),
           ("Different games get different boards",
            "const a = createGame();\nconst b = createGame();\nplaceMines(a, 4, 4);\nplaceMines(b, 4, 4);\nassert(a.mines.join('') !== b.mines.join(''), 'two games in a row should not be identical');"),
           ("Every square can hold a mine sometimes",
            "const seen = {};\nfor (let trial = 0; trial < 300; trial++) {\n    const state = createGame();\n    placeMines(state, 0, 0);\n    state.mines.forEach(function (isMine, i) { if (isMine) { seen[i] = true; } });\n}\nassert(Object.keys(seen).length > CELL_COUNT / 2, 'the mines should be spread over the whole board');")]),
  py=dict(starter="def place_mines(state, safe_column, safe_row):\n    # never under the first click, or next to it\n    pass\n",
    answer="def place_mines(state, safe_column, safe_row):\n    banned = {cell_index(safe_column, safe_row)}\n    for c, r in neighbours(safe_column, safe_row):\n        banned.add(cell_index(c, r))\n\n    allowed = [i for i in range(CELL_COUNT) if i not in banned]\n    random.shuffle(allowed)\n\n    state[\"mines\"] = [False] * CELL_COUNT\n    for index in allowed[:MINE_COUNT]:\n        state[\"mines\"][index] = True\n    state[\"mines_placed\"] = True\n",
    hints=["A set is the natural way to hold the banned squares.",
           "random.shuffle(allowed) then allowed[:MINE_COUNT] picks ten with no repeats.",
           "Do not forget state['mines_placed'] = True at the end."],
    tests=[("It lays exactly MINE_COUNT mines",
            "state = create_game()\nplace_mines(state, 4, 4)\nassert sum(state['mines']) == MINE_COUNT"),
           ("The clicked square is never a mine",
            "for _ in range(60):\n    state = create_game()\n    place_mines(state, 4, 4)\n    assert state['mines'][cell_index(4, 4)] is False"),
           ("Nor are any of its neighbours",
            "for _ in range(60):\n    state = create_game()\n    place_mines(state, 4, 4)\n    for c, r in neighbours(4, 4):\n        assert state['mines'][cell_index(c, r)] is False, 'the first click must open an AREA'"),
           ("It works in a corner too",
            "state = create_game()\nplace_mines(state, 0, 0)\nassert sum(state['mines']) == MINE_COUNT\nassert state['mines'][cell_index(0, 0)] is False"),
           ("It remembers that the mines are down",
            "state = create_game()\nplace_mines(state, 4, 4)\nassert state['mines_placed'] is True"),
           ("Different games get different boards",
            "a = create_game()\nb = create_game()\nplace_mines(a, 4, 4)\nplace_mines(b, 4, 4)\nassert a['mines'] != b['mines']"),
           ("Every square can hold a mine sometimes",
            "seen = set()\nfor _ in range(300):\n    state = create_game()\n    place_mines(state, 0, 0)\n    seen.update(i for i, m in enumerate(state['mines']) if m)\nassert len(seen) > CELL_COUNT / 2")]),
  demo=dict(kind="game", caption="Dig anywhere. Your first click can never be a mine — try it a few times."),
  warning="Ban the neighbours as well as the square itself. Ban only the one square and your first click often opens a single number, which is no fun at all."),

step("reveal_cell", "revealCell", "reveal_cell",
  "Flood fill", "One click opens a whole field.",
  "<p>This is the big one — the most valuable algorithm in this entire collection. It is called <strong>flood fill</strong>, and the paint bucket in every drawing program is the same idea.</p>"
  "<p>The rule is simple: uncover a square; if it has no mines touching it, there is nothing to work out around it, so uncover its neighbours too — and keep going.</p>"
  "<p>Rather than a function that calls itself, this version keeps a <em>to-do list</em>. Take a square off, deal with it, and if it is blank put its neighbours on. When the list is empty you are done.</p>",
  "state, column, row",
  "True if anything was uncovered",
  ["Refuse if the game is over or the square is off the board.",
   "Refuse if it is already open or flagged.",
   "If the mines are not down yet, lay them now — this click is the first.",
   "If this square IS a mine: uncover it and the game is over.",
   "Otherwise start a to-do list holding just this square. While it is not empty: take one off, skip it if it is already open or flagged, uncover it, and if count-mines is 0 add all its neighbours to the list.",
   "Finally, check whether that won the game."],
  js=dict(starter="function revealCell(state, column, row) {\n    // guards, then the first click, then FLOOD FILL\n}\n",
    answer="function revealCell(state, column, row) {\n    if (state.isOver || !isInsideGrid(column, row)) {\n        return false;\n    }\n    const first = cellIndex(column, row);\n    if (state.revealed[first] || state.flagged[first]) {\n        return false;\n    }\n\n    if (!state.minesPlaced) {\n        placeMines(state, column, row);\n    }\n\n    if (state.mines[first]) {\n        state.revealed[first] = true;\n        state.isOver = true;\n        state.hitMine = first;\n        return true;\n    }\n\n    const todo = [{ column: column, row: row }];\n    while (todo.length > 0) {\n        const cell = todo.pop();\n        const index = cellIndex(cell.column, cell.row);\n\n        if (state.revealed[index] || state.flagged[index]) {\n            continue;\n        }\n        state.revealed[index] = true;\n\n        if (countMines(state, cell.column, cell.row) === 0) {\n            const around = neighbours(cell.column, cell.row);\n            for (let i = 0; i < around.length; i++) {\n                todo.push(around[i]);\n            }\n        }\n    }\n\n    checkWin(state);\n    return true;\n}\n",
    hints=["The to-do list is just an array. push() puts one on, pop() takes one off.",
           "The 'already open' check inside the loop is what stops it going round for ever.",
           "Only spread out from squares whose count is 0."],
    tests=[("Digging a safe square opens it",
            "const state = createGame();\nrevealCell(state, 4, 4);\nassert(state.revealed[cellIndex(4, 4)] === true);"),
           ("The first click lays the mines",
            "const state = createGame();\nassert(state.minesPlaced === false);\nrevealCell(state, 4, 4);\nassert(state.minesPlaced === true);"),
           ("You can never lose on the first click",
            "for (let trial = 0; trial < 60; trial++) {\n    const state = createGame();\n    revealCell(state, 4, 4);\n    assert(state.isOver === false || state.isWon === true, 'the first click must be safe');\n}"),
           ("The first click opens more than one square",
            "for (let trial = 0; trial < 30; trial++) {\n    const state = createGame();\n    revealCell(state, 4, 4);\n    assert(revealedCount(state) >= 9, 'only ' + revealedCount(state) + ' opened — the flood should spread');\n}"),
           ("Digging a mine ends the game",
            "const state = createGame();\nrevealCell(state, 0, 0);\nlet mine = state.mines.indexOf(true);\nconst column = mine % GRID_SIZE;\nconst row = Math.floor(mine / GRID_SIZE);\nrevealCell(state, column, row);\nassert(state.isOver === true);"),
           ("A flagged square is protected",
            "const state = createGame();\nrevealCell(state, 0, 0);\n/* whichever square is still covered — the flood fill may have opened a lot */\nconst covered = state.revealed.indexOf(false);\nconst column = covered % GRID_SIZE;\nconst row = Math.floor(covered / GRID_SIZE);\ntoggleFlag(state, column, row);\nrevealCell(state, column, row);\nassert(state.revealed[covered] === false, 'a flag should stop a fumbled click');"),
           ("The flood never goes past a number",
            "const state = createGame();\nrevealCell(state, 4, 4);\nstate.revealed.forEach(function (open, i) {\n    if (open) { assert(state.mines[i] === false, 'the flood uncovered a mine!'); }\n});"),
           ("Opening every safe square wins",
            "const state = createGame();\nrevealCell(state, 4, 4);\nfor (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 0; column < GRID_SIZE; column++) {\n        if (!state.mines[cellIndex(column, row)]) { revealCell(state, column, row); }\n    }\n}\nassert(state.isWon === true, 'every safe square is open — that is a win');"),
           ("Digging the same square twice does nothing",
            "const state = createGame();\nrevealCell(state, 4, 4);\nconst before = revealedCount(state);\nassert(revealCell(state, 4, 4) === false);\nassert(revealedCount(state) === before);")]),
  py=dict(starter="def reveal_cell(state, column, row):\n    # guards, then the first click, then FLOOD FILL\n    pass\n",
    answer="def reveal_cell(state, column, row):\n    if state[\"is_over\"] or not is_inside_grid(column, row):\n        return False\n    first = cell_index(column, row)\n    if state[\"revealed\"][first] or state[\"flagged\"][first]:\n        return False\n\n    if not state[\"mines_placed\"]:\n        place_mines(state, column, row)\n\n    if state[\"mines\"][first]:\n        state[\"revealed\"][first] = True\n        state[\"is_over\"] = True\n        state[\"hit_mine\"] = first\n        return True\n\n    todo = [(column, row)]\n    while todo:\n        c, r = todo.pop()\n        index = cell_index(c, r)\n\n        if state[\"revealed\"][index] or state[\"flagged\"][index]:\n            continue\n        state[\"revealed\"][index] = True\n\n        if count_mines(state, c, r) == 0:\n            todo.extend(neighbours(c, r))\n\n    check_win(state)\n    return True\n",
    hints=["The to-do list is just a list. append() puts one on, pop() takes one off.",
           "`while todo:` keeps going until the list is empty.",
           "The 'already open' check inside the loop is what stops it going round for ever."],
    tests=[("Digging a safe square opens it",
            "state = create_game()\nreveal_cell(state, 4, 4)\nassert state['revealed'][cell_index(4, 4)] is True"),
           ("The first click lays the mines",
            "state = create_game()\nassert state['mines_placed'] is False\nreveal_cell(state, 4, 4)\nassert state['mines_placed'] is True"),
           ("You can never lose on the first click",
            "for _ in range(60):\n    state = create_game()\n    reveal_cell(state, 4, 4)\n    assert state['is_over'] is False or state['is_won'] is True"),
           ("The first click opens more than one square",
            "for _ in range(30):\n    state = create_game()\n    reveal_cell(state, 4, 4)\n    assert revealed_count(state) >= 9, 'the flood should spread'"),
           ("Digging a mine ends the game",
            "state = create_game()\nreveal_cell(state, 0, 0)\nmine = state['mines'].index(True)\nreveal_cell(state, mine % GRID_SIZE, mine // GRID_SIZE)\nassert state['is_over'] is True"),
           ("A flagged square is protected",
            "state = create_game()\nreveal_cell(state, 0, 0)\n# whichever square is still covered - the flood fill may have opened a lot\ncovered = state['revealed'].index(False)\ncolumn, row = covered % GRID_SIZE, covered // GRID_SIZE\ntoggle_flag(state, column, row)\nreveal_cell(state, column, row)\nassert state['revealed'][covered] is False, 'a flag should stop a fumbled click'"),
           ("The flood never uncovers a mine",
            "state = create_game()\nreveal_cell(state, 4, 4)\nfor i, open_ in enumerate(state['revealed']):\n    if open_:\n        assert state['mines'][i] is False"),
           ("Opening every safe square wins",
            "state = create_game()\nreveal_cell(state, 4, 4)\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE):\n        if not state['mines'][cell_index(column, row)]:\n            reveal_cell(state, column, row)\nassert state['is_won'] is True"),
           ("Digging the same square twice does nothing",
            "state = create_game()\nreveal_cell(state, 4, 4)\nbefore = revealed_count(state)\nassert reveal_cell(state, 4, 4) is False\nassert revealed_count(state) == before")]),
  demo=dict(kind="game", caption="Dig around and watch one click open a whole area."),
  warning="Check 'is it already open?' INSIDE the loop, not just before it. A square can land on the to-do list several times, and without that check the loop never ends."),

step("toggle_flag", "toggleFlag", "toggle_flag",
  "Plant a flag", "You can mark the mines you have found.",
  "<p>A flag is a note to yourself: <em>I have worked out that this one is a mine.</em></p>"
  "<p>It also protects the square. Once flagged, digging refuses to open it — which is exactly what you want when you are clicking quickly and your finger slips.</p>",
  "state, column, row",
  "True if the flag changed",
  ["Refuse if the game is over or the square is off the board.",
   "Refuse if the square is already open — there is nothing left to mark.",
   "Otherwise flip the flag: on becomes off, off becomes on."],
  js=dict(starter="function toggleFlag(state, column, row) {\n    // only on a covered square, and it flips\n}\n",
    answer="function toggleFlag(state, column, row) {\n    if (state.isOver || !isInsideGrid(column, row)) {\n        return false;\n    }\n    const index = cellIndex(column, row);\n    if (state.revealed[index]) {\n        return false;\n    }\n    state.flagged[index] = !state.flagged[index];\n    return true;\n}\n",
    hints=["Flipping a true/false is just x = !x;",
           "Three guards first, then the one line that does the work.",
           "state.flagged[index] = !state.flagged[index];"],
    tests=[("Flagging a covered square works",
            "const state = createGame();\ntoggleFlag(state, 2, 2);\nassert(state.flagged[cellIndex(2, 2)] === true);"),
           ("Flagging it again takes the flag off",
            "const state = createGame();\ntoggleFlag(state, 2, 2);\ntoggleFlag(state, 2, 2);\nassert(state.flagged[cellIndex(2, 2)] === false, 'the same action should undo itself');"),
           ("An open square cannot be flagged",
            "const state = createGame();\nrevealCell(state, 4, 4);\nassert(toggleFlag(state, 4, 4) === false);"),
           ("A square off the board cannot be flagged",
            "const state = createGame();\nassert(toggleFlag(state, -1, 4) === false);\nassert(toggleFlag(state, GRID_SIZE, 4) === false);"),
           ("The mines-left number goes down",
            "const state = createGame();\nassert(minesLeft(state) === MINE_COUNT);\ntoggleFlag(state, 2, 2);\nassert(minesLeft(state) === MINE_COUNT - 1, 'gave ' + minesLeft(state));"),
           ("A finished game cannot be flagged",
            "const state = createGame();\nstate.isOver = true;\nassert(toggleFlag(state, 2, 2) === false);")]),
  py=dict(starter="def toggle_flag(state, column, row):\n    # only on a covered square, and it flips\n    pass\n",
    answer="def toggle_flag(state, column, row):\n    if state[\"is_over\"] or not is_inside_grid(column, row):\n        return False\n    index = cell_index(column, row)\n    if state[\"revealed\"][index]:\n        return False\n    state[\"flagged\"][index] = not state[\"flagged\"][index]\n    return True\n",
    hints=["Flipping a True/False is just x = not x",
           "Three guards first, then the one line that does the work.",
           "state['flagged'][index] = not state['flagged'][index]"],
    tests=[("Flagging a covered square works",
            "state = create_game()\ntoggle_flag(state, 2, 2)\nassert state['flagged'][cell_index(2, 2)] is True"),
           ("Flagging it again takes the flag off",
            "state = create_game()\ntoggle_flag(state, 2, 2)\ntoggle_flag(state, 2, 2)\nassert state['flagged'][cell_index(2, 2)] is False"),
           ("An open square cannot be flagged",
            "state = create_game()\nreveal_cell(state, 4, 4)\nassert toggle_flag(state, 4, 4) is False"),
           ("A square off the board cannot be flagged",
            "state = create_game()\nassert toggle_flag(state, -1, 4) is False\nassert toggle_flag(state, GRID_SIZE, 4) is False"),
           ("The mines-left number goes down",
            "state = create_game()\nassert mines_left(state) == MINE_COUNT\ntoggle_flag(state, 2, 2)\nassert mines_left(state) == MINE_COUNT - 1"),
           ("A finished game cannot be flagged",
            "state = create_game()\nstate['is_over'] = True\nassert toggle_flag(state, 2, 2) is False")]),
  demo=dict(kind="game", caption="Dig a bit, then flag the squares you think are mines.")),

step("check_win", "checkWin", "check_win",
  "Have you won?", "The game can be finished.",
  "<p>The winning condition catches a lot of people out, so read it carefully: <strong>you win by uncovering every square that is not a mine</strong>.</p>"
  "<p>Flags have nothing to do with it. You can win having planted no flags at all, and flagging all ten mines is not a win on its own — the safe squares still have to be open.</p>",
  "state",
  "True if the player has won",
  ["Count the uncovered squares.",
   "If that equals CELL_COUNT - MINE_COUNT, the game is won and over.",
   "Otherwise return False."],
  js=dict(starter="function checkWin(state) {\n    // every safe square open — flags do not matter\n}\n",
    answer="function checkWin(state) {\n    if (revealedCount(state) === CELL_COUNT - MINE_COUNT) {\n        state.isWon = true;\n        state.isOver = true;\n        return true;\n    }\n    return false;\n}\n",
    hints=["revealedCount(state) is written for you.",
           "There are CELL_COUNT squares and MINE_COUNT of them are mines.",
           "Set isWon AND isOver — a won game has also finished."],
    tests=[("A new game is not won",
            "const state = createGame();\nassert(checkWin(state) === false);"),
           ("A half-open board is not won",
            "const state = createGame();\nrevealCell(state, 4, 4);\nassert(state.isWon === false || revealedCount(state) === CELL_COUNT - MINE_COUNT);"),
           ("Every safe square open is a win",
            "const state = createGame();\nplaceMines(state, 4, 4);\nfor (let i = 0; i < CELL_COUNT; i++) {\n    if (!state.mines[i]) { state.revealed[i] = true; }\n}\nassert(checkWin(state) === true);\nassert(state.isWon === true && state.isOver === true);"),
           ("One square short is not a win",
            "const state = createGame();\nplaceMines(state, 4, 4);\nlet left = 1;\nfor (let i = 0; i < CELL_COUNT; i++) {\n    if (!state.mines[i]) {\n        if (left > 0) { left = left - 1; } else { state.revealed[i] = true; }\n    }\n}\nassert(checkWin(state) === false, 'there is still one square to open');"),
           ("Flags alone do not win",
            "const state = createGame();\nplaceMines(state, 4, 4);\nfor (let i = 0; i < CELL_COUNT; i++) {\n    if (state.mines[i]) { state.flagged[i] = true; }\n}\nassert(checkWin(state) === false, 'flagging every mine is not a win — the safe squares still have to be opened');"),
           ("A real game can be won",
            "const state = createGame();\nrevealCell(state, 4, 4);\nfor (let row = 0; row < GRID_SIZE; row++) {\n    for (let column = 0; column < GRID_SIZE; column++) {\n        if (!state.mines[cellIndex(column, row)]) { revealCell(state, column, row); }\n    }\n}\nassert(state.isWon === true);")]),
  py=dict(starter="def check_win(state):\n    # every safe square open - flags do not matter\n    pass\n",
    answer="def check_win(state):\n    if revealed_count(state) == CELL_COUNT - MINE_COUNT:\n        state[\"is_won\"] = True\n        state[\"is_over\"] = True\n        return True\n    return False\n",
    hints=["revealed_count(state) is written for you.",
           "There are CELL_COUNT squares and MINE_COUNT of them are mines.",
           "Set is_won AND is_over - a won game has also finished."],
    tests=[("A new game is not won",
            "assert check_win(create_game()) is False"),
           ("Every safe square open is a win",
            "state = create_game()\nplace_mines(state, 4, 4)\nfor i in range(CELL_COUNT):\n    if not state['mines'][i]:\n        state['revealed'][i] = True\nassert check_win(state) is True\nassert state['is_won'] is True and state['is_over'] is True"),
           ("One square short is not a win",
            "state = create_game()\nplace_mines(state, 4, 4)\nsafe = [i for i in range(CELL_COUNT) if not state['mines'][i]]\nfor i in safe[1:]:\n    state['revealed'][i] = True\nassert check_win(state) is False"),
           ("Flags alone do not win",
            "state = create_game()\nplace_mines(state, 4, 4)\nfor i in range(CELL_COUNT):\n    if state['mines'][i]:\n        state['flagged'][i] = True\nassert check_win(state) is False, 'the safe squares still have to be opened'"),
           ("A real game can be won",
            "state = create_game()\nreveal_cell(state, 4, 4)\nfor row in range(GRID_SIZE):\n    for column in range(GRID_SIZE):\n        if not state['mines'][cell_index(column, row)]:\n            reveal_cell(state, column, row)\nassert state['is_won'] is True")]),
  demo=dict(kind="game", caption="Clear the whole board and see the win message.")),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function: move the cursor, dig, flag.</p>"
  "<p>The mouse works too — a left click digs and a right click flags — but a keyboard player deserves the same game.</p>",
  "key", "an action name, or nothing at all",
  ["The arrows or WASD move the cursor.",
   "Space or Enter → 'dig'. F → 'flag'.",
   "P → 'pause'. R → 'restart'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // move, dig, flag, pause, restart\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter') { return 'dig'; }\n    if (k === 'f') { return 'flag'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["The arrows are 'ArrowUp', 'ArrowDown', 'ArrowLeft' and 'ArrowRight'.",
           "Both the space bar and Enter should dig — players reach for either.",
           "Eight ifs and a return null;"],
    tests=[("The arrows move the cursor",
            "assert(actionForKey('ArrowUp') === 'up');\nassert(actionForKey('ArrowDown') === 'down');\nassert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("WASD moves it too",
            "assert(actionForKey('w') === 'up');\nassert(actionForKey('s') === 'down');\nassert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("Space digs", "assert(actionForKey(' ') === 'dig');"),
           ("Enter digs too", "assert(actionForKey('Enter') === 'dig');"),
           ("F plants a flag", "assert(actionForKey('f') === 'flag');"),
           ("Capital letters work",
            "assert(actionForKey('F') === 'flag');\nassert(actionForKey('R') === 'restart');"),
           ("Other keys do nothing",
            "assert(actionForKey('z') === null);\nassert(actionForKey('Tab') === null);")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowup\": \"up\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"dig\", \"spacebar\": \"dig\", \"enter\": \"dig\",\n        \"f\": \"flag\", \"p\": \"pause\", \"r\": \"restart\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["A dictionary is much tidier than eight ifs.",
           "Both \" \" and \"enter\" should dig.",
           "keys.get(...) gives None for anything not listed."],
    tests=[("The arrows move the cursor",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD moves it too",
            "assert action_for_key('w') == 'up'\nassert action_for_key('s') == 'down'\nassert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("Space digs", "assert action_for_key(' ') == 'dig'"),
           ("Enter digs too", "assert action_for_key('Enter') == 'dig'"),
           ("F plants a flag", "assert action_for_key('f') == 'flag'"),
           ("Capital letters work",
            "assert action_for_key('F') == 'flag'\nassert action_for_key('R') == 'restart'"),
           ("Other keys do nothing",
            "assert action_for_key('z') is None\nassert action_for_key('Tab') is None")]),
  demo=dict(kind="final", caption="Click the page, then play with the arrows, SPACE to dig and F to flag.")),
]

write_workshop("mines", "Minesweeper", STEPS)
