"""The five steps of "Build Reaction Test", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("random_delay", "randomDelay", "random_delay",
  "Make it unpredictable", "The wait is never the same twice.",
  "<p>The whole test depends on the player not knowing when the signal will come.</p>"
  "<p>Wait exactly two seconds every time and after three goes anyone can press on the beat with their eyes shut — and score 20 ms, which nobody can really do. A random wait between 1.5 and 4.5 seconds makes that impossible.</p>",
  "nothing", "milliseconds, between SHORTEST_WAIT and LONGEST_WAIT",
  ["Work out how much room there is between the two: LONGEST_WAIT - SHORTEST_WAIT.",
   "Take a random slice of that.",
   "Add it to SHORTEST_WAIT."],
  js=dict(starter="function randomDelay() {\n    // somewhere between the shortest and the longest wait\n}\n",
    answer="function randomDelay() {\n    return SHORTEST_WAIT + Math.random() * (LONGEST_WAIT - SHORTEST_WAIT);\n}\n",
    hints=["Math.random() gives a decimal from 0 up to (not including) 1.",
           "Multiply it by the gap between the two limits.",
           "return SHORTEST_WAIT + Math.random() * (LONGEST_WAIT - SHORTEST_WAIT);"],
    tests=[("It never comes back too short",
            "for (let i = 0; i < 500; i++) {\n    assert(randomDelay() >= SHORTEST_WAIT, 'gave ' + randomDelay());\n}"),
           ("It never comes back too long",
            "for (let i = 0; i < 500; i++) {\n    assert(randomDelay() <= LONGEST_WAIT, 'gave ' + randomDelay());\n}"),
           ("Two waits in a row are different",
            "assert(randomDelay() !== randomDelay(), 'a predictable wait would let a player press with their eyes shut');"),
           ("It really does use the whole range",
            "let shortest = LONGEST_WAIT;\nlet longest = SHORTEST_WAIT;\nfor (let i = 0; i < 800; i++) {\n    const wait = randomDelay();\n    if (wait < shortest) { shortest = wait; }\n    if (wait > longest) { longest = wait; }\n}\nassert(shortest < SHORTEST_WAIT + 400, 'the short waits never happen');\nassert(longest > LONGEST_WAIT - 400, 'the long waits never happen');"),
           ("The average lands in the middle",
            "let total = 0;\nfor (let i = 0; i < 2000; i++) { total = total + randomDelay(); }\nconst average = total / 2000;\nconst middle = (SHORTEST_WAIT + LONGEST_WAIT) / 2;\nassert(Math.abs(average - middle) < 300, 'the average was ' + Math.round(average) + ' but should be near ' + middle);")]),
  py=dict(starter="def random_delay():\n    # somewhere between the shortest and the longest wait\n    pass\n",
    answer="def random_delay():\n    return random.uniform(SHORTEST_WAIT, LONGEST_WAIT)\n",
    hints=["random.uniform(a, b) gives a decimal between two numbers.",
           "One line.", "return random.uniform(SHORTEST_WAIT, LONGEST_WAIT)"],
    tests=[("It never comes back too short",
            "for _ in range(500):\n    assert random_delay() >= SHORTEST_WAIT"),
           ("It never comes back too long",
            "for _ in range(500):\n    assert random_delay() <= LONGEST_WAIT"),
           ("Two waits in a row are different",
            "assert random_delay() != random_delay()"),
           ("It really does use the whole range",
            "waits = [random_delay() for _ in range(800)]\nassert min(waits) < SHORTEST_WAIT + 400, 'the short waits never happen'\nassert max(waits) > LONGEST_WAIT - 400, 'the long waits never happen'"),
           ("The average lands in the middle",
            "waits = [random_delay() for _ in range(2000)]\naverage = sum(waits) / len(waits)\nmiddle = (SHORTEST_WAIT + LONGEST_WAIT) / 2\nassert abs(average - middle) < 300, f'the average was {average:.0f}'")]),
  demo=dict(kind="phases", caption="Press to arm it, then wait. The delay is different every time.")),

step("update_game", "updateGame", "update_game",
  "The clock", "The signal arrives by itself.",
  "<p>One clock, two completely different jobs — and which one it is doing depends on the phase.</p>"
  "<p>While <strong>waiting</strong>, it is counting down to the signal. The instant it arrives, the phase becomes 'go' and the clock is <em>reset to zero</em> — because from that moment on the same clock is measuring the player.</p>"
  "<p>That single line, <code>elapsed = 0</code>, is what turns a countdown into a stopwatch.</p>",
  "state, elapsedMs", "nothing; it moves the game along",
  ["Do nothing at all if the game is paused.",
   "If the phase is 'waiting': add the time on. Once it reaches waitFor, switch to 'go' AND set the clock back to 0.",
   "If the phase is 'go': just add the time on — that is the player's score ticking up.",
   "In any other phase, nothing happens."],
  js=dict(starter="function updateGame(state, elapsedMs) {\n    // waiting: count down to the signal\n    // go: count up the player's time\n}\n",
    answer="function updateGame(state, elapsedMs) {\n    if (state.isPaused) {\n        return;\n    }\n\n    if (state.phase === 'waiting') {\n        state.elapsed = state.elapsed + elapsedMs;\n        if (state.elapsed >= state.waitFor) {\n            state.phase = 'go';\n            state.elapsed = 0;\n        }\n    } else if (state.phase === 'go') {\n        state.elapsed = state.elapsed + elapsedMs;\n    }\n}\n",
    hints=["Two branches: one for 'waiting' and one for 'go'.",
           "Do not forget state.elapsed = 0 when the signal comes.",
           "Every other phase does nothing at all."],
    tests=[("Waiting counts up towards the signal",
            "const state = createGame();\nstate.phase = 'waiting';\nstate.waitFor = 1000;\nstate.elapsed = 0;\nupdateGame(state, 400);\nassert(state.elapsed === 400);\nassert(state.phase === 'waiting', 'it is not time yet');"),
           ("The signal comes when the wait is up",
            "const state = createGame();\nstate.phase = 'waiting';\nstate.waitFor = 1000;\nstate.elapsed = 0;\nupdateGame(state, 1200);\nassert(state.phase === 'go', 'phase is ' + state.phase);"),
           ("The clock restarts at the signal",
            "const state = createGame();\nstate.phase = 'waiting';\nstate.waitFor = 1000;\nstate.elapsed = 0;\nupdateGame(state, 1200);\nassert(state.elapsed === 0, 'elapsed is ' + state.elapsed + ' — the stopwatch must start from zero, or the player gets the whole wait added to their time');"),
           ("On 'go' the clock counts the player",
            "const state = createGame();\nstate.phase = 'go';\nstate.elapsed = 0;\nupdateGame(state, 150);\nupdateGame(state, 100);\nassert(state.elapsed === 250);"),
           ("Nothing happens while showing a result",
            "const state = createGame();\nstate.phase = 'result';\nstate.elapsed = 0;\nupdateGame(state, 500);\nassert(state.elapsed === 0);"),
           ("Nothing happens before the game has begun",
            "const state = createGame();\nupdateGame(state, 500);\nassert(state.phase === 'ready');"),
           ("A paused game is frozen",
            "const state = createGame();\nstate.phase = 'go';\nstate.elapsed = 0;\nstate.isPaused = true;\nupdateGame(state, 500);\nassert(state.elapsed === 0);"),
           ("A whole wait plays out sensibly",
            "const state = createGame();\nstate.phase = 'waiting';\nstate.waitFor = 2000;\nstate.elapsed = 0;\nlet frames = 0;\nfor (let i = 0; i < 500; i++) {\n    updateGame(state, 16);\n    if (state.phase === 'go') { break; }\n    frames = frames + 1;\n}\nassert(state.phase === 'go', 'the signal never came');\nassert(frames > 100 && frames < 140, 'two seconds at 16 ms a frame is about 125 frames, but it took ' + frames);")]),
  py=dict(starter="def update_game(state, elapsed_ms):\n    # waiting: count down to the signal\n    # go: count up the player's time\n    pass\n",
    answer="def update_game(state, elapsed_ms):\n    if state[\"is_paused\"]:\n        return\n\n    if state[\"phase\"] == \"waiting\":\n        state[\"elapsed\"] += elapsed_ms\n        if state[\"elapsed\"] >= state[\"wait_for\"]:\n            state[\"phase\"] = \"go\"\n            state[\"elapsed\"] = 0\n    elif state[\"phase\"] == \"go\":\n        state[\"elapsed\"] += elapsed_ms\n",
    hints=["Two branches: one for 'waiting' and one for 'go'.",
           "Do not forget state['elapsed'] = 0 when the signal comes.",
           "Every other phase does nothing at all."],
    tests=[("Waiting counts up towards the signal",
            "state = create_game()\nstate.update({'phase': 'waiting', 'wait_for': 1000, 'elapsed': 0})\nupdate_game(state, 400)\nassert state['elapsed'] == 400 and state['phase'] == 'waiting'"),
           ("The signal comes when the wait is up",
            "state = create_game()\nstate.update({'phase': 'waiting', 'wait_for': 1000, 'elapsed': 0})\nupdate_game(state, 1200)\nassert state['phase'] == 'go'"),
           ("The clock restarts at the signal",
            "state = create_game()\nstate.update({'phase': 'waiting', 'wait_for': 1000, 'elapsed': 0})\nupdate_game(state, 1200)\nassert state['elapsed'] == 0, 'the stopwatch must start from zero'"),
           ("On 'go' the clock counts the player",
            "state = create_game()\nstate.update({'phase': 'go', 'elapsed': 0})\nupdate_game(state, 150)\nupdate_game(state, 100)\nassert state['elapsed'] == 250"),
           ("Nothing happens while showing a result",
            "state = create_game()\nstate.update({'phase': 'result', 'elapsed': 0})\nupdate_game(state, 500)\nassert state['elapsed'] == 0"),
           ("Nothing happens before the game has begun",
            "state = create_game()\nupdate_game(state, 500)\nassert state['phase'] == 'ready'"),
           ("A paused game is frozen",
            "state = create_game()\nstate.update({'phase': 'go', 'elapsed': 0, 'is_paused': True})\nupdate_game(state, 500)\nassert state['elapsed'] == 0"),
           ("A whole wait plays out sensibly",
            "state = create_game()\nstate.update({'phase': 'waiting', 'wait_for': 2000, 'elapsed': 0})\nframes = 0\nfor _ in range(500):\n    update_game(state, 16)\n    if state['phase'] == 'go':\n        break\n    frames += 1\nassert state['phase'] == 'go', 'the signal never came'\nassert 100 < frames < 140, f'about 125 frames expected, got {frames}'")]),
  demo=dict(kind="phases", caption="Press, then wait for the black. Or press Skip the wait to hurry it along."),
  warning="Reset the clock to zero when the signal comes. Forget that one line and every score includes the whole wait — three thousand milliseconds instead of three hundred."),

step("press", "press", "press",
  "The button", "The game works!",
  "<p>One button, and it means five different things depending on the phase. That is what makes this game a good place to meet the idea.</p>"
  "<p>The interesting case is 'waiting'. A press there is a <strong>false start</strong>: it does not count, it does not score, and it certainly does not become a very fast time. Miss that branch and the whole game can be beaten by holding the space bar down.</p>",
  "state", "the phase the game has moved into",
  ["Do nothing if the game is paused.",
   "'ready' → start waiting.",
   "'waiting' → that is a false start: phase becomes 'toosoon' and count it.",
   "'go' → round the elapsed time, remember it, keep only the last HISTORY_LENGTH, count the attempt, and show the result.",
   "Anything else → start waiting again."],
  js=dict(starter="function press(state) {\n    // what a press means depends on the phase\n}\n",
    answer="function press(state) {\n    if (state.isPaused) {\n        return state.phase;\n    }\n\n    if (state.phase === 'ready') {\n        startWaiting(state);\n    } else if (state.phase === 'waiting') {\n        state.phase = 'toosoon';\n        state.falseStarts = state.falseStarts + 1;\n    } else if (state.phase === 'go') {\n        state.lastTime = Math.round(state.elapsed);\n        state.times.push(state.lastTime);\n        if (state.times.length > HISTORY_LENGTH) {\n            state.times.shift();\n        }\n        state.attempts = state.attempts + 1;\n        state.phase = 'result';\n    } else {\n        startWaiting(state);\n    }\n    return state.phase;\n}\n",
    hints=["startWaiting(state) is written for you — it picks a fresh delay.",
           "shift() takes the OLDEST time off the front of the list.",
           "The last branch covers both 'result' and 'toosoon': go again."],
    tests=[("The first press arms the test",
            "const state = createGame();\nassert(press(state) === 'waiting');"),
           ("Pressing too early is a false start",
            "const state = createGame();\npress(state);\nassert(press(state) === 'toosoon', 'phase is ' + state.phase);\nassert(state.falseStarts === 1);"),
           ("A false start does not score",
            "const state = createGame();\npress(state);\npress(state);\nassert(state.times.length === 0, 'jumping the gun must not count as a very fast time');\nassert(state.attempts === 0);"),
           ("Pressing on the signal records the time",
            "const state = createGame();\nstate.phase = 'go';\nstate.elapsed = 237.4;\nassert(press(state) === 'result');\nassert(state.lastTime === 237, 'gave ' + state.lastTime);\nassert(state.times[0] === 237);"),
           ("A recorded go counts as an attempt",
            "const state = createGame();\nstate.phase = 'go';\nstate.elapsed = 300;\npress(state);\nassert(state.attempts === 1);"),
           ("Pressing after a result goes again",
            "const state = createGame();\nstate.phase = 'result';\nassert(press(state) === 'waiting');"),
           ("Pressing after a false start goes again",
            "const state = createGame();\nstate.phase = 'toosoon';\nassert(press(state) === 'waiting');"),
           ("Only the last few times are kept",
            "const state = createGame();\nfor (let i = 0; i < HISTORY_LENGTH + 5; i++) {\n    state.phase = 'go';\n    state.elapsed = 200 + i;\n    press(state);\n}\nassert(state.times.length === HISTORY_LENGTH, 'the list is ' + state.times.length + ' long');\nassert(state.times[state.times.length - 1] === 200 + HISTORY_LENGTH + 4, 'the newest go must be at the end');"),
           ("A paused game ignores presses",
            "const state = createGame();\nstate.isPaused = true;\npress(state);\nassert(state.phase === 'ready');")]),
  py=dict(starter="def press(state):\n    # what a press means depends on the phase\n    pass\n",
    answer="def press(state):\n    if state[\"is_paused\"]:\n        return state[\"phase\"]\n\n    if state[\"phase\"] == \"ready\":\n        start_waiting(state)\n    elif state[\"phase\"] == \"waiting\":\n        state[\"phase\"] = \"toosoon\"\n        state[\"false_starts\"] += 1\n    elif state[\"phase\"] == \"go\":\n        state[\"last_time\"] = round(state[\"elapsed\"])\n        state[\"times\"].append(state[\"last_time\"])\n        if len(state[\"times\"]) > HISTORY_LENGTH:\n            state[\"times\"].pop(0)\n        state[\"attempts\"] += 1\n        state[\"phase\"] = \"result\"\n    else:\n        start_waiting(state)\n    return state[\"phase\"]\n",
    hints=["start_waiting(state) is written for you - it picks a fresh delay.",
           "pop(0) takes the OLDEST time off the front of the list.",
           "The last branch covers both 'result' and 'toosoon': go again."],
    tests=[("The first press arms the test",
            "assert press(create_game()) == 'waiting'"),
           ("Pressing too early is a false start",
            "state = create_game()\npress(state)\nassert press(state) == 'toosoon'\nassert state['false_starts'] == 1"),
           ("A false start does not score",
            "state = create_game()\npress(state)\npress(state)\nassert state['times'] == [] and state['attempts'] == 0"),
           ("Pressing on the signal records the time",
            "state = create_game()\nstate.update({'phase': 'go', 'elapsed': 237.4})\nassert press(state) == 'result'\nassert state['last_time'] == 237\nassert state['times'][0] == 237"),
           ("A recorded go counts as an attempt",
            "state = create_game()\nstate.update({'phase': 'go', 'elapsed': 300})\npress(state)\nassert state['attempts'] == 1"),
           ("Pressing after a result goes again",
            "state = create_game()\nstate['phase'] = 'result'\nassert press(state) == 'waiting'"),
           ("Pressing after a false start goes again",
            "state = create_game()\nstate['phase'] = 'toosoon'\nassert press(state) == 'waiting'"),
           ("Only the last few times are kept",
            "state = create_game()\nfor i in range(HISTORY_LENGTH + 5):\n    state.update({'phase': 'go', 'elapsed': 200 + i})\n    press(state)\nassert len(state['times']) == HISTORY_LENGTH\nassert state['times'][-1] == 200 + HISTORY_LENGTH + 4"),
           ("A paused game ignores presses",
            "state = create_game()\nstate['is_paused'] = True\npress(state)\nassert state['phase'] == 'ready'")]),
  demo=dict(kind="game", caption="Play it properly. Try pressing early on purpose and see what happens."),
  warning="Handle the 'waiting' press. Without that branch, a player can hold the button down and score 0 ms every time."),

step("average_time", "averageTime", "average_time",
  "How fast are you really?", "The scoreboard fills in.",
  "<p>One good go might be luck. The average of the last eight is what you actually are.</p>"
  "<p>And once again the whole difficulty is the empty case: at the start of a game there are no times at all, and dividing by zero is not a number. Check for it first.</p>",
  "state", "the average in milliseconds, or 0 if there are none",
  ["If the list of times is empty, return 0.",
   "Add all the times up.",
   "Divide by how many there are, and round."],
  js=dict(starter="function averageTime(state) {\n    // the average of state.times, or 0 if there are none\n}\n",
    answer="function averageTime(state) {\n    if (state.times.length === 0) {\n        return 0;\n    }\n    let total = 0;\n    for (let i = 0; i < state.times.length; i++) {\n        total = total + state.times[i];\n    }\n    return Math.round(total / state.times.length);\n}\n",
    hints=["Check for an empty list BEFORE you divide.",
           "Add the times up in a loop, then divide by state.times.length.",
           "Math.round(...) gives a whole number of milliseconds."],
    tests=[("No goes gives 0",
            "const state = createGame();\nassert(averageTime(state) === 0, 'gave ' + averageTime(state) + ' — an empty list must not be divided by');"),
           ("One go is its own average",
            "const state = createGame();\nstate.times = [240];\nassert(averageTime(state) === 240);"),
           ("Two goes average out",
            "const state = createGame();\nstate.times = [200, 300];\nassert(averageTime(state) === 250);"),
           ("Four goes average out",
            "const state = createGame();\nstate.times = [240, 310, 195, 420];\nassert(averageTime(state) === 291, 'gave ' + averageTime(state));"),
           ("The answer is a whole number",
            "const state = createGame();\nstate.times = [200, 201];\nassert(averageTime(state) === Math.round(averageTime(state)));"),
           ("The average sits between the fastest and the slowest",
            "const state = createGame();\nstate.times = [180, 260, 310, 420, 600];\nconst average = averageTime(state);\nassert(average >= bestTime(state), 'the average cannot be faster than your best go');\nassert(average <= 600, 'nor slower than your worst');")]),
  py=dict(starter="def average_time(state):\n    # the average of state['times'], or 0 if there are none\n    pass\n",
    answer="def average_time(state):\n    if not state[\"times\"]:\n        return 0\n    return round(sum(state[\"times\"]) / len(state[\"times\"]))\n",
    hints=["Check for an empty list BEFORE you divide.",
           "sum(...) adds a list up and len(...) counts it.",
           "round(sum(state['times']) / len(state['times']))"],
    tests=[("No goes gives 0", "assert average_time(create_game()) == 0"),
           ("One go is its own average",
            "state = create_game()\nstate['times'] = [240]\nassert average_time(state) == 240"),
           ("Two goes average out",
            "state = create_game()\nstate['times'] = [200, 300]\nassert average_time(state) == 250"),
           ("Four goes average out",
            "state = create_game()\nstate['times'] = [240, 310, 195, 420]\nassert average_time(state) == 291"),
           ("The answer is a whole number",
            "state = create_game()\nstate['times'] = [200, 201]\nassert isinstance(average_time(state), int)"),
           ("The average sits between the fastest and the slowest",
            "state = create_game()\nstate['times'] = [180, 260, 310, 420, 600]\nassert best_time(state) <= average_time(state) <= 600")]),
  demo=dict(kind="stats", caption="Add fast and slow goes with the buttons and watch the average move.")),

step("rating", "rating", "rating",
  "Say something nice", "The game talks back.",
  "<p>A number on its own means very little to a seven-year-old. \"quick\" means a lot.</p>"
  "<p>This is a ladder of bands, and the order is the whole trick: check the fastest first. Write them the other way round and every single time would come back as \"were you asleep?\", because every number under 200 is also under 550.</p>",
  "milliseconds", "a short description",
  ["Under 200 → 'lightning!'", "Under 250 → 'very quick'",
   "Under 320 → 'quick'", "Under 400 → 'not bad'",
   "Under 550 → 'a bit slow'", "Anything else → 'were you asleep?'"],
  js=dict(starter="function rating(milliseconds) {\n    // a ladder of bands — fastest first!\n}\n",
    answer="function rating(milliseconds) {\n    if (milliseconds < 200) { return 'lightning!'; }\n    if (milliseconds < 250) { return 'very quick'; }\n    if (milliseconds < 320) { return 'quick'; }\n    if (milliseconds < 400) { return 'not bad'; }\n    if (milliseconds < 550) { return 'a bit slow'; }\n    return 'were you asleep?';\n}\n",
    hints=["Six lines, each one an if with a return.",
           "The order matters: fastest band first.",
           "The last one needs no if at all — anything that got that far is slow."],
    tests=[("150 ms is lightning", "assert(rating(150) === 'lightning!');"),
           ("230 ms is very quick", "assert(rating(230) === 'very quick');"),
           ("300 ms is quick", "assert(rating(300) === 'quick');"),
           ("380 ms is not bad", "assert(rating(380) === 'not bad');"),
           ("500 ms is a bit slow", "assert(rating(500) === 'a bit slow');"),
           ("900 ms was a nap", "assert(rating(900) === 'were you asleep?');"),
           ("The bands are in the right order",
            "assert(rating(199) === 'lightning!', '199 must be the top band — did you check the slow bands first?');\nassert(rating(200) === 'very quick', '200 is exactly the edge and belongs to the next band down');"),
           ("A faster time is never rated worse",
            "const bands = [];\nfor (let ms = 50; ms < 900; ms += 10) {\n    const band = rating(ms);\n    if (bands.length === 0 || bands[bands.length - 1] !== band) { bands.push(band); }\n}\nassert(bands.length === 6, 'there should be six bands, going from fastest to slowest — got ' + bands.length);\nassert(bands[0] === 'lightning!' && bands[5] === 'were you asleep?');")]),
  py=dict(starter="def rating(milliseconds):\n    # a ladder of bands - fastest first!\n    pass\n",
    answer="def rating(milliseconds):\n    if milliseconds < 200:\n        return \"lightning!\"\n    if milliseconds < 250:\n        return \"very quick\"\n    if milliseconds < 320:\n        return \"quick\"\n    if milliseconds < 400:\n        return \"not bad\"\n    if milliseconds < 550:\n        return \"a bit slow\"\n    return \"were you asleep?\"\n",
    hints=["Six branches, each one an if with a return.",
           "The order matters: fastest band first.",
           "The last one needs no if at all."],
    tests=[("150 ms is lightning", "assert rating(150) == 'lightning!'"),
           ("230 ms is very quick", "assert rating(230) == 'very quick'"),
           ("300 ms is quick", "assert rating(300) == 'quick'"),
           ("380 ms is not bad", "assert rating(380) == 'not bad'"),
           ("500 ms is a bit slow", "assert rating(500) == 'a bit slow'"),
           ("900 ms was a nap", "assert rating(900) == 'were you asleep?'"),
           ("The bands are in the right order",
            "assert rating(199) == 'lightning!', 'did you check the slow bands first?'\nassert rating(200) == 'very quick'"),
           ("A faster time is never rated worse",
            "bands = []\nfor ms in range(50, 900, 10):\n    band = rating(ms)\n    if not bands or bands[-1] != band:\n        bands.append(band)\nassert len(bands) == 6, f'six bands expected, got {len(bands)}'\nassert bands[0] == 'lightning!' and bands[5] == 'were you asleep?'")]),
  demo=dict(kind="final", caption="Click the page, then press SPACE and see what the game says about you."),
  warning="Fastest band first. The other way round and everybody is told they were asleep."),
]

write_workshop("reaction", "Reaction Test", STEPS)
