"""The six steps of "Build Simon Says", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("random_pad", "randomPad", "random_pad",
  "Pick a pad", "The game can think of a pad.",
  "<p>Four pads, numbered 0 to 3. Everything in this game starts with picking one at random.</p>",
  "nothing", "0, 1, 2 or 3",
  ["Pick a random whole number from 0 up to PAD_COUNT - 1."],
  js=dict(starter="function randomPad() {\n    // a random pad number\n}\n",
    answer="function randomPad() {\n    return Math.floor(Math.random() * PAD_COUNT);\n}\n",
    hints=["Math.random() gives a decimal from 0 up to (not including) 1.",
           "Multiply by PAD_COUNT and round down with Math.floor.",
           "return Math.floor(Math.random() * PAD_COUNT);"],
    tests=[("Every answer is a real pad",
            "for (let i = 0; i < 200; i++) { const pad = randomPad();\n    assert(pad >= 0 && pad < PAD_COUNT, 'gave ' + pad); }"),
           ("The answers are whole numbers",
            "for (let i = 0; i < 50; i++) { assert(Number.isInteger(randomPad()), 'gave a decimal — did you round down?'); }"),
           ("All four pads come up",
            "const seen = {};\nfor (let i = 0; i < 500; i++) { seen[randomPad()] = true; }\nassert(Object.keys(seen).length === PAD_COUNT, 'in 500 tries it only used ' + Object.keys(seen).length + ' pads');")]),
  py=dict(starter="def random_pad():\n    # a random pad number\n    pass\n",
    answer="def random_pad():\n    return random.randrange(PAD_COUNT)\n",
    hints=["random.randrange(4) gives 0, 1, 2 or 3 (random is already imported).",
           "One line.", "return random.randrange(PAD_COUNT)"],
    tests=[("Every answer is a real pad",
            "for _ in range(200):\n    pad = random_pad()\n    assert 0 <= pad < PAD_COUNT, f'gave {pad}'"),
           ("The answers are whole numbers",
            "assert all(isinstance(random_pad(), int) for _ in range(50))"),
           ("All four pads come up",
            "seen = {random_pad() for _ in range(500)}\nassert len(seen) == PAD_COUNT, f'in 500 tries it only used {len(seen)} pads'")]),
  demo=dict(kind="pads", caption="Press the buttons to light each pad — these are the four your function picks from.")),

step("add_step", "addStep", "add_step",
  "Grow the sequence", "The game remembers a longer and longer tune.",
  "<p>Every round the game adds one more pad to the end of the sequence. The sequence you already had stays exactly the same — that is what makes the game a memory test rather than a new puzzle each time.</p>",
  "sequence - the pads so far",
  "a NEW list with one more random pad on the end",
  ["Copy the list.", "Add a random pad to the end of the copy.", "Return the copy."],
  js=dict(starter="function addStep(sequence) {\n    // a copy, plus one more random pad\n}\n",
    answer="function addStep(sequence) {\n    const longer = sequence.slice();\n    longer.push(randomPad());\n    return longer;\n}\n",
    hints=["sequence.slice() copies a list.", "push() adds to the end.",
           "Use the randomPad you wrote in step 1."],
    tests=[("It makes the sequence one longer",
            "assert(addStep([]).length === 1, 'gave ' + addStep([]).length);\nassert(addStep([0, 1, 2]).length === 4);"),
           ("The pads already there do not change",
            "const before = [3, 1, 2];\nconst after = addStep(before);\nassert(after.slice(0, 3).join(',') === '3,1,2', 'gave ' + after.join(','));"),
           ("The new pad is a real pad",
            "for (let i = 0; i < 50; i++) { const pad = addStep([])[0];\n    assert(pad >= 0 && pad < PAD_COUNT, 'gave ' + pad); }"),
           ("The list you were given is not changed",
            "const before = [1];\naddStep(before);\nassert(before.length === 1, 'you changed the list you were given instead of a copy');"),
           ("It returns a new list",
            "const before = [1];\nassert(addStep(before) !== before);")]),
  py=dict(starter="def add_step(sequence):\n    # a copy, plus one more random pad\n    pass\n",
    answer="def add_step(sequence):\n    return list(sequence) + [random_pad()]\n",
    hints=["list(sequence) copies a list.",
           "Two lists can be glued together with +.",
           "return list(sequence) + [random_pad()]"],
    tests=[("It makes the sequence one longer",
            "assert len(add_step([])) == 1\nassert len(add_step([0, 1, 2])) == 4"),
           ("The pads already there do not change",
            "after = add_step([3, 1, 2])\nassert after[:3] == [3, 1, 2], f'gave {after}'"),
           ("The new pad is a real pad",
            "for _ in range(50):\n    pad = add_step([])[0]\n    assert 0 <= pad < PAD_COUNT, f'gave {pad}'"),
           ("The list you were given is not changed",
            "before = [1]\nadd_step(before)\nassert before == [1], 'you changed the list you were given'"),
           ("It returns a new list", "before = [1]\nassert add_step(before) is not before")]),
  demo=dict(kind="sequence", caption="Press Add a step and watch the sequence grow.")),

step("is_correct_so_far", "isCorrectSoFar", "is_correct_so_far",
  "Is the answer still right?", "The game watches every pad you press.",
  "<p>The game does not wait until the end to check you. After <em>every</em> press it asks: is this still right?</p>"
  "<p>Careful with two edge cases: pressing nothing yet is fine (you have not gone wrong), and pressing more pads than the sequence has is always wrong.</p>",
  "sequence - what the game flashed. input - what the player has pressed.",
  "True while every pad pressed matches the sequence",
  ["If the input is longer than the sequence, it is wrong.",
   "Compare each pressed pad with the pad in the same place in the sequence.",
   "If any pair differs, it is wrong; otherwise it is still right."],
  js=dict(starter="function isCorrectSoFar(sequence, input) {\n    // every pressed pad must match the same place in the sequence\n}\n",
    answer="function isCorrectSoFar(sequence, input) {\n    if (input.length > sequence.length) {\n        return false;\n    }\n    for (let i = 0; i < input.length; i++) {\n        if (input[i] !== sequence[i]) {\n            return false;\n        }\n    }\n    return true;\n}\n",
    hints=["Deal with the too-long case first.",
           "Loop over the INPUT, not the sequence — the player may not have finished.",
           "return true; goes after the loop."],
    tests=[("Nothing pressed yet is fine",
            "assert(isCorrectSoFar([1, 2, 3], []) === true, 'the player has not gone wrong yet');"),
           ("A right first pad is fine",
            "assert(isCorrectSoFar([1, 2, 3], [1]) === true);"),
           ("A wrong first pad is not",
            "assert(isCorrectSoFar([1, 2, 3], [2]) === false, 'gave ' + isCorrectSoFar([1, 2, 3], [2]));"),
           ("A right start of a longer answer is fine",
            "assert(isCorrectSoFar([1, 2, 3], [1, 2]) === true);"),
           ("The whole sequence is fine",
            "assert(isCorrectSoFar([1, 2, 3], [1, 2, 3]) === true);"),
           ("Going wrong at the end is spotted",
            "assert(isCorrectSoFar([1, 2, 3], [1, 2, 0]) === false, 'the last pad is wrong');"),
           ("Too many pads is wrong",
            "assert(isCorrectSoFar([1], [1, 1]) === false, 'the player pressed more pads than the game flashed');")]),
  py=dict(starter="def is_correct_so_far(sequence, input_pads):\n    # every pressed pad must match the same place in the sequence\n    pass\n",
    answer="def is_correct_so_far(sequence, input_pads):\n    if len(input_pads) > len(sequence):\n        return False\n    return all(pad == sequence[i] for i, pad in enumerate(input_pads))\n",
    hints=["Deal with the too-long case first.",
           "enumerate(input_pads) gives the position and the pad together.",
           "all(...) is True when every comparison is."],
    tests=[("Nothing pressed yet is fine",
            "assert is_correct_so_far([1, 2, 3], []) is True"),
           ("A right first pad is fine", "assert is_correct_so_far([1, 2, 3], [1]) is True"),
           ("A wrong first pad is not",
            "got = is_correct_so_far([1, 2, 3], [2])\nassert got is False, f'gave {got!r}'"),
           ("A right start of a longer answer is fine",
            "assert is_correct_so_far([1, 2, 3], [1, 2]) is True"),
           ("The whole sequence is fine", "assert is_correct_so_far([1, 2, 3], [1, 2, 3]) is True"),
           ("Going wrong at the end is spotted",
            "assert is_correct_so_far([1, 2, 3], [1, 2, 0]) is False"),
           ("Too many pads is wrong",
            "assert is_correct_so_far([1], [1, 1]) is False")]),
  demo=dict(kind="sequence", caption="Build a sequence, then press pads and watch the answer change."),
  warning="An empty input is CORRECT so far. If you get that wrong the game ends the moment the player's turn starts."),

step("is_round_complete", "isRoundComplete", "is_round_complete",
  "Has the round been finished?", "Finishing a round starts the next one.",
  "<p>A round is finished when the player has repeated the whole sequence — right, <em>and</em> all of it.</p>"
  "<p>This one is built entirely from the function you just wrote.</p>",
  "sequence, input",
  "True when the input matches the sequence exactly",
  ["It must be correct so far.",
   "AND the input must be the same length as the sequence."],
  js=dict(starter="function isRoundComplete(sequence, input) {\n    // right so far, and the same length\n}\n",
    answer="function isRoundComplete(sequence, input) {\n    return isCorrectSoFar(sequence, input) && input.length === sequence.length;\n}\n",
    hints=["Reuse isCorrectSoFar — you already wrote it.",
           "Join the two checks with &&.",
           "return isCorrectSoFar(sequence, input) && input.length === sequence.length;"],
    tests=[("Repeating the whole sequence finishes the round",
            "assert(isRoundComplete([1, 2], [1, 2]) === true);"),
           ("Half an answer does not",
            "assert(isRoundComplete([1, 2], [1]) === false, 'there is one pad still to press');"),
           ("Nothing pressed does not",
            "assert(isRoundComplete([1, 2], []) === false);"),
           ("A wrong answer of the right length does not",
            "assert(isRoundComplete([1, 2], [1, 3]) === false, 'the second pad is wrong');"),
           ("A one-pad round works",
            "assert(isRoundComplete([3], [3]) === true);")]),
  py=dict(starter="def is_round_complete(sequence, input_pads):\n    # right so far, and the same length\n    pass\n",
    answer="def is_round_complete(sequence, input_pads):\n    return is_correct_so_far(sequence, input_pads) and len(input_pads) == len(sequence)\n",
    hints=["Reuse is_correct_so_far.", "Join the two checks with `and`.",
           "return is_correct_so_far(sequence, input_pads) and len(input_pads) == len(sequence)"],
    tests=[("Repeating the whole sequence finishes the round",
            "assert is_round_complete([1, 2], [1, 2]) is True"),
           ("Half an answer does not", "assert is_round_complete([1, 2], [1]) is False"),
           ("Nothing pressed does not", "assert is_round_complete([1, 2], []) is False"),
           ("A wrong answer of the right length does not",
            "assert is_round_complete([1, 2], [1, 3]) is False"),
           ("A one-pad round works", "assert is_round_complete([3], [3]) is True")]),
  demo=dict(kind="sequence", caption="Press the pads in the right order — the note says COMPLETE when you finish.")),

step("flash_interval", "flashInterval", "flash_interval",
  "Make it faster", "Later rounds flash quicker.",
  "<p>Round 1 flashes each pad for 620 milliseconds — slow and friendly. Every round takes 25 ms off, down to a floor of 260 ms.</p>"
  "<p>Without the floor, round 30 would flash for a negative time and you would see nothing at all.</p>",
  "round - which round you are on", "milliseconds each flash lasts",
  ["Work out 620 - (round - 1) * 25.", "Never return less than 260."],
  js=dict(starter="function flashInterval(round) {\n    // 620 ms in round 1, 25 ms quicker each round, never below 260\n}\n",
    answer="function flashInterval(round) {\n    const milliseconds = 620 - (round - 1) * 25;\n    if (milliseconds < 260) {\n        return 260;\n    }\n    return milliseconds;\n}\n",
    hints=["Work the number out into a variable first.",
           "Round 1 must give exactly 620, so the sum uses (round - 1).",
           "Math.max(260, milliseconds) does the floor in one line."],
    tests=[("Round 1 flashes for 620 ms", "assert(flashInterval(1) === 620, 'gave ' + flashInterval(1));"),
           ("Round 2 flashes for 595 ms", "assert(flashInterval(2) === 595, 'gave ' + flashInterval(2));"),
           ("Round 5 flashes for 520 ms", "assert(flashInterval(5) === 520);"),
           ("Round 20 has hit the floor", "assert(flashInterval(20) === 260, 'gave ' + flashInterval(20));"),
           ("Round 99 is still 260", "assert(flashInterval(99) === 260);"),
           ("It never goes below 260",
            "for (let round = 1; round <= 60; round++) { assert(flashInterval(round) >= 260, 'round ' + round + ' gave ' + flashInterval(round)); }")]),
  py=dict(starter="def flash_interval(round_number):\n    # 620 ms in round 1, 25 ms quicker each round, never below 260\n    pass\n",
    answer="def flash_interval(round_number):\n    return max(260, 620 - (round_number - 1) * 25)\n",
    hints=["max(260, something) gives 260 whenever something drops below it.",
           "Round 1 must give exactly 620, so the sum uses (round_number - 1).",
           "return max(260, 620 - (round_number - 1) * 25)"],
    tests=[("Round 1 flashes for 620 ms", "got = flash_interval(1)\nassert got == 620, f'gave {got}'"),
           ("Round 2 flashes for 595 ms", "assert flash_interval(2) == 595"),
           ("Round 5 flashes for 520 ms", "assert flash_interval(5) == 520"),
           ("Round 20 has hit the floor", "got = flash_interval(20)\nassert got == 260, f'gave {got}'"),
           ("Round 99 is still 260", "assert flash_interval(99) == 260"),
           ("It never goes below 260",
            "for r in range(1, 61):\n    assert flash_interval(r) >= 260, f'round {r} gave {flash_interval(r)}'")]),
  demo=dict(kind="game", caption="Play a few rounds and feel the flashes speed up.")),

step("press_pad", "pressPad", "press_pad",
  "Press a pad", "The game can be played!",
  "<p>The move itself, and it pulls together everything you have written.</p>"
  "<p>One press can do three different things: nothing (if it is not your turn), end the game (if it is wrong), or start the next round (if it finishes the sequence).</p>",
  "state - the game. pad - 0 to 3.",
  "True if the press counted",
  ["Ignore the press unless state.phase is 'play' and the game is running.",
   "Add the pad to the input, light it up and reset the flash timer.",
   "If the answer is no longer correct so far: the phase becomes 'over' and the game ends.",
   "If the round is complete: add score-for-round points, add 1 to the round, grow the sequence with add-step, empty the input, and go back to phase 'watch' at the first flash."],
  js=dict(starter="function pressPad(state, pad) {\n    // 1. only during your turn\n    // 2. remember the press\n    // 3. wrong? game over. complete? next round.\n}\n",
    answer="function pressPad(state, pad) {\n    if (state.phase !== 'play' || state.isOver || state.isPaused) {\n        return false;\n    }\n\n    state.input.push(pad);\n    state.lit = pad;\n    state.flashTimer = 0;\n\n    if (!isCorrectSoFar(state.sequence, state.input)) {\n        state.phase = 'over';\n        state.isOver = true;\n        return true;\n    }\n\n    if (isRoundComplete(state.sequence, state.input)) {\n        state.score = state.score + scoreForRound(state.round);\n        state.round = state.round + 1;\n        state.sequence = addStep(state.sequence);\n        state.input = [];\n        state.phase = 'watch';\n        state.flashIndex = 0;\n        state.flashOn = true;\n        state.lit = state.sequence[0];\n    }\n    return true;\n}\n",
    hints=["The guard is: state.phase !== 'play' — presses during the flashing do not count.",
           "Check for WRONG before checking for complete.",
           "Starting the next round means resetting input, flashIndex and phase together."],
    tests=[("A press during your turn is remembered",
            "const state = createGame();\nstate.phase = 'play';\nstate.sequence = [1, 2];\nstate.input = [];\npressPad(state, 1);\nassert(state.input.join(',') === '1', 'input is ' + JSON.stringify(state.input));"),
           ("A press while the game is flashing is ignored",
            "const state = createGame();\nstate.phase = 'watch';\nstate.sequence = [1];\nstate.input = [];\npressPad(state, 1);\nassert(state.input.length === 0, 'presses only count on your turn');"),
           ("A wrong pad ends the game",
            "const state = createGame();\nstate.phase = 'play';\nstate.sequence = [1, 2];\nstate.input = [];\npressPad(state, 3);\nassert(state.isOver === true, 'pad 3 is not pad 1');"),
           ("Finishing the sequence scores and starts the next round",
            "const state = createGame();\nstate.phase = 'play';\nstate.round = 1;\nstate.sequence = [1];\nstate.input = [];\npressPad(state, 1);\nassert(state.score === 10, 'score is ' + state.score);\nassert(state.round === 2, 'round is ' + state.round);\nassert(state.sequence.length === 2, 'the sequence should have grown');\nassert(state.input.length === 0, 'the input should be empty for the new round');\nassert(state.phase === 'watch', 'the game should be flashing again');"),
           ("Half an answer keeps your turn going",
            "const state = createGame();\nstate.phase = 'play';\nstate.sequence = [1, 2];\nstate.input = [];\npressPad(state, 1);\nassert(state.phase === 'play', 'there is still one pad to press');\nassert(state.isOver === false);"),
           ("A finished game ignores presses",
            "const state = createGame();\nstate.phase = 'play';\nstate.isOver = true;\nstate.sequence = [1];\nstate.input = [];\npressPad(state, 1);\nassert(state.input.length === 0);")]),
  py=dict(starter="def press_pad(state, pad):\n    # 1. only during your turn\n    # 2. remember the press\n    # 3. wrong? game over. complete? next round.\n    pass\n",
    answer="def press_pad(state, pad):\n    if state[\"phase\"] != \"play\" or state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n\n    state[\"input\"].append(pad)\n    state[\"lit\"] = pad\n    state[\"flash_timer\"] = 0\n\n    if not is_correct_so_far(state[\"sequence\"], state[\"input\"]):\n        state[\"phase\"] = \"over\"\n        state[\"is_over\"] = True\n        return True\n\n    if is_round_complete(state[\"sequence\"], state[\"input\"]):\n        state[\"score\"] += score_for_round(state[\"round\"])\n        state[\"round\"] += 1\n        state[\"sequence\"] = add_step(state[\"sequence\"])\n        state[\"input\"] = []\n        state[\"phase\"] = \"watch\"\n        state[\"flash_index\"] = 0\n        state[\"flash_on\"] = True\n        state[\"lit\"] = state[\"sequence\"][0]\n    return True\n",
    hints=["The guard is: state[\"phase\"] != \"play\".",
           "Check for WRONG before checking for complete.",
           "Starting the next round resets input, flash_index and phase together."],
    tests=[("A press during your turn is remembered",
            "state = create_game()\nstate.update({'phase': 'play', 'sequence': [1, 2], 'input': []})\npress_pad(state, 1)\nassert state['input'] == [1], f\"input is {state['input']}\""),
           ("A press while the game is flashing is ignored",
            "state = create_game()\nstate.update({'phase': 'watch', 'sequence': [1], 'input': []})\npress_pad(state, 1)\nassert state['input'] == [], 'presses only count on your turn'"),
           ("A wrong pad ends the game",
            "state = create_game()\nstate.update({'phase': 'play', 'sequence': [1, 2], 'input': []})\npress_pad(state, 3)\nassert state['is_over'] is True"),
           ("Finishing the sequence scores and starts the next round",
            "state = create_game()\nstate.update({'phase': 'play', 'round': 1, 'sequence': [1], 'input': []})\npress_pad(state, 1)\nassert state['score'] == 10, f\"score is {state['score']}\"\nassert state['round'] == 2\nassert len(state['sequence']) == 2, 'the sequence should have grown'\nassert state['input'] == []\nassert state['phase'] == 'watch'"),
           ("Half an answer keeps your turn going",
            "state = create_game()\nstate.update({'phase': 'play', 'sequence': [1, 2], 'input': []})\npress_pad(state, 1)\nassert state['phase'] == 'play' and state['is_over'] is False"),
           ("A finished game ignores presses",
            "state = create_game()\nstate.update({'phase': 'play', 'is_over': True, 'sequence': [1], 'input': []})\npress_pad(state, 1)\nassert state['input'] == []")]),
  demo=dict(kind="final", caption="Watch the flashes, then repeat them. Click the page and the number keys work too."),
  warning="Check whether the answer is WRONG before checking whether it is complete — otherwise a wrong last pad would still finish the round."),
]

write_workshop("simon", "Simon Says", STEPS)
