"""The six steps of "Build Sokoban", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("is_wall", "isWall", "is_wall",
  "What can you walk on?", "The walls become solid.",
  "<p>The level is stored as a list of true/false: is this square a wall?</p>"
  "<p>There is one extra rule worth copying into every grid game you ever write: anything <em>outside</em> the level counts as a wall too. Get that right here and no other function ever has to worry about walking off the edge of the world.</p>",
  "state, x, y", "True if you cannot walk there",
  ["If x or y is outside the level, return True.",
   "Otherwise look the square up in state.walls."],
  js=dict(starter="function isWall(state, x, y) {\n    // outside the level counts as a wall too\n}\n",
    answer="function isWall(state, x, y) {\n    if (x < 0 || x >= LEVEL_WIDTH || y < 0 || y >= LEVEL_HEIGHT) {\n        return true;\n    }\n    return state.walls[cellIndex(x, y)];\n}\n",
    hints=["Check the edges FIRST, before looking anything up in the list.",
           "cellIndex(x, y) turns a pair into a place in the list.",
           "Outside the level returns true — not false."],
    tests=[("The border of every level is wall",
            "const state = createGame();\nassert(isWall(state, 0, 0) === true);\nassert(isWall(state, 0, 3) === true);"),
           ("Open floor is not",
            "const state = createGame();\nassert(isWall(state, 4, 3) === false, 'the player is standing there');"),
           ("Outside the level counts as wall",
            "const state = createGame();\nassert(isWall(state, -1, 3) === true, 'off the left edge');\nassert(isWall(state, LEVEL_WIDTH, 3) === true, 'off the right edge');\nassert(isWall(state, 4, -1) === true);\nassert(isWall(state, 4, LEVEL_HEIGHT) === true);"),
           ("The level with a wall in the middle knows about it",
            "const state = createGame();\nloadLevel(state, 3);\nassert(isWall(state, 4, 2) === true, 'level 4 has a wall standing in the way');"),
           ("You can never walk off any level",
            "const state = createGame();\nfor (let level = 0; level < LEVELS.length; level++) {\n    loadLevel(state, level);\n    for (let x = 0; x < LEVEL_WIDTH; x++) {\n        assert(isWall(state, x, 0) && isWall(state, x, LEVEL_HEIGHT - 1), 'level ' + level + ' has a hole in its top or bottom wall');\n    }\n}")]),
  py=dict(starter="def is_wall(state, x, y):\n    # outside the level counts as a wall too\n    pass\n",
    answer="def is_wall(state, x, y):\n    if not (0 <= x < LEVEL_WIDTH) or not (0 <= y < LEVEL_HEIGHT):\n        return True\n    return state[\"walls\"][cell_index(x, y)]\n",
    hints=["Check the edges FIRST, before looking anything up in the list.",
           "0 <= x < LEVEL_WIDTH checks both edges in one go.",
           "Outside the level returns True - not False."],
    tests=[("The border of every level is wall",
            "state = create_game()\nassert is_wall(state, 0, 0) is True\nassert is_wall(state, 0, 3) is True"),
           ("Open floor is not",
            "state = create_game()\nassert is_wall(state, 4, 3) is False"),
           ("Outside the level counts as wall",
            "state = create_game()\nassert is_wall(state, -1, 3) is True\nassert is_wall(state, LEVEL_WIDTH, 3) is True\nassert is_wall(state, 4, -1) is True\nassert is_wall(state, 4, LEVEL_HEIGHT) is True"),
           ("The level with a wall in the middle knows about it",
            "state = create_game()\nload_level(state, 3)\nassert is_wall(state, 4, 2) is True"),
           ("You can never walk off any level",
            "state = create_game()\nfor level in range(len(LEVELS)):\n    load_level(state, level)\n    for x in range(LEVEL_WIDTH):\n        assert is_wall(state, x, 0) and is_wall(state, x, LEVEL_HEIGHT - 1)")]),
  demo=dict(kind="walls", caption="Move the dashed box around and see which squares are wall.")),

step("box_at", "boxAt", "box_at",
  "Which box is that?", "The game can find its boxes.",
  "<p>The boxes are a list of positions, and the move function needs to know not just <em>whether</em> there is a box in the way, but <strong>which one</strong> — so it can move that one.</p>"
  "<p>So this returns a number: 0, 1, 2 … or -1 for none. Using -1 to mean 'not found' is an old convention you will meet everywhere.</p>",
  "state, x, y", "which box it is, or -1 for none",
  ["Look through the boxes one at a time.",
   "If a box's x and y both match, return its position in the list.",
   "If you get all the way through, return -1."],
  js=dict(starter="function boxAt(state, x, y) {\n    // which box is standing here? -1 for none\n}\n",
    answer="function boxAt(state, x, y) {\n    for (let i = 0; i < state.boxes.length; i++) {\n        if (state.boxes[i].x === x && state.boxes[i].y === y) {\n            return i;\n        }\n    }\n    return -1;\n}\n",
    hints=["A for loop with the counter i, so you can return i itself.",
           "BOTH the x and the y have to match.",
           "return -1; goes after the loop, not inside it."],
    tests=[("It finds a box that is there",
            "const state = createGame();\nconst box = state.boxes[0];\nassert(boxAt(state, box.x, box.y) === 0);"),
           ("Empty floor gives -1",
            "const state = createGame();\nassert(boxAt(state, 1, 1) === -1, 'gave ' + boxAt(state, 1, 1));"),
           ("It finds the SECOND box too",
            "const state = createGame();\nloadLevel(state, 2);\nconst box = state.boxes[1];\nassert(boxAt(state, box.x, box.y) === 1, 'gave ' + boxAt(state, box.x, box.y) + ' — the answer must say WHICH box');"),
           ("Both the x and the y have to match",
            "const state = createGame();\nconst box = state.boxes[0];\nassert(boxAt(state, box.x, box.y + 1) === -1, 'the square below the box is empty');\nassert(boxAt(state, box.x + 1, box.y) === -1);"),
           ("Every box can be found where it stands",
            "const state = createGame();\nloadLevel(state, 4);\nfor (let i = 0; i < state.boxes.length; i++) {\n    assert(boxAt(state, state.boxes[i].x, state.boxes[i].y) === i, 'box ' + i + ' was not found at its own position');\n}")]),
  py=dict(starter="def box_at(state, x, y):\n    # which box is standing here? -1 for none\n    pass\n",
    answer="def box_at(state, x, y):\n    for i, box in enumerate(state[\"boxes\"]):\n        if box[\"x\"] == x and box[\"y\"] == y:\n            return i\n    return -1\n",
    hints=["enumerate gives you the position and the box together.",
           "BOTH the x and the y have to match.",
           "return -1 goes after the loop, not inside it."],
    tests=[("It finds a box that is there",
            "state = create_game()\nbox = state['boxes'][0]\nassert box_at(state, box['x'], box['y']) == 0"),
           ("Empty floor gives -1",
            "state = create_game()\nassert box_at(state, 1, 1) == -1"),
           ("It finds the SECOND box too",
            "state = create_game()\nload_level(state, 2)\nbox = state['boxes'][1]\nassert box_at(state, box['x'], box['y']) == 1, 'the answer must say WHICH box'"),
           ("Both the x and the y have to match",
            "state = create_game()\nbox = state['boxes'][0]\nassert box_at(state, box['x'], box['y'] + 1) == -1\nassert box_at(state, box['x'] + 1, box['y']) == -1"),
           ("Every box can be found where it stands",
            "state = create_game()\nload_level(state, 4)\nfor i, box in enumerate(state['boxes']):\n    assert box_at(state, box['x'], box['y']) == i")]),
  demo=dict(kind="boxes", caption="Move the dashed box onto a crate and watch the number change.")),

step("boxes_on_goals", "boxesOnGoals", "boxes_on_goals",
  "How many are home?", "The game can tell how you are doing.",
  "<p>A short one that does two jobs: it fills in the scoreboard, and the next function is built entirely out of it.</p>",
  "state", "how many boxes are standing on a target",
  ["Start a count at 0.",
   "For each box, ask is-goal whether it is standing on a target.",
   "Add 1 if it is."],
  js=dict(starter="function boxesOnGoals(state) {\n    // count the boxes standing on a target\n}\n",
    answer="function boxesOnGoals(state) {\n    let count = 0;\n    for (let i = 0; i < state.boxes.length; i++) {\n        if (isGoal(state, state.boxes[i].x, state.boxes[i].y)) {\n            count = count + 1;\n        }\n    }\n    return count;\n}\n",
    hints=["isGoal(state, x, y) is written for you.",
           "Walk the BOXES, not the whole level.",
           "One loop, one if, one count."],
    tests=[("A fresh level has nothing home",
            "const state = createGame();\nassert(boxesOnGoals(state) === 0);"),
           ("Pushing a box home counts it",
            "const state = createGame();\nmovePlayer(state, -1, 0);\nassert(boxesOnGoals(state) === 1, 'that push put the box on the target');"),
           ("It counts every box, not just the first",
            "const state = createGame();\nloadLevel(state, 2);\nstate.boxes[0] = { x: 4, y: 2 };\nstate.boxes[1] = { x: 5, y: 2 };\nassert(boxesOnGoals(state) === 2, 'gave ' + boxesOnGoals(state));"),
           ("A box on plain floor does not count",
            "const state = createGame();\nloadLevel(state, 2);\nstate.boxes[0] = { x: 1, y: 1 };\nassert(boxesOnGoals(state) < state.boxes.length);"),
           ("It never counts more boxes than there are",
            "const state = createGame();\nfor (let level = 0; level < LEVELS.length; level++) {\n    loadLevel(state, level);\n    assert(boxesOnGoals(state) <= state.boxes.length);\n}")]),
  py=dict(starter="def boxes_on_goals(state):\n    # count the boxes standing on a target\n    pass\n",
    answer="def boxes_on_goals(state):\n    return sum(1 for box in state[\"boxes\"] if is_goal(state, box[\"x\"], box[\"y\"]))\n",
    hints=["is_goal(state, x, y) is written for you.",
           "Walk the BOXES, not the whole level.",
           "sum(1 for ... if ...) counts the ones that match."],
    tests=[("A fresh level has nothing home",
            "assert boxes_on_goals(create_game()) == 0"),
           ("Pushing a box home counts it",
            "state = create_game()\nmove_player(state, -1, 0)\nassert boxes_on_goals(state) == 1"),
           ("It counts every box, not just the first",
            "state = create_game()\nload_level(state, 2)\nstate['boxes'][0] = {'x': 4, 'y': 2}\nstate['boxes'][1] = {'x': 5, 'y': 2}\nassert boxes_on_goals(state) == 2"),
           ("A box on plain floor does not count",
            "state = create_game()\nload_level(state, 2)\nstate['boxes'][0] = {'x': 1, 'y': 1}\nassert boxes_on_goals(state) < len(state['boxes'])"),
           ("It never counts more boxes than there are",
            "state = create_game()\nfor level in range(len(LEVELS)):\n    load_level(state, level)\n    assert boxes_on_goals(state) <= len(state['boxes'])")]),
  demo=dict(kind="push", caption="Push the boxes about and watch the count.")),

step("move_player", "movePlayer", "move_player",
  "Walk and push", "The game can be played!",
  "<p>The heart of Sokoban, and it is all about looking <em>two</em> squares ahead.</p>"
  "<p>Step into a wall and nothing happens. Step into a box and you have to check the square <strong>behind the box</strong> as well — because that is where the box is going. If a wall or another box is there, nothing moves at all: not the box, and not you.</p>"
  "<p>Save a snapshot for undo <em>before</em> you change anything, or the undo will remember the move you just made instead of the one before it.</p>",
  "state. dx, dy — the step, e.g. 1 and 0 for 'right'.",
  "True if anything moved",
  ["Work out the square you are stepping into. If it is a wall, stop.",
   "Ask box-at whether a box is there.",
   "If it is: work out where the box would go. If that square is a wall or holds another box, stop.",
   "Save a snapshot onto the history, then move the box and count the push.",
   "If there was no box, just save the snapshot.",
   "Move yourself, count the move, and see whether the level is solved."],
  js=dict(starter="function movePlayer(state, dx, dy) {\n    // 1. wall? stop\n    // 2. box? check BEHIND the box too\n    // 3. save for undo, then move\n}\n",
    answer="function movePlayer(state, dx, dy) {\n    if (state.isSolved || state.isPaused) {\n        return false;\n    }\n    const toX = state.player.x + dx;\n    const toY = state.player.y + dy;\n\n    if (isWall(state, toX, toY)) {\n        return false;\n    }\n\n    const box = boxAt(state, toX, toY);\n    if (box !== -1) {\n        const boxToX = toX + dx;\n        const boxToY = toY + dy;\n        if (isWall(state, boxToX, boxToY) || boxAt(state, boxToX, boxToY) !== -1) {\n            return false;\n        }\n        state.history.push(snapshot(state));\n        state.boxes[box] = { x: boxToX, y: boxToY };\n        state.pushes = state.pushes + 1;\n    } else {\n        state.history.push(snapshot(state));\n    }\n\n    state.player = { x: toX, y: toY };\n    state.moves = state.moves + 1;\n\n    if (isSolved(state)) {\n        state.isSolved = true;\n    }\n    return true;\n}\n",
    hints=["The box goes one step FURTHER in the same direction: toX + dx.",
           "Two things can block a box: a wall, and another box.",
           "snapshot(state) and state.history.push(...) do the undo bookkeeping."],
    tests=[("Walking on empty floor works",
            "const state = createGame();\nconst before = state.player.x;\nmovePlayer(state, 1, 0);\nassert(state.player.x === before + 1);"),
           ("A wall stops you dead",
            "const state = createGame();\nstate.player = { x: 1, y: 1 };\nassert(movePlayer(state, -1, 0) === false);\nassert(state.player.x === 1, 'you should not have moved');"),
           ("Walking into a box pushes it",
            "const state = createGame();\nconst box = { x: state.boxes[0].x, y: state.boxes[0].y };\nmovePlayer(state, -1, 0);\nassert(state.boxes[0].x === box.x - 1, 'the box should have been pushed along');"),
           ("Pushing a box into a wall does nothing at all",
            "const state = createGame();\nloadLevel(state, 1);\nstate.player = { x: 5, y: 2 };\nstate.boxes[0] = { x: 5, y: 1 };\nassert(movePlayer(state, 0, -1) === false, 'there is a wall behind that box');\nassert(state.player.y === 2, 'you must not move either');"),
           ("A box cannot be pushed into another box",
            "const state = createGame();\nloadLevel(state, 2);\nstate.player = { x: 2, y: 3 };\nstate.boxes[0] = { x: 3, y: 3 };\nstate.boxes[1] = { x: 4, y: 3 };\nassert(movePlayer(state, 1, 0) === false, 'the second box is in the way');"),
           ("A push is counted",
            "const state = createGame();\nmovePlayer(state, -1, 0);\nassert(state.pushes === 1, 'pushes is ' + state.pushes);"),
           ("Walking without pushing does not count as a push",
            "const state = createGame();\nmovePlayer(state, 1, 0);\nassert(state.pushes === 0);"),
           ("Every move is remembered for undo",
            "const state = createGame();\nmovePlayer(state, 1, 0);\nmovePlayer(state, 0, 1);\nassert(state.history.length === 2, 'history has ' + state.history.length + ' snapshots');"),
           ("Getting the box home solves the level",
            "const state = createGame();\nmovePlayer(state, -1, 0);\nassert(state.isSolved === true, 'that push finished level 1');"),
           ("Level 1 can really be solved",
            "const state = createGame();\nassert(movePlayer(state, -1, 0) === true);\nassert(boxesOnGoals(state) === state.boxes.length);")]),
  py=dict(starter="def move_player(state, dx, dy):\n    # 1. wall? stop\n    # 2. box? check BEHIND the box too\n    # 3. save for undo, then move\n    pass\n",
    answer="def move_player(state, dx, dy):\n    if state[\"is_solved\"] or state[\"is_paused\"]:\n        return False\n    to_x = state[\"player\"][\"x\"] + dx\n    to_y = state[\"player\"][\"y\"] + dy\n\n    if is_wall(state, to_x, to_y):\n        return False\n\n    box = box_at(state, to_x, to_y)\n    if box != -1:\n        box_to_x = to_x + dx\n        box_to_y = to_y + dy\n        if is_wall(state, box_to_x, box_to_y) or box_at(state, box_to_x, box_to_y) != -1:\n            return False\n        state[\"history\"].append(snapshot(state))\n        state[\"boxes\"][box] = {\"x\": box_to_x, \"y\": box_to_y}\n        state[\"pushes\"] += 1\n    else:\n        state[\"history\"].append(snapshot(state))\n\n    state[\"player\"] = {\"x\": to_x, \"y\": to_y}\n    state[\"moves\"] += 1\n\n    if is_solved(state):\n        state[\"is_solved\"] = True\n    return True\n",
    hints=["The box goes one step FURTHER in the same direction: to_x + dx.",
           "Two things can block a box: a wall, and another box.",
           "snapshot(state) and state['history'].append(...) do the undo bookkeeping."],
    tests=[("Walking on empty floor works",
            "state = create_game()\nbefore = state['player']['x']\nmove_player(state, 1, 0)\nassert state['player']['x'] == before + 1"),
           ("A wall stops you dead",
            "state = create_game()\nstate['player'] = {'x': 1, 'y': 1}\nassert move_player(state, -1, 0) is False\nassert state['player']['x'] == 1"),
           ("Walking into a box pushes it",
            "state = create_game()\nbefore = dict(state['boxes'][0])\nmove_player(state, -1, 0)\nassert state['boxes'][0]['x'] == before['x'] - 1"),
           ("Pushing a box into a wall does nothing at all",
            "state = create_game()\nload_level(state, 1)\nstate['player'] = {'x': 5, 'y': 2}\nstate['boxes'][0] = {'x': 5, 'y': 1}\nassert move_player(state, 0, -1) is False\nassert state['player']['y'] == 2"),
           ("A box cannot be pushed into another box",
            "state = create_game()\nload_level(state, 2)\nstate['player'] = {'x': 2, 'y': 3}\nstate['boxes'][0] = {'x': 3, 'y': 3}\nstate['boxes'][1] = {'x': 4, 'y': 3}\nassert move_player(state, 1, 0) is False"),
           ("A push is counted",
            "state = create_game()\nmove_player(state, -1, 0)\nassert state['pushes'] == 1"),
           ("Walking without pushing does not count as a push",
            "state = create_game()\nmove_player(state, 1, 0)\nassert state['pushes'] == 0"),
           ("Every move is remembered for undo",
            "state = create_game()\nmove_player(state, 1, 0)\nmove_player(state, 0, 1)\nassert len(state['history']) == 2"),
           ("Getting the box home solves the level",
            "state = create_game()\nmove_player(state, -1, 0)\nassert state['is_solved'] is True"),
           ("Level 1 can really be solved",
            "state = create_game()\nassert move_player(state, -1, 0) is True\nassert boxes_on_goals(state) == len(state['boxes'])")]),
  demo=dict(kind="push", caption="Walk around and push the boxes onto the rings."),
  warning="Check the square BEHIND the box as well. Miss that and boxes will happily slide into walls and through each other."),

step("undo_move", "undoMove", "undo_move",
  "Undo", "You can take a move back.",
  "<p>Sokoban only lets you push, never pull. Shove a box into a corner and the level is finished — not lost, just impossible. Without undo that would be miserable.</p>"
  "<p>The history is a <strong>stack</strong>: snapshots piled up, newest on top. Undo takes the top one off and puts it back. Because every move added exactly one, undo can walk all the way to the start of the level.</p>",
  "state", "True if there was anything to undo",
  ["If the history is empty, there is nothing to undo.",
   "Take the newest snapshot off the top.",
   "Put its player and boxes back into the state.",
   "Count it as a move, and work out whether the level is still solved."],
  js=dict(starter="function undoMove(state) {\n    // take the newest snapshot off the stack and put it back\n}\n",
    answer="function undoMove(state) {\n    if (state.history.length === 0) {\n        return false;\n    }\n    const past = state.history.pop();\n    state.player = past.player;\n    state.boxes = past.boxes;\n    state.moves = state.moves + 1;\n    state.isSolved = isSolved(state);\n    return true;\n}\n",
    hints=["pop() takes the LAST thing off a list — the newest snapshot.",
           "Put back both the player and the boxes.",
           "Work out isSolved again — undoing can un-solve a level."],
    tests=[("Undo puts the player back",
            "const state = createGame();\nconst before = state.player.x;\nmovePlayer(state, 1, 0);\nundoMove(state);\nassert(state.player.x === before, 'x is ' + state.player.x);"),
           ("Undo puts a pushed box back",
            "const state = createGame();\nconst before = state.boxes[0].x;\nmovePlayer(state, -1, 0);\nundoMove(state);\nassert(state.boxes[0].x === before, 'the box should be back where it was');"),
           ("Undo with nothing to undo does nothing",
            "const state = createGame();\nassert(undoMove(state) === false);"),
           ("Undo can walk all the way back",
            "const state = createGame();\nconst startX = state.player.x;\nconst startY = state.player.y;\nmovePlayer(state, 1, 0);\nmovePlayer(state, 0, 1);\nmovePlayer(state, 1, 0);\nwhile (undoMove(state)) { /* keep going */ }\nassert(state.player.x === startX && state.player.y === startY, 'undo should reach the very start');"),
           ("Undo un-solves a solved level",
            "const state = createGame();\nmovePlayer(state, -1, 0);\nassert(state.isSolved === true);\nundoMove(state);\nassert(state.isSolved === false, 'taking the winning push back must un-win the level');"),
           ("The snapshots really are separate copies",
            "const state = createGame();\nmovePlayer(state, -1, 0);\nstate.boxes[0].x = 99;\nundoMove(state);\nassert(state.boxes[0].x !== 99, 'the saved snapshot must be a COPY — changing a box afterwards must not change history');")]),
  py=dict(starter="def undo_move(state):\n    # take the newest snapshot off the stack and put it back\n    pass\n",
    answer="def undo_move(state):\n    if not state[\"history\"]:\n        return False\n    past = state[\"history\"].pop()\n    state[\"player\"] = past[\"player\"]\n    state[\"boxes\"] = past[\"boxes\"]\n    state[\"moves\"] += 1\n    state[\"is_solved\"] = is_solved(state)\n    return True\n",
    hints=["pop() takes the LAST thing off a list - the newest snapshot.",
           "Put back both the player and the boxes.",
           "Work out is_solved again - undoing can un-solve a level."],
    tests=[("Undo puts the player back",
            "state = create_game()\nbefore = state['player']['x']\nmove_player(state, 1, 0)\nundo_move(state)\nassert state['player']['x'] == before"),
           ("Undo puts a pushed box back",
            "state = create_game()\nbefore = state['boxes'][0]['x']\nmove_player(state, -1, 0)\nundo_move(state)\nassert state['boxes'][0]['x'] == before"),
           ("Undo with nothing to undo does nothing",
            "assert undo_move(create_game()) is False"),
           ("Undo can walk all the way back",
            "state = create_game()\nstart = dict(state['player'])\nmove_player(state, 1, 0)\nmove_player(state, 0, 1)\nmove_player(state, 1, 0)\nwhile undo_move(state):\n    pass\nassert state['player'] == start"),
           ("Undo un-solves a solved level",
            "state = create_game()\nmove_player(state, -1, 0)\nassert state['is_solved'] is True\nundo_move(state)\nassert state['is_solved'] is False"),
           ("The snapshots really are separate copies",
            "state = create_game()\nmove_player(state, -1, 0)\nstate['boxes'][0]['x'] = 99\nundo_move(state)\nassert state['boxes'][0]['x'] != 99, 'the saved snapshot must be a COPY'")]),
  demo=dict(kind="game", caption="Push a box somewhere silly, then press Undo until you are back at the start.")),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function. Four directions, plus undo, reset and next.</p>"
  "<p>Notice that undo has three keys — U, Z and Backspace. Different people reach for different ones, and letting all three work costs nothing.</p>",
  "key", "an action name, or nothing at all",
  ["The arrows or WASD walk.",
   "U, Z or Backspace → 'undo'. R → 'reset'. N or Enter → 'next'. P → 'pause'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // walk, undo, reset, next, pause\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === 'u' || k === 'z' || k === 'backspace') { return 'undo'; }\n    if (k === 'r') { return 'reset'; }\n    if (k === 'n' || k === 'enter') { return 'next'; }\n    if (k === 'p') { return 'pause'; }\n\n    return null;\n}\n",
    hints=["Backspace's key name is exactly 'Backspace'.",
           "Three keys can all return 'undo' — just list them in one if.",
           "toLowerCase() up front means capitals work too."],
    tests=[("The arrows walk",
            "assert(actionForKey('ArrowUp') === 'up');\nassert(actionForKey('ArrowDown') === 'down');\nassert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("WASD walks too",
            "assert(actionForKey('w') === 'up');\nassert(actionForKey('s') === 'down');\nassert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("All three undo keys work",
            "assert(actionForKey('u') === 'undo');\nassert(actionForKey('z') === 'undo');\nassert(actionForKey('Backspace') === 'undo');"),
           ("R resets and N moves on",
            "assert(actionForKey('r') === 'reset');\nassert(actionForKey('n') === 'next');\nassert(actionForKey('Enter') === 'next');"),
           ("Capital letters work",
            "assert(actionForKey('U') === 'undo');\nassert(actionForKey('R') === 'reset');"),
           ("Other keys do nothing",
            "assert(actionForKey('q') === null);\nassert(actionForKey('Tab') === null);")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowup\": \"up\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \"u\": \"undo\", \"z\": \"undo\", \"backspace\": \"undo\",\n        \"r\": \"reset\", \"n\": \"next\", \"enter\": \"next\", \"p\": \"pause\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["Backspace's key name is exactly 'Backspace' - lower-cased, 'backspace'.",
           "Three different keys can all point at \"undo\".",
           "keys.get(...) gives None for anything not listed."],
    tests=[("The arrows walk",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD walks too",
            "assert action_for_key('w') == 'up'\nassert action_for_key('s') == 'down'\nassert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("All three undo keys work",
            "assert action_for_key('u') == 'undo'\nassert action_for_key('z') == 'undo'\nassert action_for_key('Backspace') == 'undo'"),
           ("R resets and N moves on",
            "assert action_for_key('r') == 'reset'\nassert action_for_key('n') == 'next'\nassert action_for_key('Enter') == 'next'"),
           ("Capital letters work",
            "assert action_for_key('U') == 'undo'\nassert action_for_key('R') == 'reset'"),
           ("Other keys do nothing",
            "assert action_for_key('q') is None\nassert action_for_key('Tab') is None")]),
  demo=dict(kind="final", caption="Click the page, then solve all six levels with the arrow keys. U undoes.")),
]

write_workshop("sokoban", "Sokoban", STEPS)
