"""The seven steps of "Build Tic-Tac-Toe", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("square_index", "squareIndex", "square_index",
  "Number the squares", "The board has places to play.",
  "<p>Nine squares, stored as one flat <strong>list</strong> of nine marks. Each holds <code>''</code> (empty), <code>'X'</code> (you) or <code>'O'</code> (the computer).</p>"
  "<pre class=\"mini-code\">0 | 1 | 2\n3 | 4 | 5\n6 | 7 | 8</pre>",
  "column, row - each 0, 1 or 2",
  "the position of that square in the flat list of nine",
  ["Skip a whole row of squares for every row above: row * GRID_SIZE.",
   "Add the column.", "Return the answer."],
  js=dict(starter="function squareIndex(column, row) {\n    // skip whole rows, then add the column\n}\n",
    answer="function squareIndex(column, row) {\n    return row * GRID_SIZE + column;\n}\n",
    hints=["One line.", "Skipping `row` rows means skipping row * GRID_SIZE squares.",
           "return row * GRID_SIZE + column;"],
    tests=[("The top-left square is 0", "assert(squareIndex(0, 0) === 0, 'gave ' + squareIndex(0, 0));"),
           ("The middle is 4", "assert(squareIndex(1, 1) === 4, 'gave ' + squareIndex(1, 1));"),
           ("The bottom-right is 8", "assert(squareIndex(2, 2) === 8, 'gave ' + squareIndex(2, 2));"),
           ("One step right adds 1", "assert(squareIndex(2, 1) - squareIndex(1, 1) === 1);"),
           ("All nine squares get different numbers",
            "const seen = {};\nfor (let r = 0; r < 3; r++) { for (let c = 0; c < 3; c++) { seen[squareIndex(c, r)] = true; } }\nassert(Object.keys(seen).length === 9, 'only ' + Object.keys(seen).length + ' different numbers');")]),
  py=dict(starter="def square_index(column, row):\n    # skip whole rows, then add the column\n    pass\n",
    answer="def square_index(column, row):\n    return row * GRID_SIZE + column\n",
    hints=["One line.", "Skipping `row` rows means skipping row * GRID_SIZE squares.",
           "return row * GRID_SIZE + column"],
    tests=[("The top-left square is 0", "got = square_index(0, 0)\nassert got == 0, f'gave {got}'"),
           ("The middle is 4", "got = square_index(1, 1)\nassert got == 4, f'gave {got}'"),
           ("The bottom-right is 8", "assert square_index(2, 2) == 8"),
           ("One step right adds 1", "assert square_index(2, 1) - square_index(1, 1) == 1"),
           ("All nine squares get different numbers",
            "seen = {square_index(c, r) for r in range(3) for c in range(3)}\nassert len(seen) == 9, f'only {len(seen)} different numbers'")]),
  demo=dict(kind="grid", caption="Your function numbers every square on the board.")),

step("empty_squares", "emptySquares", "empty_squares",
  "Where can we play?", "The game knows which squares are free.",
  "<p>Before anybody moves — you or the computer — the game needs the list of squares that are still empty.</p>"
  "<p>Careful: it wants the <strong>numbers</strong> of the free squares, not the marks in them.</p>",
  "board - the list of nine marks",
  "a list of the index numbers that are still empty",
  ["Walk the board, keeping the numbers whose square is EMPTY.",
   "Return that list."],
  js=dict(starter="function emptySquares(board) {\n    // the NUMBERS of the squares that are still empty\n}\n",
    answer="function emptySquares(board) {\n    const free = [];\n    for (let index = 0; index < board.length; index++) {\n        if (board[index] === EMPTY) {\n            free.push(index);\n        }\n    }\n    return free;\n}\n",
    hints=["Use a plain for loop so you have the index number.",
           "if (board[index] === EMPTY) { free.push(index); }",
           "Push the index, not board[index]."],
    tests=[("A new board has all nine free",
            "const board = new Array(9).fill(EMPTY);\nassert(emptySquares(board).length === 9, 'gave ' + emptySquares(board).length);"),
           ("A full board has none free",
            "assert(emptySquares(new Array(9).fill('X')).length === 0);"),
           ("It gives the right numbers",
            "const board = ['X', EMPTY, 'O', EMPTY, EMPTY, 'X', 'O', 'X', EMPTY];\nassert(emptySquares(board).join(',') === '1,3,4,8', 'gave ' + emptySquares(board).join(','));"),
           ("It returns numbers, not marks",
            "const board = [EMPTY, 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X'];\nassert(emptySquares(board)[0] === 0, 'the free square is number 0');"),
           ("The numbers come back in order",
            "const board = new Array(9).fill(EMPTY);\nboard[0] = 'X';\nassert(emptySquares(board).join(',') === '1,2,3,4,5,6,7,8');")]),
  py=dict(starter="def empty_squares(board):\n    # the NUMBERS of the squares that are still empty\n    pass\n",
    answer="def empty_squares(board):\n    return [index for index, mark in enumerate(board) if mark == EMPTY]\n",
    hints=["enumerate(board) gives the number and the mark together.",
           "A list comprehension can end with an `if`.",
           "Collect index, not mark."],
    tests=[("A new board has all nine free",
            "assert len(empty_squares([EMPTY] * 9)) == 9"),
           ("A full board has none free", "assert empty_squares(['X'] * 9) == []"),
           ("It gives the right numbers",
            "board = ['X', EMPTY, 'O', EMPTY, EMPTY, 'X', 'O', 'X', EMPTY]\ngot = empty_squares(board)\nassert got == [1, 3, 4, 8], f'gave {got}'"),
           ("It returns numbers, not marks",
            "board = [EMPTY] + ['X'] * 8\nassert empty_squares(board) == [0]"),
           ("The numbers come back in order",
            "board = ['X'] + [EMPTY] * 8\nassert empty_squares(board) == [1, 2, 3, 4, 5, 6, 7, 8]")]),
  demo=dict(kind="game", caption="Play a few squares and watch the free list shrink.")),

step("place_mark", "placeMark", "place_mark",
  "Make a move", "Marks can be put on the board.",
  "<p>Putting an X or an O on the board makes a <strong>new</strong> board rather than changing the old one. That matters more than it looks: in a moment the computer will want to try moves out without really making them.</p>",
  "board - the nine marks. index - which square. mark - 'X' or 'O'.",
  "a NEW board with the mark added",
  ["Copy the board.",
   "If that square is EMPTY, put the mark in it.",
   "Return the copy."],
  js=dict(starter="function placeMark(board, index, mark) {\n    // a NEW board with the mark added, if that square was free\n}\n",
    answer="function placeMark(board, index, mark) {\n    const next = board.slice();\n    if (next[index] === EMPTY) {\n        next[index] = mark;\n    }\n    return next;\n}\n",
    hints=["board.slice() copies a list.", "Only write into the square if it is EMPTY.",
           "Return the copy, not the original."],
    tests=[("The mark lands on the right square",
            "const board = placeMark(new Array(9).fill(EMPTY), 4, 'X');\nassert(board[4] === 'X', 'square 4 is ' + JSON.stringify(board[4]));"),
           ("The other squares are untouched",
            "const board = placeMark(new Array(9).fill(EMPTY), 4, 'X');\nassert(board.filter(m => m === 'X').length === 1, 'only one square should change');"),
           ("A square that is taken does not change",
            "const board = placeMark(['O', EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY], 0, 'X');\nassert(board[0] === 'O', 'you cannot play on top of another mark');"),
           ("The board you were given is not changed",
            "const before = new Array(9).fill(EMPTY);\nplaceMark(before, 0, 'X');\nassert(before[0] === EMPTY, 'you changed the board you were given instead of a copy');"),
           ("It returns a new list, not the old one",
            "const before = new Array(9).fill(EMPTY);\nassert(placeMark(before, 0, 'X') !== before);")]),
  py=dict(starter="def place_mark(board, index, mark):\n    # a NEW board with the mark added, if that square was free\n    pass\n",
    answer="def place_mark(board, index, mark):\n    next_board = list(board)\n    if next_board[index] == EMPTY:\n        next_board[index] = mark\n    return next_board\n",
    hints=["list(board) copies a list.", "Only write into the square if it is EMPTY.",
           "Return the copy, not the original."],
    tests=[("The mark lands on the right square",
            "board = place_mark([EMPTY] * 9, 4, 'X')\nassert board[4] == 'X', f'square 4 is {board[4]!r}'"),
           ("The other squares are untouched",
            "board = place_mark([EMPTY] * 9, 4, 'X')\nassert board.count('X') == 1"),
           ("A square that is taken does not change",
            "board = place_mark(['O'] + [EMPTY] * 8, 0, 'X')\nassert board[0] == 'O', 'you cannot play on top of another mark'"),
           ("The board you were given is not changed",
            "before = [EMPTY] * 9\nplace_mark(before, 0, 'X')\nassert before[0] == EMPTY, 'you changed the board you were given'"),
           ("It returns a new list, not the old one",
            "before = [EMPTY] * 9\nassert place_mark(before, 0, 'X') is not before")]),
  demo=dict(kind="game", caption="Every mark you see was put there by your function.")),

step("winning_line", "winningLine", "winning_line",
  "Spot three in a row", "The game can be won.",
  "<p>There are exactly eight ways to make three in a row: three rows, three columns and two diagonals. They are already written down for you in <code>WINNING_LINES</code>.</p>"
  "<pre class=\"mini-code\">[0,1,2] [3,4,5] [6,7,8]      the rows\n[0,3,6] [1,4,7] [2,5,8]      the columns\n[0,4,8] [2,4,6]              the diagonals</pre>",
  "board - the nine marks",
  "the winning line (a list of three numbers), or nothing if no one has won",
  ["Try each line in WINNING_LINES.",
   "Look at the mark in its first square. If that square is EMPTY, skip this line.",
   "If all three squares hold that same mark, this line has won — return it.",
   "If no line wins, return null (JavaScript) or None (Python)."],
  js=dict(starter="function winningLine(board) {\n    // try each of the eight lines\n}\n",
    answer="function winningLine(board) {\n    for (let i = 0; i < WINNING_LINES.length; i++) {\n        const line = WINNING_LINES[i];\n        const first = board[line[0]];\n        if (first !== EMPTY && first === board[line[1]] && first === board[line[2]]) {\n            return line;\n        }\n    }\n    return null;\n}\n",
    hints=["Loop over WINNING_LINES; each line is three numbers like [0, 4, 8].",
           "Check the first square is not EMPTY before comparing — three empty squares are not a win!",
           "return null; goes AFTER the loop."],
    tests=[("A top row of Xs wins",
            "const board = ['X','X','X',EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY];\nassert(JSON.stringify(winningLine(board)) === '[0,1,2]', 'gave ' + JSON.stringify(winningLine(board)));"),
           ("A column of Os wins",
            "const board = ['O',EMPTY,EMPTY,'O',EMPTY,EMPTY,'O',EMPTY,EMPTY];\nassert(JSON.stringify(winningLine(board)) === '[0,3,6]', 'gave ' + JSON.stringify(winningLine(board)));"),
           ("A diagonal wins",
            "const board = ['X',EMPTY,EMPTY,EMPTY,'X',EMPTY,EMPTY,EMPTY,'X'];\nassert(JSON.stringify(winningLine(board)) === '[0,4,8]');"),
           ("An empty board has no winner",
            "assert(winningLine(new Array(9).fill(EMPTY)) === null, 'three empty squares are NOT three in a row');"),
           ("A mixed line does not win",
            "const board = ['X','O','X',EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY];\nassert(winningLine(board) === null, 'gave ' + JSON.stringify(winningLine(board)));"),
           ("A full board with no line has no winner",
            "const board = ['X','O','X','X','O','O','O','X','X'];\nassert(winningLine(board) === null, 'gave ' + JSON.stringify(winningLine(board)));")]),
  py=dict(starter="def winning_line(board):\n    # try each of the eight lines\n    pass\n",
    answer="def winning_line(board):\n    for line in WINNING_LINES:\n        first = board[line[0]]\n        if first != EMPTY and first == board[line[1]] == board[line[2]]:\n            return line\n    return None\n",
    hints=["`for line in WINNING_LINES` gives each line in turn.",
           "Check the first square is not EMPTY before comparing.",
           "Python lets you chain: first == board[line[1]] == board[line[2]]"],
    tests=[("A top row of Xs wins",
            "board = ['X','X','X'] + [EMPTY] * 6\nassert winning_line(board) == [0,1,2], f'gave {winning_line(board)}'"),
           ("A column of Os wins",
            "board = ['O',EMPTY,EMPTY,'O',EMPTY,EMPTY,'O',EMPTY,EMPTY]\nassert winning_line(board) == [0,3,6]"),
           ("A diagonal wins",
            "board = ['X',EMPTY,EMPTY,EMPTY,'X',EMPTY,EMPTY,EMPTY,'X']\nassert winning_line(board) == [0,4,8]"),
           ("An empty board has no winner",
            "assert winning_line([EMPTY] * 9) is None, 'three empty squares are NOT three in a row'"),
           ("A mixed line does not win",
            "board = ['X','O','X'] + [EMPTY] * 6\nassert winning_line(board) is None"),
           ("A full board with no line has no winner",
            "board = ['X','O','X','X','O','O','O','X','X']\nassert winning_line(board) is None")]),
  demo=dict(kind="lines", caption="Press Next line to see all eight ways to win — your function finds each one.")),

step("is_draw", "isDraw", "is_draw",
  "Spot a draw", "Nobody wins, and that is fine.",
  "<p>A draw is the boring ending: the board is full and no line has three in a row. Notice that this step is built entirely out of the two functions you have already written.</p>",
  "board - the nine marks",
  "True when the board is full AND nobody has won",
  ["Ask empty-squares whether any square is left.",
   "Ask winning-line whether anybody has won.",
   "It is a draw only when there are no free squares and no winner."],
  js=dict(starter="function isDraw(board) {\n    // full board, no winner\n}\n",
    answer="function isDraw(board) {\n    return emptySquares(board).length === 0 && winningLine(board) === null;\n}\n",
    hints=["Reuse emptySquares(board).length and winningLine(board).",
           "Both conditions must be true, so join them with &&.",
           "return emptySquares(board).length === 0 && winningLine(board) === null;"],
    tests=[("A full board with no line is a draw",
            "const board = ['X','O','X','X','O','O','O','X','X'];\nassert(isDraw(board) === true, 'this board is full with no winner');"),
           ("An empty board is not a draw", "assert(isDraw(new Array(9).fill(EMPTY)) === false);"),
           ("A half-played board is not a draw",
            "const board = ['X','O',EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY];\nassert(isDraw(board) === false);"),
           ("A full board WITH a winner is not a draw",
            "const board = ['X','X','X','O','O','X','X','O','O'];\nassert(isDraw(board) === false, 'X won that one, so it is not a draw');")]),
  py=dict(starter="def is_draw(board):\n    # full board, no winner\n    pass\n",
    answer="def is_draw(board):\n    return not empty_squares(board) and winning_line(board) is None\n",
    hints=["`not empty_squares(board)` is Python for \"the list is empty\".",
           "Join the two halves with `and`.",
           "return not empty_squares(board) and winning_line(board) is None"],
    tests=[("A full board with no line is a draw",
            "board = ['X','O','X','X','O','O','O','X','X']\nassert is_draw(board) is True"),
           ("An empty board is not a draw", "assert is_draw([EMPTY] * 9) is False"),
           ("A half-played board is not a draw",
            "assert is_draw(['X','O'] + [EMPTY] * 7) is False"),
           ("A full board WITH a winner is not a draw",
            "board = ['X','X','X','O','O','X','X','O','O']\nassert is_draw(board) is False, 'X won that one'")]),
  demo=dict(kind="game", caption="Play until the board fills up — your function spots the draw.")),

step("computer_move", "computerMove", "computer_move",
  "Teach the computer to play", "You have an opponent!",
  "<p>Now for the fun part: the computer's brain. It is only four rules, but they are enough to make it very hard to beat.</p>"
  "<p>The trick is that the computer <em>tries</em> a move on a copy of the board — that is why <code>placeMark</code> never changes the original.</p>",
  "board - the nine marks",
  "the index the computer should play, or -1 if the board is full",
  ["Get the free squares. If there are none, return -1.",
   "1. If playing a square would make the COMPUTER win, play it.",
   "2. Otherwise, if playing a square would make the PLAYER win, play it — that blocks them.",
   "3. Otherwise take the middle (square 4) if it is free: it sits on four lines.",
   "4. Otherwise take a free corner (0, 2, 6 or 8), and if there are none, anything left."],
  js=dict(starter="function computerMove(board) {\n    const free = emptySquares(board);\n    // win, block, middle, corner, anything\n}\n",
    answer="function computerMove(board) {\n    const free = emptySquares(board);\n    if (free.length === 0) {\n        return -1;\n    }\n\n    for (let i = 0; i < free.length; i++) {\n        if (winningLine(placeMark(board, free[i], COMPUTER)) !== null) {\n            return free[i];\n        }\n    }\n    for (let i = 0; i < free.length; i++) {\n        if (winningLine(placeMark(board, free[i], PLAYER)) !== null) {\n            return free[i];\n        }\n    }\n    if (board[4] === EMPTY) {\n        return 4;\n    }\n    const corners = [0, 2, 6, 8].filter(function (corner) { return board[corner] === EMPTY; });\n    if (corners.length > 0) {\n        return corners[Math.floor(Math.random() * corners.length)];\n    }\n    return free[Math.floor(Math.random() * free.length)];\n}\n",
    hints=["To try a move: winningLine(placeMark(board, square, COMPUTER)) !== null",
           "Do the winning loop FIRST, then the blocking loop — winning beats blocking.",
           "Only after both loops do you fall back to the middle, a corner, or anything free."],
    tests=[("It takes a winning move",
            "const board = ['O','O',EMPTY,'X','X',EMPTY,EMPTY,EMPTY,EMPTY];\nassert(computerMove(board) === 2, 'O can win at square 2 — gave ' + computerMove(board));"),
           ("It blocks the player",
            "const board = ['X','X',EMPTY,'O',EMPTY,EMPTY,EMPTY,EMPTY,EMPTY];\nassert(computerMove(board) === 2, 'X would win at square 2, so block it — gave ' + computerMove(board));"),
           ("Winning beats blocking",
            "const board = ['O','O',EMPTY,'X','X',EMPTY,EMPTY,EMPTY,EMPTY];\nassert(computerMove(board) === 2, 'if it can win it should win, not block');"),
           ("It takes the middle on an empty board",
            "assert(computerMove(new Array(9).fill(EMPTY)) === 4, 'gave ' + computerMove(new Array(9).fill(EMPTY)));"),
           ("It takes a corner when the middle is gone",
            "const board = [EMPTY,EMPTY,EMPTY,EMPTY,'X',EMPTY,EMPTY,EMPTY,EMPTY];\nassert([0,2,6,8].indexOf(computerMove(board)) !== -1, 'gave ' + computerMove(board));"),
           ("It says -1 when the board is full",
            "assert(computerMove(new Array(9).fill('X')) === -1);"),
           ("It always picks a free square",
            "for (let go = 0; go < 50; go++) {\n    const board = ['X','O',EMPTY,'O','X',EMPTY,EMPTY,EMPTY,'O'];\n    const move = computerMove(board);\n    assert(board[move] === EMPTY, 'it played on a taken square: ' + move);\n}")]),
  py=dict(starter="def computer_move(board):\n    free = empty_squares(board)\n    # win, block, middle, corner, anything\n    pass\n",
    answer="def computer_move(board):\n    free = empty_squares(board)\n    if not free:\n        return -1\n\n    for index in free:\n        if winning_line(place_mark(board, index, COMPUTER)) is not None:\n            return index\n    for index in free:\n        if winning_line(place_mark(board, index, PLAYER)) is not None:\n            return index\n    if board[4] == EMPTY:\n        return 4\n    corners = [corner for corner in (0, 2, 6, 8) if board[corner] == EMPTY]\n    if corners:\n        return random.choice(corners)\n    return random.choice(free)\n",
    hints=["To try a move: winning_line(place_mark(board, index, COMPUTER)) is not None",
           "Do the winning loop FIRST, then the blocking loop.",
           "random.choice(corners) picks one corner (random is already imported)."],
    tests=[("It takes a winning move",
            "board = ['O','O',EMPTY,'X','X',EMPTY,EMPTY,EMPTY,EMPTY]\ngot = computer_move(board)\nassert got == 2, f'O can win at square 2 - gave {got}'"),
           ("It blocks the player",
            "board = ['X','X',EMPTY,'O',EMPTY,EMPTY,EMPTY,EMPTY,EMPTY]\ngot = computer_move(board)\nassert got == 2, f'X would win at 2, so block it - gave {got}'"),
           ("Winning beats blocking",
            "board = ['O','O',EMPTY,'X','X',EMPTY,EMPTY,EMPTY,EMPTY]\nassert computer_move(board) == 2, 'if it can win it should win, not block'"),
           ("It takes the middle on an empty board",
            "got = computer_move([EMPTY] * 9)\nassert got == 4, f'gave {got}'"),
           ("It takes a corner when the middle is gone",
            "board = [EMPTY] * 9\nboard[4] = 'X'\nassert computer_move(board) in (0, 2, 6, 8), f'gave {computer_move(board)}'"),
           ("It says -1 when the board is full", "assert computer_move(['X'] * 9) == -1"),
           ("It always picks a free square",
            "board = ['X','O',EMPTY,'O','X',EMPTY,EMPTY,EMPTY,'O']\nfor _ in range(50):\n    move = computer_move(board)\n    assert board[move] == EMPTY, f'it played on a taken square: {move}'")]),
  demo=dict(kind="game", caption="Try to beat it. (You probably cannot — but a draw is a fine result.)"),
  warning="Check for a WIN before checking for a block. A computer that blocks when it could have won is a computer that never wins."),

step("action_for_key", "actionForKey", "action_for_key",
  "Wire up the keyboard", "You can play without a mouse — the game is finished!",
  "<p>Arrows move a dashed cursor around the nine squares and the space bar plays there.</p>",
  "key - the key name from the browser",
  "\"up\", \"down\", \"left\", \"right\", \"play\", \"pause\", \"restart\" - or nothing",
  ["Lowercase the key first.", "Arrows or WASD move the cursor.",
   "Space or Enter plays; p pauses; r starts a new round."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // return the action name, or null\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter') { return 'play'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["One if per action.", "Keys share an action with ||.", "The last line is: return null;"],
    tests=[("The arrows move the cursor",
            "assert(actionForKey('ArrowUp') === 'up' && actionForKey('ArrowDown') === 'down' && actionForKey('ArrowLeft') === 'left' && actionForKey('ArrowRight') === 'right');"),
           ("WASD works too", "assert(actionForKey('w') === 'up' && actionForKey('d') === 'right');"),
           ("Capitals still work", "assert(actionForKey('W') === 'up', 'did you lowercase the key?');"),
           ("Space plays", "assert(actionForKey(' ') === 'play', 'gave ' + actionForKey(' '));"),
           ("Enter plays too", "assert(actionForKey('Enter') === 'play');"),
           ("P pauses and R restarts", "assert(actionForKey('p') === 'pause' && actionForKey('r') === 'restart');"),
           ("An unused key gives null", "assert(actionForKey('q') === null);")]),
  py=dict(starter="def action_for_key(key):\n    k = str(key).lower()\n    # a dictionary from key names to action names, then .get(k)\n    pass\n",
    answer="def action_for_key(key):\n    k = str(key).lower()\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"play\", \"spacebar\": \"play\", \"enter\": \"play\",\n        \"p\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(k)\n",
    hints=["A dictionary IS the lookup table.", "Several keys can share an action.",
           "keys.get(k) gives None for anything missing."],
    tests=[("The arrows move the cursor",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD works too", "assert action_for_key('w') == 'up' and action_for_key('d') == 'right'"),
           ("Capitals still work", "assert action_for_key('W') == 'up'"),
           ("Space plays", "got = action_for_key(' ')\nassert got == 'play', f'gave {got!r}'"),
           ("Enter plays too", "assert action_for_key('Enter') == 'play'"),
           ("P pauses and R restarts", "assert action_for_key('p') == 'pause' and action_for_key('r') == 'restart'"),
           ("An unused key gives None", "assert action_for_key('q') is None")]),
  demo=dict(kind="final", caption="Click the page, then play with the arrow keys and space.")),
]

write_workshop("tictactoe", "Tic-Tac-Toe", STEPS)
