"""The seven steps of "Build 2048", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("slide_row", "slideRow", "slide_row",
  "Push a row along", "Tiles stop floating in mid-air.",
  "<p>Everything in 2048 happens one row at a time, and a move is really two separate jobs. This is the first: <strong>close up the gaps</strong>.</p>"
  "<p>Nothing joins together here. <code>[2, 0, 2, 4]</code> becomes <code>[2, 2, 4, 0]</code> — the tiles simply shuffle up against the left-hand wall, keeping their order.</p>",
  "row — a list of four numbers, 0 meaning empty",
  "a NEW list, the same numbers, all the gaps at the right",
  ["Make an empty list.",
   "Walk the row and copy across everything that is not 0.",
   "Add 0s to the end until the list is SIZE long.",
   "Return it."],
  js=dict(starter="function slideRow(row) {\n    // close up the gaps — nothing joins yet\n}\n",
    answer="function slideRow(row) {\n    const packed = [];\n    for (let i = 0; i < row.length; i++) {\n        if (row[i] !== 0) {\n            packed.push(row[i]);\n        }\n    }\n    while (packed.length < SIZE) {\n        packed.push(0);\n    }\n    return packed;\n}\n",
    hints=["Collect the non-zero numbers first, in the order you meet them.",
           "Then pad the answer out to four with 0s.",
           "row.filter(v => v !== 0) does the first half in one line."],
    tests=[("Gaps close up",
            "assert(slideRow([2, 0, 2, 4]).join(',') === '2,2,4,0', 'gave ' + slideRow([2, 0, 2, 4]));"),
           ("A row already packed does not change",
            "assert(slideRow([2, 4, 8, 16]).join(',') === '2,4,8,16');"),
           ("An empty row stays empty",
            "assert(slideRow([0, 0, 0, 0]).join(',') === '0,0,0,0');"),
           ("A lonely tile goes all the way",
            "assert(slideRow([0, 0, 0, 2]).join(',') === '2,0,0,0', 'gave ' + slideRow([0, 0, 0, 2]));"),
           ("The order is kept",
            "assert(slideRow([0, 8, 0, 2]).join(',') === '8,2,0,0', 'the 8 was in front, so it stays in front');"),
           ("Nothing joins up yet",
            "assert(slideRow([2, 2, 0, 0]).join(',') === '2,2,0,0', 'sliding does not merge — that is the next step');"),
           ("The answer is always four long",
            "assert(slideRow([2, 0, 0, 0]).length === SIZE);"),
           ("The row you were given is left alone",
            "const before = [2, 0, 2, 4];\nslideRow(before);\nassert(before.join(',') === '2,0,2,4', 'build a new row instead of editing this one');")]),
  py=dict(starter="def slide_row(row):\n    # close up the gaps - nothing joins yet\n    pass\n",
    answer="def slide_row(row):\n    packed = [value for value in row if value != 0]\n    return packed + [0] * (SIZE - len(packed))\n",
    hints=["[v for v in row if v != 0] collects the tiles.",
           "[0] * n makes a list of n zeros, and + glues two lists together.",
           "return packed + [0] * (SIZE - len(packed))"],
    tests=[("Gaps close up",
            "got = slide_row([2, 0, 2, 4])\nassert got == [2, 2, 4, 0], f'gave {got}'"),
           ("A row already packed does not change",
            "assert slide_row([2, 4, 8, 16]) == [2, 4, 8, 16]"),
           ("An empty row stays empty", "assert slide_row([0, 0, 0, 0]) == [0, 0, 0, 0]"),
           ("A lonely tile goes all the way",
            "assert slide_row([0, 0, 0, 2]) == [2, 0, 0, 0]"),
           ("The order is kept",
            "assert slide_row([0, 8, 0, 2]) == [8, 2, 0, 0]"),
           ("Nothing joins up yet",
            "assert slide_row([2, 2, 0, 0]) == [2, 2, 0, 0], 'sliding does not merge'"),
           ("The answer is always four long",
            "assert len(slide_row([2, 0, 0, 0])) == SIZE"),
           ("The row you were given is left alone",
            "before = [2, 0, 2, 4]\nslide_row(before)\nassert before == [2, 0, 2, 4]")]),
  demo=dict(kind="row", caption="Pick a row and watch what sliding does to it — the middle line is the answer.")),

step("merge_row", "mergeRow", "merge_row",
  "Join the twins", "Tiles combine, and you can score.",
  "<p>The second half of a move, and the heart of the game.</p>"
  "<p>Walk along a row that has already been slid. If a number equals the one after it, replace the pair with a single tile worth double — and then <strong>step past both of them</strong>.</p>"
  "<p>That last bit matters more than it looks. A row of four 2s must become two 4s, not one 8. Each tile may only join once per move, and skipping past both is how you enforce that in one line.</p>",
  "row — four numbers, already slid",
  "the new row, and how many points it scored",
  ["Start an empty result and a score of 0.",
   "Walk along with a counter i.",
   "If row[i] is not 0 and equals row[i + 1]: add row[i] × 2 to the result, add that to the score, and move i on by TWO.",
   "Otherwise add row[i] and move i on by ONE.",
   "Pad the result with 0s."],
  js=dict(starter="function mergeRow(row) {\n    // join equal neighbours — each tile joins at most once\n    return { row: row, gained: 0 };\n}\n",
    answer="function mergeRow(row) {\n    const result = [];\n    let gained = 0;\n    let i = 0;\n\n    while (i < row.length) {\n        if (row[i] !== 0 && row[i] === row[i + 1]) {\n            const joined = row[i] * 2;\n            result.push(joined);\n            gained = gained + joined;\n            i = i + 2;\n        } else {\n            result.push(row[i]);\n            i = i + 1;\n        }\n    }\n\n    while (result.length < SIZE) {\n        result.push(0);\n    }\n    return { row: result, gained: gained };\n}\n",
    hints=["A while loop is easier here than a for loop, because i jumps by 1 or 2.",
           "row[i + 1] is undefined at the end of the row — that is fine, it will not equal anything.",
           "i = i + 2 after a join is what stops one tile joining twice."],
    tests=[("Two the same become one",
            "const out = mergeRow([2, 2, 0, 0]);\nassert(out.row.join(',') === '4,0,0,0', 'gave ' + out.row);"),
           ("Joining scores the new tile's value",
            "assert(mergeRow([2, 2, 0, 0]).gained === 4, 'gave ' + mergeRow([2, 2, 0, 0]).gained);"),
           ("Four the same become TWO tiles, not one",
            "const out = mergeRow([2, 2, 2, 2]);\nassert(out.row.join(',') === '4,4,0,0', 'gave ' + out.row + ' — each tile may only join once');\nassert(out.gained === 8);"),
           ("Three the same join only the first two",
            "const out = mergeRow([4, 4, 4, 0]);\nassert(out.row.join(',') === '8,4,0,0', 'gave ' + out.row);"),
           ("Different numbers do not join",
            "assert(mergeRow([2, 4, 8, 16]).row.join(',') === '2,4,8,16');\nassert(mergeRow([2, 4, 8, 16]).gained === 0);"),
           ("Zeros never join with each other",
            "assert(mergeRow([0, 0, 0, 0]).row.join(',') === '0,0,0,0', 'two empty squares must not become a 0-tile');"),
           ("A mixed row works",
            "const out = mergeRow([2, 2, 4, 0]);\nassert(out.row.join(',') === '4,4,0,0', 'gave ' + out.row);\nassert(out.gained === 4);"),
           ("The answer is always four long",
            "assert(mergeRow([2, 2, 2, 2]).row.length === SIZE);")]),
  py=dict(starter="def merge_row(row):\n    # join equal neighbours - each tile joins at most once\n    return row, 0\n",
    answer="def merge_row(row):\n    result = []\n    gained = 0\n    i = 0\n\n    while i < len(row):\n        if row[i] != 0 and i + 1 < len(row) and row[i] == row[i + 1]:\n            joined = row[i] * 2\n            result.append(joined)\n            gained += joined\n            i += 2\n        else:\n            result.append(row[i])\n            i += 1\n\n    return result + [0] * (SIZE - len(result)), gained\n",
    hints=["A while loop is easier here than a for loop, because i jumps by 1 or 2.",
           "Check i + 1 < len(row) before looking at the next number.",
           "i += 2 after a join is what stops one tile joining twice."],
    tests=[("Two the same become one",
            "row, gained = merge_row([2, 2, 0, 0])\nassert row == [4, 0, 0, 0], f'gave {row}'"),
           ("Joining scores the new tile's value",
            "assert merge_row([2, 2, 0, 0])[1] == 4"),
           ("Four the same become TWO tiles, not one",
            "row, gained = merge_row([2, 2, 2, 2])\nassert row == [4, 4, 0, 0], f'gave {row}'\nassert gained == 8"),
           ("Three the same join only the first two",
            "row, gained = merge_row([4, 4, 4, 0])\nassert row == [8, 4, 0, 0], f'gave {row}'"),
           ("Different numbers do not join",
            "row, gained = merge_row([2, 4, 8, 16])\nassert row == [2, 4, 8, 16] and gained == 0"),
           ("Zeros never join with each other",
            "assert merge_row([0, 0, 0, 0])[0] == [0, 0, 0, 0]"),
           ("A mixed row works",
            "row, gained = merge_row([2, 2, 4, 0])\nassert row == [4, 4, 0, 0] and gained == 4"),
           ("The answer is always four long",
            "assert len(merge_row([2, 2, 2, 2])[0]) == SIZE")]),
  demo=dict(kind="row", caption="The bottom line is the merged row. Try 2,2,2,2 — it must become two 4s."),
  warning="After a join, step past BOTH tiles. Move on by one instead and four 2s turn into a single 8, which is wrong and lets a player score twice as fast."),

step("empty_cells", "emptyCells", "empty_cells",
  "Where is there room?", "The board knows where a tile can appear.",
  "<p>A short one, but three later functions depend on it: dropping a new tile, working out whether the board is full, and deciding whether the game is over.</p>",
  "board", "a list of the places still holding 0",
  ["Make an empty list.",
   "Walk the whole board.",
   "Whenever a square is 0, add its position to the list."],
  js=dict(starter="function emptyCells(board) {\n    // the positions holding nothing\n}\n",
    answer="function emptyCells(board) {\n    const found = [];\n    for (let i = 0; i < board.length; i++) {\n        if (board[i] === 0) {\n            found.push(i);\n        }\n    }\n    return found;\n}\n",
    hints=["Collect the POSITIONS (0 to 15), not the values — they are all 0 anyway.",
           "One loop and one if.",
           "found.push(i);"],
    tests=[("A new board has fourteen free squares",
            "const board = emptyBoard();\naddTile(board);\naddTile(board);\nassert(emptyCells(board).length === CELL_COUNT - 2, 'gave ' + emptyCells(board).length);"),
           ("An empty board has sixteen",
            "assert(emptyCells(emptyBoard()).length === CELL_COUNT);"),
           ("A full board has none",
            "const board = emptyBoard().map(function () { return 2; });\nassert(emptyCells(board).length === 0);"),
           ("It gives back positions, not values",
            "const board = emptyBoard();\nboard[0] = 2;\nassert(emptyCells(board)[0] === 1, 'the first free square is at position 1');"),
           ("Every position it names really is empty",
            "const board = emptyBoard();\nboard[3] = 4;\nboard[9] = 8;\nemptyCells(board).forEach(function (i) {\n    assert(board[i] === 0, 'position ' + i + ' is not empty');\n});")]),
  py=dict(starter="def empty_cells(board):\n    # the positions holding nothing\n    pass\n",
    answer="def empty_cells(board):\n    return [i for i, value in enumerate(board) if value == 0]\n",
    hints=["enumerate(board) gives the position and the value together.",
           "Collect the POSITIONS, not the values.",
           "return [i for i, value in enumerate(board) if value == 0]"],
    tests=[("A new board has fourteen free squares",
            "board = empty_board()\nadd_tile(board)\nadd_tile(board)\nassert len(empty_cells(board)) == CELL_COUNT - 2"),
           ("An empty board has sixteen",
            "assert len(empty_cells(empty_board())) == CELL_COUNT"),
           ("A full board has none",
            "assert empty_cells([2] * CELL_COUNT) == []"),
           ("It gives back positions, not values",
            "board = empty_board()\nboard[0] = 2\nassert empty_cells(board)[0] == 1"),
           ("Every position it names really is empty",
            "board = empty_board()\nboard[3] = 4\nboard[9] = 8\nfor i in empty_cells(board):\n    assert board[i] == 0")]),
  demo=dict(kind="board", caption="Slide the practice board about and watch the free-square count.")),

step("rotate_board", "rotateBoard", "rotate_board",
  "Turn the board", "One move becomes four.",
  "<p>Here is the trick that makes this whole game short.</p>"
  "<p>You have written how to slide LEFT. Writing three more copies for right, up and down would mean three more places for bugs to hide. Instead: <strong>turn the board</strong> until the way you want to go is pointing left, slide left, then turn it back.</p>"
  "<p>The square that ends up at (column, row) after a clockwise quarter turn is the one that started at (row, SIZE - 1 - column). Draw a 4×4 grid on paper and turn it once — you will see it.</p>",
  "board", "a NEW board, turned a quarter turn clockwise",
  ["Make a new empty board.",
   "For every column and row of the NEW board, fetch the square from (row, SIZE - 1 - column) of the old one.",
   "Return the new board."],
  js=dict(starter="function rotateBoard(board) {\n    const turned = emptyBoard();\n    // (column, row) comes from (row, SIZE - 1 - column)\n    return turned;\n}\n",
    answer="function rotateBoard(board) {\n    const turned = emptyBoard();\n    for (let row = 0; row < SIZE; row++) {\n        for (let column = 0; column < SIZE; column++) {\n            turned[cellIndex(column, row)] = board[cellIndex(row, SIZE - 1 - column)];\n        }\n    }\n    return turned;\n}\n",
    hints=["Two loops over the NEW board, fetching from the old one.",
           "cellIndex(column, row) turns a pair into a position.",
           "turned[cellIndex(column, row)] = board[cellIndex(row, SIZE - 1 - column)];"],
    tests=[("The top-left corner goes to the top-right",
            "const board = emptyBoard();\nboard[cellIndex(0, 0)] = 2;\nconst turned = rotateBoard(board);\nassert(turned[cellIndex(SIZE - 1, 0)] === 2, 'a clockwise turn sends the top-left corner to the top-right');"),
           ("The top-right goes to the bottom-right",
            "const board = emptyBoard();\nboard[cellIndex(SIZE - 1, 0)] = 2;\nconst turned = rotateBoard(board);\nassert(turned[cellIndex(SIZE - 1, SIZE - 1)] === 2);"),
           ("Four turns is a full circle",
            "let board = emptyBoard();\nfor (let i = 0; i < CELL_COUNT; i++) { board[i] = i; }\nconst original = board.join(',');\nfor (let i = 0; i < 4; i++) { board = rotateBoard(board); }\nassert(board.join(',') === original, 'four quarter turns must bring it back exactly');"),
           ("No tile is lost or invented",
            "let board = emptyBoard();\nfor (let i = 0; i < CELL_COUNT; i++) { board[i] = i; }\nconst turned = rotateBoard(board);\nassert(turned.slice().sort().join(',') === board.slice().sort().join(','), 'the same sixteen numbers must come out');"),
           ("A top row becomes a right-hand column",
            "const board = emptyBoard();\nsetRow(board, 0, [2, 4, 8, 16]);\nconst turned = rotateBoard(board);\nfor (let row = 0; row < SIZE; row++) {\n    assert(turned[cellIndex(SIZE - 1, row)] === [2, 4, 8, 16][row], 'the top row should stand up on the right');\n}"),
           ("The board you were given is left alone",
            "const board = emptyBoard();\nboard[0] = 2;\nrotateBoard(board);\nassert(board[0] === 2, 'build a new board instead of editing this one');")]),
  py=dict(starter="def rotate_board(board):\n    turned = empty_board()\n    # (column, row) comes from (row, SIZE - 1 - column)\n    return turned\n",
    answer="def rotate_board(board):\n    turned = empty_board()\n    for row in range(SIZE):\n        for column in range(SIZE):\n            turned[cell_index(column, row)] = board[cell_index(row, SIZE - 1 - column)]\n    return turned\n",
    hints=["Two loops over the NEW board, fetching from the old one.",
           "cell_index(column, row) turns a pair into a position.",
           "turned[cell_index(column, row)] = board[cell_index(row, SIZE - 1 - column)]"],
    tests=[("The top-left corner goes to the top-right",
            "board = empty_board()\nboard[cell_index(0, 0)] = 2\nturned = rotate_board(board)\nassert turned[cell_index(SIZE - 1, 0)] == 2"),
           ("The top-right goes to the bottom-right",
            "board = empty_board()\nboard[cell_index(SIZE - 1, 0)] = 2\nturned = rotate_board(board)\nassert turned[cell_index(SIZE - 1, SIZE - 1)] == 2"),
           ("Four turns is a full circle",
            "board = list(range(CELL_COUNT))\nwork = board\nfor _ in range(4):\n    work = rotate_board(work)\nassert work == board"),
           ("No tile is lost or invented",
            "board = list(range(CELL_COUNT))\nassert sorted(rotate_board(board)) == sorted(board)"),
           ("A top row becomes a right-hand column",
            "board = empty_board()\nset_row(board, 0, [2, 4, 8, 16])\nturned = rotate_board(board)\nfor row in range(SIZE):\n    assert turned[cell_index(SIZE - 1, row)] == [2, 4, 8, 16][row]"),
           ("The board you were given is left alone",
            "board = empty_board()\nboard[0] = 2\nrotate_board(board)\nassert board[0] == 2")]),
  demo=dict(kind="board", caption="Press Turn a few times. Four turns bring the board right back.")),

step("move_board", "moveBoard", "move_board",
  "All four directions", "The board slides any way you like.",
  "<p>Now cash in the trick. Turn, slide left, turn back.</p>"
  "<p>How many turns? Sliding left needs none. Down needs one. Right needs two. Up needs three. Then turn the rest of the way — <code>SIZE - turns</code> more — to bring the board back the right way up.</p>",
  "board, direction — 'left', 'right', 'up' or 'down'",
  "the new board, and the points scored",
  ["Ask turns-for-direction how many quarter turns you need.",
   "Rotate the board that many times.",
   "Slide it left with move-left, keeping the points.",
   "Rotate it (SIZE - turns) more times to put it back.",
   "Return the board and the points."],
  js=dict(starter="function moveBoard(board, direction) {\n    // turn, slide left, turn back\n    return { board: board, gained: 0 };\n}\n",
    answer="function moveBoard(board, direction) {\n    const turns = turnsForDirection(direction);\n\n    let work = board;\n    for (let i = 0; i < turns; i++) {\n        work = rotateBoard(work);\n    }\n\n    const moved = moveLeft(work);\n    work = moved.board;\n\n    for (let i = 0; i < (SIZE - turns) % SIZE; i++) {\n        work = rotateBoard(work);\n    }\n    return { board: work, gained: moved.gained };\n}\n",
    hints=["turnsForDirection and moveLeft are both written for you.",
           "The turns before and after must add up to four — a full circle.",
           "(SIZE - turns) % SIZE handles the left case, where turns is 0."],
    tests=[("Sliding left packs tiles to the left",
            "const board = emptyBoard();\nboard[cellIndex(2, 1)] = 2;\nconst out = moveBoard(board, 'left');\nassert(out.board[cellIndex(0, 1)] === 2, 'the tile should be at the left of its row');"),
           ("Sliding right packs them to the right",
            "const board = emptyBoard();\nboard[cellIndex(1, 1)] = 2;\nconst out = moveBoard(board, 'right');\nassert(out.board[cellIndex(SIZE - 1, 1)] === 2);"),
           ("Sliding up packs them to the top",
            "const board = emptyBoard();\nboard[cellIndex(1, 2)] = 2;\nconst out = moveBoard(board, 'up');\nassert(out.board[cellIndex(1, 0)] === 2, 'the tile should be at the top of its column');"),
           ("Sliding down packs them to the bottom",
            "const board = emptyBoard();\nboard[cellIndex(1, 1)] = 2;\nconst out = moveBoard(board, 'down');\nassert(out.board[cellIndex(1, SIZE - 1)] === 2);"),
           ("Tiles still join in every direction",
            "['left', 'right', 'up', 'down'].forEach(function (direction) {\n    const board = emptyBoard();\n    setRow(board, 0, [2, 2, 0, 0]);\n    setRow(board, 1, [2, 2, 0, 0]);\n    const out = moveBoard(board, direction);\n    assert(out.gained > 0, 'nothing joined when sliding ' + direction);\n});"),
           ("A board with nothing to do does not change",
            "const board = emptyBoard();\nsetRow(board, 0, [2, 4, 8, 16]);\nsetRow(board, 1, [4, 8, 16, 32]);\nsetRow(board, 2, [2, 4, 8, 16]);\nsetRow(board, 3, [4, 8, 16, 32]);\nconst out = moveBoard(board, 'left');\nassert(out.board.join(',') === board.join(','), 'every row is already packed and nothing can join');"),
           ("The board comes back the right way up",
            "const board = emptyBoard();\nboard[cellIndex(0, 0)] = 2;\nboard[cellIndex(1, 0)] = 4;\nconst out = moveBoard(board, 'left');\nassert(out.board[cellIndex(0, 0)] === 2 && out.board[cellIndex(1, 0)] === 4, 'the turns before and after must add up to a full circle');")]),
  py=dict(starter="def move_board(board, direction):\n    # turn, slide left, turn back\n    return board, 0\n",
    answer="def move_board(board, direction):\n    turns = turns_for_direction(direction)\n\n    work = board\n    for _ in range(turns):\n        work = rotate_board(work)\n\n    work, gained = move_left(work)\n\n    for _ in range((SIZE - turns) % SIZE):\n        work = rotate_board(work)\n    return work, gained\n",
    hints=["turns_for_direction and move_left are both written for you.",
           "The turns before and after must add up to four - a full circle.",
           "(SIZE - turns) % SIZE handles the left case, where turns is 0."],
    tests=[("Sliding left packs tiles to the left",
            "board = empty_board()\nboard[cell_index(2, 1)] = 2\nout, _ = move_board(board, 'left')\nassert out[cell_index(0, 1)] == 2"),
           ("Sliding right packs them to the right",
            "board = empty_board()\nboard[cell_index(1, 1)] = 2\nout, _ = move_board(board, 'right')\nassert out[cell_index(SIZE - 1, 1)] == 2"),
           ("Sliding up packs them to the top",
            "board = empty_board()\nboard[cell_index(1, 2)] = 2\nout, _ = move_board(board, 'up')\nassert out[cell_index(1, 0)] == 2"),
           ("Sliding down packs them to the bottom",
            "board = empty_board()\nboard[cell_index(1, 1)] = 2\nout, _ = move_board(board, 'down')\nassert out[cell_index(1, SIZE - 1)] == 2"),
           ("Tiles still join in every direction",
            "for direction in ('left', 'right', 'up', 'down'):\n    board = empty_board()\n    set_row(board, 0, [2, 2, 0, 0])\n    set_row(board, 1, [2, 2, 0, 0])\n    _, gained = move_board(board, direction)\n    assert gained > 0, f'nothing joined when sliding {direction}'"),
           ("A board with nothing to do does not change",
            "board = empty_board()\nset_row(board, 0, [2, 4, 8, 16])\nset_row(board, 1, [4, 8, 16, 32])\nset_row(board, 2, [2, 4, 8, 16])\nset_row(board, 3, [4, 8, 16, 32])\nout, _ = move_board(board, 'left')\nassert out == board"),
           ("The board comes back the right way up",
            "board = empty_board()\nboard[cell_index(0, 0)] = 2\nboard[cell_index(1, 0)] = 4\nout, _ = move_board(board, 'left')\nassert out[cell_index(0, 0)] == 2 and out[cell_index(1, 0)] == 4")]),
  demo=dict(kind="board", caption="Slide the practice board every way. One function is doing all four.")),

step("has_moves", "hasMoves", "has_moves",
  "Is it over?", "The game knows when to stop.",
  "<p>A full board is <em>not</em> the same as a finished game. If two neighbours hold the same number they can still join, and that join makes room again.</p>"
  "<p>So there are two questions: is there an empty square, and is there a pair of equal neighbours? Only when the answer to both is no is the game really over.</p>",
  "board", "True if the player can still move",
  ["If there is any empty square, return True straight away.",
   "Otherwise look at every square and compare it with the one to its right and the one below.",
   "If any pair matches, return True.",
   "If you get all the way through, return False."],
  js=dict(starter="function hasMoves(board) {\n    // an empty square, or two equal neighbours\n}\n",
    answer="function hasMoves(board) {\n    if (emptyCells(board).length > 0) {\n        return true;\n    }\n    for (let row = 0; row < SIZE; row++) {\n        for (let column = 0; column < SIZE; column++) {\n            const value = board[cellIndex(column, row)];\n            if (column + 1 < SIZE && board[cellIndex(column + 1, row)] === value) {\n                return true;\n            }\n            if (row + 1 < SIZE && board[cellIndex(column, row + 1)] === value) {\n                return true;\n            }\n        }\n    }\n    return false;\n}\n",
    hints=["Checking for an empty square first saves all the rest of the work.",
           "Only look right and down — every pair gets checked once that way.",
           "Guard the edges with column + 1 < SIZE and row + 1 < SIZE."],
    tests=[("A new game has moves",
            "assert(hasMoves(createGame().board) === true);"),
           ("An empty board has moves",
            "assert(hasMoves(emptyBoard()) === true);"),
           ("A full board with a matching pair still has moves",
            "const board = [2, 4, 2, 4,\n               4, 2, 4, 2,\n               2, 4, 2, 4,\n               4, 2, 2, 8];\nassert(hasMoves(board) === true, 'the two 2s at the bottom can still join');"),
           ("A properly stuck board has none",
            "const board = [2, 4, 2, 4,\n               4, 2, 4, 2,\n               2, 4, 2, 4,\n               4, 2, 4, 2];\nassert(hasMoves(board) === false, 'no gaps and no two neighbours the same');"),
           ("A pair side by side counts",
            "const board = [2, 2, 2, 4,\n               4, 8, 4, 2,\n               2, 4, 2, 4,\n               4, 2, 4, 2];\nassert(hasMoves(board) === true);"),
           ("A pair one above the other counts too",
            "const board = [2, 4, 8, 4,\n               2, 8, 4, 2,\n               4, 4, 2, 4,\n               8, 2, 4, 2];\nassert(hasMoves(board) === true, 'the two 2s in the left column can join');"),
           ("A real game ends only when it is truly stuck",
            "const state = createGame();\nlet guard = 0;\nwhile (!state.isOver && guard < 3000) {\n    ['left', 'up', 'right', 'down'].forEach(function (d) { makeMove(state, d); });\n    guard = guard + 1;\n}\nassert(state.isOver === false || !hasMoves(state.board), 'the game may only end when nothing can move');")]),
  py=dict(starter="def has_moves(board):\n    # an empty square, or two equal neighbours\n    pass\n",
    answer="def has_moves(board):\n    if empty_cells(board):\n        return True\n    for row in range(SIZE):\n        for column in range(SIZE):\n            value = board[cell_index(column, row)]\n            if column + 1 < SIZE and board[cell_index(column + 1, row)] == value:\n                return True\n            if row + 1 < SIZE and board[cell_index(column, row + 1)] == value:\n                return True\n    return False\n",
    hints=["Checking for an empty square first saves all the rest of the work.",
           "Only look right and down - every pair gets checked once that way.",
           "Guard the edges with column + 1 < SIZE and row + 1 < SIZE."],
    tests=[("A new game has moves",
            "assert has_moves(create_game()['board']) is True"),
           ("An empty board has moves", "assert has_moves(empty_board()) is True"),
           ("A full board with a matching pair still has moves",
            "board = [2, 4, 2, 4,\n         4, 2, 4, 2,\n         2, 4, 2, 4,\n         4, 2, 2, 8]\nassert has_moves(board) is True"),
           ("A properly stuck board has none",
            "board = [2, 4, 2, 4,\n         4, 2, 4, 2,\n         2, 4, 2, 4,\n         4, 2, 4, 2]\nassert has_moves(board) is False"),
           ("A pair side by side counts",
            "board = [2, 2, 2, 4,\n         4, 8, 4, 2,\n         2, 4, 2, 4,\n         4, 2, 4, 2]\nassert has_moves(board) is True"),
           ("A pair one above the other counts too",
            "board = [2, 4, 8, 4,\n         2, 8, 4, 2,\n         4, 4, 2, 4,\n         8, 2, 4, 2]\nassert has_moves(board) is True"),
           ("A real game ends only when it is truly stuck",
            "state = create_game()\nfor _ in range(3000):\n    if state['is_over']:\n        break\n    for d in ('left', 'up', 'right', 'down'):\n        make_move(state, d)\nassert state['is_over'] is False or not has_moves(state['board'])")]),
  demo=dict(kind="game", caption="Play a real game. It only ends when nothing on the board can move."),
  warning="A full board is not a finished game. Forget the neighbour check and you will be told 'no moves left' while a perfectly good join is sitting right there."),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>Four keys, four directions, and the game is yours.</p>",
  "key", "an action name, or nothing at all",
  ["The arrows or WASD give the four directions.",
   "P → 'pause'. R → 'restart'.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // four directions, pause, restart\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["The action names must match the ones moveBoard expects exactly.",
           "toLowerCase() up front means capitals work too.",
           "Six ifs and a return null;"],
    tests=[("The arrows slide the board",
            "assert(actionForKey('ArrowUp') === 'up');\nassert(actionForKey('ArrowDown') === 'down');\nassert(actionForKey('ArrowLeft') === 'left');\nassert(actionForKey('ArrowRight') === 'right');"),
           ("WASD works too",
            "assert(actionForKey('w') === 'up');\nassert(actionForKey('s') === 'down');\nassert(actionForKey('a') === 'left');\nassert(actionForKey('d') === 'right');"),
           ("Capital letters work",
            "assert(actionForKey('W') === 'up');\nassert(actionForKey('R') === 'restart');"),
           ("P pauses and R restarts",
            "assert(actionForKey('p') === 'pause');\nassert(actionForKey('r') === 'restart');"),
           ("The names match what the game expects",
            "['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'].forEach(function (key) {\n    const state = createGame();\n    makeMove(state, actionForKey(key));\n});"),
           ("Other keys do nothing",
            "assert(actionForKey('z') === null);\nassert(actionForKey('Enter') === null);")]),
  py=dict(starter="def action_for_key(key):\n    keys = {\n        # \"arrowup\": \"up\", ...\n    }\n    return keys.get(str(key).lower())\n",
    answer="def action_for_key(key):\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \"p\": \"pause\", \"r\": \"restart\",\n    }\n    return keys.get(str(key).lower())\n",
    hints=["The action names must match the ones move_board expects exactly.",
           "A dictionary is tidier than six ifs.",
           "keys.get(...) gives None for anything not listed."],
    tests=[("The arrows slide the board",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD works too",
            "assert action_for_key('w') == 'up'\nassert action_for_key('s') == 'down'\nassert action_for_key('a') == 'left'\nassert action_for_key('d') == 'right'"),
           ("Capital letters work",
            "assert action_for_key('W') == 'up'\nassert action_for_key('R') == 'restart'"),
           ("P pauses and R restarts",
            "assert action_for_key('p') == 'pause'\nassert action_for_key('r') == 'restart'"),
           ("The names match what the game expects",
            "for key in ('ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight'):\n    make_move(create_game(), action_for_key(key))"),
           ("Other keys do nothing",
            "assert action_for_key('z') is None\nassert action_for_key('Enter') is None")]),
  demo=dict(kind="final", caption="Click the page and play with the arrow keys. How far can you get?")),
]

write_workshop("twenty48", "2048", STEPS)
