"""The five steps of "Build Typing Race", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("matching_letters", "matchingLetters", "matching_letters",
  "How much is right so far?", "Your typing turns black as it matches.",
  "<p>As you type, the game shows you how much of the word you have got right — and strikes through the moment you go wrong.</p>"
  "<p>The important detail is that you must stop at the <strong>first</strong> mistake. Type <code>wxter</code> for <code>water</code> and only the <code>w</code> counts, even though four of your five letters are in the right place. Once you have gone wrong, everything after it is wrong too.</p>",
  "word — the word to type. typed — what has been typed so far.",
  "how many letters from the start match",
  ["Start a count at 0.",
   "Walk through what has been typed, one letter at a time.",
   "If you run past the end of the word, or the letters differ, stop and return the count.",
   "Otherwise add one and carry on."],
  js=dict(starter="function matchingLetters(word, typed) {\n    // count from the start, stop at the first difference\n}\n",
    answer="function matchingLetters(word, typed) {\n    let count = 0;\n    for (let i = 0; i < typed.length; i++) {\n        if (i >= word.length || word.charAt(i) !== typed.charAt(i)) {\n            return count;\n        }\n        count = count + 1;\n    }\n    return count;\n}\n",
    hints=["Walk what was TYPED, not the word — the player may not have finished.",
           "return count; the moment two letters differ.",
           "i >= word.length catches typing more letters than the word has."],
    tests=[("Nothing typed matches nothing",
            "assert(matchingLetters('water', '') === 0);"),
           ("A right start counts",
            "assert(matchingLetters('water', 'wat') === 3, 'gave ' + matchingLetters('water', 'wat'));"),
           ("The whole word counts",
            "assert(matchingLetters('water', 'water') === 5);"),
           ("It stops at the first mistake",
            "assert(matchingLetters('water', 'wxt') === 1, 'gave ' + matchingLetters('water', 'wxt') + ' — after a wrong letter, nothing counts');"),
           ("Letters that happen to match after a mistake do not count",
            "assert(matchingLetters('water', 'wxter') === 1, 'gave ' + matchingLetters('water', 'wxter') + ' — the t, e and r are in the right place, but the word is still wrong');"),
           ("A wrong first letter counts nothing",
            "assert(matchingLetters('water', 'z') === 0);"),
           ("Typing past the end of the word is safe",
            "assert(matchingLetters('at', 'atom') === 2, 'gave ' + matchingLetters('at', 'atom'));"),
           ("It matches what isTypedRight thinks",
            "const state = createGame();\nstate.words = ['water'];\nstate.index = 0;\nstate.typed = 'wat';\nassert(isTypedRight(state) === true);\nstate.typed = 'wxt';\nassert(isTypedRight(state) === false);")]),
  py=dict(starter="def matching_letters(word, typed):\n    # count from the start, stop at the first difference\n    pass\n",
    answer="def matching_letters(word, typed):\n    count = 0\n    for i, letter in enumerate(typed):\n        if i >= len(word) or word[i] != letter:\n            return count\n        count += 1\n    return count\n",
    hints=["Walk what was TYPED, not the word - the player may not have finished.",
           "return count the moment two letters differ.",
           "i >= len(word) catches typing more letters than the word has."],
    tests=[("Nothing typed matches nothing",
            "assert matching_letters('water', '') == 0"),
           ("A right start counts", "assert matching_letters('water', 'wat') == 3"),
           ("The whole word counts", "assert matching_letters('water', 'water') == 5"),
           ("It stops at the first mistake",
            "got = matching_letters('water', 'wxt')\nassert got == 1, f'gave {got}'"),
           ("Letters that happen to match after a mistake do not count",
            "got = matching_letters('water', 'wxter')\nassert got == 1, f'gave {got}'"),
           ("A wrong first letter counts nothing",
            "assert matching_letters('water', 'z') == 0"),
           ("Typing past the end of the word is safe",
            "assert matching_letters('at', 'atom') == 2"),
           ("It matches what is_typed_right thinks",
            "state = create_game()\nstate.update({'words': ['water'], 'index': 0, 'typed': 'wat'})\nassert is_typed_right(state) is True\nstate['typed'] = 'wxt'\nassert is_typed_right(state) is False")]),
  demo=dict(kind="match", caption="Add letters and watch the count. One wrong letter spoils everything after it.")),

step("submit_word", "submitWord", "submit_word",
  "Press space", "The race moves along.",
  "<p>Space means \"I have finished that word\". Right or wrong, the game moves on — this is a <em>race</em>, and stopping to fix things would ruin the rhythm.</p>"
  "<p>Notice what gets counted when the word is right: the length of the word <strong>plus one</strong>. That extra one is the space you just pressed, and typists have always counted it. Leave it out and everyone's speed comes out about 15% too low.</p>"
  "<p>One more job: push the answer onto <code>state.results</code>. The counters only say <em>how many</em> went wrong — this list says <em>which</em>, and that is what lets the page draw a line through the words you fluffed.</p>",
  "state", "True if the word was right",
  ["Refuse if the game is over, paused, or nothing has been typed.",
   "Compare what was typed with the current word.",
   "If it matches: add one to `correct`, and add the word's length PLUS ONE to `lettersTyped`.",
   "If not: add one to `wrong`.",
   "Either way, remember the answer by pushing it onto `results`.",
   "Move on to the next word and clear what was typed.",
   "If there are no words left, the race is over."],
  js=dict(starter="function submitWord(state) {\n    // right or wrong, move on to the next word\n}\n",
    answer="function submitWord(state) {\n    if (state.isOver || state.isPaused || state.typed.length === 0) {\n        return false;\n    }\n    const right = state.typed === currentWord(state);\n\n    if (right) {\n        state.correct = state.correct + 1;\n        state.lettersTyped = state.lettersTyped + currentWord(state).length + 1;\n    } else {\n        state.wrong = state.wrong + 1;\n    }\n    state.results.push(right);\n\n    state.index = state.index + 1;\n    state.typed = '';\n\n    if (state.index >= state.words.length) {\n        state.isOver = true;\n    }\n    return right;\n}\n",
    hints=["currentWord(state) is written for you.",
           "The + 1 on lettersTyped is the space bar — it counts.",
           "state.results.push(right) records the answer for the page to draw.",
           "Move on and clear the typing whether the word was right or wrong."],
    tests=[("A right word is counted",
            "const state = createGame();\nstate.words = ['water', 'little'];\nstate.index = 0;\nstate.typed = 'water';\nassert(submitWord(state) === true);\nassert(state.correct === 1);"),
           ("A wrong word is counted too",
            "const state = createGame();\nstate.words = ['water', 'little'];\nstate.index = 0;\nstate.typed = 'wxter';\nassert(submitWord(state) === false);\nassert(state.wrong === 1);"),
           ("Either way the race moves on",
            "const state = createGame();\nstate.words = ['water', 'little'];\nstate.index = 0;\nstate.typed = 'nonsense';\nsubmitWord(state);\nassert(state.index === 1, 'the race does not stop for a mistake');\nassert(state.typed === '', 'the typing box should be empty for the next word');"),
           ("The space bar counts as a character",
            "const state = createGame();\nstate.words = ['water'];\nstate.index = 0;\nstate.typed = 'water';\nsubmitWord(state);\nassert(state.lettersTyped === 6, 'gave ' + state.lettersTyped + ' — five letters plus the space');"),
           ("A wrong word earns no characters",
            "const state = createGame();\nstate.words = ['water'];\nstate.index = 0;\nstate.typed = 'wrong';\nsubmitWord(state);\nassert(state.lettersTyped === 0);"),
           ("Pressing space with nothing typed does nothing",
            "const state = createGame();\nstate.typed = '';\nconst before = state.index;\nassert(submitWord(state) === false);\nassert(state.index === before);"),
           ("Finishing the last word ends the race",
            "const state = createGame();\nstate.words = ['water'];\nstate.index = 0;\nstate.typed = 'water';\nsubmitWord(state);\nassert(state.isOver === true);"),
           ("Which words went wrong is remembered",
            "const state = createGame();\nstate.words = ['water', 'little', 'sound'];\nstate.index = 0;\nstate.typed = 'water';\nsubmitWord(state);\nstate.typed = 'wrong';\nsubmitWord(state);\nstate.typed = 'sound';\nsubmitWord(state);\nassert(state.results.length === 3, 'one entry per word, got ' + state.results.length);\nassert(state.results[0] === true && state.results[1] === false && state.results[2] === true, 'got ' + JSON.stringify(state.results));"),
           ("A whole race can be typed",
            "const state = createGame();\nfor (let i = 0; i < state.words.length; i++) {\n    state.typed = currentWord(state);\n    submitWord(state);\n}\nassert(state.correct === state.words.length, 'every word should have been right');\nassert(state.isOver === true, 'the race should have finished');\nassert(state.results.length === state.words.length, 'results should have one entry per word');")]),
  py=dict(starter="def submit_word(state):\n    # right or wrong, move on to the next word\n    pass\n",
    answer="def submit_word(state):\n    if state[\"is_over\"] or state[\"is_paused\"] or not state[\"typed\"]:\n        return False\n    right = state[\"typed\"] == current_word(state)\n\n    if right:\n        state[\"correct\"] += 1\n        state[\"letters_typed\"] += len(current_word(state)) + 1\n    else:\n        state[\"wrong\"] += 1\n    state[\"results\"].append(right)\n\n    state[\"index\"] += 1\n    state[\"typed\"] = \"\"\n\n    if state[\"index\"] >= len(state[\"words\"]):\n        state[\"is_over\"] = True\n    return right\n",
    hints=["current_word(state) is written for you.",
           "The + 1 on letters_typed is the space bar - it counts.",
           "state['results'].append(right) records the answer for the page to draw.",
           "Move on and clear the typing whether the word was right or wrong."],
    tests=[("A right word is counted",
            "state = create_game()\nstate.update({'words': ['water', 'little'], 'index': 0, 'typed': 'water'})\nassert submit_word(state) is True\nassert state['correct'] == 1"),
           ("A wrong word is counted too",
            "state = create_game()\nstate.update({'words': ['water', 'little'], 'index': 0, 'typed': 'wxter'})\nassert submit_word(state) is False\nassert state['wrong'] == 1"),
           ("Either way the race moves on",
            "state = create_game()\nstate.update({'words': ['water', 'little'], 'index': 0, 'typed': 'nonsense'})\nsubmit_word(state)\nassert state['index'] == 1 and state['typed'] == ''"),
           ("The space bar counts as a character",
            "state = create_game()\nstate.update({'words': ['water'], 'index': 0, 'typed': 'water'})\nsubmit_word(state)\nassert state['letters_typed'] == 6, 'five letters plus the space'"),
           ("A wrong word earns no characters",
            "state = create_game()\nstate.update({'words': ['water'], 'index': 0, 'typed': 'wrong'})\nsubmit_word(state)\nassert state['letters_typed'] == 0"),
           ("Pressing space with nothing typed does nothing",
            "state = create_game()\nstate['typed'] = ''\nbefore = state['index']\nassert submit_word(state) is False\nassert state['index'] == before"),
           ("Finishing the last word ends the race",
            "state = create_game()\nstate.update({'words': ['water'], 'index': 0, 'typed': 'water'})\nsubmit_word(state)\nassert state['is_over'] is True"),
           ("Which words went wrong is remembered",
            "state = create_game()\nstate.update({'words': ['water', 'little', 'sound'], 'index': 0})\nfor typed in ('water', 'wrong', 'sound'):\n    state['typed'] = typed\n    submit_word(state)\nassert state['results'] == [True, False, True], f\"got {state['results']}\""),
           ("A whole race can be typed",
            "state = create_game()\nfor _ in range(len(state['words'])):\n    state['typed'] = current_word(state)\n    submit_word(state)\nassert state['correct'] == len(state['words'])\nassert state['is_over'] is True\nassert len(state['results']) == len(state['words'])")]),
  demo=dict(kind="game", caption="Type a word and press SPACE. Try getting one wrong on purpose.")),

step("accuracy", "accuracy", "accuracy",
  "How accurate were you?", "The scoreboard comes alive.",
  "<p>A percentage: right words out of all the words attempted.</p>"
  "<p>The whole difficulty is one line at the top. At the very start of a race nothing has been typed, so right is 0 and wrong is 0 — and <code>0 ÷ 0</code> is not a number. Every language handles that badly in its own way, so you have to say what should happen. Nothing has gone wrong yet, so: 100%.</p>",
  "state", "a percentage from 0 to 100",
  ["Add up right and wrong to get the number of words attempted.",
   "If that is 0, return 100 — nothing has gone wrong yet.",
   "Otherwise: right ÷ attempted × 100, rounded."],
  js=dict(starter="function accuracy(state) {\n    // right out of attempted, as a percentage\n}\n",
    answer="function accuracy(state) {\n    const done = state.correct + state.wrong;\n    if (done === 0) {\n        return 100;\n    }\n    return Math.round(state.correct / done * 100);\n}\n",
    hints=["Guard against dividing by zero BEFORE you divide.",
           "Math.round(...) gives a whole percentage.",
           "state.correct / done * 100"],
    tests=[("A fresh race is 100%",
            "const state = createGame();\nassert(accuracy(state) === 100, 'nothing has gone wrong yet — gave ' + accuracy(state));"),
           ("All right is 100%",
            "const state = createGame();\nstate.correct = 10;\nstate.wrong = 0;\nassert(accuracy(state) === 100);"),
           ("All wrong is 0%",
            "const state = createGame();\nstate.correct = 0;\nstate.wrong = 10;\nassert(accuracy(state) === 0);"),
           ("Half and half is 50%",
            "const state = createGame();\nstate.correct = 5;\nstate.wrong = 5;\nassert(accuracy(state) === 50);"),
           ("Twelve out of fifteen is 80%",
            "const state = createGame();\nstate.correct = 12;\nstate.wrong = 3;\nassert(accuracy(state) === 80, 'gave ' + accuracy(state));"),
           ("The answer is always a whole number",
            "const state = createGame();\nstate.correct = 1;\nstate.wrong = 2;\nassert(accuracy(state) === Math.round(accuracy(state)), 'gave ' + accuracy(state));"),
           ("It never goes outside 0 to 100",
            "for (let right = 0; right <= 20; right++) {\n    for (let wrong = 0; wrong <= 20; wrong++) {\n        const state = createGame();\n        state.correct = right;\n        state.wrong = wrong;\n        const percent = accuracy(state);\n        assert(percent >= 0 && percent <= 100, right + '/' + wrong + ' gave ' + percent);\n    }\n}")]),
  py=dict(starter="def accuracy(state):\n    # right out of attempted, as a percentage\n    pass\n",
    answer="def accuracy(state):\n    done = state[\"correct\"] + state[\"wrong\"]\n    if done == 0:\n        return 100\n    return round(state[\"correct\"] / done * 100)\n",
    hints=["Guard against dividing by zero BEFORE you divide.",
           "round(...) gives a whole percentage.",
           "state['correct'] / done * 100"],
    tests=[("A fresh race is 100%",
            "assert accuracy(create_game()) == 100"),
           ("All right is 100%",
            "state = create_game()\nstate.update({'correct': 10, 'wrong': 0})\nassert accuracy(state) == 100"),
           ("All wrong is 0%",
            "state = create_game()\nstate.update({'correct': 0, 'wrong': 10})\nassert accuracy(state) == 0"),
           ("Half and half is 50%",
            "state = create_game()\nstate.update({'correct': 5, 'wrong': 5})\nassert accuracy(state) == 50"),
           ("Twelve out of fifteen is 80%",
            "state = create_game()\nstate.update({'correct': 12, 'wrong': 3})\nassert accuracy(state) == 80"),
           ("The answer is always a whole number",
            "state = create_game()\nstate.update({'correct': 1, 'wrong': 2})\nassert isinstance(accuracy(state), int)"),
           ("It never goes outside 0 to 100",
            "for right in range(21):\n    for wrong in range(21):\n        state = create_game()\n        state.update({'correct': right, 'wrong': wrong})\n        assert 0 <= accuracy(state) <= 100")]),
  demo=dict(kind="sums", caption="Add right and wrong words with the buttons and watch the percentage."),
  warning="Deal with 0 out of 0 before you divide. In JavaScript it gives NaN and in Python it crashes — neither is what a player wants to see at the start of a race."),

step("words_per_minute", "wordsPerMinute", "words_per_minute",
  "How fast were you?", "A real typing speed.",
  "<p>Words per minute — but typists do not count real words. They agreed a hundred years ago that a \"word\" is <strong>five characters</strong>, whatever the actual words were. Otherwise someone typing <em>a a a a</em> would look faster than someone typing <em>elephant</em>.</p>"
  "<p>So: characters ÷ 5 gives you \"words\", and then scale from however many seconds have gone by up to a whole minute.</p>",
  "state", "words per minute, rounded",
  ["If less than a second has gone by, return 0 — the sum would be silly.",
   "Work out the words: lettersTyped ÷ 5.",
   "Scale up to a minute: words ÷ seconds × 60.",
   "Round it."],
  js=dict(starter="function wordsPerMinute(state) {\n    // five characters is one 'word'\n}\n",
    answer="function wordsPerMinute(state) {\n    if (state.seconds < 1) {\n        return 0;\n    }\n    const words = state.lettersTyped / 5;\n    return Math.round(words / state.seconds * 60);\n}\n",
    hints=["Guard the first second BEFORE dividing by state.seconds.",
           "words / seconds gives words per SECOND — multiply by 60 for a minute.",
           "Math.round(words / state.seconds * 60)"],
    tests=[("A race that has not started is 0",
            "const state = createGame();\nassert(wordsPerMinute(state) === 0);"),
           ("Sixty characters in sixty seconds is 12 WPM",
            "const state = createGame();\nstate.lettersTyped = 60;\nstate.seconds = 60;\nassert(wordsPerMinute(state) === 12, 'gave ' + wordsPerMinute(state) + ' — sixty characters is twelve \"words\"');"),
           ("Three hundred characters in a minute is 60 WPM",
            "const state = createGame();\nstate.lettersTyped = 300;\nstate.seconds = 60;\nassert(wordsPerMinute(state) === 60);"),
           ("The same typing in half the time is twice the speed",
            "const slow = createGame();\nslow.lettersTyped = 150;\nslow.seconds = 60;\nconst fast = createGame();\nfast.lettersTyped = 150;\nfast.seconds = 30;\nassert(wordsPerMinute(fast) === wordsPerMinute(slow) * 2);"),
           ("Half a second of typing gives 0, not a huge number",
            "const state = createGame();\nstate.lettersTyped = 20;\nstate.seconds = 0.4;\nassert(wordsPerMinute(state) === 0, 'gave ' + wordsPerMinute(state) + ' — dividing by almost nothing gives nonsense');"),
           ("A real race adds up",
            "const state = createGame();\nstate.words = ['water', 'water', 'water', 'water'];\nstate.index = 0;\nfor (let i = 0; i < 4; i++) {\n    state.typed = 'water';\n    submitWord(state);\n}\nstate.seconds = 24;\nassert(wordsPerMinute(state) === 12, 'four words of six characters in 24 seconds — gave ' + wordsPerMinute(state));")]),
  py=dict(starter="def words_per_minute(state):\n    # five characters is one 'word'\n    pass\n",
    answer="def words_per_minute(state):\n    if state[\"seconds\"] < 1:\n        return 0\n    words = state[\"letters_typed\"] / 5\n    return round(words / state[\"seconds\"] * 60)\n",
    hints=["Guard the first second BEFORE dividing by state['seconds'].",
           "words / seconds gives words per SECOND - multiply by 60 for a minute.",
           "round(words / state['seconds'] * 60)"],
    tests=[("A race that has not started is 0",
            "assert words_per_minute(create_game()) == 0"),
           ("Sixty characters in sixty seconds is 12 WPM",
            "state = create_game()\nstate.update({'letters_typed': 60, 'seconds': 60})\nassert words_per_minute(state) == 12"),
           ("Three hundred characters in a minute is 60 WPM",
            "state = create_game()\nstate.update({'letters_typed': 300, 'seconds': 60})\nassert words_per_minute(state) == 60"),
           ("The same typing in half the time is twice the speed",
            "slow = create_game()\nslow.update({'letters_typed': 150, 'seconds': 60})\nfast = create_game()\nfast.update({'letters_typed': 150, 'seconds': 30})\nassert words_per_minute(fast) == words_per_minute(slow) * 2"),
           ("Half a second of typing gives 0, not a huge number",
            "state = create_game()\nstate.update({'letters_typed': 20, 'seconds': 0.4})\nassert words_per_minute(state) == 0"),
           ("A real race adds up",
            "state = create_game()\nstate.update({'words': ['water'] * 4, 'index': 0})\nfor _ in range(4):\n    state['typed'] = 'water'\n    submit_word(state)\nstate['seconds'] = 24\nassert words_per_minute(state) == 12")]),
  demo=dict(kind="sums", caption="Add words and seconds with the buttons and watch the speed change.")),

step("action_for_key", "actionForKey", "action_for_key",
  "Take control", "The game is finished!",
  "<p>The last function, and the busiest keyboard in the collection — because in this game typing <em>is</em> the game.</p>"
  "<p>The space bar is not a letter here: it means \"I have finished that word\". Backspace rubs one out. And every letter is itself.</p>",
  "key", "'space', 'back', 'new', 'pause', a letter, or nothing",
  ["Space → 'space'. Backspace → 'back'.",
   "Enter → 'new'. Escape → 'pause'.",
   "Any single letter → that letter, in lower case.",
   "Anything else → null / None."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key);\n    // space, backspace, enter, escape, or the letter itself\n    return null;\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key);\n\n    if (k === ' ' || k.toLowerCase() === 'spacebar') { return 'space'; }\n    if (k.toLowerCase() === 'backspace') { return 'back'; }\n    if (k.toLowerCase() === 'enter') { return 'new'; }\n    if (k.toLowerCase() === 'escape') { return 'pause'; }\n\n    if (k.length === 1 && k >= 'a' && k <= 'z') { return k; }\n    if (k.length === 1 && k >= 'A' && k <= 'Z') { return k.toLowerCase(); }\n\n    return null;\n}\n",
    hints=["The named keys come first — 'Backspace' would otherwise fall through.",
           "The words are all lower case, so guesses come back lower case too.",
           "k >= 'a' && k <= 'z' is a neat way to ask 'is this a letter?'"],
    tests=[("Space submits the word",
            "assert(actionForKey(' ') === 'space');"),
           ("Backspace rubs one out",
            "assert(actionForKey('Backspace') === 'back');"),
           ("Enter starts a new race",
            "assert(actionForKey('Enter') === 'new');"),
           ("A letter comes back as itself",
            "assert(actionForKey('a') === 'a');\nassert(actionForKey('z') === 'z');"),
           ("Capitals come back in lower case",
            "assert(actionForKey('A') === 'a', 'the words are lower case, so the guesses must be too');"),
           ("Numbers and arrows do nothing",
            "assert(actionForKey('5') === null);\nassert(actionForKey('ArrowUp') === null);\nassert(actionForKey('Shift') === null);"),
           ("Every letter of the alphabet works",
            "'abcdefghijklmnopqrstuvwxyz'.split('').forEach(function (letter) {\n    assert(actionForKey(letter) === letter, letter + ' did not come back');\n});"),
           ("What comes back can be typed straight in",
            "const state = createGame();\nstate.words = ['water'];\nstate.index = 0;\nstate.typed = '';\ntypeLetter(state, actionForKey('w'));\nassert(state.typed === 'w');")]),
  py=dict(starter="def action_for_key(key):\n    text = str(key)\n    # space, backspace, enter, escape, or the letter itself\n    return None\n",
    answer="def action_for_key(key):\n    text = str(key)\n\n    if text == \" \" or text.lower() == \"spacebar\":\n        return \"space\"\n    if text.lower() == \"backspace\":\n        return \"back\"\n    if text.lower() == \"enter\":\n        return \"new\"\n    if text.lower() == \"escape\":\n        return \"pause\"\n\n    if len(text) == 1 and text.isalpha():\n        return text.lower()\n\n    return None\n",
    hints=["The named keys come first - 'Backspace' would otherwise fall through.",
           "text.isalpha() asks 'is this a letter?'",
           "The words are all lower case, so guesses come back lower case too."],
    tests=[("Space submits the word", "assert action_for_key(' ') == 'space'"),
           ("Backspace rubs one out", "assert action_for_key('Backspace') == 'back'"),
           ("Enter starts a new race", "assert action_for_key('Enter') == 'new'"),
           ("A letter comes back as itself",
            "assert action_for_key('a') == 'a'\nassert action_for_key('z') == 'z'"),
           ("Capitals come back in lower case", "assert action_for_key('A') == 'a'"),
           ("Numbers and arrows do nothing",
            "assert action_for_key('5') is None\nassert action_for_key('ArrowUp') is None\nassert action_for_key('Shift') is None"),
           ("Every letter of the alphabet works",
            "for letter in 'abcdefghijklmnopqrstuvwxyz':\n    assert action_for_key(letter) == letter"),
           ("What comes back can be typed straight in",
            "state = create_game()\nstate.update({'words': ['water'], 'index': 0, 'typed': ''})\ntype_letter(state, action_for_key('w'))\nassert state['typed'] == 'w'")]),
  demo=dict(kind="final", caption="Click the page and race. SPACE after each word.")),
]

write_workshop("typing", "Typing Race", STEPS)
