"""The six steps of "Build Whack-a-Mole", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [
step("hole_index", "holeIndex", "hole_index",
  "Number the holes", "The board has holes to whack.",
  "<p>Nine holes in a 3 x 3 grid, and — as in every board game you have built so far — they live in one flat <strong>list</strong>.</p>",
  "column, row (0 to 2)", "the position of that hole in the list of nine",
  ["Skip a whole row of holes for every row above: row * GRID_SIZE.",
   "Add the column."],
  js=dict(starter="function holeIndex(column, row) {\n    // skip whole rows, then add the column\n}\n",
    answer="function holeIndex(column, row) {\n    return row * GRID_SIZE + column;\n}\n",
    hints=["One line.", "A row is GRID_SIZE holes wide.", "return row * GRID_SIZE + column;"],
    tests=[("The top-left hole is 0", "assert(holeIndex(0, 0) === 0, 'gave ' + holeIndex(0, 0));"),
           ("The middle hole is 4", "assert(holeIndex(1, 1) === 4, 'gave ' + holeIndex(1, 1));"),
           ("The bottom-right hole is 8", "assert(holeIndex(2, 2) === 8);"),
           ("All nine holes get different numbers",
            "const seen = {};\nfor (let r = 0; r < 3; r++) { for (let c = 0; c < 3; c++) { seen[holeIndex(c, r)] = true; } }\nassert(Object.keys(seen).length === 9);")]),
  py=dict(starter="def hole_index(column, row):\n    # skip whole rows, then add the column\n    pass\n",
    answer="def hole_index(column, row):\n    return row * GRID_SIZE + column\n",
    hints=["One line.", "A row is GRID_SIZE holes wide.", "return row * GRID_SIZE + column"],
    tests=[("The top-left hole is 0", "got = hole_index(0, 0)\nassert got == 0, f'gave {got}'"),
           ("The middle hole is 4", "got = hole_index(1, 1)\nassert got == 4, f'gave {got}'"),
           ("The bottom-right hole is 8", "assert hole_index(2, 2) == 8"),
           ("All nine holes get different numbers",
            "seen = {hole_index(c, r) for r in range(3) for c in range(3)}\nassert len(seen) == 9")]),
  demo=dict(kind="grid", caption="Your function numbers every hole.")),

step("random_hole", "randomHole", "random_hole",
  "Pop up somewhere new", "The mole moves about.",
  "<p>The mole needs a random hole — but never the one it was just in. Popping out of the same hole twice in a row feels broken to a player, even though it is perfectly random.</p>"
  "<p>So we do what the Snake game does with apples: <strong>list the allowed choices, then pick one</strong>.</p>",
  "previous - the hole the mole was just in (-1 if there was none)",
  "a hole number from 0 to HOLE_COUNT - 1, never the same as previous",
  ["Build a list of every hole except `previous`.",
   "Pick one of those at random.", "Return it."],
  js=dict(starter="function randomHole(previous) {\n    // every hole except `previous`, then pick one\n}\n",
    answer="function randomHole(previous) {\n    const choices = [];\n    for (let hole = 0; hole < HOLE_COUNT; hole++) {\n        if (hole !== previous) {\n            choices.push(hole);\n        }\n    }\n    return choices[Math.floor(Math.random() * choices.length)];\n}\n",
    hints=["Loop from 0 to HOLE_COUNT - 1, skipping `previous`.",
           "Math.floor(Math.random() * choices.length) is a random position in the list.",
           "Return the hole itself, not its position in the list."],
    tests=[("It gives a real hole",
            "for (let i = 0; i < 50; i++) { const hole = randomHole(-1);\n    assert(hole >= 0 && hole < HOLE_COUNT, 'gave ' + hole); }"),
           ("It never repeats the last hole",
            "for (let i = 0; i < 200; i++) { assert(randomHole(4) !== 4, 'it popped out of the same hole twice'); }"),
           ("It still uses all the other holes",
            "const seen = {};\nfor (let i = 0; i < 300; i++) { seen[randomHole(4)] = true; }\nassert(Object.keys(seen).length === HOLE_COUNT - 1, 'it only used ' + Object.keys(seen).length + ' of the other holes');"),
           ("With no previous hole, every hole is possible",
            "const seen = {};\nfor (let i = 0; i < 400; i++) { seen[randomHole(-1)] = true; }\nassert(Object.keys(seen).length === HOLE_COUNT, 'it only used ' + Object.keys(seen).length + ' holes');"),
           ("It really is random",
            "const first = randomHole(-1);\nlet different = false;\nfor (let i = 0; i < 40; i++) { if (randomHole(-1) !== first) { different = true; } }\nassert(different, 'forty tries all gave the same hole');")]),
  py=dict(starter="def random_hole(previous):\n    # every hole except `previous`, then pick one\n    pass\n",
    answer="def random_hole(previous):\n    choices = [hole for hole in range(HOLE_COUNT) if hole != previous]\n    return random.choice(choices)\n",
    hints=["A list comprehension with an `if` builds the choices.",
           "random.choice(choices) picks one (random is already imported).",
           "Return the hole itself, not its position."],
    tests=[("It gives a real hole",
            "for _ in range(50):\n    hole = random_hole(-1)\n    assert 0 <= hole < HOLE_COUNT, f'gave {hole}'"),
           ("It never repeats the last hole",
            "assert all(random_hole(4) != 4 for _ in range(200)), 'it popped out of the same hole twice'"),
           ("It still uses all the other holes",
            "seen = {random_hole(4) for _ in range(300)}\nassert len(seen) == HOLE_COUNT - 1, f'it only used {len(seen)} of the other holes'"),
           ("With no previous hole, every hole is possible",
            "seen = {random_hole(-1) for _ in range(400)}\nassert len(seen) == HOLE_COUNT, f'it only used {len(seen)} holes'"),
           ("It really is random",
            "first = random_hole(-1)\nassert any(random_hole(-1) != first for _ in range(40))")]),
  demo=dict(kind="game", caption="Watch the mole hop about — it never lands in the same hole twice.")),

step("mole_interval", "moleInterval", "mole_interval",
  "How long does it stay up?", "Higher levels really are faster.",
  "<p>On level 1 the mole waits 1100 milliseconds — over a second, which feels generous. Every level takes 90 ms off that, down to a floor of 350 ms.</p>"
  "<p>Why a floor? Below about a third of a second you cannot see the mole, move the hammer and swing. A game you cannot possibly win is not fun.</p>",
  "level - the level number", "milliseconds the mole stays up",
  ["Work out 1100 - (level - 1) * 90.", "Never return less than 350."],
  js=dict(starter="function moleInterval(level) {\n    // 1100 ms at level 1, 90 ms quicker each level, never below 350\n}\n",
    answer="function moleInterval(level) {\n    const milliseconds = 1100 - (level - 1) * 90;\n    if (milliseconds < 350) {\n        return 350;\n    }\n    return milliseconds;\n}\n",
    hints=["Work the number out into a variable first.",
           "Level 1 must give exactly 1100, so the sum uses (level - 1).",
           "Math.max(350, milliseconds) does the floor in one line."],
    tests=[("Level 1 waits 1100 ms", "assert(moleInterval(1) === 1100, 'gave ' + moleInterval(1));"),
           ("Level 2 waits 1010 ms", "assert(moleInterval(2) === 1010, 'gave ' + moleInterval(2));"),
           ("Level 5 waits 740 ms", "assert(moleInterval(5) === 740, 'gave ' + moleInterval(5));"),
           ("Level 10 has hit the floor", "assert(moleInterval(10) === 350, 'gave ' + moleInterval(10));"),
           ("Level 40 is still 350", "assert(moleInterval(40) === 350);"),
           ("It never goes below 350",
            "for (let level = 1; level <= 60; level++) { assert(moleInterval(level) >= 350, 'level ' + level + ' gave ' + moleInterval(level)); }")]),
  py=dict(starter="def mole_interval(level):\n    # 1100 ms at level 1, 90 ms quicker each level, never below 350\n    pass\n",
    answer="def mole_interval(level):\n    return max(350, 1100 - (level - 1) * 90)\n",
    hints=["max(350, something) gives 350 whenever something drops below it.",
           "Level 1 must give exactly 1100, so the sum uses (level - 1).",
           "return max(350, 1100 - (level - 1) * 90)"],
    tests=[("Level 1 waits 1100 ms", "got = mole_interval(1)\nassert got == 1100, f'gave {got}'"),
           ("Level 2 waits 1010 ms", "assert mole_interval(2) == 1010"),
           ("Level 5 waits 740 ms", "got = mole_interval(5)\nassert got == 740, f'gave {got}'"),
           ("Level 10 has hit the floor", "assert mole_interval(10) == 350"),
           ("Level 40 is still 350", "assert mole_interval(40) == 350"),
           ("It never goes below 350",
            "for level in range(1, 61):\n    assert mole_interval(level) >= 350, f'level {level} gave {mole_interval(level)}'")]),
  demo=dict(kind="speed", caption="Press the level buttons and watch your speed curve.")),

step("level_for_hits", "levelForHits", "level_for_hits",
  "Level up", "Five hits and it gets harder.",
  "<p>Every 5 moles you hit, the level goes up — and the moles speed up with it. Hits 0-4 are level 1, hits 5-9 are level 2, and so on.</p>",
  "hits - how many moles you have hit", "the level number, starting at 1",
  ["Divide the hits by 5 and round down.", "Add 1."],
  js=dict(starter="function levelForHits(hits) {\n    // a new level every 5 hits, starting at level 1\n}\n",
    answer="function levelForHits(hits) {\n    return Math.floor(hits / 5) + 1;\n}\n",
    hints=["Math.floor(7 / 5) is 1.", "One line.", "return Math.floor(hits / 5) + 1;"],
    tests=[("No hits yet is level 1", "assert(levelForHits(0) === 1, 'gave ' + levelForHits(0));"),
           ("4 hits is still level 1", "assert(levelForHits(4) === 1);"),
           ("5 hits reaches level 2", "assert(levelForHits(5) === 2, 'gave ' + levelForHits(5));"),
           ("23 hits is level 5", "assert(levelForHits(23) === 5, 'gave ' + levelForHits(23));"),
           ("It never returns 0", "for (let hits = 0; hits < 50; hits++) { assert(levelForHits(hits) >= 1); }")]),
  py=dict(starter="def level_for_hits(hits):\n    # a new level every 5 hits, starting at level 1\n    pass\n",
    answer="def level_for_hits(hits):\n    return hits // 5 + 1\n",
    hints=["// is whole-number divide: 7 // 5 is 1.", "One line.", "return hits // 5 + 1"],
    tests=[("No hits yet is level 1", "got = level_for_hits(0)\nassert got == 1, f'gave {got}'"),
           ("4 hits is still level 1", "assert level_for_hits(4) == 1"),
           ("5 hits reaches level 2", "got = level_for_hits(5)\nassert got == 2, f'gave {got}'"),
           ("23 hits is level 5", "assert level_for_hits(23) == 5"),
           ("It never returns 0", "assert all(level_for_hits(h) >= 1 for h in range(50))")]),
  demo=dict(kind="game", caption="Hit five moles and watch the level box tick over.")),

step("whack", "whack", "whack",
  "Swing the hammer", "The game can be played!",
  "<p>The move itself. If the mole is in the hole you hit, you score — and it runs away to a different hole at once. If it is not, that is a miss, and the mole stays exactly where it is.</p>"
  "<p>That last detail matters: if a miss moved the mole, you could find it by hitting every hole in turn.</p>",
  "state - the game. index - the hole you hit.",
  "True if there was a mole there",
  ["Do nothing if the game is over or paused.",
   "If the index is the mole's hole: count the hit, add score-for-hit points, work out the new level with level-for-hits, send the mole to a different hole with random-hole, reset the mole timer and answer True.",
   "Otherwise count a miss and answer False."],
  js=dict(starter="function whack(state, index) {\n    // hit: score and move the mole. miss: just count it.\n}\n",
    answer="function whack(state, index) {\n    if (state.isOver || state.isPaused) {\n        return false;\n    }\n\n    if (index === state.mole) {\n        state.hits = state.hits + 1;\n        state.score = state.score + scoreForHit(state.level);\n        state.level = levelForHits(state.hits);\n        state.mole = randomHole(state.mole);\n        state.moleTimer = 0;\n        state.lastResult = 'hit';\n        return true;\n    }\n\n    state.misses = state.misses + 1;\n    state.lastResult = 'miss';\n    return false;\n}\n",
    hints=["Start with the over/paused guard.",
           "Score BEFORE working out the new level, so the fifth hit is still paid at the old rate.",
           "randomHole(state.mole) sends it somewhere new."],
    tests=[("Hitting the mole scores",
            "const state = createGame();\nstate.mole = 3;\nwhack(state, 3);\nassert(state.hits === 1, 'hits is ' + state.hits);\nassert(state.score === 10, 'score is ' + state.score);"),
           ("Hitting the mole moves it",
            "const state = createGame();\nstate.mole = 3;\nwhack(state, 3);\nassert(state.mole !== 3, 'the mole should run away');"),
           ("Missing counts as a miss",
            "const state = createGame();\nstate.mole = 3;\nwhack(state, 5);\nassert(state.misses === 1, 'misses is ' + state.misses);\nassert(state.hits === 0);"),
           ("Missing does NOT move the mole",
            "const state = createGame();\nstate.mole = 3;\nwhack(state, 5);\nassert(state.mole === 3, 'a miss must not give the mole away');"),
           ("It answers true for a hit and false for a miss",
            "const state = createGame();\nstate.mole = 3;\nassert(whack(state, 3) === true);\nstate.mole = 3;\nassert(whack(state, 8) === false);"),
           ("Five hits reach level 2",
            "const state = createGame();\nfor (let i = 0; i < 5; i++) { whack(state, state.mole); }\nassert(state.level === 2, 'level is ' + state.level);"),
           ("A finished game cannot be whacked",
            "const state = createGame();\nstate.isOver = true;\nstate.mole = 3;\nwhack(state, 3);\nassert(state.hits === 0, 'the game is over');")]),
  py=dict(starter="def whack(state, index):\n    # hit: score and move the mole. miss: just count it.\n    pass\n",
    answer="def whack(state, index):\n    if state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n\n    if index == state[\"mole\"]:\n        state[\"hits\"] += 1\n        state[\"score\"] += score_for_hit(state[\"level\"])\n        state[\"level\"] = level_for_hits(state[\"hits\"])\n        state[\"mole\"] = random_hole(state[\"mole\"])\n        state[\"mole_timer\"] = 0\n        state[\"last_result\"] = \"hit\"\n        return True\n\n    state[\"misses\"] += 1\n    state[\"last_result\"] = \"miss\"\n    return False\n",
    hints=["Start with the over/paused guard.",
           "Score BEFORE working out the new level.",
           "random_hole(state[\"mole\"]) sends it somewhere new."],
    tests=[("Hitting the mole scores",
            "state = create_game()\nstate['mole'] = 3\nwhack(state, 3)\nassert state['hits'] == 1\nassert state['score'] == 10, f\"score is {state['score']}\""),
           ("Hitting the mole moves it",
            "state = create_game()\nstate['mole'] = 3\nwhack(state, 3)\nassert state['mole'] != 3, 'the mole should run away'"),
           ("Missing counts as a miss",
            "state = create_game()\nstate['mole'] = 3\nwhack(state, 5)\nassert state['misses'] == 1 and state['hits'] == 0"),
           ("Missing does NOT move the mole",
            "state = create_game()\nstate['mole'] = 3\nwhack(state, 5)\nassert state['mole'] == 3, 'a miss must not give the mole away'"),
           ("It answers True for a hit and False for a miss",
            "state = create_game()\nstate['mole'] = 3\nassert whack(state, 3) is True\nstate['mole'] = 3\nassert whack(state, 8) is False"),
           ("Five hits reach level 2",
            "state = create_game()\nfor _ in range(5):\n    whack(state, state['mole'])\nassert state['level'] == 2, f\"level is {state['level']}\""),
           ("A finished game cannot be whacked",
            "state = create_game()\nstate['is_over'] = True\nstate['mole'] = 3\nwhack(state, 3)\nassert state['hits'] == 0")]),
  demo=dict(kind="game", caption="Aim with the buttons and swing. Quick!"),
  warning="A miss must leave the mole where it is. Otherwise a player could just hit every hole in turn and never really look."),

step("action_for_key", "actionForKey", "action_for_key",
  "Wire up the keyboard", "You can play without a mouse — the game is finished!",
  "<p>Arrows aim the hammer and space swings it.</p>",
  "key - the key name from the browser",
  "\"up\", \"down\", \"left\", \"right\", \"whack\", \"pause\", \"restart\" - or nothing",
  ["Lowercase the key first.", "Arrows or WASD aim.",
   "Space or Enter swings; p pauses; r starts a new game."],
  js=dict(starter="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n    // return the action name, or null\n}\n",
    answer="function actionForKey(key) {\n    const k = String(key).toLowerCase();\n\n    if (k === 'arrowup' || k === 'w') { return 'up'; }\n    if (k === 'arrowdown' || k === 's') { return 'down'; }\n    if (k === 'arrowleft' || k === 'a') { return 'left'; }\n    if (k === 'arrowright' || k === 'd') { return 'right'; }\n    if (k === ' ' || k === 'spacebar' || k === 'enter') { return 'whack'; }\n    if (k === 'p') { return 'pause'; }\n    if (k === 'r') { return 'restart'; }\n\n    return null;\n}\n",
    hints=["One if per action.", "Keys share an action with ||.", "The last line is: return null;"],
    tests=[("The arrows aim",
            "assert(actionForKey('ArrowUp') === 'up' && actionForKey('ArrowDown') === 'down' && actionForKey('ArrowLeft') === 'left' && actionForKey('ArrowRight') === 'right');"),
           ("WASD works too", "assert(actionForKey('w') === 'up' && actionForKey('d') === 'right');"),
           ("Capitals still work", "assert(actionForKey('W') === 'up', 'did you lowercase the key?');"),
           ("Space swings", "assert(actionForKey(' ') === 'whack', 'gave ' + actionForKey(' '));"),
           ("Enter swings too", "assert(actionForKey('Enter') === 'whack');"),
           ("P pauses and R restarts", "assert(actionForKey('p') === 'pause' && actionForKey('r') === 'restart');"),
           ("An unused key gives null", "assert(actionForKey('q') === null);")]),
  py=dict(starter="def action_for_key(key):\n    k = str(key).lower()\n    # a dictionary from key names to action names, then .get(k)\n    pass\n",
    answer="def action_for_key(key):\n    k = str(key).lower()\n    keys = {\n        \"arrowup\": \"up\", \"w\": \"up\",\n        \"arrowdown\": \"down\", \"s\": \"down\",\n        \"arrowleft\": \"left\", \"a\": \"left\",\n        \"arrowright\": \"right\", \"d\": \"right\",\n        \" \": \"whack\", \"spacebar\": \"whack\", \"enter\": \"whack\",\n        \"p\": \"pause\",\n        \"r\": \"restart\",\n    }\n    return keys.get(k)\n",
    hints=["A dictionary IS the lookup table.", "Several keys can share an action.",
           "keys.get(k) gives None for anything missing."],
    tests=[("The arrows aim",
            "assert action_for_key('ArrowUp') == 'up'\nassert action_for_key('ArrowDown') == 'down'\nassert action_for_key('ArrowLeft') == 'left'\nassert action_for_key('ArrowRight') == 'right'"),
           ("WASD works too", "assert action_for_key('w') == 'up' and action_for_key('d') == 'right'"),
           ("Capitals still work", "assert action_for_key('W') == 'up'"),
           ("Space swings", "got = action_for_key(' ')\nassert got == 'whack', f'gave {got!r}'"),
           ("Enter swings too", "assert action_for_key('Enter') == 'whack'"),
           ("P pauses and R restarts", "assert action_for_key('p') == 'pause' and action_for_key('r') == 'restart'"),
           ("An unused key gives None", "assert action_for_key('q') is None")]),
  demo=dict(kind="final", caption="Click the page, then aim with the arrows and swing with space.")),
]

write_workshop("whack", "Whack-a-Mole", STEPS)
