"""The twelve steps of "Build Word Rain", in both languages."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))
from steps import step, write_workshop

STEPS = [

step("speed_for_level", "speedForLevel", "speed_for_level",
  "How fast does it fall?", "The words start coming down.",
  "<p>Every level the words fall a little faster. That is the whole promise of the game, and it is one line of arithmetic: start at <code>START_SPEED</code> and add <code>SPEED_STEP</code> for each level after the first.</p>"
  "<p>Then the interesting half: <strong>put a ceiling on it</strong>. Without one, level 30 would drop words faster than anybody could read, and level 100 would drop them faster than the screen can draw. A game nobody can play is not a hard game — it is a broken one.</p>",
  "level — 1, 2, 3 …",
  "how many pixels the words fall each second",
  ["Work out START_SPEED + (level − 1) × SPEED_STEP.",
   "If that is over MAX_SPEED, give back MAX_SPEED instead.",
   "Otherwise give back what you worked out."],
  js=dict(starter="function speedForLevel(level) {\n    return START_SPEED;\n}\n",
    answer="function speedForLevel(level) {\n    const speed = START_SPEED + (level - 1) * SPEED_STEP;\n    return speed > MAX_SPEED ? MAX_SPEED : speed;\n}\n",
    hints=["(level - 1) is what makes level 1 come out at exactly START_SPEED.",
           "Math.min(speed, MAX_SPEED) does the ceiling in one go.",
           "return speed > MAX_SPEED ? MAX_SPEED : speed;"],
    tests=[("Level 1 is the starting speed",
            "assert(speedForLevel(1) === START_SPEED, 'got ' + speedForLevel(1) + ', expected ' + START_SPEED);"),
           ("Level 2 is one step faster",
            "assert(speedForLevel(2) === START_SPEED + SPEED_STEP, 'got ' + speedForLevel(2));"),
           ("Level 5 is four steps faster",
            "assert(speedForLevel(5) === START_SPEED + 4 * SPEED_STEP, 'got ' + speedForLevel(5));"),
           ("It never stops getting harder — until the ceiling",
            "for (let level = 1; level < 20; level++) {\n    assert(speedForLevel(level + 1) >= speedForLevel(level), 'level ' + (level + 1) + ' was slower than level ' + level);\n}"),
           ("A very high level is capped",
            "assert(speedForLevel(500) === MAX_SPEED, 'got ' + speedForLevel(500) + ' — did you forget the ceiling?');"),
           ("Nothing ever goes over the ceiling",
            "for (let level = 1; level < 300; level++) {\n    assert(speedForLevel(level) <= MAX_SPEED, 'level ' + level + ' reached ' + speedForLevel(level));\n}"),
           ("A word still takes a moment to fall, even at the top speed",
            "const seconds = GROUND_Y / speedForLevel(999);\nassert(seconds > 1.5, 'at the hardest level a word falls in ' + seconds.toFixed(1) + ' seconds — nobody could type that fast');")]),
  py=dict(starter="def speed_for_level(level):\n    return START_SPEED\n",
    answer="def speed_for_level(level):\n    return min(START_SPEED + (level - 1) * SPEED_STEP, MAX_SPEED)\n",
    hints=["(level - 1) is what makes level 1 come out at exactly START_SPEED.",
           "min(a, b) gives back the smaller of two numbers — that is your ceiling.",
           "return min(START_SPEED + (level - 1) * SPEED_STEP, MAX_SPEED)"],
    tests=[("Level 1 is the starting speed",
            "assert speed_for_level(1) == START_SPEED, f'got {speed_for_level(1)}'"),
           ("Level 2 is one step faster",
            "assert speed_for_level(2) == START_SPEED + SPEED_STEP"),
           ("Level 5 is four steps faster",
            "assert speed_for_level(5) == START_SPEED + 4 * SPEED_STEP"),
           ("It never stops getting harder — until the ceiling",
            "for level in range(1, 20):\n    assert speed_for_level(level + 1) >= speed_for_level(level), f'level {level + 1} was slower'"),
           ("A very high level is capped",
            "assert speed_for_level(500) == MAX_SPEED, 'did you forget the ceiling?'"),
           ("Nothing ever goes over the ceiling",
            "for level in range(1, 300):\n    assert speed_for_level(level) <= MAX_SPEED, f'level {level} reached {speed_for_level(level)}'"),
           ("A word still takes a moment to fall, even at the top speed",
            "seconds = GROUND_Y / speed_for_level(999)\nassert seconds > 1.5, f'a word falls in {seconds:.1f} seconds at the hardest level'")]),
  demo=dict(kind="pace", caption="Press Level + and watch the words come down harder. The number under the sky is your function.")),

step("gap_for_level", "gapForLevel", "gap_for_level",
  "How often does one arrive?", "The rain gets heavier.",
  "<p>Falling faster is only half of getting harder. The other half is words arriving <em>closer together</em>, and this is the mirror image of the last step: start at <code>START_GAP</code> milliseconds and take <code>GAP_STEP</code> off for each level.</p>"
  "<p>Where the last one needed a <strong>ceiling</strong>, this one needs a <strong>floor</strong>. Keep subtracting and the gap reaches zero, then goes negative — and a gap of zero means a new word every single frame. The sky would fill up faster than you could blink.</p>"
  "<p>Two functions, the same shape, opposite directions. Getting both right is what makes a difficulty curve instead of a cliff.</p>",
  "level — 1, 2, 3 …",
  "how many milliseconds to wait before the next word",
  ["Work out START_GAP − (level − 1) × GAP_STEP.",
   "If that is under MIN_GAP, give back MIN_GAP instead.",
   "Otherwise give back what you worked out."],
  js=dict(starter="function gapForLevel(level) {\n    return START_GAP;\n}\n",
    answer="function gapForLevel(level) {\n    const gap = START_GAP - (level - 1) * GAP_STEP;\n    return gap < MIN_GAP ? MIN_GAP : gap;\n}\n",
    hints=["This one SUBTRACTS where the last one added.",
           "Math.max(gap, MIN_GAP) does the floor in one go.",
           "return gap < MIN_GAP ? MIN_GAP : gap;"],
    tests=[("Level 1 waits the full gap",
            "assert(gapForLevel(1) === START_GAP, 'got ' + gapForLevel(1));"),
           ("Level 2 waits one step less",
            "assert(gapForLevel(2) === START_GAP - GAP_STEP, 'got ' + gapForLevel(2));"),
           ("The wait keeps shrinking",
            "for (let level = 1; level < 20; level++) {\n    assert(gapForLevel(level + 1) <= gapForLevel(level), 'level ' + (level + 1) + ' waited longer than level ' + level);\n}"),
           ("A very high level hits the floor",
            "assert(gapForLevel(500) === MIN_GAP, 'got ' + gapForLevel(500) + ' — did you forget the floor?');"),
           ("The wait is never zero, and never negative",
            "for (let level = 1; level < 300; level++) {\n    assert(gapForLevel(level) >= MIN_GAP, 'level ' + level + ' asked for a gap of ' + gapForLevel(level));\n    assert(gapForLevel(level) > 0, 'a gap of ' + gapForLevel(level) + ' would drop a word every single frame');\n}"),
           ("It is the mirror of speedForLevel",
            "assert(gapForLevel(1) > gapForLevel(10), 'higher levels should wait less');\nassert(speedForLevel(1) < speedForLevel(10), 'and fall faster');"),
           ("Even at the floor there is time to type a word",
            "const arriving = MIN_GAP / 1000;\nassert(arriving > 0.3, 'a word every ' + arriving.toFixed(2) + ' seconds is not a game, it is a wall');")]),
  py=dict(starter="def gap_for_level(level):\n    return START_GAP\n",
    answer="def gap_for_level(level):\n    return max(START_GAP - (level - 1) * GAP_STEP, MIN_GAP)\n",
    hints=["This one SUBTRACTS where the last one added.",
           "max(a, b) gives back the bigger of two numbers — that is your floor.",
           "return max(START_GAP - (level - 1) * GAP_STEP, MIN_GAP)"],
    tests=[("Level 1 waits the full gap",
            "assert gap_for_level(1) == START_GAP"),
           ("Level 2 waits one step less",
            "assert gap_for_level(2) == START_GAP - GAP_STEP"),
           ("The wait keeps shrinking",
            "for level in range(1, 20):\n    assert gap_for_level(level + 1) <= gap_for_level(level), f'level {level + 1} waited longer'"),
           ("A very high level hits the floor",
            "assert gap_for_level(500) == MIN_GAP, 'did you forget the floor?'"),
           ("The wait is never zero, and never negative",
            "for level in range(1, 300):\n    assert gap_for_level(level) >= MIN_GAP, f'level {level} asked for {gap_for_level(level)}'\n    assert gap_for_level(level) > 0"),
           ("It is the mirror of speed_for_level",
            "assert gap_for_level(1) > gap_for_level(10), 'higher levels should wait less'\nassert speed_for_level(1) < speed_for_level(10), 'and fall faster'"),
           ("Even at the floor there is time to type a word",
            "arriving = MIN_GAP / 1000\nassert arriving > 0.3, f'a word every {arriving:.2f} seconds is a wall, not a game'")]),
  demo=dict(kind="pace", caption="The second number is this function — how long the sky waits before the next word.")),

step("word_width", "wordWidth", "word_width",
  "How wide is a word?", "The game can measure text.",
  "<p>Measuring text is normally a fiddly job — every letter is a different width, so you have to ask the drawing system and it has to look at the font.</p>"
  "<p>Unless the font is <strong>monospace</strong>. In a monospace font every single letter is exactly as wide as every other one — that is what the name means — and measuring text collapses into a multiplication.</p>"
  "<p>The game needs this twice: to stop a long word being dropped half off the edge of the screen, and to draw the box round the word you are typing.</p>",
  "text — a word",
  "how wide it is, in pixels",
  ["Count the letters.",
   "Multiply by LETTER_WIDTH.",
   "That is the whole function."],
  js=dict(starter="function wordWidth(text) {\n    return 0;\n}\n",
    answer="function wordWidth(text) {\n    return text.length * LETTER_WIDTH;\n}\n",
    hints=["text.length is how many letters there are.",
           "One multiplication is all it takes.",
           "return text.length * LETTER_WIDTH;"],
    tests=[("A three-letter word",
            "assert(wordWidth('cat') === 3 * LETTER_WIDTH, 'got ' + wordWidth('cat'));"),
           ("A seven-letter word",
            "assert(wordWidth('rainbow') === 7 * LETTER_WIDTH, 'got ' + wordWidth('rainbow'));"),
           ("An empty word takes no room",
            "assert(wordWidth('') === 0);"),
           ("A longer word is wider",
            "assert(wordWidth('elephant') > wordWidth('ant'));"),
           ("Two words of the same length are the same width",
            "assert(wordWidth('cat') === wordWidth('dog'), 'that is what monospace means — every letter the same');"),
           ("Every word in the game fits on the screen",
            "for (const word of WORD_POOL) {\n    assert(wordWidth(word) < FIELD_WIDTH - SKY_MARGIN * 2, '\"' + word + '\" is ' + wordWidth(word) + 'px wide, but the sky is only ' + FIELD_WIDTH + 'px');\n}"),
           ("Widths add up the way you would expect",
            "assert(wordWidth('cat') + wordWidth('dog') === wordWidth('catdog'));")]),
  py=dict(starter="def word_width(text):\n    return 0\n",
    answer="def word_width(text):\n    return len(text) * LETTER_WIDTH\n",
    hints=["len(text) is how many letters there are.",
           "One multiplication is all it takes.",
           "return len(text) * LETTER_WIDTH"],
    tests=[("A three-letter word",
            "assert word_width('cat') == 3 * LETTER_WIDTH"),
           ("A seven-letter word",
            "assert word_width('rainbow') == 7 * LETTER_WIDTH"),
           ("An empty word takes no room",
            "assert word_width('') == 0"),
           ("A longer word is wider",
            "assert word_width('elephant') > word_width('ant')"),
           ("Two words of the same length are the same width",
            "assert word_width('cat') == word_width('dog'), 'that is what monospace means'"),
           ("Every word in the game fits on the screen",
            "for word in WORD_POOL:\n    assert word_width(word) < FIELD_WIDTH - SKY_MARGIN * 2, f'{word} is {word_width(word)}px wide'"),
           ("Widths add up the way you would expect",
            "assert word_width('cat') + word_width('dog') == word_width('catdog')")]),
  demo=dict(kind="sizes", caption="Five words, each in a box exactly as wide as your function says.")),

step("word_for_level", "wordForLevel", "word_for_level",
  "Pick a word", "Longer words start arriving.",
  "<p>Level 1 should drop <em>cat</em> and <em>sun</em>. Level 20 should drop <em>thunder</em> and <em>lantern</em>. So the pool of words a level may use grows as you go.</p>"
  "<p>Work out the longest word this level is allowed — three letters at level 1, one more every two levels, never past seven — then keep only the words that short and pick one at random.</p>"
  "<p>This is <strong>filter then choose</strong>, and it turns up everywhere: narrow the list down to what is allowed, then pick from what is left. Doing it the other way round — picking first and checking afterwards — means sometimes picking again, and again, and you can never say how long that will take.</p>",
  "level — 1, 2, 3 …",
  "one word from WORD_POOL",
  ["The longest allowed is 3 + (level − 1) ÷ 2, rounded down — but never more than 7.",
   "Keep only the words in WORD_POOL that are that short.",
   "Pick one of those at random."],
  js=dict(starter="function wordForLevel(level) {\n    return WORD_POOL[0];\n}\n",
    answer="function wordForLevel(level) {\n    let longest = 3 + Math.floor((level - 1) / 2);\n    if (longest > 7) { longest = 7; }\n\n    const choices = WORD_POOL.filter(function (word) { return word.length <= longest; });\n    return choices[Math.floor(Math.random() * choices.length)];\n}\n",
    hints=["Math.floor((level - 1) / 2) grows by one every two levels.",
           "WORD_POOL.filter(...) gives you a new list of just the short enough words.",
           "choices[Math.floor(Math.random() * choices.length)] picks one."],
    tests=[("It always gives back a real word",
            "for (let i = 0; i < 40; i++) {\n    const word = wordForLevel(3);\n    assert(WORD_POOL.indexOf(word) !== -1, '\"' + word + '\" is not one of the game\\'s words');\n}"),
           ("Level 1 only drops three-letter words",
            "for (let i = 0; i < 60; i++) {\n    const word = wordForLevel(1);\n    assert(word.length === 3, 'level 1 gave \"' + word + '\" — too long for a beginner');\n}"),
           ("Level 3 allows four letters",
            "let seen = 0;\nfor (let i = 0; i < 200; i++) {\n    const word = wordForLevel(3);\n    assert(word.length <= 4, 'level 3 gave \"' + word + '\"');\n    if (word.length === 4) { seen = seen + 1; }\n}\nassert(seen > 0, 'level 3 never used a four-letter word');"),
           ("The words get longer as the levels go up",
            "const longestAt = function (level) {\n    let longest = 0;\n    for (let i = 0; i < 400; i++) { longest = Math.max(longest, wordForLevel(level).length); }\n    return longest;\n};\nassert(longestAt(9) > longestAt(1), 'level 9 should reach further than level 1');"),
           ("Nothing is ever longer than seven letters",
            "for (let i = 0; i < 300; i++) {\n    assert(wordForLevel(500).length <= 7, 'a very high level gave a word of ' + wordForLevel(500).length + ' letters');\n}"),
           ("It really is random",
            "const seen = {};\nfor (let i = 0; i < 200; i++) { seen[wordForLevel(4)] = true; }\nassert(Object.keys(seen).length > 8, 'only ' + Object.keys(seen).length + ' different words in 200 tries');"),
           ("Every word it picks fits on the screen",
            "for (let i = 0; i < 100; i++) {\n    assert(wordWidth(wordForLevel(30)) < FIELD_WIDTH - SKY_MARGIN * 2);\n}")]),
  py=dict(starter="def word_for_level(level):\n    return WORD_POOL[0]\n",
    answer="def word_for_level(level):\n    longest = min(3 + (level - 1) // 2, 7)\n    choices = [word for word in WORD_POOL if len(word) <= longest]\n    return random.choice(choices)\n",
    hints=["(level - 1) // 2 grows by one every two levels — // throws the remainder away.",
           "A list comprehension gives you just the short enough words.",
           "random.choice(choices) picks one."],
    tests=[("It always gives back a real word",
            "for i in range(40):\n    assert word_for_level(3) in WORD_POOL"),
           ("Level 1 only drops three-letter words",
            "for i in range(60):\n    word = word_for_level(1)\n    assert len(word) == 3, f'level 1 gave {word}'"),
           ("Level 3 allows four letters",
            "words = [word_for_level(3) for i in range(200)]\nassert all(len(w) <= 4 for w in words)\nassert any(len(w) == 4 for w in words), 'level 3 never used a four-letter word'"),
           ("The words get longer as the levels go up",
            "longest = lambda level: max(len(word_for_level(level)) for i in range(400))\nassert longest(9) > longest(1), 'level 9 should reach further than level 1'"),
           ("Nothing is ever longer than seven letters",
            "for i in range(300):\n    assert len(word_for_level(500)) <= 7"),
           ("It really is random",
            "seen = {word_for_level(4) for i in range(200)}\nassert len(seen) > 8, f'only {len(seen)} different words in 200 tries'"),
           ("Every word it picks fits on the screen",
            "for i in range(100):\n    assert word_width(word_for_level(30)) < FIELD_WIDTH - SKY_MARGIN * 2")]),
  demo=dict(kind="sizes", caption="Press New words — these come from your function, one for each length it allows.")),

step("make_word", "makeWord", "make_word",
  "One falling word", "Something appears in the sky.",
  "<p>A falling word needs to know three things: what it says, how far across the sky it is, and how far down. That is the whole object.</p>"
  "<p>It starts at <code>y = 0</code>, right at the top. And here is a small drawing decision that makes the rest of the game simpler: a word is drawn with its <strong>feet</strong> on its y, not its head. So a word at y = 0 is just above the screen and slides into view — and the moment it lands is the moment its feet touch the ground line. No fiddly adding on of heights anywhere else.</p>",
  "text — what the word says. x — how far across the sky.",
  "a new word: { text, x, y }",
  ["Give back an object holding the text.",
   "Put x where you were told.",
   "Start y at 0 — the very top of the sky."],
  js=dict(starter="function makeWord(text, x) {\n    return {};\n}\n",
    answer="function makeWord(text, x) {\n    return { text: text, x: x, y: 0 };\n}\n",
    hints=["Three properties: text, x and y.",
           "y always starts at 0, whatever the level.",
           "return { text: text, x: x, y: 0 };"],
    tests=[("It remembers what it says",
            "assert(makeWord('cat', 50).text === 'cat');"),
           ("It remembers where across it is",
            "assert(makeWord('cat', 50).x === 50);"),
           ("It always starts at the top",
            "assert(makeWord('cat', 50).y === 0, 'y is ' + makeWord('cat', 50).y);\nassert(makeWord('rainbow', 200).y === 0);"),
           ("Two words are two separate things",
            "const a = makeWord('cat', 10);\nconst b = makeWord('dog', 20);\na.y = 100;\nassert(b.y === 0, 'moving one word moved the other — they must not share');"),
           ("It works for any word in the game",
            "for (const word of WORD_POOL) {\n    const made = makeWord(word, 0);\n    assert(made.text === word && made.y === 0);\n}"),
           ("A brand-new word has not landed",
            "assert(hasLanded(makeWord('cat', 50)) === false, 'a word at the top of the sky cannot have landed');")]),
  py=dict(starter="def make_word(text, x):\n    return {}\n",
    answer="def make_word(text, x):\n    return {\"text\": text, \"x\": x, \"y\": 0}\n",
    hints=["Three keys: text, x and y.",
           "y always starts at 0, whatever the level.",
           "return {'text': text, 'x': x, 'y': 0}"],
    tests=[("It remembers what it says",
            "assert make_word('cat', 50)['text'] == 'cat'"),
           ("It remembers where across it is",
            "assert make_word('cat', 50)['x'] == 50"),
           ("It always starts at the top",
            "assert make_word('cat', 50)['y'] == 0\nassert make_word('rainbow', 200)['y'] == 0"),
           ("Two words are two separate things",
            "a = make_word('cat', 10)\nb = make_word('dog', 20)\na['y'] = 100\nassert b['y'] == 0, 'moving one word moved the other'"),
           ("It works for any word in the game",
            "for word in WORD_POOL:\n    made = make_word(word, 0)\n    assert made['text'] == word and made['y'] == 0"),
           ("A brand-new word has not landed",
            "assert has_landed(make_word('cat', 50)) is False")]),
  demo=dict(kind="sky", caption="Press Drop. Every word you see was built by your function.")),

step("spawn_word", "spawnWord", "spawn_word",
  "Drop it somewhere", "The rain starts falling on its own.",
  "<p>Now put a word in the sky. Pick one for the level, then pick somewhere across to drop it.</p>"
  "<p>The catch is the <strong>right-hand edge</strong>. Drop a seven-letter word at x = 330 and most of it hangs off the side of the screen where nobody can read it — and you cannot type what you cannot read. So the random position must stop early enough that the whole word still fits.</p>"
  "<p>Work out the <em>room</em> first: the width of the sky, less the width of the word, less a margin at each side. Then drop it anywhere from the left margin to the left margin plus that room.</p>",
  "state — the whole game",
  "the word that was dropped (and it is added to state.words)",
  ["Ask wordForLevel for a word.",
   "Room = FIELD_WIDTH − wordWidth(text) − SKY_MARGIN × 2. Never let it go below 0.",
   "Pick x anywhere from SKY_MARGIN to SKY_MARGIN + room.",
   "Make the word, add it to state.words, and give it back."],
  js=dict(starter="function spawnWord(state) {\n    // pick a word, pick a place, drop it\n}\n",
    answer="function spawnWord(state) {\n    const text = wordForLevel(state.level);\n    let room = FIELD_WIDTH - wordWidth(text) - SKY_MARGIN * 2;\n    if (room < 0) { room = 0; }\n\n    const word = makeWord(text, SKY_MARGIN + Math.random() * room);\n    state.words.push(word);\n    return word;\n}\n",
    hints=["Use the two functions you already wrote: wordForLevel and wordWidth.",
           "Math.random() * room gives you somewhere from 0 up to room.",
           "Do not forget state.words.push(word) — and to give the word back."],
    tests=[("It adds one word to the sky",
            "const state = createGame();\nstate.words = [];\nspawnWord(state);\nassert(state.words.length === 1, 'there are ' + state.words.length + ' words');"),
           ("It hands the word back too",
            "const state = createGame();\nstate.words = [];\nconst word = spawnWord(state);\nassert(word === state.words[0], 'give back the very word you added');"),
           ("The word starts at the top",
            "const state = createGame();\nstate.words = [];\nassert(spawnWord(state).y === 0);"),
           ("Dropping twice gives two words",
            "const state = createGame();\nstate.words = [];\nspawnWord(state);\nspawnWord(state);\nassert(state.words.length === 2);"),
           ("The whole word always fits on the screen",
            "const state = createGame();\nstate.level = 40;\nfor (let i = 0; i < 300; i++) {\n    state.words = [];\n    const word = spawnWord(state);\n    assert(word.x >= 0, '\"' + word.text + '\" was dropped at x ' + word.x.toFixed(1));\n    assert(word.x + wordWidth(word.text) <= FIELD_WIDTH, '\"' + word.text + '\" hangs ' + (word.x + wordWidth(word.text) - FIELD_WIDTH).toFixed(1) + 'px off the right edge');\n}"),
           ("Words land all over the sky, not in one place",
            "const state = createGame();\nstate.words = [];\nlet left = 0, right = 0;\nfor (let i = 0; i < 200; i++) {\n    state.words = [];\n    const word = spawnWord(state);\n    if (word.x < FIELD_WIDTH / 2) { left = left + 1; } else { right = right + 1; }\n}\nassert(left > 30 && right > 30, 'the split was ' + left + ' left, ' + right + ' right');"),
           ("It uses words the level allows",
            "const state = createGame();\nstate.level = 1;\nfor (let i = 0; i < 50; i++) {\n    state.words = [];\n    assert(spawnWord(state).text.length === 3, 'level 1 should only drop three-letter words');\n}")]),
  py=dict(starter="def spawn_word(state):\n    # pick a word, pick a place, drop it\n    pass\n",
    answer="def spawn_word(state):\n    text = word_for_level(state[\"level\"])\n    room = max(0, FIELD_WIDTH - word_width(text) - SKY_MARGIN * 2)\n\n    word = make_word(text, SKY_MARGIN + random.random() * room)\n    state[\"words\"].append(word)\n    return word\n",
    hints=["Use the two functions you already wrote: word_for_level and word_width.",
           "random.random() * room gives you somewhere from 0 up to room.",
           "Do not forget state['words'].append(word) — and to give the word back."],
    tests=[("It adds one word to the sky",
            "state = create_game()\nstate['words'] = []\nspawn_word(state)\nassert len(state['words']) == 1"),
           ("It hands the word back too",
            "state = create_game()\nstate['words'] = []\nword = spawn_word(state)\nassert word is state['words'][0], 'give back the very word you added'"),
           ("The word starts at the top",
            "state = create_game()\nstate['words'] = []\nassert spawn_word(state)['y'] == 0"),
           ("Dropping twice gives two words",
            "state = create_game()\nstate['words'] = []\nspawn_word(state)\nspawn_word(state)\nassert len(state['words']) == 2"),
           ("The whole word always fits on the screen",
            "state = create_game()\nstate['level'] = 40\nfor i in range(300):\n    state['words'] = []\n    word = spawn_word(state)\n    assert word['x'] >= 0\n    assert word['x'] + word_width(word['text']) <= FIELD_WIDTH, f\"{word['text']} hangs off the right edge\""),
           ("Words land all over the sky, not in one place",
            "state = create_game()\nxs = []\nfor i in range(200):\n    state['words'] = []\n    xs.append(spawn_word(state)['x'])\nleft = sum(1 for x in xs if x < FIELD_WIDTH / 2)\nassert 30 < left < 170, f'the split was {left} left of centre out of 200'"),
           ("It uses words the level allows",
            "state = create_game()\nstate['level'] = 1\nfor i in range(50):\n    state['words'] = []\n    assert len(spawn_word(state)['text']) == 3")]),
  demo=dict(kind="sky", caption="Press Drop and a new word appears — somewhere random, but always fully on screen.")),

step("move_words", "moveWords", "move_words",
  "Down they come", "The sky really falls.",
  "<p>One loop. Every word in the sky moves down by this level's speed, multiplied by how long the frame lasted.</p>"
  "<p>That multiplication is the part worth remembering. Without it you would be saying &ldquo;move 2 pixels per <em>frame</em>&rdquo;, and a fast computer draws twice as many frames as a slow one — so the same game would be twice as hard on a good machine. Multiplying by the seconds gone by makes <code>speedForLevel</code> mean pixels per <strong>second</strong>, which is a promise every computer can keep.</p>",
  "state — the whole game. seconds — how long this frame lasted.",
  "nothing; it moves the words",
  ["Ask speedForLevel how fast words fall on this level.",
   "For every word in state.words, add speed × seconds to its y."],
  js=dict(starter="function moveWords(state, seconds) {\n    // everything comes down\n}\n",
    answer="function moveWords(state, seconds) {\n    const speed = speedForLevel(state.level);\n    for (let i = 0; i < state.words.length; i++) {\n        state.words[i].y = state.words[i].y + speed * seconds;\n    }\n}\n",
    hints=["Work the speed out once, before the loop — it is the same for every word.",
           "Add to y. Do not replace it.",
           "state.words[i].y = state.words[i].y + speed * seconds;"],
    tests=[("An empty sky is fine",
            "const state = createGame();\nstate.words = [];\nmoveWords(state, 0.1);\nassert(state.words.length === 0);"),
           ("A word moves down",
            "const state = createGame();\nstate.level = 1;\nstate.words = [makeWord('cat', 10)];\nmoveWords(state, 1);\nassert(state.words[0].y === speedForLevel(1), 'after one second it should be ' + speedForLevel(1) + ' down, but it is ' + state.words[0].y);"),
           ("Down means a BIGGER y",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nmoveWords(state, 0.5);\nassert(state.words[0].y > 0, 'y is ' + state.words[0].y + ' — on a canvas, down is positive');"),
           ("Every word moves, not just the first",
            "const state = createGame();\nstate.words = [makeWord('cat', 10), makeWord('dog', 40), makeWord('pig', 70)];\nmoveWords(state, 0.5);\nfor (const word of state.words) {\n    assert(word.y > 0, '\"' + word.text + '\" did not move');\n}"),
           ("A longer frame moves them further",
            "const slow = createGame();\nslow.words = [makeWord('cat', 10)];\nconst fast = createGame();\nfast.words = [makeWord('cat', 10)];\nmoveWords(slow, 0.05);\nmoveWords(fast, 0.10);\nassert(Math.abs(fast.words[0].y - slow.words[0].y * 2) < 0.0001, 'twice the time should be twice the distance');"),
           ("A higher level falls faster",
            "const easy = createGame();\neasy.level = 1;\neasy.words = [makeWord('cat', 10)];\nconst hard = createGame();\nhard.level = 10;\nhard.words = [makeWord('cat', 10)];\nmoveWords(easy, 1);\nmoveWords(hard, 1);\nassert(hard.words[0].y > easy.words[0].y, 'level 10 should fall faster than level 1');"),
           ("Sideways is left alone",
            "const state = createGame();\nstate.words = [makeWord('cat', 123)];\nmoveWords(state, 1);\nassert(state.words[0].x === 123, 'words fall straight down — x must not change');"),
           ("Lots of small steps go as far as one big one",
            "const many = createGame();\nmany.level = 3;\nmany.words = [makeWord('cat', 10)];\nfor (let i = 0; i < 60; i++) { moveWords(many, 1 / 60); }\nconst once = createGame();\nonce.level = 3;\nonce.words = [makeWord('cat', 10)];\nmoveWords(once, 1);\nassert(Math.abs(many.words[0].y - once.words[0].y) < 0.0001, 'the frame rate should not matter: ' + many.words[0].y.toFixed(2) + ' vs ' + once.words[0].y.toFixed(2));")]),
  py=dict(starter="def move_words(state, seconds):\n    # everything comes down\n    pass\n",
    answer="def move_words(state, seconds):\n    speed = speed_for_level(state[\"level\"])\n    for word in state[\"words\"]:\n        word[\"y\"] += speed * seconds\n",
    hints=["Work the speed out once, before the loop — it is the same for every word.",
           "Use += so you ADD to y rather than replacing it.",
           "for word in state['words']: word['y'] += speed * seconds"],
    tests=[("An empty sky is fine",
            "state = create_game()\nstate['words'] = []\nmove_words(state, 0.1)\nassert state['words'] == []"),
           ("A word moves down",
            "state = create_game()\nstate['level'] = 1\nstate['words'] = [make_word('cat', 10)]\nmove_words(state, 1)\nassert state['words'][0]['y'] == speed_for_level(1)"),
           ("Down means a BIGGER y",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nmove_words(state, 0.5)\nassert state['words'][0]['y'] > 0, 'on a canvas, down is positive'"),
           ("Every word moves, not just the first",
            "state = create_game()\nstate['words'] = [make_word('cat', 10), make_word('dog', 40), make_word('pig', 70)]\nmove_words(state, 0.5)\nassert all(w['y'] > 0 for w in state['words'])"),
           ("A longer frame moves them further",
            "slow = create_game(); slow['words'] = [make_word('cat', 10)]\nfast = create_game(); fast['words'] = [make_word('cat', 10)]\nmove_words(slow, 0.05)\nmove_words(fast, 0.10)\nassert abs(fast['words'][0]['y'] - slow['words'][0]['y'] * 2) < 0.0001"),
           ("A higher level falls faster",
            "easy = create_game(); easy['level'] = 1; easy['words'] = [make_word('cat', 10)]\nhard = create_game(); hard['level'] = 10; hard['words'] = [make_word('cat', 10)]\nmove_words(easy, 1)\nmove_words(hard, 1)\nassert hard['words'][0]['y'] > easy['words'][0]['y']"),
           ("Sideways is left alone",
            "state = create_game()\nstate['words'] = [make_word('cat', 123)]\nmove_words(state, 1)\nassert state['words'][0]['x'] == 123, 'words fall straight down'"),
           ("Lots of small steps go as far as one big one",
            "many = create_game(); many['level'] = 3; many['words'] = [make_word('cat', 10)]\nfor i in range(60):\n    move_words(many, 1 / 60)\nonce = create_game(); once['level'] = 3; once['words'] = [make_word('cat', 10)]\nmove_words(once, 1)\nassert abs(many['words'][0]['y'] - once['words'][0]['y']) < 0.0001, 'the frame rate should not matter'")]),
  demo=dict(kind="sky", caption="Now they fall by themselves. Press Nudge to shove them all down at once.")),

step("has_landed", "hasLanded", "has_landed",
  "Has it touched down?", "The ground starts to matter.",
  "<p>The smallest function in the game, and worth having a name for anyway.</p>"
  "<p>A word is drawn with its feet on its y, so it has landed the moment its y reaches <code>GROUND_Y</code>. One comparison.</p>"
  "<p>Why not just write <code>word.y >= GROUND_Y</code> wherever it is needed? Because <code>hasLanded(word)</code> says what you <em>mean</em>, and the next step reads much better for it. A name is the cheapest comment you will ever write.</p>",
  "word — one falling word",
  "true if it has reached the ground",
  ["Give back whether the word's y has reached GROUND_Y."],
  js=dict(starter="function hasLanded(word) {\n    return false;\n}\n",
    answer="function hasLanded(word) {\n    return word.y >= GROUND_Y;\n}\n",
    hints=["You do not need an if — a comparison is already true or false.",
           "Use >= so a word sitting exactly on the line counts as landed.",
           "return word.y >= GROUND_Y;"],
    tests=[("A word at the top has not landed",
            "assert(hasLanded({ text: 'cat', x: 10, y: 0 }) === false);"),
           ("A word halfway down has not landed",
            "assert(hasLanded({ text: 'cat', x: 10, y: GROUND_Y / 2 }) === false);"),
           ("A word on the line HAS landed",
            "assert(hasLanded({ text: 'cat', x: 10, y: GROUND_Y }) === true, 'exactly on the ground counts — use >=');"),
           ("A word past the line has landed",
            "assert(hasLanded({ text: 'cat', x: 10, y: GROUND_Y + 20 }) === true);"),
           ("One pixel short does not count",
            "assert(hasLanded({ text: 'cat', x: 10, y: GROUND_Y - 1 }) === false);"),
           ("It does not care how long the word is",
            "assert(hasLanded({ text: 'a', x: 0, y: GROUND_Y }) === hasLanded({ text: 'lantern', x: 0, y: GROUND_Y }));"),
           ("A falling word eventually lands",
            "const state = createGame();\nstate.level = 1;\nstate.words = [makeWord('cat', 10)];\nlet frames = 0;\nwhile (!hasLanded(state.words[0]) && frames < 5000) {\n    moveWords(state, 1 / 60);\n    frames = frames + 1;\n}\nassert(hasLanded(state.words[0]), 'it never landed');\nassert(frames < 3000, 'it took ' + (frames / 60).toFixed(1) + ' seconds — that is a very long wait');")]),
  py=dict(starter="def has_landed(word):\n    return False\n",
    answer="def has_landed(word):\n    return word[\"y\"] >= GROUND_Y\n",
    hints=["You do not need an if — a comparison is already True or False.",
           "Use >= so a word sitting exactly on the line counts as landed.",
           "return word['y'] >= GROUND_Y"],
    tests=[("A word at the top has not landed",
            "assert has_landed({'text': 'cat', 'x': 10, 'y': 0}) is False"),
           ("A word halfway down has not landed",
            "assert has_landed({'text': 'cat', 'x': 10, 'y': GROUND_Y / 2}) is False"),
           ("A word on the line HAS landed",
            "assert has_landed({'text': 'cat', 'x': 10, 'y': GROUND_Y}) is True, 'use >='"),
           ("A word past the line has landed",
            "assert has_landed({'text': 'cat', 'x': 10, 'y': GROUND_Y + 20}) is True"),
           ("One pixel short does not count",
            "assert has_landed({'text': 'cat', 'x': 10, 'y': GROUND_Y - 1}) is False"),
           ("It does not care how long the word is",
            "assert has_landed({'text': 'a', 'x': 0, 'y': GROUND_Y}) == has_landed({'text': 'lantern', 'x': 0, 'y': GROUND_Y})"),
           ("A falling word eventually lands",
            "state = create_game()\nstate['level'] = 1\nstate['words'] = [make_word('cat', 10)]\nframes = 0\nwhile not has_landed(state['words'][0]) and frames < 5000:\n    move_words(state, 1 / 60)\n    frames += 1\nassert has_landed(state['words'][0]), 'it never landed'\nassert frames < 3000, f'it took {frames / 60:.1f} seconds'")]),
  demo=dict(kind="sky", caption="Watch a word reach the hatched ground — that is the moment this function turns true.")),

step("remove_landed_words", "removeLandedWords", "remove_landed_words",
  "That one cost you", "Missing a word finally hurts.",
  "<p>Every word that reached the ground has to go — and take a life with it.</p>"
  "<p>Build a <strong>new list</strong> of the words still falling rather than deleting from the old one. Removing items from a list while you are walking along it is one of the classic ways to skip an item by accident: the list gets shorter under your feet and the next item slides into a place you have already passed. Collecting the keepers into a fresh list simply cannot go wrong.</p>"
  "<p>Count what you left out, take that many lives, and if none are left the rain has won.</p>",
  "state — the whole game",
  "how many words landed",
  ["Start an empty list, and a count of 0.",
   "For each word: if hasLanded, count it; if not, keep it.",
   "Put the keepers back on state.words.",
   "Take that many lives off, and add to state.missed.",
   "If lives reach 0, set them to 0 and the game is over."],
  js=dict(starter="function removeLandedWords(state) {\n    return 0;\n}\n",
    answer="function removeLandedWords(state) {\n    const falling = [];\n    let landed = 0;\n\n    for (let i = 0; i < state.words.length; i++) {\n        if (hasLanded(state.words[i])) {\n            landed = landed + 1;\n        } else {\n            falling.push(state.words[i]);\n        }\n    }\n    state.words = falling;\n\n    if (landed > 0) {\n        state.missed = state.missed + landed;\n        state.lives = state.lives - landed;\n        if (state.lives <= 0) {\n            state.lives = 0;\n            state.isOver = true;\n        }\n    }\n    return landed;\n}\n",
    hints=["Make an empty array first and push the survivors into it.",
           "hasLanded(word) is the test — you wrote it last step.",
           "Do not let lives go negative: if they reach 0 or below, set them to 0 and end the game."],
    tests=[("An empty sky loses nothing",
            "const state = createGame();\nstate.words = [];\nassert(removeLandedWords(state) === 0);"),
           ("A word still falling is kept",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(removeLandedWords(state) === 0);\nassert(state.words.length === 1, 'it had not landed yet');"),
           ("A landed word is taken away",
            "const state = createGame();\nconst word = makeWord('cat', 10);\nword.y = GROUND_Y;\nstate.words = [word];\nassert(removeLandedWords(state) === 1);\nassert(state.words.length === 0);"),
           ("And it costs a life",
            "const state = createGame();\nconst before = state.lives;\nconst word = makeWord('cat', 10);\nword.y = GROUND_Y;\nstate.words = [word];\nremoveLandedWords(state);\nassert(state.lives === before - 1, 'lives went from ' + before + ' to ' + state.lives);\nassert(state.missed === 1);"),
           ("The ones still falling are kept, in order",
            "const state = createGame();\nconst a = makeWord('aaa', 10);\nconst b = makeWord('bbb', 20); b.y = GROUND_Y;\nconst c = makeWord('ccc', 30);\nstate.words = [a, b, c];\nassert(removeLandedWords(state) === 1);\nassert(state.words.length === 2, 'kept ' + state.words.length);\nassert(state.words[0].text === 'aaa' && state.words[1].text === 'ccc', 'got ' + state.words.map(function (w) { return w.text; }).join(','));"),
           ("Several landing at once cost several lives",
            "const state = createGame();\nstate.lives = 5;\nstate.words = [];\nfor (let i = 0; i < 3; i++) {\n    const word = makeWord('cat', i * 40);\n    word.y = GROUND_Y + 5;\n    state.words.push(word);\n}\nassert(removeLandedWords(state) === 3);\nassert(state.lives === 2, 'lives is ' + state.lives);"),
           ("Nothing is ever skipped",
            "const state = createGame();\nstate.lives = 99;\nstate.words = [];\nfor (let i = 0; i < 6; i++) {\n    const word = makeWord('cat', i * 40);\n    word.y = GROUND_Y + 1;\n    state.words.push(word);\n}\nassert(removeLandedWords(state) === 6, 'only ' + state.words.length + ' were left — deleting from a list while looping over it skips items');\nassert(state.words.length === 0);"),
           ("Losing the last life ends the game",
            "const state = createGame();\nstate.lives = 1;\nconst word = makeWord('cat', 10);\nword.y = GROUND_Y;\nstate.words = [word];\nremoveLandedWords(state);\nassert(state.isOver === true, 'the game should be over');\nassert(state.lives === 0, 'lives is ' + state.lives + ' — it must never go negative');")]),
  py=dict(starter="def remove_landed_words(state):\n    return 0\n",
    answer="def remove_landed_words(state):\n    falling = []\n    landed = 0\n\n    for word in state[\"words\"]:\n        if has_landed(word):\n            landed += 1\n        else:\n            falling.append(word)\n    state[\"words\"] = falling\n\n    if landed > 0:\n        state[\"missed\"] += landed\n        state[\"lives\"] -= landed\n        if state[\"lives\"] <= 0:\n            state[\"lives\"] = 0\n            state[\"is_over\"] = True\n    return landed\n",
    hints=["Make an empty list first and append the survivors to it.",
           "has_landed(word) is the test — you wrote it last step.",
           "Do not let lives go negative: if they reach 0 or below, set them to 0 and end the game."],
    tests=[("An empty sky loses nothing",
            "state = create_game()\nstate['words'] = []\nassert remove_landed_words(state) == 0"),
           ("A word still falling is kept",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert remove_landed_words(state) == 0\nassert len(state['words']) == 1"),
           ("A landed word is taken away",
            "state = create_game()\nword = make_word('cat', 10)\nword['y'] = GROUND_Y\nstate['words'] = [word]\nassert remove_landed_words(state) == 1\nassert state['words'] == []"),
           ("And it costs a life",
            "state = create_game()\nbefore = state['lives']\nword = make_word('cat', 10)\nword['y'] = GROUND_Y\nstate['words'] = [word]\nremove_landed_words(state)\nassert state['lives'] == before - 1\nassert state['missed'] == 1"),
           ("The ones still falling are kept, in order",
            "state = create_game()\na = make_word('aaa', 10)\nb = make_word('bbb', 20); b['y'] = GROUND_Y\nc = make_word('ccc', 30)\nstate['words'] = [a, b, c]\nassert remove_landed_words(state) == 1\nassert [w['text'] for w in state['words']] == ['aaa', 'ccc']"),
           ("Several landing at once cost several lives",
            "state = create_game()\nstate['lives'] = 5\nstate['words'] = []\nfor i in range(3):\n    word = make_word('cat', i * 40)\n    word['y'] = GROUND_Y + 5\n    state['words'].append(word)\nassert remove_landed_words(state) == 3\nassert state['lives'] == 2"),
           ("Nothing is ever skipped",
            "state = create_game()\nstate['lives'] = 99\nstate['words'] = []\nfor i in range(6):\n    word = make_word('cat', i * 40)\n    word['y'] = GROUND_Y + 1\n    state['words'].append(word)\nassert remove_landed_words(state) == 6, 'deleting from a list while looping over it skips items'\nassert state['words'] == []"),
           ("Losing the last life ends the game",
            "state = create_game()\nstate['lives'] = 1\nword = make_word('cat', 10)\nword['y'] = GROUND_Y\nstate['words'] = [word]\nremove_landed_words(state)\nassert state['is_over'] is True\nassert state['lives'] == 0, 'lives must never go negative'")]),
  demo=dict(kind="sky", caption="Let one reach the ground. It vanishes — and in the real game that is a life gone.")),

step("matching_word", "matchingWord", "matching_word",
  "Which one do you mean?", "The game reads your mind.",
  "<p>This is the clever bit, and the reason the game feels good to play.</p>"
  "<p>Six words are falling. You never click one, never press Tab, never choose at all — you just start typing, and the game knows. Type <strong>c</strong> and only the words beginning with c are still in the running. Type <strong>ca</strong> and it is narrower still.</p>"
  "<p>When several still match, take the one <strong>furthest down</strong> — the one in the most trouble. That is almost always the one the player meant, and it is the one they would lose a life over.</p>"
  "<p>It is the same idea as a search box finishing your sentence: the letters themselves are the choice.</p>",
  "state — the whole game. typed — the letters so far.",
  "the word being typed, or nothing at all",
  ["If nothing has been typed, there is no match — give back nothing.",
   "Look at every word in the sky.",
   "Skip it unless its text STARTS WITH what has been typed.",
   "Of the ones left, keep the one with the biggest y — the lowest in the sky.",
   "Give that one back, or nothing if none matched."],
  warning="A word STARTS WITH the typing — it does not merely contain it. Typing “at” must not match “cat”, or the letters you press would go somewhere you never expected.",
  js=dict(starter="function matchingWord(state, typed) {\n    return null;\n}\n",
    answer="function matchingWord(state, typed) {\n    if (typed.length === 0) {\n        return null;\n    }\n    let best = null;\n    for (let i = 0; i < state.words.length; i++) {\n        const word = state.words[i];\n        if (word.text.indexOf(typed) === 0) {\n            if (best === null || word.y > best.y) {\n                best = word;\n            }\n        }\n    }\n    return best;\n}\n",
    hints=["word.text.indexOf(typed) === 0 means the word STARTS WITH what was typed.",
           "Keep a `best` starting at null, and replace it whenever you find one further down.",
           "Bigger y means lower down the screen, and lower down means more urgent."],
    tests=[("Typing nothing matches nothing",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(matchingWord(state, '') === null);"),
           ("An empty sky matches nothing",
            "const state = createGame();\nstate.words = [];\nassert(matchingWord(state, 'c') === null);"),
           ("One letter finds the word",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(matchingWord(state, 'c').text === 'cat');"),
           ("A letter that fits nothing finds nothing",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(matchingWord(state, 'z') === null);"),
           ("It must START with the typing, not just contain it",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(matchingWord(state, 'at') === null, 'typing \"at\" must not land on \"cat\"');\nassert(matchingWord(state, 'ca').text === 'cat');"),
           ("The whole word still matches itself",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nassert(matchingWord(state, 'cat').text === 'cat');"),
           ("More letters narrow it down",
            "const state = createGame();\nstate.words = [makeWord('cat', 10), makeWord('cow', 60)];\nassert(matchingWord(state, 'c') !== null, 'both still match');\nassert(matchingWord(state, 'ca').text === 'cat');\nassert(matchingWord(state, 'co').text === 'cow');"),
           ("When two match, it takes the lower one",
            "const state = createGame();\nconst high = makeWord('cat', 10); high.y = 40;\nconst low = makeWord('cup', 60); low.y = 300;\nstate.words = [high, low];\nassert(matchingWord(state, 'c').text === 'cup', 'the one nearest the ground is the one in trouble');"),
           ("Order in the list makes no difference",
            "const high = makeWord('cat', 10); high.y = 40;\nconst low = makeWord('cup', 60); low.y = 300;\nconst one = createGame(); one.words = [high, low];\nconst two = createGame(); two.words = [low, high];\nassert(matchingWord(one, 'c').text === matchingWord(two, 'c').text);"),
           ("It gives back the very word from the sky",
            "const state = createGame();\nconst word = makeWord('cat', 10);\nstate.words = [word];\nassert(matchingWord(state, 'ca') === word, 'give back the word itself, not a copy of it');")]),
  py=dict(starter="def matching_word(state, typed):\n    return None\n",
    answer="def matching_word(state, typed):\n    if not typed:\n        return None\n\n    best = None\n    for word in state[\"words\"]:\n        if word[\"text\"].startswith(typed):\n            if best is None or word[\"y\"] > best[\"y\"]:\n                best = word\n    return best\n",
    hints=["Python has a word for this: word['text'].startswith(typed).",
           "Keep a `best` starting at None, and replace it whenever you find one further down.",
           "Bigger y means lower down the screen, and lower down means more urgent."],
    tests=[("Typing nothing matches nothing",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert matching_word(state, '') is None"),
           ("An empty sky matches nothing",
            "state = create_game()\nstate['words'] = []\nassert matching_word(state, 'c') is None"),
           ("One letter finds the word",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert matching_word(state, 'c')['text'] == 'cat'"),
           ("A letter that fits nothing finds nothing",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert matching_word(state, 'z') is None"),
           ("It must START with the typing, not just contain it",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert matching_word(state, 'at') is None, 'typing \"at\" must not land on \"cat\"'\nassert matching_word(state, 'ca')['text'] == 'cat'"),
           ("The whole word still matches itself",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nassert matching_word(state, 'cat')['text'] == 'cat'"),
           ("More letters narrow it down",
            "state = create_game()\nstate['words'] = [make_word('cat', 10), make_word('cow', 60)]\nassert matching_word(state, 'c') is not None\nassert matching_word(state, 'ca')['text'] == 'cat'\nassert matching_word(state, 'co')['text'] == 'cow'"),
           ("When two match, it takes the lower one",
            "state = create_game()\nhigh = make_word('cat', 10); high['y'] = 40\nlow = make_word('cup', 60); low['y'] = 300\nstate['words'] = [high, low]\nassert matching_word(state, 'c')['text'] == 'cup', 'the one nearest the ground is in trouble'"),
           ("Order in the list makes no difference",
            "high = make_word('cat', 10); high['y'] = 40\nlow = make_word('cup', 60); low['y'] = 300\none = create_game(); one['words'] = [high, low]\ntwo = create_game(); two['words'] = [low, high]\nassert matching_word(one, 'c')['text'] == matching_word(two, 'c')['text']"),
           ("It gives back the very word from the sky",
            "state = create_game()\nword = make_word('cat', 10)\nstate['words'] = [word]\nassert matching_word(state, 'ca') is word, 'give back the word itself, not a copy'")]),
  demo=dict(kind="match", caption="Press Type ▶ and watch the line move to whichever word you are on.")),

step("type_letter", "typeLetter", "type_letter",
  "One letter at a time", "You can type at the sky.",
  "<p>A letter is only worth taking if it still spells something up there.</p>"
  "<p>So <strong>try it first</strong>: stick the letter on the end and ask <code>matchingWord</code> whether anything still matches. If nothing does, throw the letter away and count it as a slip. If something does, keep it.</p>"
  "<p>That one guard is what stops the game becoming unplayable. Without it, a single mistyped letter would leave you spelling a word that is not in the sky, and every letter after it would be wasted while the rain kept falling.</p>",
  "state — the whole game. letter — one letter.",
  "true if the letter was taken",
  ["Refuse if the game is over or paused.",
   "Refuse anything that is not exactly one character.",
   "Work out what the typing WOULD be with this letter on the end.",
   "If matchingWord finds nothing for that, add one to state.slips and give back false.",
   "Otherwise keep it, count the keystroke, and give back true."],
  js=dict(starter="function typeLetter(state, letter) {\n    return false;\n}\n",
    answer="function typeLetter(state, letter) {\n    if (state.isOver || state.isPaused) {\n        return false;\n    }\n    if (String(letter).length !== 1) {\n        return false;\n    }\n\n    const wanted = state.typed + letter;\n    if (matchingWord(state, wanted) === null) {\n        state.slips = state.slips + 1;\n        return false;\n    }\n\n    state.typed = wanted;\n    state.keystrokes = state.keystrokes + 1;\n    return true;\n}\n",
    hints=["Build the would-be typing in a variable first: state.typed + letter.",
           "Then ask matchingWord about THAT, before changing anything.",
           "Only set state.typed once you know the letter is worth keeping."],
    tests=[("A letter that fits is taken",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nassert(typeLetter(state, 'c') === true);\nassert(state.typed === 'c');"),
           ("A letter that fits nothing is refused",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nassert(typeLetter(state, 'z') === false);\nassert(state.typed === '', 'the typing should be untouched');"),
           ("A refused letter is counted as a slip",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nstate.slips = 0;\ntypeLetter(state, 'z');\nassert(state.slips === 1, 'slips is ' + state.slips);"),
           ("Letters build up",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\ntypeLetter(state, 'c');\ntypeLetter(state, 'a');\ntypeLetter(state, 't');\nassert(state.typed === 'cat', 'got \"' + state.typed + '\"');"),
           ("A wrong letter halfway through is refused too",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = 'c';\nassert(typeLetter(state, 'x') === false);\nassert(state.typed === 'c', 'you should still be on \"c\", not \"cx\"');"),
           ("A finished game takes no letters",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nstate.isOver = true;\nassert(typeLetter(state, 'c') === false);\nassert(state.typed === '');"),
           ("A paused game takes no letters",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nstate.isPaused = true;\nassert(typeLetter(state, 'c') === false);"),
           ("Two words starting the same both stay possible",
            "const state = createGame();\nstate.words = [makeWord('cat', 10), makeWord('cow', 60)];\nstate.typed = '';\nassert(typeLetter(state, 'c') === true);\nassert(typeLetter(state, 'o') === true, 'after \"c\", both cat and cow are still going — \"o\" must be allowed');\nassert(state.typed === 'co');"),
           ("You can always type a word right through",
            "const state = createGame();\nstate.words = [makeWord('lantern', 10)];\nstate.typed = '';\nfor (const letter of 'lantern') {\n    assert(typeLetter(state, letter) === true, 'it refused \"' + letter + '\" of lantern');\n}\nassert(state.typed === 'lantern');")]),
  py=dict(starter="def type_letter(state, letter):\n    return False\n",
    answer="def type_letter(state, letter):\n    if state[\"is_over\"] or state[\"is_paused\"]:\n        return False\n    if len(str(letter)) != 1:\n        return False\n\n    wanted = state[\"typed\"] + letter\n    if matching_word(state, wanted) is None:\n        state[\"slips\"] += 1\n        return False\n\n    state[\"typed\"] = wanted\n    state[\"keystrokes\"] += 1\n    return True\n",
    hints=["Build the would-be typing in a variable first: state['typed'] + letter.",
           "Then ask matching_word about THAT, before changing anything.",
           "Only set state['typed'] once you know the letter is worth keeping."],
    tests=[("A letter that fits is taken",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nassert type_letter(state, 'c') is True\nassert state['typed'] == 'c'"),
           ("A letter that fits nothing is refused",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nassert type_letter(state, 'z') is False\nassert state['typed'] == ''"),
           ("A refused letter is counted as a slip",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nstate['slips'] = 0\ntype_letter(state, 'z')\nassert state['slips'] == 1"),
           ("Letters build up",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nfor letter in 'cat':\n    type_letter(state, letter)\nassert state['typed'] == 'cat'"),
           ("A wrong letter halfway through is refused too",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = 'c'\nassert type_letter(state, 'x') is False\nassert state['typed'] == 'c'"),
           ("A finished game takes no letters",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nstate['is_over'] = True\nassert type_letter(state, 'c') is False"),
           ("A paused game takes no letters",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nstate['is_paused'] = True\nassert type_letter(state, 'c') is False"),
           ("Two words starting the same both stay possible",
            "state = create_game()\nstate['words'] = [make_word('cat', 10), make_word('cow', 60)]\nstate['typed'] = ''\nassert type_letter(state, 'c') is True\nassert type_letter(state, 'o') is True, 'cow is still going, so o must be allowed'\nassert state['typed'] == 'co'"),
           ("You can always type a word right through",
            "state = create_game()\nstate['words'] = [make_word('lantern', 10)]\nstate['typed'] = ''\nfor letter in 'lantern':\n    assert type_letter(state, letter) is True, f'it refused {letter}'\nassert state['typed'] == 'lantern'")]),
  demo=dict(kind="match", caption="Each press of Type ▶ is one call to your function — watch the black letters grow.")),

step("zap_word", "zapWord", "zap_word",
  "Gone!", "Word Rain is finished. Go and play it.",
  "<p>The last one. When what you have typed spells a whole word, that word disappears and you score for it.</p>"
  "<p>Two details make it right. Only a word typed <strong>in full</strong> counts — being partway through <em>lantern</em> must not clear it. And when you take it out, compare the words <strong>themselves</strong>, not what they say: <code>word !== target</code> asks &ldquo;is this a different word object?&rdquo;, where <code>word.text !== target.text</code> would ask &ldquo;does it say something different?&rdquo; — and would wipe out both if two words in the sky happened to say the same thing.</p>"
  "<p>Then score by length, and step up a level every <code>WORDS_PER_LEVEL</code>. That is the whole game.</p>",
  "state — the whole game",
  "true if a word was cleared",
  ["Ask matchingWord which word is being typed.",
   "If there is none, or its text is not exactly what was typed, give back false.",
   "Keep every word except that very one.",
   "Score its length × POINTS_PER_LETTER, count it cleared, and empty the typing.",
   "Every WORDS_PER_LEVEL words cleared, go up a level."],
  js=dict(starter="function zapWord(state) {\n    return false;\n}\n",
    answer="function zapWord(state) {\n    const target = matchingWord(state, state.typed);\n    if (target === null || target.text !== state.typed) {\n        return false;\n    }\n\n    state.words = state.words.filter(function (word) { return word !== target; });\n    state.score = state.score + target.text.length * POINTS_PER_LETTER;\n    state.cleared = state.cleared + 1;\n    state.typed = '';\n\n    if (state.cleared % WORDS_PER_LEVEL === 0) {\n        state.level = state.level + 1;\n    }\n    return true;\n}\n",
    hints=["target.text !== state.typed is the 'not finished yet' guard.",
           "filter keeps everything the test says true for — so keep the words that are NOT the target.",
           "state.cleared % WORDS_PER_LEVEL === 0 is 'every sixth word'."],
    tests=[("A half-typed word is not cleared",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = 'ca';\nassert(zapWord(state) === false);\nassert(state.words.length === 1, 'it should still be falling');"),
           ("Typing nothing clears nothing",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = '';\nassert(zapWord(state) === false);"),
           ("A finished word disappears",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = 'cat';\nassert(zapWord(state) === true);\nassert(state.words.length === 0);"),
           ("And the typing is cleared for the next one",
            "const state = createGame();\nstate.words = [makeWord('cat', 10)];\nstate.typed = 'cat';\nzapWord(state);\nassert(state.typed === '', 'got \"' + state.typed + '\"');"),
           ("A longer word is worth more",
            "const short = createGame();\nshort.words = [makeWord('cat', 10)];\nshort.typed = 'cat';\nshort.score = 0;\nzapWord(short);\nconst long = createGame();\nlong.words = [makeWord('lantern', 10)];\nlong.typed = 'lantern';\nlong.score = 0;\nzapWord(long);\nassert(long.score > short.score, 'lantern scored ' + long.score + ', cat scored ' + short.score);\nassert(short.score === 3 * POINTS_PER_LETTER);"),
           ("Only that word goes",
            "const state = createGame();\nstate.words = [makeWord('cat', 10), makeWord('dog', 60), makeWord('pig', 110)];\nstate.typed = 'dog';\nzapWord(state);\nassert(state.words.length === 2, 'kept ' + state.words.length);\nassert(state.words[0].text === 'cat' && state.words[1].text === 'pig');"),
           ("Two words saying the same thing do not both vanish",
            "const state = createGame();\nconst first = makeWord('cat', 10);\nconst second = makeWord('cat', 200);\nsecond.y = 100;\nstate.words = [first, second];\nstate.typed = 'cat';\nzapWord(state);\nassert(state.words.length === 1, 'both went — compare the words themselves, not what they say');"),
           ("Six words takes you up a level",
            "const state = createGame();\nstate.level = 1;\nstate.cleared = 0;\nfor (let i = 0; i < WORDS_PER_LEVEL; i++) {\n    state.words = [makeWord('cat', 10)];\n    state.typed = 'cat';\n    zapWord(state);\n}\nassert(state.level === 2, 'level is ' + state.level + ' after ' + WORDS_PER_LEVEL + ' words');"),
           ("But five words does not",
            "const state = createGame();\nstate.level = 1;\nstate.cleared = 0;\nfor (let i = 0; i < WORDS_PER_LEVEL - 1; i++) {\n    state.words = [makeWord('cat', 10)];\n    state.typed = 'cat';\n    zapWord(state);\n}\nassert(state.level === 1, 'level is ' + state.level + ' too early');"),
           ("A whole game can be played",
            "const state = createGame();\nlet cleared = 0;\nfor (let frame = 0; frame < 4000 && !state.isOver; frame++) {\n    updateGame(state, 16);\n    let lowest = null;\n    for (const word of state.words) {\n        if (state.typed.length > 0 && word.text.indexOf(state.typed) !== 0) { continue; }\n        if (lowest === null || word.y > lowest.y) { lowest = word; }\n    }\n    if (lowest !== null) {\n        typeLetter(state, lowest.text.charAt(state.typed.length));\n        if (zapWord(state)) { cleared = cleared + 1; }\n    }\n}\nassert(cleared > 20, 'a perfect typist only cleared ' + cleared + ' words');\nassert(state.level > 3, 'and only reached level ' + state.level);")]),
  py=dict(starter="def zap_word(state):\n    return False\n",
    answer="def zap_word(state):\n    target = matching_word(state, state[\"typed\"])\n    if target is None or target[\"text\"] != state[\"typed\"]:\n        return False\n\n    state[\"words\"] = [word for word in state[\"words\"] if word is not target]\n    state[\"score\"] += len(target[\"text\"]) * POINTS_PER_LETTER\n    state[\"cleared\"] += 1\n    state[\"typed\"] = \"\"\n\n    if state[\"cleared\"] % WORDS_PER_LEVEL == 0:\n        state[\"level\"] += 1\n    return True\n",
    hints=["target['text'] != state['typed'] is the 'not finished yet' guard.",
           "`is not` asks whether it is a DIFFERENT object; != would ask whether it says something different.",
           "state['cleared'] % WORDS_PER_LEVEL == 0 is 'every sixth word'."],
    tests=[("A half-typed word is not cleared",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = 'ca'\nassert zap_word(state) is False\nassert len(state['words']) == 1"),
           ("Typing nothing clears nothing",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = ''\nassert zap_word(state) is False"),
           ("A finished word disappears",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = 'cat'\nassert zap_word(state) is True\nassert state['words'] == []"),
           ("And the typing is cleared for the next one",
            "state = create_game()\nstate['words'] = [make_word('cat', 10)]\nstate['typed'] = 'cat'\nzap_word(state)\nassert state['typed'] == ''"),
           ("A longer word is worth more",
            "short = create_game(); short['words'] = [make_word('cat', 10)]; short['typed'] = 'cat'; short['score'] = 0\nzap_word(short)\nlong = create_game(); long['words'] = [make_word('lantern', 10)]; long['typed'] = 'lantern'; long['score'] = 0\nzap_word(long)\nassert long['score'] > short['score']\nassert short['score'] == 3 * POINTS_PER_LETTER"),
           ("Only that word goes",
            "state = create_game()\nstate['words'] = [make_word('cat', 10), make_word('dog', 60), make_word('pig', 110)]\nstate['typed'] = 'dog'\nzap_word(state)\nassert [w['text'] for w in state['words']] == ['cat', 'pig']"),
           ("Two words saying the same thing do not both vanish",
            "state = create_game()\nfirst = make_word('cat', 10)\nsecond = make_word('cat', 200); second['y'] = 100\nstate['words'] = [first, second]\nstate['typed'] = 'cat'\nzap_word(state)\nassert len(state['words']) == 1, 'both went — compare the words themselves, not what they say'"),
           ("Six words takes you up a level",
            "state = create_game()\nstate['level'] = 1\nstate['cleared'] = 0\nfor i in range(WORDS_PER_LEVEL):\n    state['words'] = [make_word('cat', 10)]\n    state['typed'] = 'cat'\n    zap_word(state)\nassert state['level'] == 2"),
           ("But five words does not",
            "state = create_game()\nstate['level'] = 1\nstate['cleared'] = 0\nfor i in range(WORDS_PER_LEVEL - 1):\n    state['words'] = [make_word('cat', 10)]\n    state['typed'] = 'cat'\n    zap_word(state)\nassert state['level'] == 1"),
           ("A whole game can be played",
            "state = create_game()\ncleared = 0\nfor frame in range(4000):\n    if state['is_over']:\n        break\n    update_game(state, 16)\n    lowest = None\n    for word in state['words']:\n        if state['typed'] and not word['text'].startswith(state['typed']):\n            continue\n        if lowest is None or word['y'] > lowest['y']:\n            lowest = word\n    if lowest is not None:\n        type_letter(state, lowest['text'][len(state['typed'])])\n        if zap_word(state):\n            cleared += 1\nassert cleared > 20, f'a perfect typist only cleared {cleared} words'\nassert state['level'] > 3, f\"and only reached level {state['level']}\"")]),
  demo=dict(kind="final", caption="Every function is yours now. Type at the sky — or press Type ▶ if you would rather watch.")),
]

write_workshop("wordfall", "Word Rain", STEPS)
